Repository swiftlang/swift, pull requests merged in 2018-12, with the labels that each got.

#20966 [AutoDiff] Work around duplicate diff task registration
  lib/SILOptimizer/Mandatory/TFDifferentiation.cpp
  stdlib/public/core/FloatingPoint.swift
Labels: tensorflow

#20789 [5.0] [Mangle] Include generic arguments of extensions for the Objective-C runtime
  lib/Demangling/OldRemangler.cpp
  test/Demangle/remangle.swift
  validation-test/stdlib/Lazy.swift.gyb
Labels: pending-convergence

#20774 [5.0] [Runtime] Cache and unique based on protocol conformance descriptors, not witness tables
  include/swift/Basic/Lazy.h
  stdlib/public/runtime/Metadata.cpp
  stdlib/public/runtime/MetadataCache.h
  stdlib/public/runtime/Private.h
  stdlib/public/runtime/ProtocolConformance.cpp
  test/Runtime/Inputs/synthesized_decl_uniqueness.swift
  test/Runtime/synthesized_decl_uniqueness.swift
  validation-test/stdlib/SetAnyHashableExtensions.swift
Labels: pending-convergence

#20800 [5.0] stdlib: Make ArrayBufferProtocol.init inlinable to facilitate specialization
  stdlib/public/core/ArrayBufferProtocol.swift
Labels: pending-convergence

#20814 Remove DebugTypeInfo::isImplicitlyIndirect()
  lib/IRGen/DebugTypeInfo.h
  lib/IRGen/IRGenSIL.cpp
  test/DebugInfo/generic_arg.swift
  test/DebugInfo/generic_arg2.swift
  test/DebugInfo/generic_arg3.swift
Labels: pending-convergence

#20877 Re-apply [5.0] Change Default Linker to Gold for AArch64
  lib/Driver/UnixToolChains.cpp
Labels: AArch64 Linux, pending-convergence

#21012 [AutoDiff] IRGen `autodiff_function` and `autodiff_function_extract` instructions
  include/swift/AST/AutoDiff.h
  lib/AST/AutoDiff.cpp
  lib/IRGen/GenFunc.cpp
  lib/IRGen/IRGenSIL.cpp
  lib/SIL/SILInstructions.cpp
  test/AutoDiff/autodiff_function_inst_irgen.sil
Labels: tensorflow

#20765 [5.0] Be conservative with classifying some casts that could change in the future.
  lib/SIL/DynamicCasts.cpp
Labels: pending-convergence

#20891 [5.0] Limit access of implicit typealiases for associated type witnesses
  lib/Sema/TypeCheckProtocol.cpp
  test/attr/accessibility_print_inferred_type_witnesses.swift
Labels: pending-convergence

#20802 [5.0] [CMake] Disable generation of .swiftinterface files
  CMakeLists.txt
  cmake/modules/SwiftSource.cmake
  validation-test/ParseableInterface/verify_all_overlays.swift
  validation-test/ParseableInterface/verify_all_overlays_O.swift
  validation-test/ParseableInterface/verify_simd.swift
Labels: pending-convergence

#20982 [5.0] sourcekit: avoid evaluating pound conditions while perform syntactic parsing.
  test/SourceKit/SyntaxTree/pound_if.swift
  tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp
Labels: pending-convergence

#20990 [5.0][CodeCompletion] Propagate completion status of parseGenericArguments()
  include/swift/Parse/Parser.h
  lib/Parse/ParseExpr.cpp
  lib/Parse/ParseType.cpp
  test/IDE/complete_type.swift
Labels: pending-convergence

#20991 [5.0][CodeCompletion] Eat identifier characters after CC position
  lib/Parse/Lexer.cpp
  test/IDE/complete_decl_attribute.swift
Labels: pending-convergence

#21040 [AutoDiff] Make `autodiff_function_extract` able to extract the original function.
  docs/SIL.rst
  include/swift/AST/DiagnosticsParse.def
  include/swift/SIL/SILBuilder.h
  include/swift/SIL/SILCloner.h
  include/swift/SIL/SILInstruction.h
  lib/IRGen/IRGenSIL.cpp
  lib/ParseSIL/ParseSIL.cpp
  lib/SIL/SILInstructions.cpp
  lib/SIL/SILPrinter.cpp
  lib/SIL/SILVerifier.cpp
  test/AutoDiff/autodiff_function_inst.sil
  test/AutoDiff/autodiff_function_inst_irgen.sil
Labels: tensorflow

#21042 NFC: Remove dead code and suppress warnings
  lib/SILOptimizer/Mandatory/TFLowerGraph.cpp
  stdlib/public/TensorFlow/Ops.swift
Labels: tensorflow

#20785 [5.0][CodeCompletion] Rework getOperatorCompletions()
  include/swift/Sema/IDETypeChecking.h
  lib/IDE/CodeCompletion.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/ConstraintSystem.h
  lib/Sema/TypeCheckConstraints.cpp
  lib/Sema/TypeCheckExpr.cpp
  lib/Sema/TypeChecker.cpp
  lib/Sema/TypeChecker.h
  test/IDE/complete_from_stdlib.swift
  test/IDE/complete_operators.swift
  validation-test/IDE/slow_fixed/rdar45511835.swift
Labels: pending-convergence

#21111 [5.0][ConstraintSystem] Handle `InOut` base introduced by diagnostic re-ty…
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/closures.swift
Labels: pending-convergence

#20831 [5.0][CSSimplify] Delay binding metatype instance types if one side is typ…
  lib/Sema/CSSimplify.cpp
  test/Constraints/rdar44816848.swift
Labels: pending-convergence

#20878 [5.0][TypeChecker] Improve error about mutating self capture by escaping c…
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckCaptures.cpp
  test/Sema/diag_invalid_inout_captures.swift
Labels: pending-convergence

#21002 [CSDiag] Verify that @autoclosure param has function type before casting
  lib/Sema/CSDiag.cpp
  test/Constraints/rdar46377919.swift
Labels: pending-convergence

#21014 Backward deployment fixes and tests [5.0]
  include/swift/ABI/Metadata.h
  include/swift/AST/Attr.def
  include/swift/AST/ProtocolConformance.h
  lib/AST/Decl.cpp
  lib/AST/ProtocolConformance.cpp
  lib/IRGen/Linking.cpp
  stdlib/public/runtime/Metadata.cpp
  test/IRGen/Inputs/weak_import_native_helper.swift
  test/IRGen/weak_import_native.swift
  test/lit.cfg
  utils/rth
  validation-test/Evolution/Inputs/backward_deploy_class.swift
  validation-test/Evolution/Inputs/backward_deploy_enum.swift
  validation-test/Evolution/Inputs/backward_deploy_protocol.swift
  validation-test/Evolution/Inputs/backward_deploy_struct.swift
  validation-test/Evolution/Inputs/backward_deploy_top_level.swift
  validation-test/Evolution/Inputs/bitwise_takable.swift
  validation-test/Evolution/Inputs/protocol_add_requirements.swift
  validation-test/Evolution/test_backward_deploy_class.swift
  validation-test/Evolution/test_backward_deploy_enum.swift
  validation-test/Evolution/test_backward_deploy_protocol.swift
  validation-test/Evolution/test_backward_deploy_struct.swift
  validation-test/Evolution/test_backward_deploy_top_level.swift
Labels: pending-convergence

#20713 [5.0][CSDiagnostics] Add custom diagnostic for invalid @autoclosure forwarding
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSFix.h
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintSystem.cpp
  lib/Sema/ConstraintSystem.h
  test/Compatibility/attr_autoclosure.swift
  test/attr/attr_autoclosure.swift
Labels: pending-convergence

#21124 [5.0][CSDiagnostics] Diagnose invalid optional unwrap via fixes
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSFix.h
  lib/Sema/CSSimplify.cpp
  test/Constraints/diagnostics.swift
  test/Constraints/dynamic_lookup.swift
  test/Constraints/optional.swift
  test/Parse/operators.swift
  test/decl/init/failable.swift
Labels: pending-convergence

#21144 [AutoDiff] Add `Builtin.autodiffGet(JVP|VJP)` for extracting AD associated functions
  include/swift/AST/ASTContext.h
  include/swift/AST/AutoDiff.h
  include/swift/AST/Builtins.def
  include/swift/AST/Types.h
  lib/AST/ASTContext.cpp
  lib/AST/AutoDiff.cpp
  lib/AST/Builtins.cpp
  lib/AST/Type.cpp
  lib/SILGen/SILGenBuiltin.cpp
  lib/SILGen/SILGenExpr.cpp
  lib/Sema/TypeCheckType.cpp
  test/AutoDiff/autodiff_function_silgen.swift
  test/AutoDiff/core_builtins.swift
  test/AutoDiff/differentiable_func_type_type_checking.swift
Labels: tensorflow

#21163 DI: Lower AssignInst in a post-processing pass [5.0]
  lib/SILOptimizer/Mandatory/DefiniteInitialization.cpp
  test/SILOptimizer/definite_init_diagnostics.swift
  test/SILOptimizer/definite_init_markuninitialized_var.sil
Labels: pending-convergence

#21174 [5.0][CSDiagnostics] Fix requirement source lookup to support member refer…
  lib/Sema/CSDiagnostics.cpp
Labels: pending-convergence

#20932 [5.0] Don't map Bool back to ObjCBool for SIL types in unbridged contexts
  include/swift/AST/ModuleLoader.h
  include/swift/SIL/TypeLowering.h
  lib/ClangImporter/ImporterImpl.h
  lib/SIL/AbstractionPattern.cpp
  lib/SIL/Bridging.cpp
  lib/SIL/SILFunctionType.cpp
  lib/SIL/TypeLowering.cpp
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenBridging.cpp
  test/ClangImporter/Inputs/custom-modules/BlocksReturningBool.h
  test/ClangImporter/Inputs/custom-modules/module.map
  test/ClangImporter/blocks_returning_bool.swift
Labels: pending-convergence

#21239 [5.0] Fix SILCombine to devirtualize existentials wrapped in enum.
  include/swift/SILOptimizer/Utils/Existential.h
  include/swift/SILOptimizer/Utils/Local.h
  lib/SILOptimizer/SILCombiner/SILCombinerApplyVisitors.cpp
  lib/SILOptimizer/Utils/Existential.cpp
  lib/SILOptimizer/Utils/Local.cpp
  test/SILOptimizer/devirt_specialized_conformance.swift
  test/SILOptimizer/sil_combine_concrete_existential.sil
Labels: pending-convergence

#20796 Mark lazy properties as having mutating getters immediately.
  lib/Sema/CodeSynthesis.cpp
  lib/Sema/TypeCheckDecl.cpp
  test/multifile/Inputs/external_lazy_property.swift
  test/multifile/lazy.swift
Labels: pending-convergence

#21282 [AutoDiff] Enable end-to-end differentiation using `Builtin.autodiffGetVJP`
  lib/AST/Builtins.cpp
  lib/IRGen/IRGenSIL.cpp
  lib/SIL/SILFunction.cpp
  lib/SIL/SILFunctionType.cpp
  lib/SILGen/SILGenBuiltin.cpp
  lib/SILGen/SILGenExpr.cpp
  test/AutoDiff/autodiff_function_silgen.swift
  test/AutoDiff/builtin_differential_operators.swift
  test/AutoDiff/core_builtins.swift
  test/AutoDiff/differential_operators.swift
  test/lit.cfg
Labels: tensorflow

#21323 [5.0][CSDiag] Account for expression sanitizer mutating AST
  lib/Sema/CSDiag.cpp
  lib/Sema/CSGen.cpp
  validation-test/compiler_crashers_2_fixed/0186-rdar46497155.swift
Labels: pending-convergence

#21225 [5.0] Add Result type to standard library.
  stdlib/public/core/CMakeLists.txt
  stdlib/public/core/GroupInfo.json
  stdlib/public/core/Result.swift
  test/multifile/typealias/two-modules/main.swift
  test/stdlib/Result.swift
Labels: pending-convergence

#21395 [AutoDiff] Define functional differential operators in stdlib
  lib/Serialization/Serialization.cpp
  stdlib/public/core/AutoDiff.swift
  test/AutoDiff/differential_operators.swift
Labels: tensorflow

#20840 [5.0] statically map CF types in the ClangImporter
  lib/ClangImporter/MappedTypes.def
  test/ClangImporter/ctypes_parse_objc.swift
  test/Inputs/clang-importer-sdk/usr/include/CoreFoundation.h
Labels: pending-convergence

#21472 [5.0][Diagnostics] NFC: Remove redundant "because" from `witness_not_usabl…
  include/swift/AST/DiagnosticsSema.def
  test/Compatibility/attr_usableFromInline_protocol.swift
  test/attr/attr_usableFromInline_protocol.swift
Labels: pending-convergence

#21480 [AutoDiff] Cleanup 1: Remove gradient synthesis and ban #gradient.
  include/swift/AST/DiagnosticsSIL.def
  lib/IRGen/IRGenSIL.cpp
  lib/SILOptimizer/Mandatory/TFDifferentiation.cpp
  stdlib/public/core/AutoDiff.swift
  test/AutoDiff/autodiff_basic.sil
  test/AutoDiff/autodiff_diagnostics.swift
  test/AutoDiff/autodiff_e2e_basic.swift
  test/AutoDiff/builtin_math.sil
  test/AutoDiff/closures.swift
  test/AutoDiff/generic_real_vector.swift
  test/AutoDiff/method.swift
  test/AutoDiff/primalgen.swift
  test/AutoDiff/refcounting.swift
  test/AutoDiff/repeated_calls.swift
  test/AutoDiff/simple_math.swift
  test/AutoDiff/simple_model.swift
  test/AutoDiff/simple_real_vector.swift
  test/AutoDiff/superset_adjoint.swift
  test/TensorFlow/tensor_autodiff.swift
  test/TensorFlow/tensor_primitive_autodiff.swift
  test/TensorFlowRuntime/tensor_autodiff_runtime.swift
Labels: tensorflow

#21486 [AutoDiff] Cleanup 2: Kill `#gradient` expressions.
  include/swift/AST/AutoDiff.h
  include/swift/AST/DiagnosticsParse.def
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/Expr.h
  include/swift/AST/ExprNodes.def
  include/swift/Serialization/ModuleFormat.h
  lib/AST/ASTDumper.cpp
  lib/AST/ASTWalker.cpp
  lib/AST/Expr.cpp
  lib/Parse/ParseDecl.cpp
  lib/Parse/ParseExpr.cpp
  lib/SILGen/SILGenExpr.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CSDiag.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/MiscDiagnostics.cpp
  lib/Serialization/Serialization.cpp
  test/AutoDiff/gradient_expr_parse.swift
  test/AutoDiff/gradient_expr_silgen.swift
  test/AutoDiff/gradient_expr_type_checking.swift
  test/AutoDiff/gradient_hof_silgen.swift
  test/Syntax/Outputs/round_trip_parse_gen.swift.withkinds
  test/Syntax/round_trip_parse_gen.swift
  utils/gyb_syntax_support/ExprNodes.py
  utils/gyb_syntax_support/Token.py
Labels: tensorflow

#21488 [AutoDiff] Cleanup 3: Kill `gradient` instruction and gradient-related data structures
  docs/SIL.rst
  include/swift/AST/AutoDiff.h
  include/swift/AST/DiagnosticsParse.def
  include/swift/SIL/SILBuilder.h
  include/swift/SIL/SILCloner.h
  include/swift/SIL/SILInstruction.h
  include/swift/SIL/SILNodes.def
  include/swift/Serialization/ModuleFormat.h
  lib/IRGen/IRGenSIL.cpp
  lib/ParseSIL/ParseSIL.cpp
  lib/SIL/OperandOwnership.cpp
  lib/SIL/OwnershipUtils.cpp
  lib/SIL/SILFunctionType.cpp
  lib/SIL/SILInstructions.cpp
  lib/SIL/SILPrinter.cpp
  lib/SIL/SILVerifier.cpp
  lib/SIL/ValueOwnership.cpp
  lib/SILOptimizer/Mandatory/TFDifferentiation.cpp
  lib/SILOptimizer/Utils/SILInliner.cpp
  lib/Serialization/DeserializeSIL.cpp
  lib/Serialization/SILFormat.h
  lib/Serialization/SerializeSIL.cpp
  test/AutoDiff/gradient_inst.sil
Labels: tensorflow

#21503 [5.0][CSDiag] Always attempt to erase open existentials after re-typecheck
  lib/Sema/CSDiag.cpp
  test/Constraints/rdar46544601.swift
Labels: pending-convergence

#21522 Split `VectorNumeric` into `ShapedVectorNumeric` protocol.
  stdlib/public/TensorFlow/Ops.swift
  stdlib/public/core/AutoDiff.swift
  test/AutoDiff/generic_real_vector.swift
  test/AutoDiff/refcounting.swift
  test/AutoDiff/simple_model.swift
  test/AutoDiff/simple_real_vector.swift
Labels: tensorflow

#21543 [ParameterUpdate] Clean up ParameterGroup/Parameterized synthesis.
  lib/AST/Decl.cpp
  lib/Sema/DerivedConformanceParameterGroup.cpp
  lib/Sema/DerivedConformanceParameterized.cpp
  test/Sema/parameterized.swift
Labels: tensorflow

#21544 [AutoDiff] Remove differentiation mode.
  include/swift/AST/Attr.h
  include/swift/AST/AutoDiff.h
  include/swift/AST/DiagnosticsParse.def
  include/swift/Parse/Parser.h
  include/swift/Serialization/ModuleFormat.h
  lib/AST/Attr.cpp
  lib/Parse/ParseDecl.cpp
  lib/SILGen/SILGen.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Serialization/Deserialization.cpp
  lib/Serialization/Serialization.cpp
  stdlib/public/TensorFlow/CompositeMath.swift
  stdlib/public/TensorFlow/Gradients.swift
  stdlib/public/TensorFlow/Ops.swift
  stdlib/public/TensorFlow/Tensor.swift
  stdlib/public/core/FloatingPoint.swift
  stdlib/public/core/FloatingPointTypes.swift.gyb
  test/AutoDiff/autodiff_diagnostics.swift
  test/AutoDiff/autodiff_e2e_basic.swift
  test/AutoDiff/diagnose_missing_synthesis.swift
  test/AutoDiff/differentiable_attr_access_control.swift
  test/AutoDiff/differentiable_attr_parse.swift
  test/AutoDiff/differentiable_attr_silgen.swift
  test/AutoDiff/differentiable_attr_type_checking.swift
  test/AutoDiff/generic_real_vector.swift
  test/AutoDiff/method.swift
  test/AutoDiff/protocol_requirement_autodiff.swift
  test/AutoDiff/refcounting.swift
  test/AutoDiff/sildeclref_parse.sil
  test/AutoDiff/simple_real_vector.swift
  test/AutoDiff/superset_adjoint.swift
  test/AutoDiff/tbdgen.swift
  test/AutoDiff/witness_method_autodiff.sil
  test/AutoDiff/witness_table_irgen.sil
  test/AutoDiff/witness_table_silgen.swift
  test/Serialization/differentiable_attr.swift
  test/Syntax/Outputs/round_trip_parse_gen.swift.withkinds
  test/Syntax/round_trip_parse_gen.swift
  test/TensorFlowRuntime/tensor_autodiff_runtime.swift
  utils/gyb_syntax_support/AttributeNodes.py
Labels: tensorflow

#21557 Add `KeyPathIterable` protocol and synthesis.
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/KnownIdentifiers.def
  include/swift/AST/KnownProtocols.def
  lib/IRGen/GenMeta.cpp
  lib/Sema/CMakeLists.txt
  lib/Sema/DerivedConformanceKeyPathIterable.cpp
  lib/Sema/DerivedConformances.cpp
  lib/Sema/DerivedConformances.h
  lib/Sema/TypeCheckProtocol.cpp
  stdlib/public/core/CMakeLists.txt
  stdlib/public/core/GroupInfo.json
  stdlib/public/core/KeyPathIterable.swift
  test/Sema/key_path_iterable.swift
  test/TensorFlowRuntime/key_path_iterable.swift
Labels: tensorflow

#21558 [AutoDiff] Use `AdditiveArithmetic.zero` to initialize cotangent vectors
  include/swift/AST/KnownIdentifiers.def
  lib/SILOptimizer/Mandatory/TFDifferentiation.cpp
  stdlib/public/core/Integers.swift
  test/AutoDiff/simple_model.swift
  test/TensorFlowRuntime/tensor_autodiff_runtime.swift
Labels: tensorflow

#21568 [API] Derive conformances for `AdditiveArithmetic` and `VectorNumeric`.
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/KnownIdentifiers.def
  lib/Sema/CMakeLists.txt
  lib/Sema/DerivedConformanceAdditiveArithmeticVectorNumeric.cpp
  lib/Sema/DerivedConformances.cpp
  lib/Sema/DerivedConformances.h
  lib/Sema/TypeCheckProtocol.cpp
  test/Sema/struct_additive_arithmetic.swift
  test/Sema/struct_vector_numeric.swift
Labels: tensorflow
