Repository swiftlang/swift, pull requests merged in 2019-03, with the labels that each got.

#23006 [AutoDiff] Follow-up to #22983.
  lib/SILOptimizer/Mandatory/Differentiation.cpp
  lib/Sema/TypeCheckAttr.cpp
Labels: tensorflow

#23032 [Doc] Move public TensorFlow runtime APIs to new file.
  stdlib/public/TensorFlow/CMakeLists.txt
  stdlib/public/TensorFlow/CompilerRuntime.swift
  stdlib/public/TensorFlow/Execution.swift
Labels: tensorflow

#23036 [AutoDiff] [stdlib] Add operators for custom gradients.
  stdlib/public/core/AutoDiff.swift
  test/AutoDiff/custom_derivatives.swift
Labels: tensorflow

#23042 [TF] Update checkout for tensorflow/swift-apis
  utils/update_checkout/update-checkout-config.json
Labels: tensorflow

#23055 [Python] fix UInt.pythonObject for Python 3.7
  stdlib/public/Python/Python.swift
  stdlib/public/Python/PythonLibrary+Symbols.swift
Labels: tensorflow

#23058 [TF API] Add a setter to ShapedArray's 'scalar' property.
  stdlib/public/TensorFlow/ShapedArray.swift
  test/TensorFlowRuntime/shaped_array.swift
Labels: tensorflow

#23059 [TF API] Add VJP for 'Tensor.scalarized()'.
  stdlib/public/TensorFlow/Tensor.swift
  test/TensorFlowRuntime/tensor_autodiff_runtime.swift
Labels: tensorflow

#23060 [TF API] Underscore 'TensorElementLiteral'.
  stdlib/public/TensorFlow/ShapedArray.swift
  stdlib/public/TensorFlow/Tensor.swift
  stdlib/public/TensorFlow/TensorGroup.swift
  test/TensorFlow/sema_errors.swift
Labels: tensorflow

#23069 [Doc] API documentation updates.
  stdlib/public/Python/NumpyConversion.swift
  stdlib/public/TensorFlow/CompilerRuntime.swift
  stdlib/public/TensorFlow/Execution.swift
  stdlib/public/TensorFlow/NumpyConversion.swift
  stdlib/public/core/AutoDiff.swift
Labels: tensorflow

#23093 [Doc] API documentation updates.
  stdlib/public/TensorFlow/DataTypes.swift
  stdlib/public/TensorFlow/Dataset.swift
  stdlib/public/TensorFlow/NumpyConversion.swift
  stdlib/public/TensorFlow/Ops.swift
  stdlib/public/TensorFlow/ShapedArray.swift
  stdlib/public/TensorFlow/TensorGroup.swift
  stdlib/public/TensorFlow/TensorHandle.swift
  stdlib/public/TensorFlow/TensorPair.swift
  stdlib/public/TensorFlow/TensorShape.swift
  stdlib/public/core/AutoDiff.swift
Labels: tensorflow

#23124 [AutoDiff] [stdlib] Fix derivative of square root.
  stdlib/public/core/FloatingPoint.swift
Labels: tensorflow

#23139 [AutoDiff][stdlib] Fix `FloatingPoint.squareRoot()`'s derivative again.
  stdlib/public/core/FloatingPoint.swift
Labels: tensorflow

#23188 [Build System: CMake] Partially revert PR #22840, manually adding the LLVM CMake module path to CMAKE_MODULE_PATH rather than using find_package.
  cmake/modules/StandaloneOverlay.cmake
Labels: bug

#23299 [AutoDiff][TF] Add derivative for `abs`.
  stdlib/public/TensorFlow/Gradients.swift
  stdlib/public/TensorFlow/Ops.swift
  test/TensorFlowRuntime/tensor_autodiff_runtime.swift
Labels: tensorflow

#23340 [Syntax] Add syntax support for `@differentiating` attribute.
  lib/Parse/ParseDecl.cpp
  test/Syntax/Outputs/round_trip_parse_gen.swift.withkinds
  test/Syntax/round_trip_parse_gen.swift
  utils/gyb_syntax_support/AttributeNodes.py
  utils/gyb_syntax_support/NodeSerializationCodes.py
Labels: tensorflow

#23349 [Gardening] Remove redundant generic constraint for `Tracked`.
  stdlib/private/DifferentiationUnittest/GenericLifetimeTracked.swift
Labels: tensorflow

#23350 [AutoDiff] Unify code for differentiation parameter inference.
  include/swift/AST/AutoDiff.h
  lib/AST/AutoDiff.cpp
  lib/AST/Builtins.cpp
  lib/SILGen/SILGenPoly.cpp
  lib/Sema/TypeCheckAttr.cpp
  test/AutoDiff/custom_derivatives.swift
  test/AutoDiff/derivative_registration.swift
  utils/gyb_syntax_support/AttributeNodes.py
Labels: tensorflow

#23352 [TF] Rename `ShapedArray` initializers to `init(repeating:shape:)`.
  stdlib/public/TensorFlow/ShapedArray.swift
  stdlib/public/TensorFlow/Tensor.swift
  test/TensorFlowRuntime/numpy_conversion.swift
  test/TensorFlowRuntime/shaped_array.swift
  test/TensorFlowRuntime/tensor.swift
  test/TensorFlowRuntime/tensor_api.swift
  test/TensorFlowRuntime/tensor_autodiff_runtime.swift
Labels: tensorflow

#23353 [AutoDiff] Fix `@differentiating` type-checking for differentials.
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckAttr.cpp
  test/AutoDiff/differentiating_attr_type_checking.swift
Labels: tensorflow

#23371 [AutoDiff] Fix `.withoutDerivative()` fixit location.
  lib/SILOptimizer/Mandatory/Differentiation.cpp
  test/AutoDiff/autodiff_diagnostics.swift
  test/AutoDiff/generics.swift
Labels: tensorflow

#23351 [Python] Make `Optional` conditionally `PythonConvertible`.
  stdlib/public/Python/Python.swift
  test/Python/python_runtime.swift
Labels: tensorflow

#23370 [AutoDiff] Support `wrt` clause for `@differentiating` attribute.
  include/swift/AST/Attr.h
  include/swift/AST/DiagnosticsParse.def
  include/swift/AST/DiagnosticsSema.def
  include/swift/Parse/Parser.h
  include/swift/Serialization/ModuleFormat.h
  lib/AST/Attr.cpp
  lib/Parse/ParseDecl.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Serialization/Deserialization.cpp
  lib/Serialization/Serialization.cpp
  test/AutoDiff/differentiable_attr_type_checking.swift
  test/AutoDiff/differentiating_attr_type_checking.swift
  test/AutoDiff/simple_math.swift
  test/Syntax/Outputs/round_trip_parse_gen.swift.withkinds
  utils/gyb_syntax_support/AttributeNodes.py
Labels: tensorflow

#23373 [AutoDiff] Enable `@differentiable` on subscripts.
  include/swift/AST/Attr.def
  lib/Sema/TypeCheckAttr.cpp
  lib/TBDGen/TBDGen.cpp
  test/AutoDiff/differentiable_attr_type_checking.swift
  test/AutoDiff/tbdgen.swift
Labels: tensorflow

#23379 [AutoDiff] Fix `wrt` differentiation parameter clause printing.
  include/swift/AST/Attr.h
  include/swift/AST/AutoDiff.h
  lib/AST/Attr.cpp
  lib/AST/AutoDiff.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckProtocol.cpp
  test/AutoDiff/Inputs/differentiable_requirement_other_module.swift
  test/AutoDiff/differentiable_attr_type_checking.swift
  test/AutoDiff/differentiable_requirement_cross_module.swift
  test/Serialization/differentiable_attr.swift
Labels: tensorflow

#23383 [AutoDiff] Fix `@differentiable` attribute where clause printing.
  lib/AST/Attr.cpp
  test/AutoDiff/differentiable_attr_type_checking.swift
  test/Serialization/differentiable_attr.swift
Labels: tensorflow

#23384 [AutoDiff] Support `@differentiating` with extra generic constraints.
  lib/Sema/TypeCheckAttr.cpp
  test/AutoDiff/differentiating_attr_type_checking.swift
Labels: tensorflow

#23339 make TensorHandle Scalar @usableFromInline
  stdlib/public/TensorFlow/TensorHandle.swift
Labels: tensorflow

#23367 [TF] Update TensorFlowRuntime tests
  test/TensorFlowRuntime/accelerator_only.swift
  test/TensorFlowRuntime/codable.swift
  test/TensorFlowRuntime/conflicting_module.swift
  test/TensorFlowRuntime/control_flow_objc.swift
  test/TensorFlowRuntime/dataset_global.swift
  test/TensorFlowRuntime/dynamic_attributes.swift
  test/TensorFlowRuntime/dynamic_compilation.swift
  test/TensorFlowRuntime/dynamic_compilation_tensor_group.swift
  test/TensorFlowRuntime/gpu_negative_tests.swift
  test/TensorFlowRuntime/model_autodiff_runtime.swift
  test/TensorFlowRuntime/raw_ops.swift
  test/TensorFlowRuntime/runtime_entry_points.swift
  test/TensorFlowRuntime/sese_loop_canonicalization.swift
  test/TensorFlowRuntime/sese_regions.swift
  test/TensorFlowRuntime/tensor_api.swift
  test/TensorFlowRuntime/tensor_autodiff_indirect.swift
  test/TensorFlowRuntime/tensor_autodiff_indirect_crasher.swift
  test/TensorFlowRuntime/tensor_autodiff_runtime.swift
  test/TensorFlowRuntime/top_level_1.swift
  test/TensorFlowRuntime/top_level_2.swift
Labels: tensorflow

#23385 [AutoDiff] Fix `@differentiable` attribute where clause printing.
  lib/AST/Attr.cpp
  test/AutoDiff/differentiable_attr_type_checking.swift
  test/Serialization/differentiable_attr.swift
Labels: tensorflow

#23380 [AutoDiff] Fix printing/serialization for `@differentiating` attribute.
  lib/AST/Attr.cpp
  lib/Sema/TypeCheckAttr.cpp
  test/Serialization/differentiating_attr.swift
Labels: tensorflow

#23418 [AutoDiff] Fix `@differentiating` derivative registration.
  lib/Sema/TypeCheckAttr.cpp
  test/AutoDiff/differentiating_attr_type_checking.swift
Labels: tensorflow

#23355 [AutoDiff][TF] Derivatives for reshaping methods
  stdlib/public/TensorFlow/Gradients.swift
  stdlib/public/TensorFlow/Tensor.swift
  test/TensorFlowRuntime/tensor_autodiff_runtime.swift
Labels: tensorflow

#23441 [AutoDiff] Fix `@differentiating` attribute.
  include/swift/AST/Attr.def
  include/swift/AST/Attr.h
  lib/AST/Attr.cpp
  lib/Serialization/Deserialization.cpp
  lib/Serialization/Serialization.cpp
  test/Serialization/differentiating_attr.swift
Labels: tensorflow

#23193 [AutoDiff] [stdlib] Switch to '@differentiating' as much as possible.
  stdlib/public/core/AutoDiff.swift
  stdlib/public/core/FloatingPointTypes.swift.gyb
  test/AutoDiff/differentiable_attr_silgen_cross_module.swift
Labels: tensorflow

#23134 [stdlib] Make unsafe array initializer public
  CHANGELOG.md
  stdlib/public/core/Array.swift
  stdlib/public/core/ContiguousArray.swift
  test/stdlib/Inputs/CommonArrayTests.gyb
Labels: swift-evolution-approved

#23523 [AutoDiff] Optimize derivative for `Tensor.mean`.
  stdlib/public/TensorFlow/Gradients.swift
Labels: tensorflow

#23521 [AutoDiff] Implement `AnyDerivative`.
  stdlib/public/core/AutoDiff.swift
  test/AutoDiff/anyderivative.swift
Labels: tensorflow

#19743 [Sema] Synthesize default values for memberwise init
  include/swift/AST/Decl.h
  include/swift/AST/DefaultArgumentKind.h
  include/swift/Serialization/ModuleFormat.h
  lib/AST/ASTDumper.cpp
  lib/AST/Decl.cpp
  lib/IDE/CodeCompletion.cpp
  lib/SILGen/SILGen.cpp
  lib/SILGen/SILGenApply.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CodeSynthesis.cpp
  lib/Serialization/Deserialization.cpp
  lib/Serialization/Serialization.cpp
  test/IDE/complete_at_top_level.swift
  test/IDE/complete_constructor.swift
  test/IDE/complete_value_expr.swift
  test/IDE/print_ast_tc_decls.swift
  test/SILGen/stored_property_default_arg.swift
  test/attr/accessibility_print.swift
  test/decl/func/default-values.swift
Labels: swift-evolution-approved

#23565 [AutoDiff] Improve `AnyDerivative` fatal error message.
  stdlib/public/core/AutoDiff.swift
Labels: tensorflow

#22854 [TF] TensorGroup and TensorArrayProtocol conformance derivation
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/KnownIdentifiers.def
  include/swift/AST/KnownProtocols.def
  lib/AST/ASTContext.cpp
  lib/Sema/CMakeLists.txt
  lib/Sema/DerivedConformanceAdditiveArithmeticVectorNumeric.cpp
  lib/Sema/DerivedConformanceTensorArrayProtocol.cpp
  lib/Sema/DerivedConformanceTensorGroup.cpp
  lib/Sema/DerivedConformances.cpp
  lib/Sema/DerivedConformances.h
  lib/Sema/TypeCheckProtocol.cpp
  stdlib/public/TensorFlow/CMakeLists.txt
  stdlib/public/TensorFlow/CompilerRuntime.swift
  stdlib/public/TensorFlow/Dataset.swift
  stdlib/public/TensorFlow/TensorGroup.swift
  stdlib/public/TensorFlow/TensorPair.swift
  test/TensorFlowRuntime/tensor_array_protocol.swift
  test/TensorFlowRuntime/tensor_group.swift
Labels: tensorflow
