Repository swiftlang/swift, pull requests merged in 2020-06, with the labels that each got.

#32081 Test C++ out-of-line operator functions
  test/Interop/Cxx/operators/Inputs/module.modulemap
  test/Interop/Cxx/operators/Inputs/non-member-out-of-line.cpp
  test/Interop/Cxx/operators/Inputs/non-member-out-of-line.h
  test/Interop/Cxx/operators/non-member-out-of-line-irgen.swift
  test/Interop/Cxx/operators/non-member-out-of-line-silgen.swift
  test/Interop/Cxx/operators/non-member-out-of-line.swift
Labels: C++ Interop

#32181 Revert "Test C++ out-of-line operator functions"
  test/Interop/Cxx/operators/Inputs/module.modulemap
  test/Interop/Cxx/operators/Inputs/non-member-out-of-line.cpp
  test/Interop/Cxx/operators/Inputs/non-member-out-of-line.h
  test/Interop/Cxx/operators/non-member-out-of-line-irgen.swift
  test/Interop/Cxx/operators/non-member-out-of-line-silgen.swift
  test/Interop/Cxx/operators/non-member-out-of-line.swift
Labels: C++ Interop

#31968 [5.3] IRGen: Always eliminate frame pointers of leaf functions
  include/swift/AST/IRGenOptions.h
  include/swift/Option/Options.td
  lib/Driver/ToolChains.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/IRGen/IRGenModule.cpp
  test/IRGen/c_globals.swift
  test/IRGen/framepointer.sil
  test/IRGen/framepointer_arm64.sil
  test/Misc/tbi.sil
Labels: r5.3

#32168 [5.3] Fix dynamic member lookup index-while-building crash
  lib/Sema/ConstraintSystem.cpp
  test/Index/index_keypath_member_lookup.swift
Labels: r5.3

#32186 Resubmit Interop/Cxx/operators/non-member-out-of-line-irgen.swift
  test/Interop/Cxx/operators/Inputs/module.modulemap
  test/Interop/Cxx/operators/Inputs/non-member-out-of-line.cpp
  test/Interop/Cxx/operators/Inputs/non-member-out-of-line.h
  test/Interop/Cxx/operators/non-member-out-of-line-irgen.swift
  test/Interop/Cxx/operators/non-member-out-of-line-silgen.swift
  test/Interop/Cxx/operators/non-member-out-of-line.swift
Labels: C++ Interop

#32190 [5.3][CSGen] Allow `is` patterns to infer type from enclosing context
  lib/Sema/CSGen.cpp
  test/Constraints/patterns.swift
Labels: r5.3

#32197 [5.3][Parse] Avoid delayed member parsing for type decl with missing brace
  include/swift/Parse/Parser.h
  lib/Parse/ParseDecl.cpp
  test/SourceKit/CodeComplete/complete_sequence_innertype.swift
Labels: r5.3

#32203 [5.3] The test framepointer_arm64.sil requires ios
  test/IRGen/framepointer_arm64.sil
Labels: r5.3

#32230 [Incremental compilation]: Merge pull request #32219 from davidungar/quick-dependency-bug-fix
  lib/AST/AbstractSourceFileDepGraphFactory.cpp
  test/Frontend/Fingerprints/class-fingerprint.swift
  test/Frontend/Fingerprints/enum-fingerprint.swift
  test/Frontend/Fingerprints/protocol-fingerprint.swift
  test/Frontend/Fingerprints/struct-fingerprint.swift
  unittests/Driver/TypeBodyFingerprintsDependencyGraphTests.cpp
Labels: r5.3

#32254 [czar][test] Disable multifile/batch-mode-llvmIRHash-consistency
  test/multifile/batch-mode-llvmIRHash-consistency.swift
Labels: r5.3

#32272 [5.3][CodeCompletion] Fix non-determinisc failures in dependency check tests
  test/SourceKit/CodeComplete/complete_checkdeps_bridged.swift
  test/SourceKit/CodeComplete/complete_checkdeps_clangmodule.swift
  test/SourceKit/CodeComplete/complete_checkdeps_otherfile.swift
  test/SourceKit/CodeComplete/complete_checkdeps_swiftmodule.swift
Labels: r5.3

#32271 [5.3][SourceKit] Disable complete_build_session.swift test file
  test/SourceKit/CodeComplete/complete_build_session.swift
Labels: r5.3

#32273 [5.3][memory-lifetime] Teach the verifier that select_enum_addr doesn't write to memory.
  lib/SIL/Verifier/SILVerifier.cpp
  test/SIL/memory_lifetime.sil
Labels: r5.3

#32300 [5.3] Mark non-foreign entry points of `@objc dynamic` methods in generic classes `dynamically_replaceable`
  include/swift/AST/Decl.h
  include/swift/Serialization/Validation.h
  lib/AST/ASTVerifier.cpp
  lib/AST/Decl.cpp
  lib/IRGen/GenArchetype.cpp
  lib/IRGen/GenDecl.cpp
  lib/IRGen/GenMeta.cpp
  lib/IRGen/GenObjC.cpp
  lib/SIL/IR/SILDeclRef.cpp
  lib/SIL/IR/SILFunctionBuilder.cpp
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenBridging.cpp
  lib/SILGen/SILGenConstructor.cpp
  lib/SILGen/SILGenFunction.cpp
  lib/SILGen/SILGenLValue.cpp
  lib/SILGen/SILGenPoly.cpp
  lib/SILGen/SILGenType.cpp
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/ResilienceDiagnostics.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckDecl.cpp
  lib/Sema/TypeCheckDeclObjC.cpp
  lib/Sema/TypeCheckDeclOverride.cpp
  lib/Sema/TypeCheckStorage.cpp
  lib/Serialization/ModuleFile.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/Serialization.cpp
  lib/Serialization/SerializedModuleLoader.cpp
  lib/TBDGen/TBDGen.cpp
  test/SILGen/Inputs/objc_dynamic_replacement_ext.swift
  test/SILGen/objc_dynamic_replacement_ext.swift
Labels: r5.3

#32207 [5.3][CodeCompletion] Wrap base expression with CodeCompletionExpr
  include/swift/AST/Expr.h
  lib/AST/ASTWalker.cpp
  lib/Parse/ParseExpr.cpp
  lib/Parse/ParseStmt.cpp
  lib/Sema/CSGen.cpp
  test/IDE/complete_enum_elements.swift
  test/IDE/complete_rdar63965160.swift
Labels: r5.3

#32316 [5.3][preset] Add missing libicu dependencies to package presets
  utils/build-presets.ini
Labels: r5.3

#32315 [5.3][SourceKit] Disable labeled trailing closure support except code completion
  include/swift/Parse/CodeCompletionCallbacks.h
  lib/IDE/CodeCompletion.cpp
  lib/Parse/ParseExpr.cpp
  test/IDE/conforming-methods-afterclosure.swift
Labels: r5.3

#32335 [cxx-interop] Add support for C++ logical and/or operators.
  lib/ClangImporter/ImportName.cpp
  test/Interop/Cxx/operators/Inputs/non-member-inline.h
  test/Interop/Cxx/operators/non-member-inline-module-interface.swift
  test/Interop/Cxx/operators/non-member-inline-typechecker.swift
  test/Interop/Cxx/operators/non-member-inline.swift
Labels: C++ Interop

#32333 [cxx-interop] Add support for C++ shift operators.
  lib/ClangImporter/ImportName.cpp
  test/Interop/Cxx/operators/Inputs/non-member-inline.h
  test/Interop/Cxx/operators/non-member-inline-module-interface.swift
  test/Interop/Cxx/operators/non-member-inline-typechecker.swift
  test/Interop/Cxx/operators/non-member-inline.swift
Labels: C++ Interop

#32343 [AutoDiff] Skip implicit `GenericTypeParamDecl` AST verification.
  lib/AST/ASTVerifier.cpp
Labels: tensorflow

#32332 [cxx-interop] Add support for percent, ampersand, and pipe operators.
  lib/ClangImporter/ImportName.cpp
  test/Interop/Cxx/operators/Inputs/non-member-inline.h
  test/Interop/Cxx/operators/non-member-inline-module-interface.swift
  test/Interop/Cxx/operators/non-member-inline-typechecker.swift
  test/Interop/Cxx/operators/non-member-inline.swift
Labels: C++ Interop

#32323 [5.3] [Function builders] Use one-way constraints for closure parameters.
  include/swift/Basic/LangOptions.h
  include/swift/Option/FrontendOptions.td
  lib/Frontend/CompilerInvocation.cpp
  lib/Sema/CSBindings.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/CSSolver.cpp
  lib/Sema/Constraint.cpp
  lib/Sema/Constraint.h
  test/Constraints/function_builder_diags.swift
  test/Constraints/function_builder_one_way.swift
  test/Constraints/one_way_closure_params.swift
Labels: r5.3

#31766 [5.3] Remove stray backtick in doc comment.
  stdlib/public/core/UnsafeBufferPointer.swift.gyb
Labels: r5.3

#32361 [5.3] [CS] Fix a crash in AllowArgumentMismatch
  lib/Sema/ConstraintSystem.cpp
  validation-test/compiler_crashers_2_fixed/sr12990.swift
Labels: r5.3

#32370 [5.3] [Runtime] Zero out the entire witness table during instantiation.
  stdlib/public/runtime/Metadata.cpp
Labels: r5.3

#31923 GSB: Fix maybeResolveEquivalenceClass() with member type of superclass-constrained type [5.3]
  lib/AST/GenericSignatureBuilder.cpp
  test/Constraints/same_types.swift
  test/Generics/Inputs/sr8945-other.swift
  test/Generics/sr8945.swift
  test/IDE/print_ast_tc_decls_errors.swift
  test/decl/protocol/req/recursion.swift
  validation-test/compiler_crashers_2_fixed/0159-rdar40009245.swift
  validation-test/compiler_crashers_2_fixed/0163-sr8033.swift
Labels: r5.3

#32422 [5.3][test/Syntax/round_trip_stdlib.swift] Exclude the test for an ASAN build
  test/Syntax/round_trip_stdlib.swift
Labels: r5.3

#32415 [5.3][CodeCompletion] Typecheck without CodeCompletionExpr
  lib/IDE/CodeCompletion.cpp
  lib/IDE/ExprContextAnalysis.cpp
  lib/IDE/ExprContextAnalysis.h
  test/IDE/complete_multiple_trailingclosure.swift
Labels: r5.3

#32432 [5.3][ModuleInterface] Prefer the swiftmodule in the SDK over the prebuilt-module cache
  lib/Frontend/ModuleInterfaceLoader.cpp
  test/ModuleInterface/loading-order.swift
Labels: r5.3

#32381 [5.3] MandatoryInlining: fix a memory lifetime bug related to partial_apply with in_guaranteed parameters.
  lib/SILOptimizer/Mandatory/MandatoryInlining.cpp
  test/SILOptimizer/mandatory_inlining.sil
Labels: r5.3

#32441 [5.3][CodeCompletion] Suggest 'macOS' instead of 'OSX'
  lib/IDE/CodeCompletion.cpp
  test/IDE/complete_decl_attribute.swift
  test/IDE/complete_pound_statement.swift
Labels: r5.3

#32351 [cxx-interop] Add support for C++ comparison operators.
  lib/ClangImporter/ImportName.cpp
  test/Interop/Cxx/operators/Inputs/non-member-inline.h
  test/Interop/Cxx/operators/non-member-inline-module-interface.swift
  test/Interop/Cxx/operators/non-member-inline-typechecker.swift
  test/Interop/Cxx/operators/non-member-inline.swift
Labels: C++ Interop

#32489 GSB: Teach 'derived via concrete' computation about superclass constraints [5.3]
  lib/AST/GenericSignatureBuilder.cpp
  test/Generics/superclass_constraint_self_derived.swift
  test/SILGen/class_conforms_with_default_implementation.swift
  validation-test/compiler_crashers_2_fixed/sr11108.swift
Labels: r5.3

#32491 [5.3][CSApply] Always try to load arguments constructing object literals
  lib/Sema/CSApply.cpp
  test/Sema/object_literals_osx.swift
Labels: r5.3

#32490 [5.3][ConstraintSystem] Don't propagate holes through supertype inference
  lib/Sema/CSBindings.cpp
  test/Constraints/overload.swift
Labels: r5.3

#32532 [5.3][CodeCompletion] Assume non-'isSimpleDidSet' in code completion
  lib/Sema/TypeCheckDecl.cpp
  test/IDE/complete_in_accessors.swift
Labels: r5.3

#32526 [5.3][CodeCompletion] Fallback to nominal member completion after trailing closure
  lib/IDE/CodeCompletion.cpp
  lib/Parse/ParseExpr.cpp
  test/IDE/complete_multiple_trailingclosure.swift
Labels: r5.3

#32533 [5.3][SourceKit/Indentation] Fix over-indent after function declaration with no param list or body.
  lib/IDE/Formatting.cpp
  test/swift-indent/basic.swift
Labels: r5.3

#32570 [5.3] test: xfail Driver/SourceRanges/range-lifecycle.swift
  test/Driver/SourceRanges/range-lifecycle.swift
Labels: r5.3

#32552 Revert "[Sema] Fix leak of implementation-only imported types in SPI signatures"
  lib/Sema/TypeCheckAccess.cpp
  test/SPI/implementation_only_spi_import_exposability.swift
Labels: r5.3

#32534 [cxx-interop] Do not give the default C++ constructor's return statement a result.
  lib/ClangImporter/ImportDecl.cpp
  validation-test/SILGen/Inputs/cxx-types.h
  validation-test/SILGen/Inputs/module.modulemap
  validation-test/SILGen/cxx-address-only-object-init.swift
Labels: C++ Interop

#32566 [5.3] [Function builders] Run syntactic diagnostics for function bodies.
  lib/Sema/BuilderTransform.cpp
  test/decl/var/function_builders_availability.swift
Labels: r5.3

#32583 [5.3][SourceKit/CodeFormat] Fix multi-line array literal elements not indenting relative to their first line.
  lib/IDE/Formatting.cpp
  test/swift-indent/basic.swift
Labels: r5.3

#32603 [5.3][SourceKit/CursorInfo] Still print implicit decls in cursorinfo to handle compiler synthesized decls
  test/SourceKit/CursorInfo/cursor_info_synthesized_refs.swift
  tools/SourceKit/lib/SwiftLang/SwiftSourceDocInfo.cpp
Labels: r5.3

#32608 [5.3][Function Builders] Fix a function builder crash due to constraint generation failures
  lib/Sema/BuilderTransform.cpp
  test/Constraints/function_builder_diags.swift
Labels: r5.3

#32579 [5.3][SourceKit] Enable ASTContext caching in other completion-like requests
  include/swift/IDE/ConformingMethodList.h
  include/swift/IDE/TypeContextInfo.h
  test/SourceKit/ConformingMethods/basic.swift
  test/SourceKit/ConformingMethods/basic.swift.response
  test/SourceKit/Misc/mixed_completion_sequence.swift
  test/SourceKit/Misc/mixed_completion_sequence.swift.response
  test/SourceKit/TypeContextInfo/typecontext_basic.swift
  test/SourceKit/TypeContextInfo/typecontext_basic.swift.response
  tools/SourceKit/include/SourceKit/Core/LangSupport.h
  tools/SourceKit/lib/SwiftLang/SwiftConformingMethodList.cpp
  tools/SourceKit/lib/SwiftLang/SwiftLangSupport.h
  tools/SourceKit/lib/SwiftLang/SwiftTypeContextInfo.cpp
  tools/SourceKit/tools/sourcekitd-test/sourcekitd-test.cpp
  tools/SourceKit/tools/sourcekitd/lib/API/Requests.cpp
  utils/gyb_sourcekit_support/UIDs.py
Labels: r5.3

#32624 [5.3][CSGen] Handle incorrect patterns (e.g. referencing unknown types)
  lib/Sema/CSGen.cpp
  test/Constraints/patterns.swift
Labels: r5.3
