Repository swiftlang/swift, pull requests merged in 2020-07, with the labels that each got.

#32640 [AutoDiff] Fix protocol witness SILGen for `@differentiable` class methods.
  include/swift/SIL/SILDeclRef.h
  lib/SILGen/SILGenPoly.cpp
  test/AutoDiff/compiler_crashers_fixed/tf1180-silgen-vtable-method-does-not-appear.swift
Labels: tensorflow

#32597 [5.3][RemoteMirror] Gracefully handle a NULL TypeInfo passed to convertChild.
  stdlib/public/SwiftRemoteMirror/SwiftRemoteMirror.cpp
Labels: r5.3

#32641 [5.3] Loosen a CopyForwarding assert: store instead of deinit.
  lib/SILOptimizer/Transforms/CopyForwarding.cpp
  test/SILOptimizer/copyforward.sil
Labels: r5.3

#32650 [5.3][CodeCompletion] Force apply a viable solution even if ambiguous
  lib/Sema/CSGen.cpp
  lib/Sema/CSRanking.cpp
  lib/Sema/ConstraintSystem.h
  test/IDE/complete_builder_multiviable.swift
Labels: r5.3

#32647 [5.3] [stdlib] Performance fixes for removeFirst and removeLast
  stdlib/public/core/BidirectionalCollection.swift
  stdlib/public/core/Collection.swift
  stdlib/public/core/RangeReplaceableCollection.swift
Labels: r5.3

#32671 [AutoDiff] Fix unexpected non-differentiable property access error.
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  include/swift/SILOptimizer/Differentiation/Common.h
  lib/AST/AutoDiff.cpp
  lib/SILOptimizer/Differentiation/Common.cpp
  lib/SILOptimizer/Differentiation/JVPEmitter.cpp
  lib/SILOptimizer/Differentiation/PullbackEmitter.cpp
  lib/Sema/DerivedConformanceDifferentiable.cpp
  test/AutoDiff/SILOptimizer/differentiation_diagnostics.swift
Labels: tensorflow

#31979 [5.3] Fix NULL deref for invalid mangled input (#31878)
  lib/Demangling/Demangler.cpp
  test/Demangle/Inputs/manglings.txt
Labels: r5.3

#32663 [5.3] Use Formal Access To Compute Override Elision Check
  lib/AST/Attr.cpp
  test/ModuleInterface/skip-override-keyword.swift
Labels: r5.3

#32636 [5.3] Improved codgen for FP inits from Integer
  stdlib/public/Darwin/CoreGraphics/CGFloat.swift.gyb
  stdlib/public/core/FloatingPoint.swift
  stdlib/public/core/FloatingPointTypes.swift.gyb
Labels: r5.3

#32665 [5.3] AST: isEquivalentToExtendedContext() should consider use patterns of @_originallyDefinedIn
  lib/AST/Decl.cpp
  test/TBD/move_to_extension.swift
Labels: r5.3

#32686 Disable a RUN line in osx-targets.swift
  test/IRGen/osx-targets.swift
Labels: r5.3

#32655 [5.3] [sourcekit] Retain semantic annotations across queries
  test/SourceKit/Sema/sema_annotations_saved.swift
  test/SourceKit/Sema/sema_annotations_saved.swift.response
  tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp
Labels: r5.3

#32687 [5.3] Front-end: disable interface file locking for the -compile-module-from-interface action
  lib/Frontend/ArgsToFrontendOptionsConverter.cpp
Labels: r5.3

#32693 [5.3] [CS] Avoid checking RHS of one-way constraint for reactivation
  lib/Sema/ConstraintGraph.cpp
  test/Constraints/rdar64890308.swift
Labels: r5.3

#32293 Import member operator functions as static members
  include/swift/SIL/AbstractionPattern.h
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImportName.cpp
  lib/ClangImporter/ImportType.cpp
  lib/ClangImporter/SwiftLookupTable.cpp
  lib/ClangImporter/SwiftLookupTable.h
  lib/SIL/IR/AbstractionPattern.cpp
  lib/SIL/IR/SILFunctionType.cpp
  test/Interop/Cxx/operators/Inputs/member-inline.h
  test/Interop/Cxx/operators/Inputs/module.modulemap
  test/Interop/Cxx/operators/member-inline-irgen.swift
  test/Interop/Cxx/operators/member-inline-module-interface.swift
  test/Interop/Cxx/operators/member-inline-silgen.swift
  test/Interop/Cxx/operators/member-inline-typechecker.swift
  test/Interop/Cxx/operators/member-inline.swift
Labels: C++ Interop

#32699 Add bug reference to XFAIL operator tests
  test/Interop/Cxx/operators/member-inline-irgen.swift
  test/Interop/Cxx/operators/member-inline.swift
Labels: C++ Interop

#32658 [NFC] [cxx-interop] Add SILGen tests for synthesized initializers.
  test/Interop/Cxx/class/Inputs/module.modulemap
  test/Interop/Cxx/class/Inputs/synthesized-initializers.h
  test/Interop/Cxx/class/synthesized-initializers.swift
Labels: C++ Interop

#32600 [5.3] parse COW support builtins as no-ops
  include/swift/AST/Builtins.def
  lib/AST/Builtins.cpp
  lib/SILGen/SILGenBuiltin.cpp
  lib/SILOptimizer/Analysis/ArraySemantic.cpp
  test/IRGen/builtins.swift
  test/SILGen/builtins.swift
Labels: r5.3

#31973 [5.3] OOB read in demangler with corrupted input
  include/swift/Demangling/Demangler.h
  lib/Demangling/Demangler.cpp
Labels: r5.3

#32728 [5.3][CSBindings] Open collection binding associated with @autoclosure argument
  lib/Sema/CSBindings.cpp
  test/Constraints/keyword_arguments.swift
Labels: r5.3

#32718 Add tests for C++ out-of-line member operators
  test/Interop/Cxx/operators/Inputs/member-out-of-line.cpp
  test/Interop/Cxx/operators/Inputs/member-out-of-line.h
  test/Interop/Cxx/operators/Inputs/module.modulemap
  test/Interop/Cxx/operators/member-out-of-line-irgen.swift
  test/Interop/Cxx/operators/member-out-of-line-silgen.swift
  test/Interop/Cxx/operators/member-out-of-line.swift
Labels: C++ Interop

#32734 cherry-pick fix that enables optimization in REPL and jupyter
  utils/update_checkout/update-checkout-config.json
Labels: tensorflow

#32656 [verifier] [cxx-interop] Remove empty return result from constructors.
  lib/AST/ASTVerifier.cpp
  lib/ClangImporter/ImportDecl.cpp
Labels: C++ Interop

#32741 [5.3][Sema] Mark the direct callee as being a callee for all ApplyExpr not just CallExpr
  lib/Sema/TypeCheckConstraints.cpp
  test/Constraints/operator.swift
Labels: r5.3

#32715 [cxx-interop] [nfc] Remove swift namespace from SwiftShims in C++ mode.
  stdlib/public/SwiftShims/AssertionReporting.h
  stdlib/public/SwiftShims/CoreFoundationShims.h
  stdlib/public/SwiftShims/DispatchOverlayShims.h
  stdlib/public/SwiftShims/FoundationShims.h
  stdlib/public/SwiftShims/LibcShims.h
  stdlib/public/SwiftShims/Random.h
  stdlib/public/SwiftShims/RuntimeShims.h
  stdlib/public/SwiftShims/RuntimeStubs.h
  stdlib/public/SwiftShims/UnicodeShims.h
  stdlib/public/runtime/BackDeployment.cpp
  stdlib/public/stubs/Assert.cpp
  stdlib/public/stubs/Availability.mm
  stdlib/public/stubs/FoundationHelpers.mm
  stdlib/public/stubs/GlobalObjects.cpp
  stdlib/public/stubs/LibcShims.cpp
  stdlib/public/stubs/Random.cpp
  stdlib/public/stubs/Stubs.cpp
  stdlib/public/stubs/UnicodeNormalization.cpp
Labels: C++ Interop

#32749 [5.3][Index] Fast path for getting value member
  lib/Sema/CSGen.cpp
Labels: r5.3

#32692 ClangImporter: Preserve CChar type
  include/swift/ClangImporter/BuiltinMappedTypes.def
  lib/ClangImporter/ImportType.cpp
  test/ClangImporter/ctypes_parse.swift
  test/ClangImporter/ctypes_parse_swift4.swift
  test/IDE/infer_import_as_member.swift
  test/IDE/print_omit_needless_words.swift
  test/IDE/print_omit_needless_words_appkit.swift
  test/Interop/C/chars/Inputs/import-cchar-types.h
  test/Interop/C/chars/Inputs/module.modulemap
  test/Interop/C/chars/import-cchar-types.swift
  test/SourceKit/DocSupport/doc_clang_module.swift.response
  test/SourceKit/InterfaceGen/gen_clang_module.swift.response
Labels: C++ Interop

#32739 [Runtime] Fix SWIFT_ISA_MASK for ARM64 simulators.
  stdlib/public/runtime/Private.h
Labels: r5.3

#32768 [5.3] [AssociatedTypeInference] Strip 'self' parameter from function type of an enum case witness
  lib/Sema/TypeCheckProtocolInference.cpp
  test/decl/protocol/req/associated_type_inference.swift
Labels: r5.3

#32766 [5.3][CodeCompletion] Remove redundant entries from possible callee analysis
  lib/IDE/ExprContextAnalysis.cpp
  test/IDE/complete_expr_after_paren.swift
Labels: r5.3

#32764 [5.3] [Build System] Support host target prefix in symbols package
  utils/build-script
Labels: r5.3

#30914 Link against the C++ standard library when C++ interop is enabled
  include/swift/AST/DiagnosticsDriver.def
  include/swift/Driver/ToolChain.h
  include/swift/Option/Options.td
  lib/Driver/DarwinToolChains.cpp
  lib/Driver/ToolChains.cpp
  lib/Driver/UnixToolChains.cpp
  lib/Driver/WindowsToolChains.cpp
  test/Driver/cxx_interop.swift
  test/Driver/linker.swift
Labels: C++ Interop

#32783 Rename synthesized initializer test to follow the pattern
  test/Interop/Cxx/class/synthesized-initializers-silgen.swift
  validation-test/SILGen/Inputs/cxx-types.h
  validation-test/SILGen/Inputs/module.modulemap
  validation-test/SILGen/cxx-address-only-object-init.swift
Labels: C++ Interop

#32402 [cxx-interop] Mark types with a destructor a non-trivial.
  lib/SIL/IR/TypeLowering.cpp
  test/Interop/Cxx/class/Inputs/module.modulemap
  test/Interop/Cxx/class/Inputs/type-classification.h
  test/Interop/Cxx/class/type-classification-loadable-silgen.swift
  test/Interop/Cxx/class/type-classification-non-trivial-silgen.swift
Labels: C++ Interop

#32820 [5.3][CodeCompletion] Safer getEquivalentDeclContextFromSourceFile()
  lib/IDE/CompletionInstance.cpp
Labels: r5.3

#32823 [5.3] Handle Boolean Patterns Matching Against Invalid Constructor Forms
  lib/Sema/TypeCheckSwitchStmt.cpp
  validation-test/compiler_crashers_2_fixed/rdar65229620.swift
Labels: r5.3

#32832 [5.3] Availability-related fixes with keypaths, _modify, and/or property wrappers
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintSystem.h
  lib/Sema/TypeCheckStorage.cpp
  test/Sema/generalized_accessors_availability.swift
  test/expr/unary/keypath/keypath-availability.swift
Labels: r5.3

#32853 [Test] Un-Xfail ParseableInterface/verify_all_overlays.py.
  validation-test/ParseableInterface/verify_all_overlays.py
Labels: r5.3

#32864 [Test] Loosen Generics/deduction.swift expectation.
  test/Generics/deduction.swift
Labels: r5.3

#32863 [Test] Disable two tests that hang asan bots.
  validation-test/compiler_crashers_2/0207-sr7371.swift
  validation-test/compiler_crashers_2/0208-sr8751.swift
Labels: r5.3

#32867 [5.3][ASTPrinter][IDE] Print PlatformKind::OSX as "macOS" rather than "OSX" in generated interfaces
  include/swift/AST/Attr.h
  include/swift/AST/PlatformKind.h
  include/swift/AST/PrintOptions.h
  lib/AST/Attr.cpp
  lib/AST/PlatformKind.cpp
  test/IDE/print_swift_module_with_available.swift
  test/IDE/print_synthesized_extensions_nomerge.swift
  test/SourceKit/DocSupport/doc_swift_module.swift.response
  test/SourceKit/InterfaceGen/gen_clang_module.swift.response
Labels: r5.3

#32809 [5.3][Foundation] Update & simplify class name stability check
  include/swift/Runtime/FoundationSupport.h
  stdlib/public/Darwin/Foundation/CMakeLists.txt
  stdlib/public/Darwin/Foundation/CheckClass.mm
  stdlib/public/Darwin/Foundation/CheckClass.swift
  stdlib/public/SwiftShims/FoundationOverlayShims.h
  stdlib/public/runtime/CMakeLists.txt
  stdlib/public/runtime/FoundationSupport.cpp
  test/Interpreter/SDK/check_class_for_archiving.swift
  test/Interpreter/SDK/check_class_for_archiving_log.swift
Labels: r5.3

#32796 [5.3][ModuleInterface] Don't print SPI attributes on unsupported decls
  lib/AST/ASTPrinter.cpp
  test/SPI/private_swiftinterface.swift
Labels: r5.3

#32878 [5.3] ModuleInterface: teach the compiler to look into SDK-versioned prebuilt module cache dir
  lib/Frontend/CompilerInvocation.cpp
  test/ModuleInterface/default-prebuilt-module-location-sdk-versioned.swift
Labels: r5.3

#32889 [5.3] Revert "Merge pull request #32655 from benlangmuir/sema-repeat-53"
  test/SourceKit/Sema/sema_annotations_saved.swift
  test/SourceKit/Sema/sema_annotations_saved.swift.response
  tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp
Labels: r5.3

#32881 [5.3] IRGen: Name the symbol for the private use area attached to protocol conformance descriptors.
  docs/ABI/Mangling.rst
  include/swift/Demangling/DemangleNodes.def
  lib/Demangling/Demangler.cpp
  lib/Demangling/NodePrinter.cpp
  lib/Demangling/OldRemangler.cpp
  lib/Demangling/Remangler.cpp
  lib/IRGen/GenProto.cpp
  lib/IRGen/IRGenMangler.cpp
  lib/IRGen/IRGenMangler.h
  test/IRGen/protocol_resilience_descriptors.swift
Labels: r5.3

#32883 [5.3][Sema] Only require a default implementation for SPI requirements in non-SPI protocols
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckProtocol.cpp
  test/SPI/protocol_requirement.swift
Labels: r5.3

#32904 [5.3][CodeCompletion] Fix a crash in CCExprRemover
  lib/IDE/ExprContextAnalysis.cpp
  validation-test/IDE/crashers_2_fixed/rdar65556791.swift
Labels: r5.3

#32759 [5.3] [Runtime] Let existential types satisfy superclass requirements.
  stdlib/public/runtime/ProtocolConformance.cpp
  validation-test/Runtime/rdar64672291.swift
Labels: r5.3

#31908 [5.3] [SR-12842] Restore missing docs for RangeExpression.~=
  stdlib/public/core/Range.swift
Labels: r5.3

#32921 [Test] Disabled rdar64672291.swift when appropriate.
  validation-test/Runtime/rdar64672291.swift
Labels: r5.3

#32929 [5.3][stdlib] Make _convertConstStringToUTF8PointerArgument transparent
  stdlib/public/core/Pointer.swift
Labels: r5.3

#32700 Revise #file changes from SE-0274
  include/swift/AST/DefaultArgumentKind.h
  include/swift/AST/DiagnosticsCommon.def
  include/swift/AST/DiagnosticsDriver.def
  include/swift/AST/Expr.h
  include/swift/AST/MagicIdentifierKinds.def
  include/swift/AST/Module.h
  include/swift/Option/Options.td
  lib/AST/ASTDumper.cpp
  lib/AST/ASTPrinter.cpp
  lib/AST/Decl.cpp
  lib/AST/Module.cpp
  lib/IDE/CodeCompletion.cpp
  lib/Parse/ParseExpr.cpp
  lib/Parse/ParsePattern.cpp
  lib/SIL/IR/SILPrinter.cpp
  lib/SILGen/SILGen.cpp
  lib/SILGen/SILGen.h
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenConvert.cpp
  lib/SILGen/SILGenExpr.cpp
  lib/SILGen/SILGenFunction.h
  lib/Sema/CSApply.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/CodeSynthesis.cpp
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/TypeCheckExpr.cpp
  lib/Sema/TypeChecker.cpp
  lib/Serialization/Deserialization.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/Serialization.cpp
  stdlib/public/core/CMakeLists.txt
  test/IDE/complete_pound_expr.swift
  test/SILGen/Inputs/MagicIdentifierFileSwift.swift
  test/SILGen/Inputs/magic_identifier_file_conflicting_other.swift
  test/SILGen/enum_debuginfo.swift
  test/SILGen/magic_identifier_file.swift
  test/SILGen/magic_identifier_file_conflicting.swift.gyb
  test/SILGen/optional.swift
  test/SILOptimizer/Inputs/specialize_inherited_multifile_other.swift
  test/SILOptimizer/specialize_inherited_multifile.swift
  test/Sema/diag_mismatched_magic_literals.swift
  test/Sema/diag_mismatched_magic_literals_swift5.swift
  test/Sema/diag_mismatched_magic_literals_swift6.swift
  test/Serialization/Inputs/multi-file-type-eraser-other.swift
  test/Serialization/multi-file-type-eraser.swift
  test/stdlib/Error.swift
  utils/gyb_syntax_support/ExprNodes.py
  utils/gyb_syntax_support/NodeSerializationCodes.py
  utils/gyb_syntax_support/Token.py
Labels: swift-evolution-approved

#32936 [5.3] Avoid creating a ConcurrentMap for nongeneric instantiated witness tables
  stdlib/public/runtime/Metadata.cpp
Labels: r5.3

#32934 [5.3][Sema] SPI info on a wrapped property should propagate to the backing storage
  lib/AST/Module.cpp
  test/SPI/private_swiftinterface.swift
Labels: r5.3

#32902 [5.3][ModuleInterface] Print some implementation-only imports in the private interface
  include/swift/Frontend/ModuleInterfaceSupport.h
  include/swift/Option/FrontendOptions.td
  lib/Frontend/CompilerInvocation.cpp
  lib/Frontend/ModuleInterfaceSupport.cpp
  test/SPI/experimental_spi_imports_swiftinterface.swift
  test/SPI/experimental_spi_imports_type_check.swift
Labels: r5.3

#32952 [5.3][CodeCompletion] Fast completion inside function builder function
  include/swift/AST/Stmt.h
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/Sema/BuilderTransform.cpp
  test/SourceKit/CodeComplete/complete_sequence_builderfunc.swift
Labels: r5.3

#32957 [5.3] Refactor Mirror to reduce metadata allocation
  stdlib/public/core/CMakeLists.txt
  stdlib/public/core/DebuggerSupport.swift
  stdlib/public/core/Dump.swift
  stdlib/public/core/EitherSequence.swift
  stdlib/public/core/GroupInfo.json
  stdlib/public/core/Mirror.swift
  stdlib/public/core/OutputStream.swift
  stdlib/public/core/ReflectionMirror.swift
Labels: r5.3

#32958 [5.3] Add fast string interpolation for metatypes
  stdlib/public/core/StringInterpolation.swift
  test/IDE/complete_at_top_level.swift
  test/stdlib/TypeNameInterpolation.swift
Labels: r5.3

#32811 [5.3] Revise #file changes from SE-0274
  include/swift/AST/DefaultArgumentKind.h
  include/swift/AST/DiagnosticsCommon.def
  include/swift/AST/DiagnosticsDriver.def
  include/swift/AST/Expr.h
  include/swift/AST/MagicIdentifierKinds.def
  include/swift/AST/Module.h
  include/swift/Option/Options.td
  lib/AST/ASTDumper.cpp
  lib/AST/ASTPrinter.cpp
  lib/AST/Decl.cpp
  lib/AST/Module.cpp
  lib/IDE/CodeCompletion.cpp
  lib/Parse/ParseExpr.cpp
  lib/Parse/ParsePattern.cpp
  lib/SIL/IR/SILPrinter.cpp
  lib/SILGen/SILGen.cpp
  lib/SILGen/SILGen.h
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenConvert.cpp
  lib/SILGen/SILGenExpr.cpp
  lib/SILGen/SILGenFunction.h
  lib/Sema/CSApply.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/CodeSynthesis.cpp
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/TypeCheckExpr.cpp
  lib/Sema/TypeChecker.cpp
  lib/Serialization/Deserialization.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/Serialization.cpp
  stdlib/public/core/CMakeLists.txt
  test/IDE/complete_pound_expr.swift
  test/SILGen/Inputs/MagicIdentifierFileSwift.swift
  test/SILGen/Inputs/magic_identifier_file_conflicting_other.swift
  test/SILGen/magic_identifier_file.swift
  test/SILGen/magic_identifier_file_conflicting.swift.gyb
  test/SILGen/optional.swift
  test/SILOptimizer/Inputs/specialize_inherited_multifile_other.swift
  test/SILOptimizer/specialize_inherited_multifile.swift
  test/Sema/diag_mismatched_magic_literals.swift
  test/Sema/diag_mismatched_magic_literals_swift5.swift
  test/Sema/diag_mismatched_magic_literals_swift6.swift
  test/Serialization/Inputs/multi-file-type-eraser-other.swift
  test/Serialization/multi-file-type-eraser.swift
  test/stdlib/Error.swift
  utils/gyb_syntax_support/ExprNodes.py
  utils/gyb_syntax_support/NodeSerializationCodes.py
  utils/gyb_syntax_support/Token.py
Labels: r5.3, swift-evolution-approved

#32949 [5.3] [SIL] Fix a regression with optional class-constrained unowned property
  lib/SIL/IR/TypeLowering.cpp
  test/SILGen/unowned.swift
Labels: r5.3

#32943 GSB: Fix use-after-free error when vending ResolvedType [5.3]
  lib/AST/GenericSignatureBuilderImpl.h
  validation-test/compiler_crashers_2_fixed/rdar65040635.swift
  validation-test/compiler_crashers_2_fixed/sr12812.swift
Labels: r5.3

#32962 [5.3] SILOptimizer: A new "TempLValueOpt" optimization for copy_addr
  include/swift/SIL/SILInstruction.h
  include/swift/SILOptimizer/PassManager/Passes.def
  lib/SILOptimizer/Analysis/AliasAnalysis.cpp
  lib/SILOptimizer/Analysis/MemoryBehavior.cpp
  lib/SILOptimizer/PassManager/PassPipeline.cpp
  lib/SILOptimizer/Transforms/CMakeLists.txt
  lib/SILOptimizer/Transforms/TempLValueOpt.cpp
  test/SILOptimizer/basic-aa.sil
  test/SILOptimizer/mem-behavior-all.sil
  test/SILOptimizer/temp_rvalue_opt.sil
  test/SILOptimizer/templvalueopt.sil
  test/SILOptimizer/templvalueopt.swift
Labels: r5.3

#33008 [5.3] Reflection Library crash inspecting certain BoundGeneric types (#32983)
  stdlib/public/Reflection/TypeRef.cpp
Labels: r5.3

#32995 [5.3] [Function builders] Use buildLimitedAvailability() for #available block
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/KnownIdentifiers.def
  lib/Sema/BuilderTransform.cpp
  test/Constraints/function_builder_availability.swift
Labels: r5.3

#32908 [Sema][os_log] Allow wrapping os_log strings within constant evaluable functions
  lib/Sema/ConstantnessSemaDiagnostics.cpp
  test/SILOptimizer/OSLogMandatoryOptTest.swift
  test/Sema/diag_constantness_check_os_log.swift
Labels: r5.3

#33041 [5.3] [CS] Emit syntactic diagnostics for for loop where clauses
  lib/Sema/ConstraintSystem.h
  lib/Sema/TypeCheckConstraints.cpp
  test/Constraints/availability.swift
Labels: r5.3

#32815 [cxx-interop] Temporarily disable emitting debug info for C++ types.
  lib/IRGen/IRGenDebugInfo.cpp
  lib/IRGen/IRGenSIL.cpp
  test/Interop/Cxx/class/Inputs/debug-info.h
  test/Interop/Cxx/class/Inputs/module.modulemap
  test/Interop/Cxx/class/debug-info-irgen.swift
Labels: C++ Interop

#33056 [5.3][fso] Do not try to specialize pseudo-generic functions today.
  lib/SILOptimizer/FunctionSignatureTransforms/FunctionSignatureOpts.cpp
  test/SILOptimizer/funcsig_pseudogenerics.sil
  test/lit.cfg
Labels: r5.3

#33077 [cxx-interop] Rename ClangRecordTypeInfo -> LoadableClangRecordTypeInfo.
  lib/IRGen/GenStruct.cpp
Labels: C++ Interop

#33084 [5.3][CSGen] Add a null check to prevent using invalid superclass type
  lib/Sema/CSGen.cpp
  test/Constraints/super_method.swift
Labels: r5.3

#33026 [5.3][build] Fix --skip-build-llvm so that its minimal targets, like tblgen, are still built
  test/lit.cfg
  test/lit.site.cfg.in
  utils/build-script-impl
  utils/swift_build_support/swift_build_support/cmake.py
  validation-test/BuildSystem/skip_cmark_swift_llvm.test-sh
  validation-test/lit.site.cfg.in
Labels: r5.3

#32965 [5.3][stdlib] Add _forEachField(of:options:body:) function (#32873)
  stdlib/public/core/ReflectionMirror.swift
  stdlib/public/runtime/ReflectionMirror.mm
  test/stdlib/ForEachField.swift
Labels: r5.3

#33155 [build-script] copy over the simulator libclang_rt.*.a libraries to a…
  utils/build-script-impl
Labels: r5.3

#33094 [5.3] [SE-0286] Trailing closure forward scan
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/Types.h
  include/swift/Basic/LangOptions.h
  include/swift/Option/Options.td
  lib/AST/Expr.cpp
  lib/AST/Type.cpp
  lib/Driver/ToolChains.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSFix.h
  lib/Sema/CSGen.cpp
  lib/Sema/CSRanking.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/CSSolver.cpp
  lib/Sema/Constraint.cpp
  lib/Sema/Constraint.h
  lib/Sema/ConstraintSystem.h
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/TypeCheckConstraints.cpp
  test/Constraints/closures.swift
  test/Constraints/diag_missing_arg.swift
  test/Constraints/diagnostics.swift
  test/Constraints/one_way_solve.swift
  test/Constraints/overload_filtering.swift
  test/Parse/multiple_trailing_closures.swift
  test/expr/closure/trailing.swift
  test/expr/postfix/call/forward_trailing_closure.swift
  test/expr/postfix/call/forward_trailing_closure_ambiguity.swift
  test/expr/postfix/call/forward_trailing_closure_errors.swift
  test/expr/postfix/call/forward_trailing_closure_fuzzy.swift
Labels: r5.3

#32661 Fix typo in 'KeyedEncodingContainer.superEncoder' documentation.
  stdlib/public/core/Codable.swift
Labels: r5.3

#33162 [5.3][AST] Mark repr invalid only if `@autoclosure` parameter doesn't poin…
  lib/Sema/TypeCheckType.cpp
  test/attr/attr_autoclosure.swift
Labels: r5.3

#33174 [5.3][Function Builders] Teach diagnostics about function builder body result types...
  lib/Sema/BuilderTransform.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/ConstraintLocator.cpp
  lib/Sema/ConstraintLocator.h
  lib/Sema/ConstraintLocatorPathElts.def
  test/Constraints/function_builder_diags.swift
Labels: r5.3

#33104 Only execute test for supported simulator plaforms
  test/Constraints/trailing_closures_objc.swift
  utils/swift_build_support/swift_build_support/host_specific_configuration.py
  validation-test/Sema/SwiftUI/rdar57201781.swift
Labels: r5.3

#33172 [5.3][Serialization] Add option to load swiftmodule files as volatile and avoid mmap
  include/swift/Basic/LangOptions.h
  include/swift/Option/FrontendOptions.td
  lib/Frontend/CompilerInvocation.cpp
  lib/Serialization/SerializedModuleLoader.cpp
Labels: r5.3

#33173 [5.3] Adjust to simulator compiler-rt change
  include/swift/Basic/Platform.h
  lib/Basic/Platform.cpp
  lib/Driver/DarwinToolChains.cpp
  test/Driver/linker-clang_rt.swift
Labels: r5.3

#33184 [5.3] Add missing `-f` to check which checks if a compiler-rt archive…
  utils/build-script-impl
Labels: r5.3

#33209 [5.3][SourceKit] Fix issue where `CompletionCheckDependencyInterval` is set to 0 when the global config request is sent
  test/SourceKit/CodeComplete/complete_checkdeps_avoid_check.swift
  tools/SourceKit/tools/sourcekitd/lib/API/Requests.cpp
Labels: r5.3

#33193 [5.3] IRGen: Give ObjC metadata symbols internal linkage.
  lib/IRGen/GenClass.cpp
  test/IRGen/class.sil
  test/IRGen/class_update_callback_with_fixed_layout.sil
  test/IRGen/class_update_callback_with_stub.swift
  test/IRGen/class_update_callback_without_fixed_layout.sil
  test/IRGen/generic_casts.swift
  test/IRGen/metadata.swift
  test/IRGen/objc_attr_NSManaged.sil
  test/IRGen/objc_bridge.swift
  test/IRGen/objc_class_empty_fields.swift
  test/IRGen/objc_class_export.swift
  test/IRGen/objc_class_property.swift
  test/IRGen/objc_extensions.swift
  test/IRGen/objc_int_encoding.sil
  test/IRGen/objc_methods.swift
  test/IRGen/objc_properties.swift
  test/IRGen/objc_protocol_extended_method_types.swift
  test/IRGen/objc_protocols.swift
  test/IRGen/objc_runtime_name_attr.swift
  test/IRGen/objc_subclass.swift
  test/IRGen/objc_subscripts.swift
  test/IRGen/objc_type_encoding.swift
  test/IRGen/protocol_metadata.swift
  test/IRGen/subclass.swift
  test/decl/protocol/special/JSExport.swift
Labels: r5.3

#33210 [5.3][CodeCompletion] Fix issue in dependency checking for the editing file
  lib/IDE/CompletionInstance.cpp
  test/SourceKit/CodeComplete/complete_checkdeps_ownfile.swift
Labels: r5.3

#33177 [5.3] Mark main() as used
  lib/IRGen/GenDecl.cpp
  test/IRGen/unused.sil
Labels: r5.3

#33213 [5.3][Sema] Warn on exporting implementation-only imported types in SPI
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckAccess.cpp
  test/SPI/implementation_only_spi_import_exposability.swift
Labels: r5.3

#33219 [5.3][CodeCompletion] Handle @autoclosure in context type analysis
  lib/IDE/ExprContextAnalysis.cpp
  test/IDE/complete_unresolved_members.swift
Labels: r5.3
