Repository swiftlang/swift, pull requests merged in 2020-04, with the labels that each got.

#30760 Removing _ExpressibleByTensorFlowOp since #tfop is gone
  stdlib/public/core/CompilerProtocols.swift
Labels: tensorflow

#30130 Add Float16 to stdlib
  include/swift/ClangImporter/BuiltinMappedTypes.def
  lib/ClangImporter/ImportType.cpp
  lib/SILOptimizer/Utils/ConstantFolding.cpp
  stdlib/public/SwiftShims/RuntimeShims.h
  stdlib/public/core/CTypes.swift
  stdlib/public/core/Codable.swift
  stdlib/public/core/FloatingPointParsing.swift.gyb
  stdlib/public/core/FloatingPointTypes.swift.gyb
  stdlib/public/core/IntegerTypes.swift.gyb
  stdlib/public/core/Runtime.swift
  stdlib/public/core/SIMDVectorTypes.swift.gyb
  stdlib/public/runtime/CMakeLists.txt
  stdlib/public/runtime/Float16Support.cpp
  stdlib/public/stubs/Stubs.cpp
  test/ClangImporter/cfuncs_parse.swift
  test/ClangImporter/simd.swift
  test/Inputs/clang-importer-sdk/usr/include/cfuncs.h
  test/Inputs/clang-importer-sdk/usr/include/simd.h
  test/stdlib/Inputs/FloatingPointConversion.swift.gyb
  utils/SwiftFloatingPointTypes.py
Labels: swift-evolution-approved

#27776 [SE-0276] Support multiple patterns in catch clauses
  include/swift/AST/ASTScope.h
  include/swift/AST/NameLookup.h
  include/swift/AST/Stmt.h
  include/swift/AST/StmtNodes.def
  include/swift/Parse/Parser.h
  lib/AST/ASTDumper.cpp
  lib/AST/ASTPrinter.cpp
  lib/AST/ASTScope.cpp
  lib/AST/ASTScopeCreation.cpp
  lib/AST/ASTScopeLookup.cpp
  lib/AST/ASTScopeSourceRange.cpp
  lib/AST/ASTVerifier.cpp
  lib/AST/ASTWalker.cpp
  lib/AST/Decl.cpp
  lib/AST/NameLookup.cpp
  lib/AST/Stmt.cpp
  lib/IDE/Formatting.cpp
  lib/IDE/Refactoring.cpp
  lib/Parse/ParseExpr.cpp
  lib/Parse/ParseStmt.cpp
  lib/SIL/IR/SILProfiler.cpp
  lib/SILGen/SILGenFunction.h
  lib/SILGen/SILGenPattern.cpp
  lib/SILGen/SILGenStmt.cpp
  lib/Sema/BuilderTransform.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/DerivedConformanceCodingKey.cpp
  lib/Sema/DerivedConformanceComparable.cpp
  lib/Sema/DerivedConformanceEquatableHashable.cpp
  lib/Sema/DerivedConformanceRawRepresentable.cpp
  lib/Sema/DerivedConformances.cpp
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/PCMacro.cpp
  lib/Sema/PlaygroundTransform.cpp
  lib/Sema/TypeCheckError.cpp
  lib/Sema/TypeCheckStmt.cpp
  lib/Sema/TypeChecker.h
  test/Interpreter/errors.swift
  test/Parse/errors.swift
  test/SILGen/errors.swift
  test/Syntax/Outputs/round_trip_parse_gen.swift.withkinds
  test/Syntax/round_trip_parse_gen.swift
  test/stmt/errors.swift
  utils/gyb_syntax_support/NodeSerializationCodes.py
  utils/gyb_syntax_support/StmtNodes.py
Labels: swift-evolution-approved

#26632 [SE-0268] [Typechecker] Refine didSet semantics
  include/swift/AST/Decl.h
  include/swift/AST/KnownIdentifiers.def
  include/swift/AST/StorageImpl.h
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/AST/ASTDumper.cpp
  lib/AST/Decl.cpp
  lib/AST/TypeCheckRequests.cpp
  lib/SIL/IR/TypeLowering.cpp
  lib/Sema/TypeCheckDecl.cpp
  lib/Sema/TypeCheckStorage.cpp
  lib/Serialization/Deserialization.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/Serialization.cpp
  test/IDE/complete_in_accessors.swift
  test/ModuleInterface/inlinable-function.swift
  test/PCMacro/didset.swift
  test/SILGen/accessors.swift
  test/SILGen/didset_oldvalue_not_accessed_silgen.swift
  test/SILGen/modify.swift
  test/SILGen/multi_file.swift
  test/SILGen/objc_extensions.swift
  test/SILGen/observers.swift
  test/SILGen/properties_swift4.swift
  test/SILGen/properties_swift5.swift
  test/SILGen/property_wrappers.swift
  test/SILOptimizer/di_property_wrappers.swift
  test/attr/attr_native_dynamic.swift
  test/decl/var/didset_oldvalue.swift
Labels: swift-evolution-approved

#30931 [NFC] reduce the diff to master
  docs/SIL.rst
  include/swift/ABI/MetadataValues.h
  include/swift/AST/Expr.h
  include/swift/AST/Types.h
  include/swift/SIL/SILBasicBlock.h
  include/swift/SIL/SILDeclRef.h
  include/swift/SIL/SILFunction.h
  include/swift/SIL/SILFunctionBuilder.h
  include/swift/SIL/SILValue.h
  include/swift/SILOptimizer/Analysis/BottomUpIPAnalysis.h
  lib/AST/ASTMangler.cpp
  lib/IRGen/GenCall.cpp
  lib/IRGen/GenClangType.cpp
  lib/IRGen/GenDecl.cpp
  lib/IRGen/IRGenModule.h
  lib/IRGen/MetadataRequest.cpp
  lib/IRGen/ProtocolInfo.h
  lib/SIL/IR/SILFunction.cpp
  lib/SIL/IR/SILModule.cpp
  lib/SIL/IR/SILValue.cpp
  lib/SIL/IR/TypeLowering.cpp
  lib/SILOptimizer/FunctionSignatureTransforms/ExistentialSpecializer.cpp
  lib/SILOptimizer/FunctionSignatureTransforms/ExistentialTransform.h
  lib/Serialization/Deserialization.cpp
  lib/Serialization/DeserializeSIL.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/SILFormat.h
  lib/Serialization/SerializeSIL.cpp
  lib/Serialization/SerializedSILLoader.cpp
  test/IRGen/sil_linkage.sil
Labels: tensorflow

#31059 Sema: Force property wrappers in EmittedMembersRequest::evaluate() [5.2]
  lib/Sema/TypeCheckDecl.cpp
  test/SILGen/Inputs/property_wrappers_multifile_other.swift
  test/SILGen/property_wrappers_multifile.swift
  test/multifile/Inputs/rdar61229365.swift
  test/multifile/Inputs/sr12429.swift
  test/multifile/property-wrappers-rdar61229365.swift
Labels: r5.2

#31083 [IRGen] Fix SynthesizedFileUnit.
  lib/AST/Module.cpp
  lib/IRGen/IRGen.cpp
Labels: tensorflow

#31079 [5.2][CodeCompletion] Fix a crash in context type analysis for tuple expr
  lib/IDE/ExprContextAnalysis.cpp
  test/IDE/complete_call_arg.swift
Labels: r5.2

#31102 [AutoDiff][NFC] remove upstreamed tests
  test/AutoDiff/downstream/control_flow.swift
  test/AutoDiff/downstream/control_flow_diagnostics.swift
  test/AutoDiff/downstream/control_flow_sil.swift
  test/AutoDiff/downstream/reabstraction_e2e.swift
  test/AutoDiff/downstream/simple_math.swift
  test/AutoDiff/downstream/simple_model.swift
Labels: tensorflow

#31053 [5.2] Remove dependency on libatomic on Linux
  cmake/modules/AddSwift.cmake
  cmake/modules/AddSwiftUnittests.cmake
  stdlib/public/SwiftShims/RefCount.h
  stdlib/public/runtime/Metadata.cpp
  unittests/runtime/CMakeLists.txt
  unittests/runtime/LongTests/CMakeLists.txt
  utils/gen-static-stdlib-link-args
  utils/static-executable-args.lnk
Labels: r5.2

#31203 [5.3] Outliner: Fix a use after release issue
  lib/SILOptimizer/Transforms/Outliner.cpp
  test/SILOptimizer/outliner.sil
Labels: r5.3

#31204 [5.3] SinkAddressProjections: Abort when we can't sink an address pro…
  lib/SILOptimizer/Utils/BasicBlockOptUtils.cpp
  test/SILOptimizer/simplify_cfg_jump_thread_crash.sil
Labels: r5.3

#31202 [5.3] IRGen: Map interface to archetypes in keypath function
  lib/IRGen/GenKeyPath.cpp
  test/IRGen/Inputs/ResilientBase.swift
  test/IRGen/keypath.swift
Labels: r5.3

#31166 [SymbolGraph] Type subheadings: don't print generics/inheritance
  lib/SymbolGraphGen/DeclarationFragmentPrinter.cpp
  lib/SymbolGraphGen/DeclarationFragmentPrinter.h
  lib/SymbolGraphGen/SymbolGraph.cpp
  test/SymbolGraph/Symbols/Mixins/DeclarationFragments/SubheadingDeclarationFragmentsTypes.swift
Labels: r5.3

#31193 [SymbolGraph] Filter @_spi declarations
  lib/SymbolGraphGen/SymbolGraph.cpp
  test/SymbolGraph/Symbols/SkipsSPI.swift
Labels: r5.3

#31211 [5.3] [CS] A couple of fixes for static and dynamic callables
  lib/Sema/CSApply.cpp
  test/SILGen/call_as_function.swift
  test/SILGen/dynamic_callable_attribute.swift
Labels: r5.3

#31222 [5.3] Fix layering of cross-import and clang overlays
  include/swift/AST/SourceFile.h
  lib/AST/ASTDumper.cpp
  lib/AST/Module.cpp
  lib/Sema/ImportResolution.cpp
  test/CrossImport/Inputs/lib-templates/Frameworks/ClangFramework.framework/Modules/ClangFramework.swiftcrossimport/BystandingLibrary.swiftoverlay
  test/CrossImport/Inputs/lib-templates/Frameworks/OverlaidClangFramework.framework/Modules/OverlaidClangFramework.swiftcrossimport/BystandingLibrary.swiftoverlay
  test/CrossImport/Inputs/lib-templates/Frameworks/SwiftFramework.framework/Modules/SwiftFramework.swiftcrossimport/BystandingLibrary.swiftoverlay
  test/CrossImport/Inputs/lib-templates/Frameworks/_ClangFramework_BystandingLibrary.framework/Modules/_ClangFramework_BystandingLibrary.swiftmodule/module-triple-here.swiftinterface
  test/CrossImport/Inputs/lib-templates/Frameworks/_OverlaidClangFramework_BystandingLibrary.framework/Modules/_OverlaidClangFramework_BystandingLibrary.swiftmodule/module-triple-here.swiftinterface
  test/CrossImport/Inputs/lib-templates/Frameworks/_SwiftFramework_BystandingLibrary.framework/Modules/_SwiftFramework_BystandingLibrary.swiftmodule/module-triple-here.swiftinterface
  test/CrossImport/Inputs/lib-templates/lib/swift/OverlaidClangFramework.swiftmodule/module-triple-here.swiftinterface
  test/CrossImport/common-case.swift
Labels: r5.3

#31216 add option for "tensorflow toolchain" without tensorflow-swift-apis
  README.md
  test/CMakeLists.txt
  utils/build-presets.ini
  utils/build-script
  utils/build-script-impl
  utils/build-toolchain-tensorflow
  utils/build_swift/build_swift/driver_arguments.py
  utils/build_swift/tests/expected_options.py
  utils/swift_build_support/swift_build_support/toolchain.py
Labels: tensorflow

#31221 [5.3] Lazily Associate a SILRemarkStreamer with an LLVMContext
  include/swift/SIL/SILModule.h
  include/swift/SIL/SILRemarkStreamer.h
  lib/IRGen/IRGen.cpp
  lib/SIL/Utils/SILRemarkStreamer.cpp
  test/Driver/opt-record-bitstream.swift
  tools/sil-opt/SILOpt.cpp
Labels: r5.3

#31233 [5.3][SR-12425] Improving diagnostics for key path application on non-convertible root type
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSFix.h
  lib/Sema/CSSimplify.cpp
  test/attr/attr_dynamic_member_lookup.swift
Labels: r5.3

#31235 [5.3][build] copy Python detection code into StandaloneOverlays.cmake
  cmake/modules/StandaloneOverlay.cmake
Labels: r5.3

#31237 [5.3] Remove fallback for arm64e -> arm64.
  lib/Serialization/SerializedModuleLoader.cpp
  test/ModuleInterface/Inputs/DummyFramework.framework/Modules/DummyFramework.swiftmodule/arm64-apple-ios.swiftinterface
  test/ModuleInterface/Inputs/DummyFramework.framework/Modules/DummyFramework.swiftmodule/arm64.swiftinterface
  test/ModuleInterface/ModuleCache/force-module-loading-mode-archs.swift
  test/ModuleInterface/ModuleCache/force-module-loading-mode-framework.swift
  test/ModuleInterface/arm64e-fallback.swift
Labels: r5.3

#31241 [5.3] WinSDK: add some more constants to the overlay
  stdlib/public/Windows/WinSDK.swift
Labels: r5.3

#31245 [5.3] XFAIL test/Interpreter/metadata_access.swift on arm64e
  test/Interpreter/metadata_access.swift
Labels: r5.3

#31244 [5.2] Fix linker flags for -static-executable
  lib/Driver/UnixToolChains.cpp
  test/Driver/static-executable.swift
  test/lit.cfg
  utils/static-executable-args.lnk
Labels: r5.2

#31249 [AutoDiff] Enable cross-file derivative registration by default.
  include/swift/Basic/LangOptions.h
  include/swift/Option/Options.td
  lib/Frontend/CompilerInvocation.cpp
  lib/Sema/TypeCheckAttr.cpp
  stdlib/cmake/modules/AddSwiftStdlib.cmake
  test/AutoDiff/Sema/DerivativeRegistrationCrossModule/main.swift
  test/AutoDiff/Sema/derivative_attr_type_checking.swift
  test/AutoDiff/downstream/always_emit_into_client_multi_file.swift
  test/AutoDiff/downstream/always_emit_into_client_single_file.swift
  test/AutoDiff/downstream/cross_module_derivative_attr_e2e.swift
  test/AutoDiff/downstream/derivative_attr_type_checking.swift
  test/AutoDiff/downstream/derivative_registration_foreign/main.swift
Labels: tensorflow

#31268 [5.3] TempRValueOpt: fix a compile time crash in tryOptimizeStoreIntoTemp
  lib/SILOptimizer/Transforms/TempRValueElimination.cpp
  test/SILOptimizer/temp_rvalue_opt_ossa.sil
Labels: r5.3

#31263 [5.3][AST] Fix a linker error for the parser-only library build
  lib/AST/ASTContext.cpp
Labels: r5.3

#31257 [5.3][IDE][AST] Handle frameworks with traditional overlays where the underlying module declares cross imports in sourcekit
  include/swift/AST/FileUnit.h
  include/swift/AST/Module.h
  include/swift/Serialization/SerializedModuleLoader.h
  lib/AST/Module.cpp
  lib/IDE/ModuleInterfacePrinting.cpp
  lib/Serialization/SerializedModuleLoader.cpp
  test/CrossImport/Inputs/rewrite-module-triples.py
  test/SourceKit/CursorInfo/cursor_info_cross_import_common_case.swift
  test/SourceKit/DocSupport/doc_cross_import_common.swift
  test/SourceKit/DocSupport/doc_cross_import_common.swift.ClangFramework.response
  test/SourceKit/DocSupport/doc_cross_import_common.swift.OverlaidClangFramework.response
  test/SourceKit/DocSupport/doc_cross_import_common.swift.SwiftFramework.response
  test/SourceKit/InterfaceGen/gen_swift_module_cross_import_common.swift
  test/SourceKit/InterfaceGen/gen_swift_module_cross_import_common.swift.ClangFramework.response
  test/SourceKit/InterfaceGen/gen_swift_module_cross_import_common.swift.OverlaidClangFramework.response
  test/SourceKit/InterfaceGen/gen_swift_module_cross_import_common.swift.SwiftFramework.response
Labels: r5.3

#31258 [5.3][Parse] Don't drop parsed error types in where clause from AST
  lib/Parse/ParseDecl.cpp
  lib/Parse/ParseGeneric.cpp
  lib/Parse/ParsePattern.cpp
  lib/Parse/ParseType.cpp
  test/IDE/complete_where_clause.swift
  test/Parse/recovery.swift
Labels: r5.3

#31272 [IRGen] Check as early as possible for Clang decls we've seen before.
  lib/IRGen/GenClangDecl.cpp
Labels: C++ Interop

#31275 [5.3] Handle begin_apply in TempRVO
  lib/SILOptimizer/Transforms/TempRValueElimination.cpp
Labels: r5.3

#31273 [5.3] Diagnose non-throwing methods implementing a throwing @objc protocol …
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckDeclObjC.cpp
  test/Sema/impl_throw_objc.swift
Labels: r5.3

#31281 [5.3] Compatibility51: Backport the 5.2 implementation of the conformance cache.
  include/swift/Runtime/Config.h
  stdlib/toolchain/CMakeLists.txt
  stdlib/toolchain/Compatibility50/Overrides.cpp
  stdlib/toolchain/Compatibility50/Overrides.h
  stdlib/toolchain/Compatibility50/ProtocolConformance.cpp
  stdlib/toolchain/Compatibility51/CMakeLists.txt
  stdlib/toolchain/Compatibility51/Concurrent.h
  stdlib/toolchain/Compatibility51/Overrides.cpp
  stdlib/toolchain/Compatibility51/Overrides.h
  stdlib/toolchain/Compatibility51/ProtocolConformance.cpp
  validation-test/Evolution/test_backward_deploy_conformance.swift
Labels: r5.3

#31277 [5.3] [string] Add _deconstructUTF8 for internal usage
  stdlib/public/core/StringObject.swift
  stdlib/public/core/StringTesting.swift
  test/stdlib/StringDeconstruction.swift
Labels: r5.3

#31292 [5.3][Property Wrappers] Only re-write assign_by_wrapper to assignment if all fields have been initialized.
  lib/SILOptimizer/Mandatory/DefiniteInitialization.cpp
  test/SILOptimizer/di_property_wrappers.swift
Labels: r5.3

#31285 [5.3][Sema] Maintain the implicitness of call argument tuple/parens in coerceCallArguments
  include/swift/AST/Expr.h
  lib/IDE/SyntaxModel.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/TypeCheckExpr.cpp
  test/SourceKit/Refactoring/basic.swift
Labels: r5.3

#31294 [5.3][ConstraintSystem] Properly diagnose operator reference ambiguities
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/operator.swift
Labels: r5.3

#31302 [5.3][CodeCompletion] Don't perform completion at declaration name position
  lib/Parse/ParseDecl.cpp
  test/IDE/complete_declname.swift
Labels: r5.3

#31306 [SymbolGraph] [5.3] Pick best synthesized member when possible
  lib/SymbolGraphGen/SymbolGraph.cpp
  lib/SymbolGraphGen/SymbolGraph.h
  test/SymbolGraph/Relationships/Synthesized/PickBestCandidate.swift
  tools/driver/swift_symbolgraph_extract_main.cpp
Labels: r5.3

#31314 [SymbolGraph] [5.3] Add navigator declaration fragments
  include/swift/AST/PrintOptions.h
  lib/AST/ASTPrinter.cpp
  lib/SymbolGraphGen/Symbol.cpp
  lib/SymbolGraphGen/SymbolGraph.cpp
  lib/SymbolGraphGen/SymbolGraph.h
  test/SymbolGraph/Symbols/Mixins/DeclarationFragments/Navigator.swift
  test/SymbolGraph/Symbols/Mixins/DeclarationFragments/SubheadingDeclarationFragments.swift
Labels: r5.3

#31290 [5.3] Fix ReactiveKit failure seen in source compatibility suite
  lib/Serialization/SerializedModuleLoader.cpp
  test/ModuleInterface/ModuleCache/force-module-loading-mode-archs.swift
  test/ModuleInterface/ModuleCache/force-module-loading-mode-framework.swift
  test/ModuleInterface/arm64e-fallback.swift
  test/ModuleInterface/can-import.swift
Labels: r5.3

#31282 [5.3] Revert "Merge pull request #30024 from Azoy/calling-metadata-accessor-from-swift"
  stdlib/public/SwiftShims/CMakeLists.txt
  stdlib/public/SwiftShims/Metadata.h
  stdlib/public/SwiftShims/module.modulemap
  stdlib/public/stubs/CMakeLists.txt
  stdlib/public/stubs/Metadata.cpp
  test/Interpreter/metadata_access.swift
Labels: r5.3

#31313 [5.3] [CS] Connect closure to referenced vars
  lib/Sema/CSGen.cpp
  test/stmt/foreach.swift
Labels: r5.3

#31311 [5.3] [NFC] [arm64e] Delete arm64e fallback test.
  test/Serialization/load-arch-fallback-arm64e.swift
Labels: r5.3

#31312 [5.3] [NFC] [arm64e] Mark arm64e fallback test unsupported for Catalyst.
  test/ModuleInterface/arm64e-fallback.swift
Labels: r5.3

#31236 [5.3] [NFC] [arm64e] Turn on IRGen/opaque_result_type.swift test case.
  test/IRGen/opaque_result_type.swift
Labels: r5.3

#31322 [5.3] Fix analysis invalidation in ClosureLifetimeFixup
  lib/SILOptimizer/Mandatory/ClosureLifetimeFixup.cpp
  test/Interpreter/objc_throw_in_noescape_block.swift
Labels: r5.3

#31337 Small fixes to CppInteroperabilityManifesto.md
  docs/CppInteroperabilityManifesto.md
Labels: C++ Interop

#31341 [5.3][SourceKit] Fix unreachable hit in DocumentStructureWalker
  test/SourceKit/DocumentStructure/Inputs/main.swift
  test/SourceKit/DocumentStructure/structure.swift.empty.response
  test/SourceKit/DocumentStructure/structure.swift.foobar.response
  test/SourceKit/DocumentStructure/structure.swift.response
  tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp
Labels: r5.3

#31343 [5.3][CodeCompletion] Prioritize type matching overload for unresovled member
  lib/IDE/CodeCompletion.cpp
  lib/IDE/CodeCompletionResultBuilder.h
  test/IDE/complete_annotation.swift
  test/IDE/complete_call_arg.swift
  test/IDE/complete_call_as_function.swift
  test/IDE/complete_constrained.swift
  test/IDE/complete_enum_elements.swift
  test/IDE/complete_property_delegate_attribute.swift
  test/IDE/complete_single_expression_return.swift
  test/IDE/complete_stmt_controlling_expr.swift
  test/IDE/complete_string_interpolation.swift
  test/IDE/complete_unresolved_members.swift
  test/SourceKit/CodeComplete/complete_unresolvedmember.swift.response
Labels: r5.3

#31365 [5.3][AST] Fix assertion hit in AutoClosureExpr::getUnwrappedCurryThunkExpr()
  lib/AST/Expr.cpp
  test/Index/roles.swift
Labels: r5.3

#31371 [5.3] IRGen: Fix alignment of global variable buffer for non-fixed types
  lib/IRGen/GenDecl.cpp
  test/IRGen/global_resilience.sil
Labels: r5.3

#31386 [5.3][Diagnostics] Tailored diagnostics for missing member failure when in…
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  test/Constraints/members.swift
Labels: r5.3

#31376 [5.3] Rename Mac Catalyst-related test
  test/ModuleInterface/swift_build_sdk_interfaces/Inputs/maccatalyst-sdk/System/Library/Frameworks/FMWK.framework/Modules/FMWK.swiftmodule/x86_64-apple-macos.swiftinterface
  test/ModuleInterface/swift_build_sdk_interfaces/Inputs/maccatalyst-sdk/System/Library/Frameworks/Zippered.framework/Modules/Zippered.swiftmodule/x86_64-apple-ios-macabi.swiftinterface
  test/ModuleInterface/swift_build_sdk_interfaces/Inputs/maccatalyst-sdk/System/Library/Frameworks/Zippered.framework/Modules/Zippered.swiftmodule/x86_64-apple-macos.swiftinterface
  test/ModuleInterface/swift_build_sdk_interfaces/Inputs/maccatalyst-sdk/System/iOSSupport/System/Library/Frameworks/FMWK.framework/Modules/FMWK.swiftmodule/x86_64-apple-ios-macabi.swiftinterface
  test/ModuleInterface/swift_build_sdk_interfaces/Inputs/maccatalyst-sdk/System/iOSSupport/usr/lib/swift/Foo.swiftmodule/x86_64-apple-ios-macabi.swiftinterface
  test/ModuleInterface/swift_build_sdk_interfaces/Inputs/maccatalyst-sdk/usr/lib/swift/Foo.swiftmodule/x86_64-apple-macos.swiftinterface
  test/ModuleInterface/swift_build_sdk_interfaces/iosmac.test-sh
  test/ModuleInterface/swift_build_sdk_interfaces/maccatalyst.test-sh
Labels: r5.3

#31362 [CxxInterop] Add tests for static variables
  test/Interop/Cxx/static/Inputs/module.modulemap
  test/Interop/Cxx/static/Inputs/static-var.cc
  test/Interop/Cxx/static/Inputs/static-var.h
  test/Interop/Cxx/static/static-var-irgen.swift
  test/Interop/Cxx/static/static-var-silgen.swift
  test/Interop/Cxx/static/static-var.swift
Labels: C++ Interop

#31339 [NFC] Get rid of -Wrange-loop-analysis warnings.
  lib/AST/ASTScopeCreation.cpp
  lib/AST/ASTScopeLookup.cpp
  lib/AST/Decl.cpp
  lib/AST/FrontendSourceFileDepGraphFactory.cpp
  lib/AST/GenericSignatureBuilder.cpp
  lib/AST/IncrementalRanges.cpp
  lib/AST/NameLookup.cpp
  lib/Basic/OutputFileMap.cpp
  lib/Driver/Job.cpp
  lib/IDE/CommentConversion.cpp
  lib/SILOptimizer/Mandatory/MandatoryInlining.cpp
  lib/SILOptimizer/UtilityPasses/SerializeSILPass.cpp
  lib/Sema/ImportResolution.cpp
  lib/Sema/LookupVisibleDecls.cpp
  lib/Sema/TypeCheckDecl.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Serialization/SerializeSIL.cpp
  lib/SymbolGraphGen/SymbolGraph.cpp
  lib/SymbolGraphGen/SymbolGraphASTWalker.cpp
Labels: r5.3

#31382 [5.3][Foundation] Adjust Foundation shims for compatibility
  stdlib/public/Darwin/Foundation/NSObject.swift
  stdlib/public/SwiftShims/FoundationOverlayShims.h
Labels: r5.3

#31397 [5.3] cross-module-optimiations: Fix an compiler crash and a wrong linkage
  lib/SILOptimizer/IPO/CrossModuleSerializationSetup.cpp
  test/SILOptimizer/Inputs/cross-module.swift
  test/SILOptimizer/cross-module-optimization.swift
Labels: r5.3

#31356 [5.3] Update Devirtualizer's analysis invalidation
  include/swift/SILOptimizer/Utils/InstOptUtils.h
  lib/SILOptimizer/Transforms/SimplifyCFG.cpp
  lib/SILOptimizer/Utils/Devirtualize.cpp
  lib/SILOptimizer/Utils/InstOptUtils.cpp
  test/SILOptimizer/sil_combine_concrete_existential.swift
Labels: r5.3

#31402 [5.3][ASTPrinter][SourceKit] Print 'Any' as a keyword.
  lib/AST/ASTPrinter.cpp
  lib/AST/TypeRepr.cpp
  test/IDE/complete_annotation.swift
  test/SourceKit/CursorInfo/cursor_info.swift
  test/SourceKit/DocSupport/Inputs/cake.swift
  test/SourceKit/DocSupport/doc_clang_module.swift.response
  test/SourceKit/DocSupport/doc_swift_module.swift.response
Labels: r5.3

#31418 [5.3][ConstraintSystem] Don't attempt property wrapper fixes for key path …
  lib/Sema/CSSimplify.cpp
  test/Constraints/sr12520.swift
Labels: r5.3

#31399 [TF] Change PythonKit deployment target to macOS 10.10.
  utils/swift_build_support/swift_build_support/products/pythonkit.py
Labels: tensorflow

#31411 [5.3] [Typechecker] Allow property observers on lazy variables
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckStorage.cpp
  test/SILGen/lazy_property_with_observers.swift
  test/decl/var/lazy_properties.swift
Labels: r5.3

#31396 Test static member functions
  test/Interop/Cxx/static/Inputs/module.modulemap
  test/Interop/Cxx/static/Inputs/static-member-func.cc
  test/Interop/Cxx/static/Inputs/static-member-func.h
  test/Interop/Cxx/static/static-member-func-irgen.swift
  test/Interop/Cxx/static/static-member-func-silgen.swift
  test/Interop/Cxx/static/static-member-func.swift
Labels: C++ Interop

#31417 [5.3][build] set CMAKE_OSX_ARCHITECTURES in swift_cmake_options
  utils/build-script-impl
Labels: r5.3

#31439 Change C++ extension for test inputs from .cc to .cpp
  test/Interop/Cxx/extern-var/Inputs/extern-var.cpp
  test/Interop/Cxx/extern-var/extern-var.swift
  test/Interop/Cxx/static/Inputs/inline-static-member-var.cpp
  test/Interop/Cxx/static/Inputs/static-local-var.cpp
  test/Interop/Cxx/static/Inputs/static-member-func.cpp
  test/Interop/Cxx/static/Inputs/static-member-var.cpp
  test/Interop/Cxx/static/Inputs/static-var.cpp
  test/Interop/Cxx/static/constexpr-static-member-var.swift
  test/Interop/Cxx/static/inline-static-member-var.swift
  test/Interop/Cxx/static/static-local-var.swift
  test/Interop/Cxx/static/static-member-func.swift
  test/Interop/Cxx/static/static-member-var.swift
  test/Interop/Cxx/static/static-var.swift
Labels: C++ Interop

#31385 [5.3] SILCombine: Fix update of substitution map when substituting opened opaque archetypes
  include/swift/AST/ProtocolConformanceRef.h
  include/swift/AST/Type.h
  lib/AST/ASTDumper.cpp
  lib/AST/ProtocolConformance.cpp
  lib/SIL/IR/SILPrinter.cpp
  lib/SILOptimizer/SILCombiner/SILCombinerApplyVisitors.cpp
  test/SILOptimizer/sil_combine_concrete_existential.sil
Labels: r5.3

#31364 [5.3] Outliner: Fix an iterator problem
  lib/SILOptimizer/Transforms/Outliner.cpp
  test/SILOptimizer/outliner.sil
Labels: r5.3

#31410 [5.3] Test needs an optimized stdlib
  test/SILOptimizer/outliner.swift
Labels: r5.3

#31434 Sema: Fix crash with stored property that has on-demand 'modify' accessor [5.3]
  lib/Sema/TypeCheckStorage.cpp
  test/SILGen/observers_with_on_demand_modify_accessor.swift
Labels: r5.3

#31428 [5.3][Darwin] Import all overlay shims with @_implementationOnly
  stdlib/public/Darwin/Dispatch/Block.swift
  stdlib/public/Darwin/Dispatch/Data.swift
  stdlib/public/Darwin/Dispatch/Dispatch.swift
  stdlib/public/Darwin/Dispatch/Queue.swift
  stdlib/public/Darwin/Dispatch/Source.swift
  stdlib/public/Darwin/Dispatch/Time.swift
  stdlib/public/Darwin/Network/NWConnection.swift
  stdlib/public/Darwin/Network/NWEndpoint.swift
  stdlib/public/Darwin/Network/NWError.swift
  stdlib/public/Darwin/Network/NWPath.swift
  stdlib/public/Darwin/ObjectiveC/ObjectiveC.swift
  stdlib/public/Darwin/SafariServices/SafariServices.swift
  stdlib/public/Darwin/UIKit/UIKit.swift
  stdlib/public/Darwin/XCTest/XCTest.swift
  stdlib/public/Darwin/XPC/XPC.swift
  stdlib/public/Darwin/os/os_log.swift
  stdlib/public/Darwin/os/os_signpost.swift
Labels: r5.3

#31441 Add header guards to headers in test/interop
  test/Interop/C/function/Inputs/emit-called-inline-function.h
  test/Interop/Cxx/class/Inputs/access-specifiers.h
  test/Interop/Cxx/class/Inputs/member-variables.h
  test/Interop/Cxx/class/Inputs/memory-layout.h
  test/Interop/Cxx/extern-var/Inputs/extern-var.h
  test/Interop/Cxx/static/Inputs/inline-static-member-var.h
  test/Interop/Cxx/static/Inputs/static-local-var.h
  test/Interop/Cxx/static/Inputs/static-member-func.h
  test/Interop/Cxx/static/Inputs/static-member-var.h
  test/Interop/Cxx/static/Inputs/static-var.h
Labels: C++ Interop

#31400 [CxxInterop] Add C++ demangled name for globals/static member variables to SIL
  lib/SIL/IR/SILPrinter.cpp
  test/Interop/Cxx/extern-var/extern-var-silgen.swift
  test/Interop/Cxx/static/inline-static-member-var-silgen.swift
  test/Interop/Cxx/static/static-member-func-silgen.swift
  test/Interop/Cxx/static/static-member-var-silgen.swift
  test/Interop/Cxx/static/static-var-silgen.swift
Labels: C++ Interop
