Repository swiftlang/swift, pull requests merged in 2020-09, with the labels that each got.

#33673 build: repair the build for newer MSVC release
  cmake/modules/SwiftWindowsSupport.cmake
  stdlib/CMakeLists.txt
Labels: r5.3

#33732 [5.3] [Constraint application] Find trailing closure direction more carefully.
  lib/Sema/CSApply.cpp
Labels: r5.3

#33741 [5.3] CSE: disable CSE of lazy property getters of struct
  lib/SILOptimizer/Transforms/CSE.cpp
  test/SILOptimizer/cse.sil
  test/SILOptimizer/lazy_property_getters.swift
Labels: r5.3

#33743 DI: Correctly handle conditional destroy of 'self' in root class [5.3]
  lib/SILOptimizer/Mandatory/DIMemoryUseCollector.h
  lib/SILOptimizer/Mandatory/DefiniteInitialization.cpp
  test/Interpreter/failable_initializers_root_class.swift
  test/SILOptimizer/definite_init_root_class.swift
Labels: r5.3

#33744 [5.3] Remove The Parser Hack For If-Let
  include/swift/Parse/Parser.h
  lib/AST/ASTPrinter.cpp
  lib/Parse/ParsePattern.cpp
  lib/Parse/ParseStmt.cpp
  lib/Sema/ConstraintSystem.cpp
  lib/Sema/ConstraintSystem.h
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/TypeCheckPattern.cpp
  test/stmt/statements.swift
Labels: r5.3

#33771 [TF] build: update checkout for swift-driver.
  utils/update_checkout/update-checkout-config.json
Labels: tensorflow

#33778 [release/5.3] Re-enable @available(macOS 11) test
  test/attr/attr_availability_canonical_macos_version.swift
Labels: r5.3

#33678 [5.3] Properly compute resource folder when linking statically
  include/swift/Frontend/Frontend.h
  include/swift/Frontend/FrontendOptions.h
  include/swift/Option/FrontendOptions.td
  lib/Driver/Driver.cpp
  lib/Driver/ToolChains.cpp
  lib/Frontend/ArgsToFrontendOptionsConverter.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/FrontendTool/FrontendTool.cpp
  stdlib/cmake/modules/AddSwiftStdlib.cmake
  stdlib/cmake/modules/SwiftSource.cmake
  stdlib/public/Platform/CMakeLists.txt
  stdlib/public/SwiftShims/CMakeLists.txt
  test/Driver/print_target_info.swift
  tools/driver/modulewrap_main.cpp
Labels: r5.3

#33779 [5.3] [Preset] Source compat suite cross compile for macOS arm64
  cmake/modules/DarwinSDKs.cmake
  utils/build-presets.ini
  utils/build-script
  utils/recursive-lipo
Labels: r5.3

#33785 [5.3] SILCombine: fix an assertion crash in SILCombine when casting AnyClass to Any
  lib/SILOptimizer/SILCombiner/SILCombinerApplyVisitors.cpp
  lib/SILOptimizer/SILCombiner/SILCombinerMiscVisitors.cpp
  test/SILOptimizer/sil_combine.sil
Labels: r5.3

#33794 [5.3][ConstraintSystem] Extend invalid function body fix to cover constrai…
  include/swift/AST/DiagnosticEngine.h
  lib/Sema/BuilderTransform.cpp
  lib/Sema/CSFix.cpp
  lib/Sema/CSFix.h
  lib/Sema/ConstraintSystem.h
  test/Constraints/function_builder_diags.swift
Labels: r5.3

#29735 [SE-0284] Allow Multiple Variadic Parameters in Functions, Subscripts, and Initializers
  include/swift/AST/DiagnosticsParse.def
  lib/Parse/ParsePattern.cpp
  test/Constraints/argument_matching.swift
  test/Interpreter/multiple_varargs.swift
  test/SILGen/arguments.swift
  test/Syntax/Outputs/round_trip_parse_gen.swift.withkinds
  test/Syntax/round_trip_parse_gen.swift
  test/decl/func/vararg.swift
Labels: swift-evolution-approved

#33868 [AutoDiff] Fix forward-mode crashes related to tangent buffers
  lib/SILOptimizer/Differentiation/JVPCloner.cpp
  lib/SILOptimizer/Differentiation/LinearMapInfo.cpp
  test/AutoDiff/SILOptimizer/forward_mode_diagnostics.swift
  test/AutoDiff/downstream/compiler_crashers_fixed/tf1033-differential-ownership-uninit-memory.swift
  test/AutoDiff/downstream/compiler_crashers_fixed/tf984-differential-unset-tangent-buffer.swift
  test/AutoDiff/validation-test/forward_mode.swift
Labels: tensorflow

#33880 [5.3] Stop ReplaceOpaqueTypesWithUnderlyingTypes recursion if it hits a fixpoint
  lib/AST/Type.cpp
  test/SILGen/Inputs/replace_opaque_type_public_assoc_type_m.swift
  test/SILGen/replace_opaque_type_public_assoc_type.swift
Labels: r5.3

#33780 [5.3] Support cross compile Xcode toolchain for Apple Silicon
  utils/build-presets.ini
  utils/build-script
  utils/build-script-impl
  utils/swift_build_support/swift_build_support/products/benchmarks.py
  utils/swift_build_support/swift_build_support/products/indexstoredb.py
  utils/swift_build_support/swift_build_support/products/product.py
  utils/swift_build_support/swift_build_support/products/skstresstester.py
  utils/swift_build_support/swift_build_support/products/swiftpm.py
  utils/swift_build_support/swift_build_support/products/swiftsyntax.py
Labels: r5.3

#33897 [AutoDiff] Generate transparent ossa reabstraction thunks.
  lib/SILOptimizer/Differentiation/Thunk.cpp
Labels: tensorflow

#33881 [5.3] IRGen: Fix asserting local extern declarations.
  lib/IRGen/GenClangDecl.cpp
  test/IRGen/Inputs/local_extern.h
  test/IRGen/local_extern.swift
  test/Interop/C/function/Inputs/emit-called-inline-function.h
  test/Interop/C/function/Inputs/module.modulemap
  test/Interop/C/function/emit-called-inline-function-irgen.swift
Labels: r5.3

#33899 [5.3] Fix glibc.modulemap generation
  stdlib/public/Platform/CMakeLists.txt
Labels: r5.3

#32389 5.3: Emit coverage mappings for all modules
  lib/IRGen/GenDecl.cpp
  test/Profiler/Inputs/coverage_num_threads1.swift
  test/Profiler/Inputs/coverage_num_threads2.swift
  test/Profiler/coverage_num_threads.swift
Labels: r5.3

#32416 Add path remapping with -coverage-prefix-map to coverage data
  include/swift/AST/DiagnosticsFrontend.def
  include/swift/AST/IRGenOptions.h
  include/swift/Option/Options.td
  lib/Driver/Driver.cpp
  lib/Driver/ToolChains.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/IRGen/GenCoverage.cpp
  test/Driver/coverage-prefix-map.swift
  test/Profiler/coverage_relative_path.swift
Labels: r5.3

#33949 [5.3] SILGen: Relax assertion that incorrectly tripped on lowered opaque capture types.
  lib/SILGen/SILGenThunk.cpp
  test/SILGen/serialized-capture-opaque-type-subst.swift
Labels: r5.3

#33904 [5.3][shims] Add AppKit overlay shims
  stdlib/public/SwiftShims/AppKitOverlayShims.h
  stdlib/public/SwiftShims/CMakeLists.txt
  stdlib/public/SwiftShims/module.modulemap
Labels: r5.3

#33947 build: allow falling back to just built compiler
  stdlib/cmake/modules/SwiftSource.cmake
  test/CMakeLists.txt
Labels: r5.3

#33964 [AutoDiff] Fix PullbackCloner tangent value category mismatch issues.
  lib/SIL/IR/SILFunctionType.cpp
  lib/SILOptimizer/Analysis/DifferentiableActivityAnalysis.cpp
  lib/SILOptimizer/Differentiation/PullbackCloner.cpp
  lib/SILOptimizer/Differentiation/VJPCloner.cpp
  test/AutoDiff/validation-test/optional-property.swift
  test/AutoDiff/validation-test/optional.swift
Labels: tensorflow

#33969 [AutoDiff] Fix pullback subset thunk generation crash.
  lib/SILOptimizer/Differentiation/Thunk.cpp
  test/AutoDiff/compiler_crashers_fixed/tf1315-pullback-subset-parameter-thunk-generation.swift
Labels: tensorflow

#33992 [TF] Add `Optional: KeyPathIterable` conformance.
  stdlib/public/core/KeyPathIterable.swift
  test/stdlib/KeyPathIterable.swift
Labels: tensorflow

#33996 [TF] Fix `Optional` completion tests.
  test/IDE/complete_generic_optional.swift
  test/IDE/complete_stmt_controlling_expr.swift
  test/IDE/complete_swift_key_path_optional_root.swift
  test/IDE/complete_unresolved_members.swift
Labels: tensorflow

#34013 Sema: Fix crash on static -vs- non-static witness mismatch with deserialized witness [5.3]
  lib/Sema/TypeCheckProtocol.cpp
  test/decl/protocol/Inputs/deserialized_witness_mismatch_other.swift
  test/decl/protocol/deserialized_witness_mismatch.swift
Labels: r5.3

#33962 [5.3] Demangler: fix a crash when re-mangling retroactive conformances
  lib/Demangling/Remangler.cpp
  test/Demangle/Inputs/manglings.txt
Labels: r5.3

#34017 [5.3][Property Wrappers] Refine assign_by_wrapper lowering
  include/swift/SIL/SILInstruction.h
  lib/SILOptimizer/Mandatory/DIMemoryUseCollector.h
  lib/SILOptimizer/Mandatory/DefiniteInitialization.cpp
  lib/SILOptimizer/Mandatory/RawSILInstLowering.cpp
  test/SILOptimizer/di_property_wrappers_leak.swift
Labels: r5.3

#33930 [cxx-interop] [NFC] Rename MemberInline.IntBox -> LoadableIntWrapper.
  test/Interop/Cxx/operators/Inputs/member-inline.h
  test/Interop/Cxx/operators/member-inline-irgen.swift
  test/Interop/Cxx/operators/member-inline-module-interface.swift
  test/Interop/Cxx/operators/member-inline-silgen.swift
  test/Interop/Cxx/operators/member-inline-typechecker.swift
  test/Interop/Cxx/operators/member-inline.swift
Labels: C++ Interop

#34060 [5.3][CSGen] Check whether parent has a contextual type before diagnosing `nil` use
  lib/Sema/CSGen.cpp
  test/Constraints/optional.swift
Labels: r5.3

#34086 [cxx-interop] Rename tests in Cxx/templates to show they are class templates.
  test/Interop/Cxx/templates/Inputs/class-template-eager-instantiation-problems.h
  test/Interop/Cxx/templates/Inputs/class-template-with-primitive-argument.h
  test/Interop/Cxx/templates/Inputs/explicit-class-specialization.h
  test/Interop/Cxx/templates/Inputs/fully-pre-defined-class-template.h
  test/Interop/Cxx/templates/Inputs/module.modulemap
  test/Interop/Cxx/templates/Inputs/not-pre-defined-class-template.h
  test/Interop/Cxx/templates/Inputs/partially-pre-defined-class-template.h
  test/Interop/Cxx/templates/class-template-eager-instatiation-problems.swift
  test/Interop/Cxx/templates/class-template-with-primitive-argument.swift
  test/Interop/Cxx/templates/explicit-class-specialization.swift
  test/Interop/Cxx/templates/fully-pre-defined-class-template.swift
  test/Interop/Cxx/templates/not-pre-defined-class-template-module-interface.swift
  test/Interop/Cxx/templates/not-pre-defined-class-template.swift
  test/Interop/Cxx/templates/partially-pre-defined-class-template-irgen.swift
  test/Interop/Cxx/templates/partially-pre-defined-class-template-silgen.swift
  test/Interop/Cxx/templates/partially-pre-defined-class-template.swift
Labels: C++ Interop
