Repository swiftlang/swift, pull requests merged in 2020-05, with the labels that each got.

#31457 [5.3] [Changelog] Mention SR-7083 in changelog under Swift 5.3
  CHANGELOG.md
Labels: r5.3

#31409 [5.3][CSApply] Fix a case where CSApply produced an invalid DeclRefExpr
  lib/Sema/CSApply.cpp
  test/Constraints/Inputs/imported_type.h
  test/Constraints/invalid_decl_ref.swift
Labels: r5.3

#31427 [5.3][Property Wrappers] For now, don't allow wrappedValue and projectedValue to have dynamic Self type.
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckPropertyWrapper.cpp
  test/decl/var/property_wrappers.swift
Labels: r5.3

#31444 Update with the new tensorflow-0.9 branches
  utils/update_checkout/update-checkout-config.json
Labels: tensorflow

#31460 [5.3] Allow initializing a wrapped property with a nonmutating setter
  lib/SILGen/SILGenLValue.cpp
  lib/SILOptimizer/Mandatory/DefiniteInitialization.cpp
  lib/Sema/CSApply.cpp
  test/SILGen/property_wrappers.swift
  test/SILOptimizer/di_property_wrappers.swift
  test/SILOptimizer/di_property_wrappers_errors.swift
Labels: r5.3

#31476 [5.3] Update docs for numericCast
  stdlib/public/core/Integers.swift
Labels: r5.3

#31494 Updating swift-syntax to release tag
  utils/update_checkout/update-checkout-config.json
Labels: tensorflow

#31440 [5.3] [test] Disabled several tests on optimized test modes.
  test/IRGen/prespecialized-metadata/enum-extradata-run.swift
  test/IRGen/prespecialized-metadata/enum-trailing-flags-run.swift
  test/IRGen/prespecialized-metadata/struct-extradata-run.swift
  test/IRGen/prespecialized-metadata/struct-trailing-flags-run.swift
Labels: r5.3

#31483 [5.3] Diagnose exclusivity in the presence of coroutines.
  CHANGELOG.md
  lib/SIL/Verifier/SILVerifier.cpp
  lib/SILOptimizer/Analysis/AccessSummaryAnalysis.cpp
  lib/SILOptimizer/Mandatory/DiagnoseStaticExclusivity.cpp
  test/SILOptimizer/access_summary_analysis.sil
  test/SILOptimizer/exclusivity_static_diagnostics.sil
  test/SILOptimizer/exclusivity_static_diagnostics.swift
Labels: r5.3

#31469 [5.3] Fix batch mode llvm ir hash consistency test
  test/multifile/batch-mode-llvmIRHash-consistency.swift
Labels: r5.3

#31478 [5.3][Docs] Clarifies `Identifiable` requirements
  stdlib/public/core/Identifiable.swift
Labels: r5.3

#31526 [build] NFC: document tensorflow branch CMake options.
  CMakeLists.txt
  utils/build-script-impl
Labels: tensorflow

#31497 [5.3] Propagate Failures Explicitly in Opaque Type Resolution
  lib/Sema/TypeCheckType.cpp
  test/ModuleInterface/invalid-opaque-result-types.swift
Labels: r5.3

#31531 [5.3][build] specify deployment targets for compatibility libraries
  stdlib/toolchain/CMakeLists.txt
  stdlib/toolchain/Compatibility50/CMakeLists.txt
  stdlib/toolchain/Compatibility51/CMakeLists.txt
  stdlib/toolchain/CompatibilityDynamicReplacements/CMakeLists.txt
Labels: r5.3

#31538 [5.3][SR-12725] Diagnose unhandled generic argument mismatch involving FunctionArgument
  lib/Sema/CSDiagnostics.cpp
  test/Constraints/diagnostics.swift
Labels: r5.3

#31530 [CxxInterop] Fix static-var-irgen test for arm/ios
  test/Interop/Cxx/static/static-var-irgen.swift
Labels: C++ Interop

#31542 Fix default arguments of inlinable local functions [5.3]
  lib/AST/DeclContext.cpp
  lib/SIL/IR/SILDeclRef.cpp
  test/SILGen/default_arguments_local.swift
  test/attr/attr_inlinable.swift
Labels: r5.3

#30580 [AutoDiff][TF-1200] Adding derivatives for stdlib `pow` function.
  stdlib/public/Differentiation/TgmathDerivatives.swift.gyb
  test/AutoDiff/stdlib/tgmath_derivatives.swift.gyb
Labels: tensorflow

#31547 [5.3][CodeCompletion] Give up fast-completion if dependent files are modified
  include/swift/IDE/CompletionInstance.h
  lib/IDE/CompletionInstance.cpp
  test/SourceKit/CodeComplete/Inputs/checkdeps/ClangFW.framework/Headers/ClangFW.h
  test/SourceKit/CodeComplete/Inputs/checkdeps/ClangFW.framework/Headers/Funcs.h
  test/SourceKit/CodeComplete/Inputs/checkdeps/ClangFW.framework/Modules/module.modulemap
  test/SourceKit/CodeComplete/Inputs/checkdeps/ClangFW.framework_mod/Headers/Funcs.h
  test/SourceKit/CodeComplete/Inputs/checkdeps/MyProject/Bridging.h
  test/SourceKit/CodeComplete/Inputs/checkdeps/MyProject/Library.swift
  test/SourceKit/CodeComplete/Inputs/checkdeps/MyProject/LibraryExt.swift
  test/SourceKit/CodeComplete/Inputs/checkdeps/MyProject/LocalCFunc.h
  test/SourceKit/CodeComplete/Inputs/checkdeps/MyProject_mod/Library.swift
  test/SourceKit/CodeComplete/Inputs/checkdeps/MyProject_mod/LocalCFunc.h
  test/SourceKit/CodeComplete/Inputs/checkdeps/SwiftFW_src/Funcs.swift
  test/SourceKit/CodeComplete/Inputs/checkdeps/SwiftFW_src_mod/Funcs.swift
  test/SourceKit/CodeComplete/Inputs/checkdeps/test.swift
  test/SourceKit/CodeComplete/complete_checkdeps_bridged.swift
  test/SourceKit/CodeComplete/complete_checkdeps_clangmodule.swift
  test/SourceKit/CodeComplete/complete_checkdeps_otherfile.swift
  test/SourceKit/CodeComplete/complete_checkdeps_swiftmodule.swift
  test/SourceKit/CodeComplete/complete_checkdeps_vfs.swift
  test/SourceKit/CodeComplete/complete_checkdeps_vfs_open.swift
  tools/SourceKit/include/SourceKit/Core/Context.h
  tools/SourceKit/include/SourceKit/Core/LangSupport.h
  tools/SourceKit/lib/Core/Context.cpp
  tools/SourceKit/lib/SwiftLang/SwiftCompletion.cpp
  tools/SourceKit/lib/SwiftLang/SwiftLangSupport.cpp
  tools/SourceKit/lib/SwiftLang/SwiftLangSupport.h
  tools/SourceKit/tools/sourcekitd-test/Options.td
  tools/SourceKit/tools/sourcekitd-test/TestOptions.cpp
  tools/SourceKit/tools/sourcekitd-test/TestOptions.h
  tools/SourceKit/tools/sourcekitd-test/sourcekitd-test.cpp
  tools/SourceKit/tools/sourcekitd/lib/API/Requests.cpp
  utils/gyb_sourcekit_support/UIDs.py
Labels: r5.3

#31567 [5.3][CodeCompletion] Make getEquivalentDeclContextFromSourceFile safer
  lib/IDE/CompletionInstance.cpp
Labels: r5.3

#31566 [5.3][CodeCompletion] Dont mark type mismatching items 'not recommended'
  include/swift/IDE/CodeCompletion.h
  lib/IDE/CodeCompletion.cpp
  lib/IDE/CodeCompletionCache.cpp
  test/IDE/complete_assignment.swift
  test/IDE/complete_at_top_level.swift
  test/IDE/complete_call_arg.swift
  test/IDE/complete_enum_elements.swift
  test/IDE/complete_func_reference.swift
  test/IDE/complete_literal.swift
  test/IDE/complete_loop.swift
  test/IDE/complete_return.swift
  test/IDE/complete_single_expression_return.swift
  test/IDE/complete_stmt_controlling_expr.swift
  test/IDE/complete_value_expr.swift
  test/SourceKit/CodeComplete/complete_sort_order.swift
  test/SourceKit/CodeComplete/complete_typerelation.swift
  test/SourceKit/CodeComplete/complete_typerelation.swift.convertible.response
  test/SourceKit/CodeComplete/complete_typerelation.swift.identical.response
  tools/SourceKit/lib/SwiftLang/CodeCompletion.h
  tools/SourceKit/lib/SwiftLang/CodeCompletionOrganizer.cpp
Labels: r5.3

#31574 [5.3] Make the ptrauth builtins no-ops when ptrauth is disabled.
  lib/IRGen/GenBuiltin.cpp
  test/IRGen/ptrauth-builtins.sil
Labels: r5.3

#31536 [5.3][SourceKit] Report macCatalyst availability as macCatalyst rather than iOS
  test/SourceKit/DocSupport/Inputs/availability_maccatalyst.swift
  test/SourceKit/DocSupport/Inputs/availability_maccatalyst_is_deprecated.swift
  test/SourceKit/DocSupport/doc_swift_module_availability_maccatalyst.swift
  test/SourceKit/DocSupport/doc_swift_module_availability_maccatalyst_is_deprecated.swift
  test/SourceKit/DocSupport/doc_swift_module_availability_maccatalyst_is_deprecated.swift.response
  tools/SourceKit/lib/SwiftLang/SwiftDocSupport.cpp
Labels: r5.3

#31537 [5.3] COWArrayOpts: fix a mis-compile related to owned function arguments
  lib/SILOptimizer/LoopTransforms/COWArrayOpt.cpp
  test/SILOptimizer/wrong_cow_arrayopt.swift
Labels: r5.3

#31594 [5.3][IDE] Loosen assertion check in IDE/SyntaxModelWalker
  lib/IDE/SyntaxModel.cpp
  test/IDE/coloring.swift
Labels: r5.3

#31596 [5.3][IDE][DocSupport] Fix DocInfo missing decls when generated for clang submodules.
  include/swift/IDE/ModuleInterfacePrinting.h
  lib/ClangImporter/ClangImporter.cpp
  lib/IDE/ModuleInterfacePrinting.cpp
  test/SourceKit/DocSupport/doc_clang_module.swift
  test/SourceKit/DocSupport/doc_clang_module.swift.sub.response
  test/SourceKit/InterfaceGen/gen_clang_module.swift.sub.response
  tools/SourceKit/lib/SwiftLang/SwiftDocSupport.cpp
  tools/SourceKit/lib/SwiftLang/SwiftEditorInterfaceGen.cpp
  tools/swift-ide-test/swift-ide-test.cpp
Labels: r5.3

#31598 [5.3][IDE][SourceKit] Support escaped identifiers for the syntactic rename and related idents requests.
  lib/IDE/Refactoring.cpp
  lib/IDE/SourceEntityWalker.cpp
  lib/IDE/SwiftSourceDocInfo.cpp
  test/Index/roles.swift
  test/SourceKit/NameTranslation/swiftnames.swift
  test/SourceKit/Refactoring/basic.swift
  test/SourceKit/RelatedIdents/related_idents.swift
  test/refactoring/SyntacticRename/FindRangeOutputs/backticks-noncollapsible-separate-arglabel.swift.expected
  test/refactoring/SyntacticRename/FindRangeOutputs/backticks-noncollapsible.swift.expected
  test/refactoring/SyntacticRename/FindRangeOutputs/backticks-separate-arglabel.swift.expected
  test/refactoring/SyntacticRename/FindRangeOutputs/backticks.swift.expected
  test/refactoring/SyntacticRename/backticks-noncollapsible-separate-arglabel.swift
  test/refactoring/SyntacticRename/backticks-noncollapsible.swift
  test/refactoring/SyntacticRename/backticks-separate-arglabel.swift
  test/refactoring/SyntacticRename/backticks.swift
  tools/SourceKit/tools/sourcekitd/lib/API/Requests.cpp
Labels: r5.3

#31576 [5.3] Fix module triples for “ios-like” Mac Catalyst modules
  stdlib/cmake/modules/SwiftSource.cmake
Labels: r5.3

#31608 [5.3] Revert "[CS] Account for type variables when matching metatypes"
  lib/Sema/CSSimplify.cpp
  test/Constraints/rdar62842651.swift
Labels: r5.3

#31618 [5.3] IRGen: Re-add XFAILs to class_resilience_objc test
  test/IRGen/class_resilience_objc.swift
Labels: r5.3

#31614 [5.3][ConstraintSystem] Always verify computed/resolved pattern types befo…
  lib/Sema/CSGen.cpp
Labels: r5.3

#31613 [5.3][Diagnostics] Diagnose passing r-value without `&` to `inout` paramet…
  lib/Sema/CSSimplify.cpp
  test/Constraints/diagnostics.swift
Labels: r5.3

#31617 Add a test that imported C++ classes can conform to protocols
  test/Interop/Cxx/class/Inputs/module.modulemap
  test/Interop/Cxx/class/Inputs/protocol-conformance.h
  test/Interop/Cxx/class/protocol-conformance-silgen.swift
  test/Interop/Cxx/class/protocol-conformance-typechecker.swift
Labels: C++ Interop

#31619 Synthesize memberwise initializers despite AccessSpecDecl
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/class/Inputs/memberwise-initializer.h
  test/Interop/Cxx/class/Inputs/module.modulemap
  test/Interop/Cxx/class/member-variables-module-interface.swift
  test/Interop/Cxx/class/memberwise-initializer-module-interface.swift
  test/Interop/Cxx/class/memberwise-initializer-typechecker.swift
Labels: C++ Interop

#31592 For the TensorFlow toolchain, keep using @rpath for libraries
  lib/Basic/Platform.cpp
  stdlib/linker-support/magic-symbols-for-install-name.c
  test/Driver/linker-rpath.swift
Labels: tensorflow

#31628 [5.3][SymbolGraph] Use `identifier` for type name fragments
  lib/SymbolGraphGen/DeclarationFragmentPrinter.cpp
  lib/SymbolGraphGen/DeclarationFragmentPrinter.h
  lib/SymbolGraphGen/SymbolGraph.cpp
  test/SymbolGraph/Symbols/Mixins/DeclarationFragments/Navigator.swift
  test/SymbolGraph/Symbols/Mixins/DeclarationFragments/SubheadingDeclarationFragmentsTypes.swift
Labels: r5.3

#31656 Correctly print an AbstractionPattern with C++ method types
  lib/SIL/IR/AbstractionPattern.cpp
Labels: C++ Interop

#31657 Synthesize memberwise initializers despite member functions
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/class/Inputs/memberwise-initializer.h
  test/Interop/Cxx/class/memberwise-initializer-module-interface.swift
  test/Interop/Cxx/class/memberwise-initializer-typechecker.swift
Labels: C++ Interop

#31556 Improved the description of loadable and address-only types
  docs/SIL.rst
Labels: C++ Interop

#31655 [5.3][ConstraintSystem] Look through key path dynamic lookup nodes while s…
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/diagnostics.swift
Labels: r5.3

#31640 Patch a Source of Iterator Invalidation
  lib/AST/Module.cpp
Labels: r5.3

#31659 [5.3] Add fix on Keypath -> Function with multiple arguments type mismatch
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSFix.h
  lib/Sema/CSSimplify.cpp
  test/Constraints/keypath_closure_conv_mismatch.swift
  test/Constraints/keypath_closure_conv_mismatch_generic.swift
  test/Constraints/keypath_closure_conv_mismatch_norettype.swift
Labels: r5.3

#31670 [AutoDiff] Fix derivative function configurations for accessors.
  lib/AST/Decl.cpp
  lib/SILOptimizer/Mandatory/Differentiation.cpp
  test/AutoDiff/SILOptimizer/Inputs/differentiation_diagnostics_other_file.swift
  test/AutoDiff/SILOptimizer/differentiation_diagnostics_cross_file.swift
Labels: tensorflow

#31677 [TF] Add "-DLLVM_ENABLE_Z3_SOLVER=NO" to tensorflow presets.
  utils/build-presets.ini
Labels: tensorflow

#31699 [AutoDiff] Remove upstreamed tensorflow branch tests.
  test/Sema/Inputs/class_differentiable_other_module.swift
  test/Sema/Inputs/struct_additive_arithmetic_other_module.swift
  test/Sema/Inputs/struct_differentiable_other_module.swift
  test/Sema/class_differentiable.swift
  test/Sema/struct_additive_arithmetic.swift
  test/Sema/struct_differentiable.swift
Labels: tensorflow

#31701 [AutoDiff] Fix semantic member accessor pullback ownership errors.
  lib/SILOptimizer/Differentiation/PullbackEmitter.cpp
  test/AutoDiff/SILOptimizer/Inputs/nontrivial_loadable_type.swift
  test/AutoDiff/SILOptimizer/property_wrappers.swift
Labels: tensorflow

#31718 [5.3][Parser/libSyntax] Avoid doing lookup for a previous parsed node when we are in backtracking mode
  include/swift/Parse/Parser.h
  include/swift/Parse/SyntaxParsingContext.h
  lib/Parse/ParseDecl.cpp
  lib/Parse/Parser.cpp
  lib/Parse/SyntaxParsingContext.cpp
  test/incrParse/add-close-brace-to-property.swift
  test/incrParse/reuse.swift
Labels: r5.3

#31660 [5.3] Allow SPI access within the same module in checkAccess
  lib/AST/Decl.cpp
  test/SPI/equatable_and_conformances.swift
Labels: r5.3

#31661 [5.3] FunctionSignatureOptimization: fix a miscompile in owned->guaranteed return value specialization
  include/swift/SILOptimizer/Analysis/EpilogueARCAnalysis.h
  test/SILOptimizer/epilogue_arc_dumper.sil
  test/SILOptimizer/functionsigopts.sil
Labels: r5.3

#31738 [CodeCompletion] Annotated type name and 'IsSystem'
  include/swift/IDE/CodeCompletion.h
  include/swift/IDE/CodeCompletionResultPrinter.h
  lib/IDE/CodeCompletion.cpp
  lib/IDE/CodeCompletionCache.cpp
  lib/IDE/CodeCompletionResultBuilder.h
  lib/IDE/CodeCompletionResultPrinter.cpp
  lib/IDE/REPLCodeCompletion.cpp
  test/IDE/complete_annotation.swift
  test/IDE/complete_at_start_1.swift
  test/IDE/complete_at_top_level.swift
  test/IDE/complete_cache.swift
  test/IDE/complete_call_arg.swift
  test/IDE/complete_crashes.swift
  test/IDE/complete_cross_import.swift
  test/IDE/complete_cross_import_indirect.swift
  test/IDE/complete_cross_import_multiple.swift
  test/IDE/complete_cross_import_no_underscore.swift
  test/IDE/complete_cross_import_no_underscore_imported.swift
  test/IDE/complete_dynamic_lookup.swift
  test/IDE/complete_enum_elements.swift
  test/IDE/complete_exception.swift
  test/IDE/complete_expr_postfix_begin.swift
  test/IDE/complete_expr_tuple.swift
  test/IDE/complete_from_clang_framework.swift
  test/IDE/complete_from_clang_importer_framework.swift
  test/IDE/complete_from_foundation_overlay.swift
  test/IDE/complete_from_stdlib.swift
  test/IDE/complete_from_swift_module.swift
  test/IDE/complete_from_swiftonly_systemmodule.swift
  test/IDE/complete_in_closures.swift
  test/IDE/complete_literal.swift
  test/IDE/complete_multifile.swift
  test/IDE/complete_multiple_trailingclosure.swift
  test/IDE/complete_operators.swift
  test/IDE/complete_override.swift
  test/IDE/complete_pound_selector.swift
  test/IDE/complete_precedencegroup.swift
  test/IDE/complete_stdlib_optional_objc.swift
  test/IDE/complete_swift_key_path.swift
  test/IDE/complete_type_subscript.swift
  test/IDE/complete_unresolved_members.swift
  test/IDE/complete_value_expr.swift
  test/IDE/complete_where_clause.swift
  test/SourceKit/CodeComplete/complete_annotateddescription.swift
  test/SourceKit/CodeComplete/complete_annotateddescription.swift.result
  test/SourceKit/CodeComplete/complete_from_system.swift
  tools/SourceKit/include/SourceKit/Core/LangSupport.h
  tools/SourceKit/lib/SwiftLang/CodeCompletionOrganizer.cpp
  tools/SourceKit/lib/SwiftLang/SwiftCompletion.cpp
  tools/SourceKit/tools/sourcekitd/include/sourcekitd/CodeCompletionResultsArray.h
  tools/SourceKit/tools/sourcekitd/lib/API/CodeCompletionResultsArray.cpp
  tools/SourceKit/tools/sourcekitd/lib/API/Requests.cpp
  utils/gyb_sourcekit_support/UIDs.py
  validation-test/IDE/complete_from_cocoa.swift
  validation-test/IDE/complete_from_cocoa_2.swift
  validation-test/IDE/crashers_fixed/subexpr-literal-in-sequence-expr.swift
Labels: r5.3

#31748 [AutoDiff] Fix semantic member accessor linear map structs.
  lib/SILOptimizer/Differentiation/LinearMapInfo.cpp
  test/AutoDiff/SILOptimizer/property_wrappers.swift
Labels: tensorflow

#31749 Remove test/Interpreter/repl.swift.
  test/Interpreter/repl.swift
Labels: tensorflow

#31702 [CxxInterop] Import C++ references.
  include/swift/AST/Types.h
  lib/AST/Type.cpp
  lib/ClangImporter/ImportType.cpp
  lib/ClangImporter/ImporterImpl.h
  lib/SIL/IR/AbstractionPattern.cpp
  test/Interop/Cxx/reference/Inputs/module.modulemap
  test/Interop/Cxx/reference/Inputs/reference.cpp
  test/Interop/Cxx/reference/Inputs/reference.h
  test/Interop/Cxx/reference/reference-irgen.swift
  test/Interop/Cxx/reference/reference-module-interface.swift
  test/Interop/Cxx/reference/reference-silgen.swift
  test/Interop/Cxx/reference/reference.swift
Labels: C++ Interop

#31707 Classify C++ structs as loadable or address-only
  include/swift/AST/Decl.h
  lib/AST/Decl.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/SIL/IR/TypeLowering.cpp
  test/Interop/Cxx/class/Inputs/loadable-types.h
  test/Interop/Cxx/class/Inputs/module.modulemap
  test/Interop/Cxx/class/loadable-types-silgen.swift
Labels: C++ Interop

#31751 [5.3][ASTPrinter] Fix issue where printing if-let variables shows their type as optional
  lib/AST/ASTPrinter.cpp
  lib/Parse/ParsePattern.cpp
  test/SourceKit/CursorInfo/sr-12631-if-let-type.swift
Labels: r5.3

#31756 [5.3][CodeCompletion] Inherit options when parsing new buffer
  lib/IDE/CompletionInstance.cpp
  lib/Parse/ParseIfConfig.cpp
  test/SourceKit/CodeComplete/complete_sequence_ifconfig.swift
Labels: r5.3

#31488 [5.3] Remove stray backtick in docs.
  stdlib/public/core/Dictionary.swift
Labels: r5.3

#31763 [5.3] [Sema] Fix a couple of AnyObject lookup bugs
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/ConstraintSystem.cpp
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/TypeCheckDeclObjC.cpp
  test/Constraints/dynamic_lookup.swift
  test/attr/attr_objc.swift
Labels: r5.3

#31761 [5.3] Check SPI usage of implementation-only types, in frozen types and on protocol requirements
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckAccess.cpp
  lib/Sema/TypeCheckAttr.cpp
  test/SPI/implementation_only_spi_import_exposability.swift
  test/SPI/local_spi_decls.swift
  test/SPI/protocol_requirement.swift
  test/SPI/resilience.swift
Labels: r5.3

#31764 [5.1 Compatibility library] Add missing #include
  stdlib/toolchain/Compatibility51/Concurrent.h
Labels: r5.3

#31772 [5.3] Reduce Generic use in Codable
  stdlib/public/core/Codable.swift
Labels: r5.3

#31788 [5.3] ReplaceOpaqueTypesWithUnderlyingTypes: Handle a type being "substituted" with itself.
  lib/AST/Type.cpp
  test/SILGen/opaque_type_lowering_in_substitution.swift
Labels: r5.3

#31792 [5.3][CodeCompletion] Avoid re-typechecking pre-checked expressions
  lib/IDE/ExprContextAnalysis.cpp
  lib/Sema/CSGen.cpp
  test/IDE/complete_call_arg.swift
Labels: r5.3

#31776 [5.3][Type-checker] Improve diagnostic for keypath used without 'keyPath:' label
  lib/Sema/CSSimplify.cpp
  test/Sema/keypath_subscript_nolabel.swift
Labels: r5.3

#31784 [CxxInterop] Import C++ references.
  include/swift/AST/Types.h
  lib/AST/Type.cpp
  lib/ClangImporter/ImportType.cpp
  lib/ClangImporter/ImporterImpl.h
  lib/SIL/IR/AbstractionPattern.cpp
  test/Interop/Cxx/reference/Inputs/module.modulemap
  test/Interop/Cxx/reference/Inputs/reference.cpp
  test/Interop/Cxx/reference/Inputs/reference.h
  test/Interop/Cxx/reference/reference-irgen.swift
  test/Interop/Cxx/reference/reference-module-interface.swift
  test/Interop/Cxx/reference/reference-silgen.swift
  test/Interop/Cxx/reference/reference.swift
Labels: C++ Interop

#31803 [5.2][test] Fix LLDB Python Path and re-enable linux-fatal-backtrace.swift
  test/lit.cfg
Labels: r5.2

#31780 [5.3] Make the lazy assignment of an associated type/wtable atomic
  stdlib/public/runtime/Metadata.cpp
  test/Runtime/associated_witness_concurrency.swift
Labels: r5.3

#31813 Added tests for edge cases in importing and mangling C structs
  test/Interop/C/struct/Inputs/module.modulemap
  test/Interop/C/struct/Inputs/struct-decl-context.h
  test/Interop/C/struct/struct-decl-context-irgen.swift
  test/Interop/C/struct/struct-decl-context-module-interface.swift
Labels: C++ Interop

#31805 Simplify lazy function body emission in SILGen
  lib/SILGen/SILGen.cpp
  lib/SILGen/SILGen.h
  lib/SILGen/SILGenThunk.cpp
  test/ClangImporter/attr-swift_private.swift
  test/ClangImporter/objc_ir.swift
  test/SILGen/objc_currying.swift
  test/SILGen/objc_imported_generic.swift
Labels: CodeHealth

#31801 SILGen: Remove obsolete hack preventing emission of allocating init for unavailable initializer [5.3]
  lib/SILGen/SILGen.cpp
  test/SILGen/Inputs/objc_init_unavailable.h
  test/SILGen/objc_init_unavailable.swift
Labels: r5.3

#31810 [5.3][ConstraintSystem] Detect and diagnose inability to infer type of clo…
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/CSBindings.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSFix.h
  lib/Sema/CSGen.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintGraph.cpp
  lib/Sema/ConstraintSystem.h
  lib/Sema/TypeCheckConstraints.cpp
  test/Constraints/closures.swift
  test/Constraints/diagnostics.swift
  test/Sema/diag_ambiguous_overloads.swift
  test/decl/typealias/generic.swift
  test/expr/closure/anonymous.swift
  test/expr/closure/basic.swift
  test/expr/unary/keypath/salvage-with-other-type-errors.swift
  validation-test/compiler_crashers_2_fixed/0186-rdar46497155.swift
Labels: r5.3

#31834 [5.3][ASTPrinter] Don't print inferred opaque result type witness
  lib/AST/Type.cpp
  test/IDE/complete_opaque_result.swift
  test/SourceKit/CursorInfo/cursor_opaque_result.swift
Labels: r5.3

#31833 [5.3] SILGen: Extend scope for evaluation in memberwise initializers to include initializer expressions.
  lib/SILGen/SILGenConstructor.cpp
  test/SILGen/memberwise_init_temporary_allocations.swift
Labels: r5.3

#31827 [5.3] Revert RangeSet additions
  stdlib/private/StdlibCollectionUnittest/CMakeLists.txt
  stdlib/private/StdlibCollectionUnittest/COWLoggingArray.swift
  stdlib/public/core/CMakeLists.txt
  stdlib/public/core/CollectionAlgorithms.swift
  stdlib/public/core/DiscontiguousSlice.swift
  stdlib/public/core/GroupInfo.json
  stdlib/public/core/MutableCollection.swift
  stdlib/public/core/RangeReplaceableCollection.swift
  stdlib/public/core/RangeSet.swift
  stdlib/public/core/RangeSetStorage.swift
  test/Constraints/members.swift
  test/type/types.swift
  validation-test/StdlibUnittest/RangeSet.swift
Labels: r5.3

#31836 GSB: Concretize nested types when adding a superclass constraint [5.3]
  lib/AST/GenericSignatureBuilder.cpp
  test/Generics/superclass_constraint_nested_type.swift
  validation-test/compiler_crashers_2_fixed/sr11232.swift
Labels: r5.3

#31862 [5.3] [CS] Diagnostic improvements for key paths
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/CSBindings.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSFix.h
  lib/Sema/CSGen.cpp
  lib/Sema/CSSimplify.cpp
  test/Constraints/rdar62201037.swift
  test/expr/unary/keypath/keypath.swift
Labels: r5.3

#31858 [5.3] IRGen: Only replace opaque result types of function result types when performing a dynamic replacement
  lib/IRGen/GenDecl.cpp
  test/IRGen/Inputs/opaque_return_type_parameter.swift
  test/IRGen/dynamic_replaceable_opaque_return_type_parameter.swift
Labels: r5.3

#31859 Consolidated four CoreGraphics execution tests
  test/Interpreter/SDK/CGImportAsMember.swift
  test/Interpreter/SDK/CoreGraphics_CGFloat.swift
  test/stdlib/CoreGraphics.swift
  validation-test/stdlib/CoreGraphics-execute.swift
Labels: CodeHealth

#31887 Remove support for a broken std::regex in libstdc++ 4.8
  CMakeLists.txt
  cmake/modules/SwiftCheckCXXNativeRegex.cmake
  include/swift/Config.h.in
  lib/IDE/SyntaxModel.cpp
  test/IDE/coloring_comments.swift
  test/SourceKit/CodeComplete/complete_crash1.swift
  test/SourceKit/CodeComplete/complete_filter.swift
  test/SourceKit/CodeComplete/complete_fuzzy.swift
  test/SourceKit/CodeComplete/complete_group_overloads.swift
  test/SourceKit/CodeComplete/complete_import_module_flag.swift
  test/SourceKit/CodeComplete/complete_inner.swift
  test/SourceKit/CodeComplete/complete_literals.swift
  test/SourceKit/CodeComplete/complete_moduleimportdepth.swift
  test/SourceKit/CodeComplete/complete_name.swift
  test/SourceKit/CodeComplete/complete_operators.swift
  test/SourceKit/CodeComplete/complete_requestlimit.swift
  test/SourceKit/CodeComplete/complete_sort_order.swift
  test/SourceKit/CodeComplete/complete_stems.swift
  test/SourceKit/CodeComplete/complete_structure.swift
  test/SourceKit/CodeComplete/complete_test.swift
  test/SourceKit/CodeComplete/complete_type_match.swift
  test/SourceKit/SyntaxMapData/syntaxmap.swift
  test/lit.site.cfg.in
Labels: CodeHealth

#31883 Reenable a test for UnicodeScalar
  test/stdlib/UnicodeScalarDiagnostics.swift
Labels: CodeHealth

#31886 [5.3] [TBDGen] Fix symbol mismatch for enum case constructors
  include/swift/SIL/SILDeclRef.h
  include/swift/SIL/SILLinkage.h
  lib/SIL/IR/SILDeclRef.cpp
  lib/SIL/Verifier/SILVerifier.cpp
  lib/SILGen/SILGenType.cpp
  lib/TBDGen/TBDGen.cpp
  test/SILGen/internal_protocol_refines_public_protocol_with_public_default_implementation.swift
  test/SILGen/protocol_enum_witness.swift
  test/TBD/enum_case_protocol_witness.swift
Labels: r5.3

#31873 [5.3][AST] Restore getSourceRange() on DefaultArgumentExpr
  include/swift/AST/Expr.h
  lib/AST/Expr.cpp
  lib/Sema/TypeCheckExpr.cpp
  test/DebugInfo/callexpr.swift
Labels: r5.3

#31897 [5.3] No dummy constraint in the public swiftinterface for SPI extensions
  lib/Frontend/ModuleInterfaceSupport.cpp
  test/SPI/private_swiftinterface.swift
Labels: r5.3

#31909 Removed support for iOS 8.2 and earlier from lit.cfg
  test/lit.cfg
Labels: CodeHealth

#31907 [SR-12842] Restore missing docs for RangeExpression.~=
  stdlib/public/core/Range.swift
Labels: bug

#31917 [5.3][CodeCompletion] Avoid suggesting duplicated module names
  lib/IDE/CodeCompletion.cpp
  test/IDE/Inputs/mock-sdk/OverlayTest.framework/Headers/OverlayTest.h
  test/IDE/Inputs/mock-sdk/OverlayTest.framework/Headers/Overlayed.h
  test/IDE/Inputs/mock-sdk/OverlayTest.framework/Modules/module.modulemap
  test/IDE/Inputs/mock-sdk/OverlayTest.swiftinterface
  test/IDE/complete_overlaymodule.swift
Labels: r5.3

#31924 [5.3] IRGen: Correctly compute the offset for a non-fixed field after…
  lib/IRGen/GenHeap.cpp
  lib/IRGen/StructLayout.cpp
  lib/IRGen/StructLayout.h
  test/IRGen/partial_apply.sil
Labels: r5.3

#31890 Fix and reenable NewArray.swift.gyb
  validation-test/stdlib/NewArray.swift.gyb
Labels: CodeHealth

#31938 [5.3] [Typechecker] Emit a specialised diagnostic for redeclaration errors when the declaration is synthesised
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsSema.def
  lib/AST/Decl.cpp
  lib/Sema/TypeCheckDeclPrimary.cpp
  test/Sema/enum_conformance_synthesis.swift
  test/decl/var/property_wrappers.swift
Labels: r5.3

#31935 [5.3] IRGen: Fix enumPayload value witness emission for huge types
  lib/IRGen/GenType.cpp
  test/IRGen/Inputs/huge_c_type.h
  test/IRGen/huge_c_type.swift
Labels: r5.3

#31958 [5.3][Property Wrappers] Fix handling of properties that are default initialized via property wrapper
  lib/AST/Decl.cpp
  lib/Sema/ConstraintSystem.cpp
  test/decl/var/property_wrappers_default_init.swift
Labels: r5.3

#31948 PrintAsObjC: Fix crash when printing typedef that was imported inside an Objective-C generic class [5.3]
  lib/PrintAsObjC/ModuleContentsWriter.cpp
  test/PrintAsObjC/Inputs/imported-generic-typealias.h
  test/PrintAsObjC/imported-generic-typealias.swift
Labels: r5.3

#31945 [5.3][SourceKit/CodeFormat] Fix var/let declaration continuation lines appearing over-indented.
  lib/IDE/Formatting.cpp
  test/SourceKit/CodeFormat/indent-multiline-string.swift
  test/SourceKit/CodeFormat/rdar_32789463.swift
  test/swift-indent/basic.swift
Labels: r5.3

#31959 [5.3][NFC][SwiftSyntax] Fix 'Traling' typo
  utils/gyb_syntax_support/ExprNodes.py
Labels: r5.3

#31972 [5.3] [ConstraintSystem] Disallow use of enum case as a key path component
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSFix.h
  validation-test/compiler_crashers_2_fixed/sr12863.swift
Labels: r5.3

#31990 ASTDemangler: Add support for member types of opaque result types [5.3]
  lib/AST/ASTDemangler.cpp
  test/TypeDecoder/opaque_return_type.swift
Labels: r5.3

#31976 [5.3][IDE][InterfaceGen] Always print the top-level decl in header file generated interfaces
  lib/IDE/ModuleInterfacePrinting.cpp
  test/SourceKit/InterfaceGen/Inputs/header3.h
  test/SourceKit/InterfaceGen/gen_header.swift
  test/SourceKit/InterfaceGen/gen_header.swift.header3.response
Labels: r5.3

#32013 [5.3] [Function builders] Infer function builder from a protocol requirement.
  include/swift/AST/ASTTypeIDZone.def
  include/swift/AST/ASTTypeIDs.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/TypeCheckRequests.h
  include/swift/Basic/SimpleDisplay.h
  lib/AST/Attr.cpp
  lib/AST/Decl.cpp
  lib/Sema/BuilderTransform.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckProtocol.cpp
  lib/Sema/TypeCheckRequestFunctions.cpp
  lib/Sema/TypeCheckStmt.cpp
  lib/Sema/TypeChecker.h
  test/Constraints/function_builder_infer.swift
  test/Incremental/single-file/AnyObject.swift
  test/ModuleInterface/function_builders.swift
  test/Serialization/function_builders.swift
Labels: r5.3

#32033 [AutoDiff] Fix differentiation crashes related to definite initialization.
  include/swift/SIL/SILCloner.h
  lib/SILOptimizer/Differentiation/VJPEmitter.cpp
  test/AutoDiff/compiler_crashers_fixed/sr12886-sr112887-vjp-emitter-definite-initialization.swift
Labels: tensorflow

#32015 Start implementing C++ operator interop
  lib/ClangImporter/ImportName.cpp
  test/Interop/Cxx/operators/Inputs/module.modulemap
  test/Interop/Cxx/operators/Inputs/non-member-inline.h
  test/Interop/Cxx/operators/non-member-inline-module-interface.swift
  test/Interop/Cxx/operators/non-member-inline-typechecker.swift
  test/Interop/Cxx/operators/non-member-inline.swift
Labels: C++ Interop

#32047 [5.3][SourceKit][InterfaceGen] Don't print clang decls marked with the swift_private attribute.
  include/swift/AST/PrintOptions.h
  lib/AST/ASTPrinter.cpp
  test/SourceKit/DocSupport/doc_clang_module.swift.response
  test/SourceKit/Inputs/libIDE-mock-sdk/Foo.framework/Headers/Foo.h
  test/SourceKit/InterfaceGen/Inputs/header.h
Labels: r5.3

#32064 [AutoDiff] Derive `Differentiable.zeroTangentVectorInitializer`.
  docs/DifferentiableProgramming.md
  include/swift/AST/KnownIdentifiers.def
  lib/Sema/CodeSynthesis.cpp
  lib/Sema/CodeSynthesis.h
  lib/Sema/DebuggerTestingTransform.cpp
  lib/Sema/DerivedConformanceDifferentiable.cpp
  lib/Sema/DerivedConformances.cpp
  lib/Sema/DerivedConformances.h
  lib/Sema/TypeCheckProtocol.cpp
  lib/Sema/TypeChecker.h
  stdlib/public/Differentiation/AnyDifferentiable.swift
  stdlib/public/Differentiation/ArrayDifferentiation.swift
  stdlib/public/Differentiation/Differentiable.swift
  stdlib/public/Differentiation/FloatingPointDifferentiation.swift.gyb
  stdlib/public/Differentiation/SIMDDifferentiation.swift.gyb
  test/AutoDiff/Sema/DerivativeRegistrationCrossModule/Inputs/b.swift
  test/AutoDiff/Sema/DerivedConformances/derived_zero_tangent_vector_initializer.swift
  test/AutoDiff/downstream/differentiable_requirement_cross_module.swift
  test/AutoDiff/validation-test/zero_tangent_vector_initializer.swift
Labels: tensorflow

#31913 Emit `/DEFAULTLIB` directive for `#pragma comment(lib, ...)` in a C module
  lib/IRGen/GenClangDecl.cpp
  test/IRGen/Inputs/autolink-coff-c-pragma-transitive.h
  test/IRGen/Inputs/autolink-coff-c-pragma.h
  test/IRGen/Inputs/module.modulemap
  test/IRGen/autolink-coff-c-pragma.swift
Labels: C++ Interop

#32075 [5.3][Serialization] Skip SPI documentation in swiftdoc files
  lib/Serialization/SerializeDoc.cpp
  test/Serialization/comments-hidden.swift
Labels: r5.3
