Repository swiftlang/swift, pull requests merged in 2021-12, with the labels that each got.

#40336 [nfc][cxx-interop] Mark lazy member loading complete only after members are loaded.
  include/swift/AST/DeclContext.h
  lib/AST/DeclContext.cpp
  lib/ClangImporter/ImportDecl.cpp
Labels: C++ Interop

#40490 Adding optional message to `_unavailableFromAsync`
  include/swift/AST/Attr.def
  include/swift/AST/Attr.h
  include/swift/AST/DiagnosticsParse.def
  include/swift/AST/DiagnosticsSema.def
  lib/AST/Attr.cpp
  lib/Parse/ParseDecl.cpp
  lib/Sema/TypeCheckAvailability.cpp
  lib/Serialization/Deserialization.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/Serialization.cpp
  test/ClangImporter/objc_async.swift
  test/Concurrency/unavailable_from_async.swift
  test/Inputs/clang-importer-sdk/usr/include/ObjCConcurrency.h
Labels: r5.6

#40505 [5.6][SE-0335] Introduce existential `any`
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsParse.def
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  include/swift/AST/TypeDifferenceVisitor.h
  include/swift/AST/TypeMatcher.h
  include/swift/AST/TypeNodes.def
  include/swift/AST/TypeRepr.h
  include/swift/AST/TypeReprNodes.def
  include/swift/AST/Types.h
  include/swift/Basic/LangOptions.h
  include/swift/Option/FrontendOptions.td
  lib/AST/ASTContext.cpp
  lib/AST/ASTDemangler.cpp
  lib/AST/ASTDumper.cpp
  lib/AST/ASTMangler.cpp
  lib/AST/ASTPrinter.cpp
  lib/AST/ASTWalker.cpp
  lib/AST/Decl.cpp
  lib/AST/NameLookup.cpp
  lib/AST/Type.cpp
  lib/AST/TypeCheckRequests.cpp
  lib/AST/TypeRepr.cpp
  lib/AST/TypeWalker.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/IRGen/Fulfillment.cpp
  lib/IRGen/GenExistential.cpp
  lib/IRGen/GenType.cpp
  lib/IRGen/GenType.h
  lib/IRGen/IRGenDebugInfo.cpp
  lib/IRGen/MetadataRequest.cpp
  lib/Parse/ParsePattern.cpp
  lib/Parse/ParseType.cpp
  lib/PrintAsObjC/DeclAndTypePrinter.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/LookupVisibleDecls.cpp
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/TypeCheckDecl.cpp
  lib/Sema/TypeCheckDeclPrimary.cpp
  lib/Sema/TypeCheckGeneric.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeCheckType.h
  lib/Sema/TypeChecker.h
  lib/Serialization/DeclTypeRecordNodes.def
  lib/Serialization/Deserialization.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/Serialization.cpp
  test/TypeDecoder/explicit_existentials.swift
  test/type/explicit_existential.swift
Labels: r5.6

#40521 `ConcurrentReadableArray`: Use `std::uninitialized_copy_n()` instead of `std::copy()` to avoid calling destructors on uninitialized memory
  include/swift/Runtime/Concurrent.h
Labels: bug

#40507 [5.6][CSClosure] Support empty return when closure result is optional `Void`
  lib/Sema/CSClosure.cpp
  test/expr/closure/multi_statement.swift
Labels: r5.6

#40527 [5.6][SourceKit] Adjust no-crash-reopen-without-compiler-args.swift test case to pass on Windows
  test/SourceKit/Misc/no-crash-reopen-with-different-compiler-args.swift
  test/SourceKit/Misc/no-crash-reopen-without-compiler-args.swift
Labels: r5.6

#40520 Synchronize adding a child task to a TaskGroup with parent task
  include/swift/ABI/TaskGroup.h
  stdlib/public/CompatibilityOverride/CompatibilityOverrideConcurrency.def
  stdlib/public/Concurrency/TaskGroup.cpp
  stdlib/public/Concurrency/TaskStatus.cpp
Labels: Concurrency

#40546 [5.6] IRGen: Fix using weak linkage to avoid duplicate metadata by only applying this to PROTOCOL related data
  lib/IRGen/GenClass.cpp
  test/IRGen/generic_casts.swift
  test/IRGen/objc_async_metadata.swift
  test/IRGen/objc_attr_NSManaged.sil
  test/IRGen/objc_bridge.swift
  test/IRGen/objc_class_property.swift
  test/IRGen/objc_extensions.swift
  test/IRGen/objc_int_encoding.sil
  test/IRGen/objc_methods.swift
  test/IRGen/objc_properties.swift
  test/IRGen/objc_protocols.swift
  test/IRGen/objc_subclass.swift
  test/IRGen/objc_subscripts.swift
  test/IRGen/prespecialized-metadata/class-with-differently-mangled-method-list.swift
Labels: r5.6

#40572 StdlibRef: Sequence.withContiguousStorageIfAvailable(_:) abstract needs a rewrite - cherry-pick to release/5.6
  stdlib/public/core/MutableCollection.swift
  stdlib/public/core/Sequence.swift
Labels: r5.6

#40588 [5.6] Fully Check Decls in Result Builders
  lib/Sema/BuilderTransform.cpp
  test/Constraints/result_builder_diags.swift
Labels: r5.6

#40655 [5.6][Diagnostics] Fixes for a couple of "failed to produce diagnostic" issues related to ambiguities
  include/swift/Sema/CSFix.h
  test/Constraints/diagnostics.swift
  test/Constraints/keypath.swift
  test/type/protocol_composition.swift
Labels: r5.6

#40577 Make namelookup not allergic to async main
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckAttr.cpp
  test/Concurrency/Runtime/actor_init.swift
  test/Concurrency/Runtime/effectful_properties.swift
  test/Concurrency/Runtime/exclusivity.swift
  test/Concurrency/Runtime/exclusivity_custom_executors.swift
  test/Concurrency/async_main_resolution.swift
  test/Concurrency/async_main_resolution_macos.swift
  test/Sanitizers/tsan/actor_counters.swift
  test/Sanitizers/tsan/basic_future.swift
Labels: Concurrency

#40662 Update main namelookup resolution
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckAttr.cpp
  test/Concurrency/Runtime/actor_init.swift
  test/Concurrency/Runtime/effectful_properties.swift
  test/Concurrency/Runtime/exclusivity.swift
  test/Concurrency/Runtime/exclusivity_custom_executors.swift
  test/Concurrency/async_main_resolution.swift
  test/Concurrency/async_main_resolution_macos.swift
  test/Distributed/Runtime/distributed_actor_deinit.swift
  test/Distributed/Runtime/distributed_actor_isRemote.swift
  test/Distributed/Runtime/distributed_actor_local.swift
  test/Distributed/Runtime/distributed_actor_remote_fieldsDontCrashDeinit.swift
  test/Distributed/Runtime/distributed_no_transport_boom.swift
  test/Sanitizers/tsan/actor_counters.swift
  test/Sanitizers/tsan/basic_future.swift
Labels: r5.6

#40675 [Distributed] Runtime: Fix retrieval of async pointer from incorrect …
  stdlib/public/Concurrency/Actor.cpp
Labels: Distributed

#40684 Fix miss-parse diagnostic to say "actor"
  include/swift/AST/DiagnosticsParse.def
  lib/Parse/ParseDecl.cpp
  test/Parse/actor.swift
Labels: r5.6

#40697 [Distributed] IRGen: A couple of fixes for accessor
  include/swift/ABI/Executor.h
  lib/IRGen/GenDistributed.cpp
  stdlib/public/Concurrency/Actor.cpp
  test/Distributed/distributed_actor_accessor_thunks_32bit.swift
  test/Distributed/distributed_actor_accessor_thunks_64bit.swift
Labels: Distributed
