Repository swiftlang/swift, pull requests merged in 2021-07, with the labels that each got.

#38129 [Distributed] inject transport.resign into deinits
  include/swift/AST/KnownIdentifiers.def
  include/swift/AST/KnownProtocols.def
  lib/AST/NameLookup.cpp
  lib/IRGen/GenMeta.cpp
  lib/SILGen/SILGenBridging.cpp
  lib/SILGen/SILGenDestructor.cpp
  lib/SILGen/SILGenFunction.h
  lib/Sema/CodeSynthesisDistributedActor.cpp
  test.swift
  test/Distributed/Runtime/distributed_actor_deinit.swift
  test/SIL/Distributed/distributed_actor_sil.swift
Labels: distributed

#37959 [5.5][TypeChecker] NFC: Complicate perf test-case (rdar://19737632) by add…
  validation-test/Sema/type_checker_perf/slow/rdar19737632.swift
Labels: r5.5

#38178 [5.5][CodeCompletion] Migrate key path completion to be solver based
  include/swift/AST/Expr.h
  include/swift/Sema/CodeCompletionTypeChecking.h
  lib/AST/ASTDumper.cpp
  lib/AST/ASTWalker.cpp
  lib/AST/Expr.cpp
  lib/IDE/CodeCompletion.cpp
  lib/IDE/SourceEntityWalker.cpp
  lib/IDE/SwiftSourceDocInfo.cpp
  lib/Parse/ParseExpr.cpp
  lib/SILGen/SILGenExpr.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintSystem.cpp
  lib/Sema/PreCheckExpr.cpp
  lib/Sema/TypeCheckAvailability.cpp
  lib/Sema/TypeCheckCodeCompletion.cpp
  lib/Sema/TypeCheckExprObjC.cpp
  test/IDE/complete_swift_key_path.swift
Labels: r5.5

#38194 [5.5][Async Refactoring] Add `return` keyword if wrapping `ReturnStmt` is implicit
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/convert_function.swift
Labels: r5.5

#38221 [5.5][Sema] Properly handle generics in enum Codable synthesis
  lib/Sema/DerivedConformanceCodable.cpp
  test/decl/protocol/special/coding/enum_codable_nested_generics.swift
Labels: r5.5

#38208 GSB: Don't forget to concretize conformances when processing a same-type requirement [5.5]
  lib/AST/GenericSignatureBuilder.cpp
  test/Generics/rdar79570734.swift
Labels: r5.5

#38190 [5.5] Fix SILGen of access to isolated static properties
  lib/SILGen/LValue.h
  lib/SILGen/SILGenLValue.cpp
  test/Concurrency/Runtime/async_properties_actor.swift
  test/SILGen/hop_to_executor.swift
  test/SILGen/hop_to_executor_async_prop.swift
Labels: Concurrency, bug, r5.5

#38228 [5.5][CodeCompletion] Suggest typealias on protocols
  lib/Sema/IDETypeCheckingRequests.cpp
  test/IDE/complete_protocol_typealias.swift
  test/IDE/complete_unresolved_members.swift
Labels: r5.5

#38216 [5.5][Sema] Properly handle missing coding keys in enum Codable synthesis
  lib/Sema/DerivedConformanceCodable.cpp
  test/decl/protocol/special/coding/enum_codable_exclude_element.swift
Labels: r5.5

#38157 [5.5] Conform Never to Identifiable
  stdlib/public/core/Policy.swift
  test/api-digester/stability-stdlib-abi-without-asserts.test
Labels: r5.5

#38200 [5.5][ResultBuilders] Allow pre-check to look into single-statement closures
  lib/Sema/BuilderTransform.cpp
  test/Constraints/result_builder_diags.swift
Labels: r5.5

#38255 C++ Interop: NFC: add missing `requires cplusplus` to the modulemaps in tests
  test/Interop/Cxx/class/inline-function-codegen/Inputs/module.modulemap
  test/Interop/Cxx/namespace/Inputs/module.modulemap
Labels: C++ Interop

#38236 [5.5][ConstraintSystem] Bind missing member in pattern match to a hole early
  lib/Sema/CSSimplify.cpp
  test/Constraints/result_builder_diags.swift
Labels: r5.5

#38195 [5.5][stdlib] fix an accidental recursion bug involving Collection
  stdlib/public/core/Collection.swift
  validation-test/stdlib/CollectionDiagnostics.swift
Labels: r5.5

#38275 Implement differently logic to strip and copy the tvos libraries
  utils/build-script-impl
Labels: r5.5

#38256 [5.5][Async Refactoring] Wrap code in a continuation if conversion doesn't yield reasonable results
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/convert_function.swift
  test/refactoring/ConvertAsync/convert_to_continuation.swift
Labels: r5.5

#38268 [5.5][Async Refactoring] Get semantics providing expr to decide if call is to completion handler
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/convert_function.swift
  test/refactoring/ConvertAsync/convert_to_continuation.swift
Labels: r5.5

#38267 [5.5][Async Refactoring] Cosmetic Improvements to "Add Async Wrapper" Refactoring
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/convert_async_wrapper.swift
Labels: r5.5

#38300 [5.5][Sema] Fix two assertion failures/crashes in solver-based key-path completion
  include/swift/Sema/ConstraintSystem.h
  lib/Sema/CSApply.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/TypeCheckCodeCompletion.cpp
  test/IDE/complete_swift_key_path.swift
Labels: r5.5

#38297 [5.5][MiscDiagnostics] Downgrade plain type use error to a warning for certain positions
  lib/Sema/MiscDiagnostics.cpp
  test/Constraints/dynamic_lookup.swift
  test/Constraints/subscript.swift
Labels: r5.5

#38278 [5.5][Diagnostics] Ignore result type failures if one side is a hole
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/generics.swift
Labels: r5.5

#38288 [5.5] ModuleInterface: sanitize arch when interface file name and encoded flags disagree
  include/swift/Serialization/SerializedModuleLoader.h
  lib/Frontend/ModuleInterfaceLoader.cpp
  lib/Serialization/SerializedModuleLoader.cpp
  test/ModuleInterface/infer-arch-from-file.swift
  test/stdlib/Reflection_objc.swift
Labels: r5.5

#38340 Sema: Check conditional availability earlier in conformance checking [5.5]
  lib/Sema/TypeCheckProtocol.cpp
  test/Sema/availability_versions.swift
  test/Sema/conformance_availability_disambiguate.swift
Labels: r5.5

#38336 Update CHANGELOG.md with a couple of correctness fixes [5.5]
  CHANGELOG.md
Labels: r5.5

#38314 [5.5] quick downgrade of actor-init restrictions to warning
  include/swift/AST/DiagnosticsSIL.def
  test/Concurrency/actor_definite_init.swift
Labels: Concurrency, r5.5

#38269 [Distributed] Handle distributed func witnessess from distributed actor protocols
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsSema.def
  lib/AST/ASTDumper.cpp
  lib/AST/Decl.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  lib/Sema/TypeCheckProtocol.cpp
  stdlib/public/Distributed/DistributedActor.swift
  test/Distributed/distributed_actor_basic.swift
  test/Distributed/distributed_actor_initialization.swift
  test/Distributed/distributed_actor_isolation.swift
  test/Distributed/distributed_actor_nonisolated.swift
  test/Distributed/distributed_protocol_isolation.swift
Labels: distributed

#38347 [5.5][Diagnostics] Diagnose ambiguous solutions with warnings like regular ambiguities
  lib/Sema/ConstraintSystem.cpp
  test/stdlib/UnsafePointerDiagnostics_warning.swift
  validation-test/Sema/type_checker_crashers_fixed/sr14817.swift
Labels: r5.5

#38350 [5.5][CodeCompletion] Revert migration of key path completion to solver-based
  include/swift/AST/Expr.h
  include/swift/Sema/CodeCompletionTypeChecking.h
  include/swift/Sema/ConstraintSystem.h
  lib/AST/ASTDumper.cpp
  lib/AST/ASTWalker.cpp
  lib/AST/Expr.cpp
  lib/IDE/CodeCompletion.cpp
  lib/IDE/SourceEntityWalker.cpp
  lib/IDE/SwiftSourceDocInfo.cpp
  lib/Parse/ParseExpr.cpp
  lib/SILGen/SILGenExpr.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintSystem.cpp
  lib/Sema/PreCheckExpr.cpp
  lib/Sema/TypeCheckAvailability.cpp
  lib/Sema/TypeCheckCodeCompletion.cpp
  lib/Sema/TypeCheckExprObjC.cpp
  test/IDE/complete_swift_key_path.swift
Labels: r5.5

#38346 [5.5][CSGen] Don't apply one-way requirement to typed patterns
  lib/Sema/CSGen.cpp
  validation-test/Sema/type_checker_crashers_fixed/sr14893.swift
Labels: r5.5

#38344 [SE-0302] Implement '@unchecked Sendable' syntax.
  include/swift/AST/ASTContext.h
  include/swift/AST/ASTPrinter.h
  include/swift/AST/Attr.def
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/NameLookup.h
  include/swift/AST/ProtocolConformance.h
  include/swift/AST/TypeLoc.h
  include/swift/AST/TypeRepr.h
  include/swift/Parse/Parser.h
  lib/AST/ASTContext.cpp
  lib/AST/ASTDumper.cpp
  lib/AST/ASTPrinter.cpp
  lib/AST/ConformanceLookupTable.cpp
  lib/AST/ConformanceLookupTable.h
  lib/AST/Decl.cpp
  lib/AST/GenericSignatureBuilder.cpp
  lib/AST/NameLookup.cpp
  lib/AST/ProtocolConformance.cpp
  lib/AST/TypeRepr.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/Frontend/ModuleInterfaceSupport.cpp
  lib/IDE/Formatting.cpp
  lib/IDE/IDETypeChecking.cpp
  lib/IDE/Refactoring.cpp
  lib/IRGen/GenClass.cpp
  lib/Index/Index.cpp
  lib/Parse/ParseDecl.cpp
  lib/Parse/ParseGeneric.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/DerivedConformanceCodable.cpp
  lib/Sema/DerivedConformanceDifferentiable.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  lib/Sema/TypeCheckConcurrency.h
  lib/Sema/TypeCheckDeclPrimary.cpp
  lib/Sema/TypeCheckProtocol.cpp
  lib/Sema/TypeCheckRequestFunctions.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeCheckType.h
  lib/Serialization/Deserialization.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/Serialization.cpp
  test/Concurrency/concurrency_warnings.swift
  test/Concurrency/concurrent_value_checking.swift
  test/ModuleInterface/actor_isolation.swift
  test/ModuleInterface/features.swift
  test/decl/class/actor/basic.swift
  test/decl/protocol/special/Actor.swift
  tools/SourceKit/lib/SwiftLang/SwiftDocSupport.cpp
Labels: r5.5

#38355 [5.5][SILGen] Correct generic signature/substitutions of property wrapper generators within a closure.
  lib/SIL/IR/TypeLowering.cpp
  lib/SILGen/SILGenExpr.cpp
  test/SILGen/default_arguments_local.swift
  test/SILGen/property_wrapper_parameter.swift
Labels: r5.5

#38351 C++ Interop: tweak subscript operator tests
  test/Interop/Cxx/operators/Inputs/member-inline.h
  test/Interop/Cxx/operators/Inputs/member-out-of-line.h
Labels: C++ Interop

#33932 [SE-0290] Add #unavailable (Negative platform checks)
  include/swift/AST/DiagnosticsParse.def
  include/swift/AST/Stmt.h
  include/swift/Parse/Parser.h
  lib/AST/Stmt.cpp
  lib/Parse/ParseDecl.cpp
  lib/Parse/ParseExpr.cpp
  lib/Parse/ParseStmt.cpp
  lib/SILGen/SILGenDecl.cpp
  lib/Sema/BuilderTransform.cpp
  lib/Sema/DerivedConformanceRawRepresentable.cpp
  lib/Sema/TypeCheckAvailability.cpp
  test/Constraints/result_builder_availability.swift
  test/Parse/availability_query.swift
  test/Parse/availability_query_unavailability.swift
  test/SILGen/availability_query.swift
  test/Sema/availability_define.swift
  test/Sema/availability_define_parsing.swift
  test/attr/attr_availability_swift.swift
  test/attr/attr_availability_unavailability.swift
  utils/gyb_syntax_support/NodeSerializationCodes.py
  utils/gyb_syntax_support/StmtNodes.py
  utils/gyb_syntax_support/Token.py
Labels: swift-evolution-approved

#38377 SIL: Allow lowering Optional<T> against a nested type of an opaque result type [5.5]
  lib/SIL/IR/AbstractionPattern.cpp
  test/SILGen/Inputs/opaque_result_type_nested_optional_other.swift
  test/SILGen/opaque_result_type_nested_optional.swift
Labels: r5.5

#38388 [5.5] [TBDGen] Use default kind for AFPAST SILDeclRef.
  lib/IRGen/Linking.cpp
  test/TBD/rdar80485869.swift
Labels: r5.5

#38362 [Distributed] struct ActorAddress -> protocol ActorIdentity
  include/swift/AST/Decl.h
  include/swift/AST/KnownIdentifiers.def
  include/swift/AST/KnownSDKTypes.def
  include/swift/AST/TypeCheckRequests.h
  lib/AST/Decl.cpp
  lib/AST/TypeCheckRequests.cpp
  lib/SILGen/SILGenDestructor.cpp
  lib/Sema/CodeSynthesis.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/DerivedConformanceEquatableHashable.cpp
  stdlib/public/Concurrency/Actor.cpp
  stdlib/public/Concurrency/TaskGroup.cpp
  stdlib/public/Distributed/ActorTransport.swift
  stdlib/public/Distributed/DistributedActor.swift
  test/Distributed/Runtime/distributed_actor_deinit.swift
  test/Distributed/Runtime/distributed_actor_dynamic_remote_func.swift
  test/Distributed/Runtime/distributed_actor_init_local.swift
  test/Distributed/Runtime/distributed_actor_isRemote.swift
  test/Distributed/Runtime/distributed_actor_local.swift
  test/Distributed/Runtime/distributed_actor_remote_functions.swift
  test/Distributed/Runtime/distributed_no_transport_boom.swift
  test/Distributed/actor_protocols.swift
  test/Distributed/distributed_actor_func_implicitly_async_throws.swift
  test/Distributed/distributed_actor_initialization.swift
  test/Distributed/distributed_actor_isolation.swift
  test/Distributed/distributed_actor_nonisolated.swift
  test/Distributed/distributed_protocol_isolation.swift
  test/decl/protocol/special/DistributedActor.swift
Labels: distributed

#38405 [Distributed] fix minor typo in request name
  include/swift/AST/TypeCheckRequests.h
  lib/AST/TypeCheckRequests.cpp
  lib/Sema/CodeSynthesis.cpp
Labels: distributed

#38398 fix SILGen of access to isolated wrapper around instance actor property
  lib/SILGen/SILGenLValue.cpp
  test/SILGen/hop_to_executor_async_prop.swift
Labels: Concurrency, bug

#38215 Inject `hop_to_executor` after `self` is fully initialized in unrestricted actor inits
  lib/SILOptimizer/Mandatory/DIMemoryUseCollector.cpp
  lib/SILOptimizer/Mandatory/DIMemoryUseCollector.h
  lib/SILOptimizer/Mandatory/DefiniteInitialization.cpp
  stdlib/public/runtime/Exclusivity.cpp
  test/Concurrency/Runtime/actor_init.swift
  test/SILGen/async_initializer.swift
  test/SILOptimizer/definite_init_actor.swift
Labels: Concurrency, bug

#38451 [5.5][SourceKit/DocInfo] Add is_async for properties with async getters
  test/SourceKit/DocSupport/Inputs/async/async.h
  test/SourceKit/DocSupport/Inputs/async/module.modulemap
  test/SourceKit/DocSupport/doc_async.swift
  tools/SourceKit/lib/SwiftLang/SwiftDocSupport.cpp
Labels: r5.5

#38439 C++ Interop: improve skipping already imported struct members
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/namespace/Inputs/module.modulemap
  test/Interop/Cxx/namespace/Inputs/templates-with-forward-decl.h
  test/Interop/Cxx/namespace/templates-with-forward-decl-module-interface.swift
Labels: C++ Interop

#38445 [5.5][build] explicitly set OSX_ARCHITECTURES for targets in stdlib
  stdlib/cmake/modules/AddSwiftStdlib.cmake
Labels: r5.5

#38422 fix parsing of `isolated` as an argument label
  include/swift/Parse/Parser.h
  lib/Parse/ParsePattern.cpp
  test/Concurrency/isolated_parameters.swift
Labels: Concurrency, bug

#38418 [5.5][Syntax] Make `PostfixIfConfigExpr.base` optional
  test/Syntax/Outputs/round_trip_parse_gen.swift.withkinds
  test/Syntax/round_trip_parse_gen.swift
  utils/gyb_syntax_support/ExprNodes.py
Labels: r5.5

#38475 [5.5] [CodeCompletion] Use substGenericArgs in getTypeOfMember
  include/swift/AST/Types.h
  lib/AST/Type.cpp
  lib/IDE/CodeCompletion.cpp
  test/IDE/complete_crashes.swift
Labels: r5.5

#38425 🍒 [Concurrency] prevent races in task cancellation
  include/swift/ABI/TaskStatus.h
  stdlib/public/Concurrency/Task.cpp
  stdlib/public/Concurrency/TaskCancellation.swift
  test/Concurrency/Runtime/async_task_cancellation_early.swift
  test/Concurrency/Runtime/async_task_cancellation_while_running.swift
Labels: Concurrency, r5.5

#38480 [5.5][CSApply] Always map types out of context when setting interface types for wrapped closure parameters.
  lib/Sema/CSApply.cpp
  test/Sema/property_wrapper_parameter.swift
Labels: r5.5

#38483 AST: Make sure that an opaque type descriptor is weak-linked if its naming declaration is [5.5]
  lib/AST/Decl.cpp
  test/IRGen/Inputs/weak_availability_opaque_result_type_helper.swift
  test/IRGen/Inputs/weak_import_opaque_result_type_helper.swift
  test/IRGen/weak_availability_opaque_result_type.swift
  test/IRGen/weak_import_opaque_result_type.swift
Labels: r5.5

#38488 [5.5] fix parsing of `isolated` as an argument label
  include/swift/Parse/Parser.h
  lib/Parse/ParsePattern.cpp
  test/Concurrency/isolated_parameters.swift
Labels: bug, r5.5

#38490 [5.5] Inject `hop_to_executor` after `self` is fully initialized in unrestricted actor inits
  lib/SILOptimizer/Mandatory/DIMemoryUseCollector.cpp
  lib/SILOptimizer/Mandatory/DIMemoryUseCollector.h
  lib/SILOptimizer/Mandatory/DefiniteInitialization.cpp
  stdlib/public/runtime/Exclusivity.cpp
  test/Concurrency/Runtime/actor_init.swift
  test/SILGen/async_initializer.swift
  test/SILOptimizer/definite_init_actor.swift
Labels: Concurrency, bug, r5.5

#38452 [5.5][runtime] Improve detection of memory allocation failures
  include/swift/Basic/Malloc.h
  stdlib/public/core/UnsafeRawBufferPointer.swift.gyb
  stdlib/public/core/UnsafeRawPointer.swift
  test/stdlib/UnsafeRawPointer.swift
Labels: r5.5

#38495 SIL: Fix verifier failure when witness_method's lookup type involves dynamic Self [5.5]
  lib/SIL/Verifier/SILVerifier.cpp
  validation-test/compiler_crashers_2_fixed/rdar80296242.swift
Labels: r5.5

#38498 AST: Don't trigger source location deserialization in request evaluator [5.5]
  include/swift/AST/AnyFunctionRef.h
  lib/AST/Decl.cpp
Labels: r5.5

#38485 [5.5] Update the ScanDependencies test to use %target-cpu
  test/ScanDependencies/Inputs/Swift/XWithTarget.swiftmodule/arm64-apple-macos.swiftinterface
  test/ScanDependencies/Inputs/Swift/XWithTarget.swiftmodule/x86_64-apple-macos.swiftinterface
  test/ScanDependencies/clang-target.swift
Labels: r5.5

#38502 [Distributed] fix all distributed *runtime* tests; they are currently not running on CI
  stdlib/public/Distributed/DistributedActor.swift
  test/Distributed/Runtime/distributed_actor_deinit.swift
  test/Distributed/Runtime/distributed_actor_dynamic_remote_func.swift
  test/Distributed/Runtime/distributed_actor_init_local.swift
  test/Distributed/Runtime/distributed_actor_isRemote.swift
  test/Distributed/Runtime/distributed_actor_local.swift
  test/Distributed/Runtime/distributed_actor_remote_functions.swift
  test/Distributed/Runtime/distributed_no_transport_boom.swift
Labels: distributed, toolchain

#38517 [5.5] [IDE] Fix another GenericFunctionType subst crasher
  lib/IDE/ConformingMethodList.cpp
  test/IDE/conforming-methods-generic.swift
  test/IDE/conforming-methods-rdar77259607.swift
Labels: r5.5

#38522 🍒 [5.5][Concurrency,docs] Update task local docs to use latest structured co…
  stdlib/public/Concurrency/TaskLocal.swift
Labels: r5.5

#38532 [5.5] [Async Refactoring] Update to use Task's init
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/async_attribute_added.swift
  test/refactoring/ConvertAsync/basic.swift
  test/refactoring/ConvertAsync/labeled_closure_params.swift
Labels: r5.5

#38530 [Distributed] Prepare stubs for static func resolve
  include/swift/AST/DiagnosticsSema.def
  include/swift/Runtime/Concurrency.h
  include/swift/Runtime/RuntimeFunctions.def
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  stdlib/public/Concurrency/Actor.cpp
  stdlib/public/Distributed/ActorTransport.swift
  stdlib/public/Distributed/DistributedActor.swift
  test/Concurrency/actor_isolation.swift
  test/Distributed/distributed_actor_initialization.swift
  test/Distributed/distributed_actor_isolation.swift
  test/Distributed/distributed_actor_resolve.swift
Labels: distributed

#38537 [5.5] [SILGen] Precompute "returned" completion handler indices.
  lib/SILGen/SILGenThunk.cpp
  test/Interpreter/Inputs/rdar80847020.h
  test/Interpreter/Inputs/rdar80847020.m
  test/Interpreter/rdar80847020.swift
Labels: r5.5

#38555 [5.5] [CS] Don't bail out of CollectVarRefs early
  lib/Sema/CSGen.cpp
  validation-test/IDE/crashers_2_fixed/sr14709.swift
Labels: r5.5

#38546 [5.5] Turn off async test on ios and watchos
  test/Concurrency/Runtime/async.swift
Labels: r5.5

#38565 Ignore whether a parameter is "isolated" for the purposes of redeclaration
  lib/AST/Decl.cpp
  test/Concurrency/isolated_parameters.swift
Labels: r5.5

#38566 [5.5] ModuleInterface: skip printing the override keyword if the overriden decl is skipped
  lib/AST/Attr.cpp
  test/ModuleInterface/skip-override-spi.swift
Labels: r5.5, textual interface

#38572 Disable async availability checking for swift_deletedAsyncMethodError.
  lib/Sema/TypeCheckDeclPrimary.cpp
  test/Concurrency/concurrency_availability.swift
Labels: r5.5

#38552 SILGen: do not emit hop_to_executor in some objc thunks
  lib/SILGen/SILGenBridging.cpp
  test/Concurrency/actor_isolation_objc.swift
  test/SILGen/objc_async_from_swift.swift
Labels: Concurrency, bug

#38587 [5.5][Diagnostics] Reword malformed swiftsourceinfo diagnostic
  include/swift/AST/DiagnosticsSema.def
  test/Serialization/load-invalid-sourceinfo.swift
Labels: r5.5

#38575 Sema: Kick off ActorIsolationRequest after checking conformances to avoid cycles [5.5]
  lib/Sema/TypeCheckDeclPrimary.cpp
  lib/Sema/TypeCheckProtocol.cpp
  test/Concurrency/actor_isolation_cycle.swift
  test/ModuleInterface/actor_isolation.swift
  test/decl/protocol/req/recursion.swift
Labels: r5.5

#38597 [5.5] SILGen: do not emit hop_to_executor in some objc thunks
  lib/SILGen/SILGenBridging.cpp
  test/Concurrency/actor_isolation_objc.swift
  test/SILGen/objc_async_from_swift.swift
Labels: Concurrency, bug, r5.5

#37695 C++ Interop: import namespaces redecls as separate extensions
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImporterImpl.h
  lib/ClangImporter/SwiftLookupTable.h
  test/Interop/Cxx/namespace/Inputs/module.modulemap
  test/Interop/Cxx/namespace/Inputs/submodule-a.h
  test/Interop/Cxx/namespace/Inputs/submodule-b.h
  test/Interop/Cxx/namespace/classes-module-interface.swift
  test/Interop/Cxx/namespace/free-functions-module-interface.swift
  test/Interop/Cxx/namespace/free-functions-second-header-module-interface.swift
  test/Interop/Cxx/namespace/submodules-module-interface.swift
  test/Interop/Cxx/namespace/templates-module-interface.swift
  test/Interop/Cxx/namespace/templates-second-header-module-interface.swift
Labels: C++ Interop

#38610 [5.5] Eat -experimental-emit-module-separately
  include/swift/Option/Options.td
  test/Driver/emit_module_separately.swift
Labels: r5.5

#38655 Enable `async let` without the experimental flag
  include/swift/AST/Attr.def
  test/SourceKit/CodeComplete/complete_override.swift.response
Labels: r5.5

#38618 C++ Interop: import const methods as non-mutating
  include/swift/AST/ClangModuleLoader.h
  include/swift/ClangImporter/ClangImporter.h
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImportType.cpp
  lib/SIL/IR/SILFunctionType.cpp
  test/ClangImporter/cxx_interop_ir.swift
  test/Interop/Cxx/class/Inputs/module.modulemap
  test/Interop/Cxx/class/Inputs/mutable-members.h
  test/Interop/Cxx/class/mutable-members-module-interface.swift
  test/Interop/Cxx/class/mutable-members-typechecker.swift
  test/Interop/Cxx/class/mutable-members.swift
  test/Interop/Cxx/operators/member-inline-module-interface.swift
  test/Interop/Cxx/operators/member-inline-silgen.swift
  test/Interop/Cxx/operators/member-inline.swift
  test/Interop/Cxx/operators/member-out-of-line-silgen.swift
  test/Interop/Cxx/operators/member-out-of-line.swift
  test/Interop/Cxx/operators/non-member-inline-typechecker.swift
  test/Interop/Cxx/templates/canonical-types-module-interface.swift
  test/Interop/Cxx/templates/member-templates-module-interface.swift
  test/Interop/Cxx/templates/not-pre-defined-class-template-module-interface.swift
  test/Interop/Cxx/templates/partially-pre-defined-class-template-silgen.swift
  test/Interop/Cxx/templates/using-directive-module-interface.swift
Labels: C++ Interop

#38692 C++ Interop: fix `ClangImporter/cxx_interop_ir.swift` on 32-bit
  test/ClangImporter/cxx_interop_ir.swift
Labels: C++ Interop

#38701 [5.5][Serialization] Ignore conformance failures when allowing errors
  lib/Serialization/Deserialization.cpp
  test/Serialization/AllowErrors/removed-decls.swift
Labels: r5.5

#38708 Allow a global-actor-isolated class to inherit from a nonisolated one.
  lib/Sema/TypeCheckConcurrency.cpp
  test/Concurrency/actor_isolation.swift
  test/Concurrency/global_actor_inference.swift
Labels: r5.5
