Repository swiftlang/swift, pull requests merged in 2021-02, with the labels that each got.

#34995 [nfc] Add tests for witness table size optimizations.
  test/Interop/Cxx/value-witness-table/Inputs/module.modulemap
  test/Interop/Cxx/value-witness-table/Inputs/witness-layout-opts.h
  test/Interop/Cxx/value-witness-table/witness-layout-opts-irgen.swift
Labels: C++ Interop, CodeHealth

#35548 [cxx-interop] Correctly import static function templates.
  lib/Sema/CSApply.cpp
  test/Interop/Cxx/templates/Inputs/member-templates.h
  test/Interop/Cxx/templates/member-templates-module-interface.swift
  test/Interop/Cxx/templates/member-templates-silgen.swift
Labels: C++ Interop

#35728 Sema: Fix inherited designated init synthesis when there's a 'where' clause but no new generic parameters [5.4]
  lib/Sema/CodeSynthesis.cpp
  test/SILGen/designated_init_inheritance_with_where_clause.swift
Labels: r5.4

#32378 [cxx-interop] Use user defined copy constructor to copy C++ objects.
  lib/ClangImporter/ImportDecl.cpp
  lib/IRGen/GenDecl.cpp
  lib/IRGen/GenDecl.h
  lib/IRGen/GenStruct.cpp
  stdlib/public/SwiftShims/RefCount.h
  test/Interop/Cxx/class/Inputs/constructors.h
  test/Interop/Cxx/class/constructors-copy-irgen.swift
  test/Interop/Cxx/class/constructors-copy-module-interface.swift
  test/Interop/Cxx/class/constructors-irgen.swift
  test/Interop/Cxx/class/type-classification-loadable-silgen.swift
  test/Interop/Cxx/class/type-classification-module-interface.swift
  test/Interop/Cxx/class/type-classification-non-trivial-irgen.swift
  test/Interop/Cxx/value-witness-table/Inputs/copy-constructors.h
  test/Interop/Cxx/value-witness-table/Inputs/module.modulemap
  test/Interop/Cxx/value-witness-table/copy-constructors-execution.swift
  test/Interop/Cxx/value-witness-table/copy-constructors-irgen.swift
Labels: C++ Interop

#35729 Sema: Tweak assertion in CustomAttrTypeRequest to allow generic typealiases [5.4]
  lib/Sema/TypeCheckType.cpp
  test/decl/var/property_wrapper_generic_aliases.swift
  test/decl/var/property_wrapper_generic_aliases_invalid.swift
Labels: r5.4

#35746 [5.4][CodeCompletion][Sema] Don't filter out any viable solutions when solving for code completion
  include/swift/Sema/ConstraintSystem.h
  test/IDE/complete_ambiguous.swift
Labels: r5.4

#35735 [5.4][Property Wrappers] Correct StorageImplInfo for local property wrappers.
  lib/Sema/TypeCheckStorage.cpp
  test/SILGen/property_wrapper_local.swift
Labels: r5.4

#35762 Avoid false FileDependnecies among Implicitly-built Swift and Clang modules
  lib/Frontend/ModuleInterfaceLoader.cpp
  test/ModuleInterface/Inputs/implicit-options-inheritance/CIMod.h
  test/ModuleInterface/Inputs/implicit-options-inheritance/SIMod.swiftinterface
  test/ModuleInterface/Inputs/implicit-options-inheritance/module.modulemap
  test/ModuleInterface/Inputs/implicit-options-inheritance/test-dummy.modulemap
  test/ModuleInterface/no-implicit-extra-clang-opts.swift
Labels: r5.4

#35796 IRGen: Only emit PragmaCommentDecls if building for Windows, or LTO is enabled [5.4]
  lib/IRGen/GenClangDecl.cpp
Labels: r5.4

#35827 Fix a couple of crash-on-invalid situations with local variables defined inside result builders [5.4]
  lib/Sema/BuilderTransform.cpp
  test/Constraints/result_builder_invalid_vars.swift
Labels: r5.4

#35821 [5.4] FunctionSignatureOptimization: prevent owned->guaranteed specialization in case of a dealloc_partial_ref
  lib/SILOptimizer/Analysis/ARCAnalysis.cpp
  test/SILOptimizer/functionsigopts.sil
Labels: r5.4

#35870 AST: Fix bad interaction between vtable layout, access control and -enable-testing [5.4]
  include/swift/AST/Decl.h
  lib/AST/Decl.cpp
  lib/SILGen/SILGenType.cpp
  lib/Sema/TypeCheckDecl.cpp
  test/Interpreter/Inputs/vtables_multifile_testable_helper.swift
  test/Interpreter/vtables_multifile_testable.swift
  test/SILGen/Inputs/accessibility_vtables_testable_helper.swift
  test/SILGen/accessibility_vtables_testable.swift
Labels: r5.4

#35783 [Testing] Cherry-pick - Unbreak read-only source builds
  test/ModuleInterface/no-implicit-extra-clang-opts.swift
Labels: r5.4

#35890 Document a couple of miscellaneous 5.4 changes in CHANGELOG.md [5.4]
  CHANGELOG.md
Labels: r5.4

#35897 SILGen: Fix assertion failure when accessing a property with a __consuming getter [5.4]
  lib/SILGen/SILGenApply.cpp
  test/SILGen/value_ownership.swift
Labels: r5.4

#35910 GSB: Better handling of unresolved DependentMemberTypes in maybeResolveEquivalenceClass() [5.4]
  lib/AST/GenericSignatureBuilder.cpp
  validation-test/compiler_crashers_2_fixed/rdar56398071.swift
  validation-test/compiler_crashers_2_fixed/rdar71162777.swift
Labels: r5.4

#35085 [cxx-interop] Re-implement namespaces using enums + extensions.
  lib/ClangImporter/ImportDecl.cpp
  test/ClangImporter/cxx_interop_ir.swift
  test/Interop/Cxx/class/linked-records-module-interface.swift
  test/Interop/Cxx/namespace/Inputs/classes-second-header.h
  test/Interop/Cxx/namespace/Inputs/classes.h
  test/Interop/Cxx/namespace/Inputs/free-functions-second-header.h
  test/Interop/Cxx/namespace/Inputs/free-functions.h
  test/Interop/Cxx/namespace/Inputs/module.modulemap
  test/Interop/Cxx/namespace/Inputs/templates-second-header.h
  test/Interop/Cxx/namespace/Inputs/templates.h
  test/Interop/Cxx/namespace/classes-irgen.swift
  test/Interop/Cxx/namespace/classes-module-interface.swift
  test/Interop/Cxx/namespace/classes-second-header-module-interface.swift
  test/Interop/Cxx/namespace/classes-second-header.swift
  test/Interop/Cxx/namespace/classes.swift
  test/Interop/Cxx/namespace/free-functions-irgen.swift
  test/Interop/Cxx/namespace/free-functions-module-interface.swift
  test/Interop/Cxx/namespace/free-functions-second-header-module-interface.swift
  test/Interop/Cxx/namespace/free-functions-second-header.swift
  test/Interop/Cxx/namespace/free-functions.swift
  test/Interop/Cxx/namespace/templates-irgen.swift
  test/Interop/Cxx/namespace/templates-module-interface.swift
  test/Interop/Cxx/namespace/templates-second-header-module-interface.swift
  test/Interop/Cxx/namespace/templates-second-header.swift
  test/Interop/Cxx/namespace/templates.swift
  test/Interop/Cxx/templates/class-template-in-namespace-module-interface.swift
  test/Interop/Cxx/templates/function-template-module-interface.swift
  test/Interop/Cxx/templates/swift-class-instantiation-in-namespace-module-interface.swift
Labels: C++ Interop

#35941 [5.4] SILCombine: don't create a strong_retain/strong_release with an Optional<reference> as an operand
  lib/SILOptimizer/Analysis/SimplifyInstruction.cpp
  test/SILOptimizer/sil_combine.sil
Labels: r5.4

#35964 [cxx-interop] Skip already-imported sub decls.
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/class/Inputs/nested-records.h
  test/Interop/Cxx/class/nested-records-module-interface.swift
Labels: C++ Interop

#35956 GSB: An unresolved DependentMemberType might resolve to a concrete TypeAliasDecl with a dependent underlying type [5.4]
  lib/AST/GenericSignatureBuilder.cpp
  validation-test/compiler_crashers_2_fixed/sr11639.swift
Labels: r5.4

#35989 [nfc][gardening] Add requires cplusplus to LinkedRecords module.
  test/Interop/Cxx/class/Inputs/module.modulemap
Labels: C++ Interop

#35996 swift-api-extract to generate JSON API information
  include/swift/AST/DiagnosticsFrontend.def
  include/swift/AST/TBDGenRequests.h
  include/swift/AST/TBDGenTypeIDZone.def
  include/swift/Driver/Driver.h
  include/swift/Option/Options.h
  include/swift/Option/Options.td
  include/swift/TBDGen/TBDGen.h
  lib/Driver/Driver.cpp
  lib/TBDGen/APIGen.cpp
  lib/TBDGen/APIGen.h
  lib/TBDGen/CMakeLists.txt
  lib/TBDGen/TBDGen.cpp
  lib/TBDGen/TBDGenRequests.cpp
  lib/TBDGen/TBDGenVisitor.h
  test/APIJSON/access.swift
  test/APIJSON/apigen.swift
  test/APIJSON/non-objc-class.swift
  test/APIJSON/spi.swift
  test/APIJSON/struct.swift
  test/lit.cfg
  tools/driver/CMakeLists.txt
  tools/driver/driver.cpp
  tools/driver/swift_api_extract_main.cpp
Labels: r5.4

#35963 [cxx-interop] Bail on deep template specializations.
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/templates/Inputs/large-class-templates.h
  test/Interop/Cxx/templates/Inputs/module.modulemap
  test/Interop/Cxx/templates/large-class-templates-module-interface.swift
Labels: C++ Interop

#36030 stdlib: Float16 needs an @available annotation for macOS [5.4]
  stdlib/public/core/FloatingPointTypes.swift.gyb
  test/IRGen/float16_macos.swift
Labels: r5.4

#36040 SIL: Fix vtable layout with @usableFromInline methods [5.4]
  include/swift/SIL/SILVTableVisitor.h
  lib/AST/Decl.cpp
  test/SILGen/Inputs/accessibility_vtables_usableFromInline_helper.swift
  test/SILGen/accessibility_vtables_usableFromInline.swift
Labels: r5.4

#34864 [cxx-interop] Support forward declared records inside other records.
  test/Interop/Cxx/class/Inputs/nested-records.h
  test/Interop/Cxx/class/nested-records-module-interface.swift
Labels: C++ Interop

#34523 [SE-0299][TypeChecker] Allow static member references on protocol metatypes in generic contexts
  include/swift/AST/DiagnosticsSema.def
  include/swift/Sema/CSBindings.h
  include/swift/Sema/CSFix.h
  include/swift/Sema/Constraint.h
  include/swift/Sema/ConstraintSystem.h
  lib/Sema/CSApply.cpp
  lib/Sema/CSBindings.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/Constraint.cpp
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/static_members_on_protocol_in_generic_context.swift
  test/decl/enum/enumtest.swift
  test/expr/delayed-ident/member_chains.swift
  unittests/Sema/BindingInferenceTests.cpp
Labels: swift-evolution-pending-discussion

#35819 [cxx-interop] Fix class template instantiation.
  lib/ClangImporter/ImportDecl.cpp
  lib/IRGen/GenClangDecl.cpp
  lib/Sema/CSApply.cpp
  test/Interop/Cxx/templates/Inputs/class-template-instantiation-errors.h
  test/Interop/Cxx/templates/class-template-instantiation-typechecker-calls-method-with-error.swift
  test/Interop/Cxx/templates/class-template-instantiation-typechecker-constructor-calls-method-with-error.swift
  test/Interop/Cxx/templates/class-template-instantiation-typechecker.swift
  test/Interop/Cxx/templates/class-template-uninstantiatable-members-irgen.swift
  test/Interop/Cxx/templates/class-template-uninstantiatable-members.swift
Labels: C++ Interop
