Repository swiftlang/swift, pull requests merged in 2021-09, with the labels that each got.

#39095 SE-0309: Unlock existential types for all protocols
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/EducationalNotes.def
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/AST/Decl.cpp
  lib/AST/TypeCheckRequests.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/TypeCheckDecl.cpp
  lib/Sema/TypeCheckDeclPrimary.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeChecker.h
  lib/Serialization/Deserialization.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/Serialization.cpp
  test/Constraints/static_members_on_protocol_in_generic_context.swift
  test/Generics/function_defs.swift
  test/Sema/existential_nested_type.swift
  test/decl/nested/protocol.swift
  test/decl/nested/type_in_function.swift
  test/decl/protocol/conforms/inherited.swift
  test/decl/protocol/protocols.swift
  test/decl/protocol/protocols_with_self_or_assoc_reqs.swift
  test/decl/protocol/protocols_with_self_or_assoc_reqs_executable.swift
  test/decl/protocol/recursive_requirement.swift
  test/decl/protocol/req/dynamic_self.swift
  test/stmt/foreach.swift
  test/type/protocol_types.swift
  userdocs/diagnostics/associated-type-requirements.md
  userdocs/diagnostics/existential-member-access-limitations.md
Labels: swift-evolution-approved

#39140 [5.5] Do not build Swift interface files into binary modules when performing a `canImport` query.
  include/swift/Frontend/ModuleInterfaceLoader.h
  include/swift/Serialization/ModuleDependencyScanner.h
  include/swift/Serialization/SerializedModuleLoader.h
  lib/Frontend/ModuleInterfaceLoader.cpp
  lib/Serialization/ModuleDependencyScanner.cpp
  lib/Serialization/SerializedModuleLoader.cpp
  test/ScanDependencies/Inputs/Swift/Foo.swiftinterface
  test/ScanDependencies/can_import_no_build.swift
  unittests/FrontendTool/ModuleLoadingTests.cpp
Labels: r5.5

#39177 C++ Interop: import caret operators
  lib/ClangImporter/ImportName.cpp
  test/Interop/Cxx/operators/Inputs/non-member-inline.h
  test/Interop/Cxx/operators/non-member-inline-module-interface.swift
  test/Interop/Cxx/operators/non-member-inline-typechecker.swift
  test/Interop/Cxx/operators/non-member-inline.swift
Labels: C++ Interop

#39134 [cxx-interop] Lazily load the result of imported functions.
  include/swift/AST/ClangModuleLoader.h
  include/swift/ClangImporter/ClangImporter.h
  lib/AST/Decl.cpp
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImportType.cpp
  lib/Sema/TypeCheckDecl.cpp
Labels: C++ Interop

#39224 [5.5] [Aync Refactoring] Better handle comment trailing whitespace
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/basic.swift
  test/refactoring/ConvertAsync/convert_function.swift
  test/refactoring/ConvertAsync/convert_params_single.swift
  test/refactoring/ConvertAsync/convert_result.swift
Labels: r5.5

#39225 [5.5] [Async Refactoring] Better handle bool flag parameter bindings
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/convert_bool.swift
Labels: r5.5

#38624 Make derived hashValue/hash(into:) nonisolated.
  lib/Sema/DerivedConformanceEquatableHashable.cpp
  test/decl/protocol/conforms/actor_derived.swift
  test/decl/protocol/special/Actor.swift
Labels: r5.5

#39223 [5.5] Serialization: include global variables in the worklist-processing
  lib/Serialization/SerializeSIL.cpp
  test/SIL/Serialization/function-global-function.sil
  tools/sil-opt/SILOpt.cpp
Labels: r5.5

#39356 [cxx-interop][libswift] Use `std::string` instead of `BridgedStringRef` 🚀
  cmake/modules/AddSwift.cmake
  include/swift/SIL/SILBridging.h
  lib/SIL/Utils/SILBridging.cpp
  libswift/Sources/SIL/BasicBlock.swift
  libswift/Sources/SIL/Function.swift
  libswift/Sources/SIL/GlobalVariable.swift
  libswift/Sources/SIL/Instruction.swift
  libswift/Sources/SIL/Utils.swift
  libswift/Sources/SIL/Value.swift
Labels: C++ Interop

#39424 [test] Restrict test/Concurrency/voucher_propagation.swift
  test/Concurrency/voucher_propagation.swift
Labels: r5.5

#37995 [cxx-interop] Allow function templates with defaulted template type parameters to be called.
  lib/AST/ClangTypeConverter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/Sema/CSApply.cpp
  test/Interop/Cxx/templates/Inputs/defaulted-template-type-parameter.h
  test/Interop/Cxx/templates/Inputs/module.modulemap
  test/Interop/Cxx/templates/defaulted-template-type-parameter-module-interface.swift
  test/Interop/Cxx/templates/defaulted-template-type-parameter.swift
Labels: C++ Interop

#39433 [nfc][cxx-interop] Factor validation logic out into lower visitors.
  lib/ClangImporter/ImportDecl.cpp
Labels: C++ Interop

#39434 [nfc][cxx-interop] Remove dead code in `VisitClassTemplateDecl`.
  lib/ClangImporter/ImportDecl.cpp
Labels: C++ Interop

#39429 [nfc][cxx-interop] Add three utilities to the `ClangModuleLoader`.
  include/swift/AST/ClangModuleLoader.h
  include/swift/ClangImporter/ClangImporter.h
  lib/ClangImporter/ClangImporter.cpp
Labels: C++ Interop

#39428 [cxx-interop] Import reference types as `inout` not `UnsafePointer`.
  lib/ClangImporter/ImportType.cpp
  lib/SIL/IR/Bridging.cpp
  test/Interop/Cxx/reference/reference-irgen.swift
  test/Interop/Cxx/reference/reference-module-interface.swift
  test/Interop/Cxx/reference/reference-silgen.swift
  test/Interop/Cxx/reference/reference.swift
  test/Interop/Cxx/templates/defaulted-template-type-parameter-module-interface.swift
Labels: C++ Interop

#37806 ClangImporter: run Clang with a proper executable path (pt 2)
  include/swift/Basic/LangOptions.h
  lib/ClangImporter/ClangImporter.cpp
  lib/Driver/ToolChains.cpp
  lib/Frontend/CompilerInvocation.cpp
  stdlib/cmake/modules/SwiftSource.cmake
  test/Interop/Cxx/stdlib/Inputs/fake-toolchain/bin/clang
  test/Interop/Cxx/stdlib/Inputs/fake-toolchain/include/c++/v1/fake-toolchain.h
  test/Interop/Cxx/stdlib/Inputs/fake-toolchain/include/c++/v1/module.modulemap
  test/Interop/Cxx/stdlib/fake-toolchain-module-interface.swift
  test/ScanDependencies/module_deps.swift
  test/ScanDependencies/module_deps_cache_reuse.swift
  tools/swift-ide-test/swift-ide-test.cpp
Labels: C++ Interop

#39451 [5.5] Collect Fingerprints for Nested Decls
  lib/Serialization/Serialization.cpp
  test/Incremental/Fingerprints/Inputs/nested-enum-fingerprint/definesAB-after.swift
  test/Incremental/Fingerprints/Inputs/nested-enum-fingerprint/definesAB-before.swift
  test/Incremental/Fingerprints/Inputs/nested-enum-fingerprint/main.swift
  test/Incremental/Fingerprints/Inputs/nested-enum-fingerprint/ofm.json
  test/Incremental/Fingerprints/Inputs/nested-enum-fingerprint/usesA.swift
  test/Incremental/Fingerprints/Inputs/nested-enum-fingerprint/usesB.swift
  test/Incremental/Fingerprints/nested-enum-fingerprint.swift
Labels: r5.5

#39432 [cxx-interop] A few misc. changes from #38675.
  lib/AST/ASTMangler.cpp
  lib/AST/ASTPrinter.cpp
  lib/ClangImporter/ImportName.cpp
Labels: C++ Interop

#39426 [5.5][Dependency Scanning] Include initial PCM arguments on Clang module dependency details
  include/swift-c/DependencyScan/DependencyScan.h
  include/swift/AST/ModuleDependencies.h
  include/swift/DependencyScan/DependencyScanImpl.h
  include/swift/DependencyScan/SerializedModuleDependencyCacheFormat.h
  lib/ClangImporter/ClangModuleDependencyScanner.cpp
  lib/DependencyScan/ModuleDependencyCacheSerialization.cpp
  lib/DependencyScan/ScanDependencies.cpp
  test/ScanDependencies/module_deps.swift
  tools/libSwiftScan/libSwiftScan.cpp
  tools/libSwiftScan/libSwiftScan.exports
Labels: r5.5

#39513 [5.5][concurrency] Fix infinite recursion in determining the mangling kind for a backdeployed feature.
  lib/IRGen/GenReflection.cpp
  lib/IRGen/IRGenMangler.h
  lib/IRGen/MetadataRequest.cpp
  test/Interpreter/opaque_return_type_protocol_ext.swift
Labels: r5.5

#39435 [cxx-interop][nfc] Add a ClangImporter request zone.
  include/swift/Basic/Statistics.def
  include/swift/Basic/TypeIDZones.def
  include/swift/ClangImporter/ClangImporterRequests.h
  include/swift/ClangImporter/ClangImporterTypeIDZone.def
  include/swift/Subsystems.h
  lib/AST/NameLookupRequests.cpp
  lib/ClangImporter/CMakeLists.txt
  lib/ClangImporter/ClangImporterRequests.cpp
  lib/Frontend/Frontend.cpp
  lib/IDE/CompletionInstance.cpp
  tools/swift-ide-test/swift-ide-test.cpp
  unittests/AST/TestContext.cpp
  unittests/Sema/SemaFixture.cpp
Labels: C++ Interop
