Repository swiftlang/swift, pull requests merged in 2021-08, with the labels that each got.

#38730 Lower the async task slab allocation to 1000 bytes.
  stdlib/public/Concurrency/TaskPrivate.h
Labels: r5.5

#38768 Emit `hop_to_executor` instructors for foreign `async` calls.
  lib/SILGen/SILGenApply.cpp
  test/SILGen/objc_async.swift
Labels: r5.5

#38790 [5.5][ConstraintSystem] Relax the left-over information check in ComponentStep
  include/swift/Sema/ConstraintSystem.h
  lib/Sema/CSSolver.cpp
  lib/Sema/CSStep.cpp
  lib/Sema/ConstraintGraph.cpp
  lib/Sema/ConstraintSystem.cpp
Labels: r5.5

#38820 [NFC] remove test use of `cmp` to compare swiftmodules
  test/Serialization/async_initializers.swift
  test/Serialization/attr-nonisolated.swift
  test/Serialization/effectful_properties.swift
Labels: CodeHealth

#38633 [5.5] [SILGen] Used formal type when bridging completion handler arguments.
  include/swift/SIL/AbstractionPattern.h
  lib/SIL/IR/AbstractionPattern.cpp
  lib/SIL/IR/SILFunctionType.cpp
  lib/SIL/IR/SILInstructions.cpp
  lib/SILGen/Callee.h
  lib/SILGen/ResultPlan.cpp
  lib/SILGen/ResultPlan.h
  lib/SILGen/SILGen.h
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenBridging.cpp
  lib/SILGen/SILGenThunk.cpp
  test/Inputs/clang-importer-sdk/usr/include/ObjCConcurrency.h
  test/SILGen/objc_async.swift
  validation-test/compiler_crashers_2_fixed/rdar79383990.swift
Labels: r5.5

#38804 [5.5] [AST] Treat actors inheriting from NSObject as SwiftNativeNSObjects.
  lib/AST/Decl.cpp
  test/SILGen/objc_actor.swift
Labels: r5.5

#38772 Make `ThrowingTaskGroup.nextResult()` non-throwing.
  stdlib/public/Concurrency/TaskGroup.swift
  test/Concurrency/Runtime/async_taskgroup_throw_recover.swift
Labels: r5.5

#38811 [5.5] [AST] Treat actors inheriting from NSObject as SwiftNativeNSObjects.
  lib/AST/Decl.cpp
  test/SILGen/objc_actor.swift
Labels: r5.5

#38833 [5.5] Fix serialization crashes found from stress tester
  lib/Serialization/Serialization.cpp
  test/Serialization/AllowErrors/invalid-deinit.swift
  validation-test/Serialization/AllowErrors/invalid-deinit.swift
  validation-test/Serialization/AllowErrors/invalid-pattern.swift
Labels: r5.5

#38834 [5.5][SourceKit] Suppress oslog_invalid_log_message diagnostic in live issues
  test/SourceKit/Sema/oslog.swift
  tools/SourceKit/lib/SwiftLang/SwiftEditor.cpp
Labels: r5.5

#38843 [5.5] [CS] Better handle null in BuilderClosureRewriter
  lib/Sema/BuilderTransform.cpp
  test/Constraints/result_builder_invalid_stmts.swift
Labels: r5.5

#38870 [Distributed] deinit aware of remote "properties" (lack thereof in storage)
  lib/SILGen/SILGenDestructor.cpp
  lib/SILGen/SILGenDistributed.cpp
  test/Distributed/Runtime/distributed_actor_remote_fieldsDontCrashDeinit.swift
  test/SIL/Distributed/distributed_actor_default_deinit_sil.swift
  test/SIL/Distributed/distributed_actor_remote_deinit_sil.swift
Labels: distributed

#38879 [5.5] ABI checker: require explicit @available attributes for new APIs
  lib/APIDigester/ModuleAnalyzerNodes.cpp
  stdlib/public/core/Policy.swift
  test/api-digester/Outputs/Cake-abi.txt
  test/api-digester/Outputs/cake-abi.json
  test/api-digester/Outputs/cake.json
Labels: r5.5

#38877 [5.5] ModuleInterface: avoid omitting platform names when printing @available
  lib/AST/Attr.cpp
  test/ModuleInterface/available-attr-no-collapse.swift
Labels: r5.5

#38865 [5.5][Refactoring] Fix invalid legacy body for Result<Void, ...> handler
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/basic.swift
  test/refactoring/ConvertAsync/convert_function.swift
Labels: r5.5

#38861 [5.5] [SILGen] Handle foreign funcs with error and async conventions.
  lib/SIL/IR/SILFunctionType.cpp
  lib/SILGen/ResultPlan.cpp
  lib/SILGen/ResultPlan.h
  lib/SILGen/SILGen.h
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenForeignError.cpp
  lib/SILGen/SILGenFunction.h
  lib/SILGen/SILGenThunk.cpp
  test/SILGen/objc_async.swift
  validation-test/compiler_crashers_2_fixed/Inputs/rdar80704984.h
  validation-test/compiler_crashers_2_fixed/Inputs/rdar80704984.m
  validation-test/compiler_crashers_2_fixed/Inputs/rdar80704984_2.h
  validation-test/compiler_crashers_2_fixed/Inputs/rdar80704984_2.m
  validation-test/compiler_crashers_2_fixed/rdar80704984.swift
  validation-test/compiler_crashers_2_fixed/rdar80704984_2.swift
Labels: r5.5

#38862 [5.5] [SILGen] Handled transforming Bridged? -> Swift.
  lib/SILGen/SILGenBridging.cpp
  test/Inputs/clang-importer-sdk/usr/include/ObjCConcurrency.h
  test/SILGen/objc_async.swift
  validation-test/compiler_crashers_2_fixed/Inputs/rdar80704382.h
  validation-test/compiler_crashers_2_fixed/Inputs/rdar80704382.m
  validation-test/compiler_crashers_2_fixed/Inputs/rdar81590807.h
  validation-test/compiler_crashers_2_fixed/Inputs/rdar81590807.m
  validation-test/compiler_crashers_2_fixed/Inputs/rdar81590807_2.h
  validation-test/compiler_crashers_2_fixed/Inputs/rdar81590807_2.m
  validation-test/compiler_crashers_2_fixed/rdar80704382.swift
  validation-test/compiler_crashers_2_fixed/rdar81590807.swift
  validation-test/compiler_crashers_2_fixed/rdar81590807_2.swift
Labels: r5.5

#38949 [5.5][PrintAsObjC] Do not output invalid decls when allowing errors
  lib/PrintAsObjC/DeclAndTypePrinter.cpp
  test/PrintAsObjC/error.swift
Labels: r5.5

#38938 [Distributed] Generate SIL for DistributedActor.resolve
  lib/IRGen/GenBuiltin.cpp
  lib/IRGen/GenDistributed.cpp
  lib/IRGen/GenDistributed.h
  lib/SILGen/SILGenDistributed.cpp
  lib/SILGen/SILGenFunction.cpp
  stdlib/public/Distributed/ActorTransport.swift
  test/Distributed/Runtime/distributed_actor_deinit.swift
  test/Distributed/Runtime/distributed_actor_dynamic_remote_func.swift
  test/Distributed/Runtime/distributed_actor_init_local.swift
  test/Distributed/Runtime/distributed_actor_isRemote.swift
  test/Distributed/Runtime/distributed_actor_local.swift
  test/Distributed/Runtime/distributed_actor_remote_fieldsDontCrashDeinit.swift
  test/Distributed/Runtime/distributed_actor_remote_functions.swift
  test/Distributed/Runtime/distributed_actor_remote_retains_transport.swift
  test/Distributed/Runtime/distributed_no_transport_boom.swift
Labels: distributed

#36740 Placeholder types: take two
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/Expr.h
  include/swift/Sema/CSFix.h
  lib/AST/Expr.cpp
  lib/AST/TypeCheckRequests.cpp
  lib/Parse/ParsePattern.cpp
  lib/Parse/ParseType.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CSBindings.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/PreCheckExpr.cpp
  lib/Sema/TypeCheckConstraints.cpp
  lib/Sema/TypeCheckDecl.cpp
  lib/Sema/TypeCheckPattern.cpp
  lib/Sema/TypeCheckStorage.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeCheckType.h
  lib/Sema/TypeChecker.cpp
  lib/Sema/TypeChecker.h
  test/AutoDiff/Sema/differentiable_attr_type_checking.swift
  test/AutoDiff/Sema/differentiable_func_type.swift
  test/Constraints/diagnostics.swift
  test/Sema/placeholder_type.swift
  test/attr/attr_objc.swift
  test/expr/expressions.swift
  test/type/opaque.swift
  validation-test/Sema/SwiftUI/sr14213.swift
Labels: swift-evolution-approved

#38974 [Distributed] Ensure _remote funcs synthesized before dynamic replacement
  include/swift/AST/Decl.h
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/AST/Decl.cpp
  lib/AST/TypeCheckRequests.cpp
  lib/SILGen/SILGenDistributed.cpp
  lib/Sema/CodeSynthesis.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckDecl.cpp
  lib/Sema/TypeCheckDeclPrimary.cpp
  lib/Sema/TypeCheckDistributed.cpp
  lib/Sema/TypeCheckDistributed.h
  lib/Sema/TypeChecker.h
  test/Distributed/Inputs/dynamic_replacement_da_decl.swift
  test/Distributed/Inputs/dynamic_replacement_da_extension.swift
  test/Distributed/distributed_actor_dynamic_replacement.swift
  test/Distributed/distributed_actor_isolation.swift
Labels: Distributed

#39011 Revert "Revert "[Distributed] Generate SIL for DistributedActor.resolve""
  lib/IRGen/GenBuiltin.cpp
  lib/IRGen/GenDistributed.cpp
  lib/IRGen/GenDistributed.h
  lib/SILGen/SILGenDistributed.cpp
  lib/SILGen/SILGenFunction.cpp
  stdlib/public/Distributed/ActorTransport.swift
  test/Distributed/Runtime/distributed_actor_deinit.swift
  test/Distributed/Runtime/distributed_actor_dynamic_remote_func.swift
  test/Distributed/Runtime/distributed_actor_init_local.swift
  test/Distributed/Runtime/distributed_actor_isRemote.swift
  test/Distributed/Runtime/distributed_actor_local.swift
  test/Distributed/Runtime/distributed_actor_remote_fieldsDontCrashDeinit.swift
  test/Distributed/Runtime/distributed_actor_remote_functions.swift
  test/Distributed/Runtime/distributed_actor_remote_retains_transport.swift
  test/Distributed/Runtime/distributed_no_transport_boom.swift
Labels: Distributed

#38998 [Distributed] decode init for DistributedActor
  lib/AST/ASTContext.cpp
  stdlib/public/Distributed/ActorTransport.swift
  stdlib/public/Distributed/DistributedActor.swift
  test/Distributed/Runtime/distributed_actor_decode.swift
Labels: Distributed

#39019 [Distributed] fix AnyActorIdentity equality impl
  stdlib/public/Distributed/DistributedActor.swift
  test/Distributed/Runtime/distributed_actor_identity.swift
Labels: Distributed

#38953 [5.5] DiagnoseInfiniteRecursion: fix a false warning caused by dead-end blocks
  lib/SILOptimizer/Mandatory/DiagnoseInfiniteRecursion.cpp
  test/SILOptimizer/infinite_recursion.swift
Labels: r5.5

#38982 [5.5][Refactoring] Do not add "async" if function is already async
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/convert_function.swift
Labels: r5.5

#39013 [5.5][Refactoring] Do not try to unique '_'
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/convert_function.swift
Labels: r5.5

#38983 [5.5][Refactorings] Add cursor refactorings for the start of the range
  lib/IDE/Refactoring.cpp
  test/SourceKit/Refactoring/basic.swift
  test/SourceKit/Refactoring/rename-objc.swift
  tools/SourceKit/lib/SwiftLang/SwiftSourceDocInfo.cpp
  tools/swift-refactor/swift-refactor.cpp
Labels: r5.5

#39058 [5.5] ClosureSpecializer: avoid an infinite optimization loop.
  lib/SILOptimizer/IPO/ClosureSpecializer.cpp
  test/SILOptimizer/closure_specialize_loop.swift
Labels: r5.5

#39018 [5.5] Fix two cross-module-optimization bugs
  include/swift/AST/Module.h
  lib/AST/Module.cpp
  lib/SILOptimizer/IPO/CrossModuleSerializationSetup.cpp
  lib/Serialization/DeserializeSIL.cpp
  test/SILOptimizer/Inputs/cross-module/c-module.c
  test/SILOptimizer/Inputs/cross-module/c-module.h
  test/SILOptimizer/Inputs/cross-module/cross-module-objc.swift
  test/SILOptimizer/Inputs/cross-module/cross-module.swift
  test/SILOptimizer/Inputs/cross-module/cross-private-submodule.swift
  test/SILOptimizer/Inputs/cross-module/cross-submodule.swift
  test/SILOptimizer/Inputs/cross-module/module.modulemap
  test/SILOptimizer/cross-module-optimization-objc.swift
  test/SILOptimizer/cross-module-optimization.swift
Labels: r5.5

#39113 Mark test as unsupported on windows to unblock CI
  test/Distributed/Runtime/distributed_actor_deinit.swift
Labels: Distributed
