Repository swiftlang/swift, pull requests merged in 2021-06, with the labels that each got.

#37715 [5.5] [Async Refactoring] Fix crash on recursive AST walk
  include/swift/IDE/SourceEntityWalker.h
  test/refactoring/ConvertAsync/convert_function.swift
Labels: r5.5

#37690 Separate CMake option for "build concurrency lib" and "import concurrency lib"
  CMakeLists.txt
  include/swift/Basic/LangOptions.h
  include/swift/Config.h.in
  utils/build-presets.ini
Labels: r5.5

#37724 [5.5-05142021] [Async Refactoring] Fix crash on recursive AST walk
  include/swift/IDE/SourceEntityWalker.h
  test/refactoring/ConvertAsync/convert_function.swift
Labels: r5.5

#37729 [5.5] IRGen: Add the `swiftasync` attribute to the resume function call for await_async_continuation
  lib/IRGen/GenCall.cpp
  test/IRGen/async/get_async_continuation.sil
Labels: r5.5

#37744 [5.5][CSBindings] Don't record variable adjacency for `member chain base` constraint
  lib/Sema/CSBindings.cpp
  test/Constraints/static_members_on_protocol_in_generic_context.swift
Labels: r5.5

#37672 [5.5][CSBindings] Account for literal bindings when checking "subtype of existential" property
  include/swift/Sema/CSBindings.h
  test/Constraints/protocols.swift
Labels: r5.5

#37717 [5.5][Refactoring] Don't crash when converting a function to async that contains a call to init
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/basic.swift
Labels: r5.5

#37750 [5.5] Fix asserts and crashes caused by skipping function bodies or allowing errors
  lib/Parse/ParseDecl.cpp
  lib/Serialization/Deserialization.cpp
  lib/Serialization/Serialization.cpp
  validation-test/Parse/delayed-members-open-if.swift
  validation-test/Parse/delayed-members-open-prop-scope.swift
  validation-test/Serialization/AllowErrors/invalid-attr-refs.swift
  validation-test/Serialization/AllowErrors/invalid-attr.swift
  validation-test/Serialization/AllowErrors/invalid-deinit.swift
  validation-test/Serialization/AllowErrors/invalid-witness.swift
  validation-test/Serialization/AllowErrors/unresolved-type.swift
Labels: r5.5

#37767 [5.5][ConstraintSystem] Simplify relational constraints with the same depe…
  lib/Sema/CSSimplify.cpp
  test/Constraints/generics.swift
Labels: r5.5

#37757 [5.5][CodeComplete] Fall back to typechecking a single expression result builder doesn't typecheck
  lib/Sema/TypeCheckStmt.cpp
  test/IDE/complete_in_result_builder.swift
Labels: r5.5

#37796 [5.5] Add all deserialization fatal output to the pretty stack trace
  include/swift/AST/DiagnosticsSema.def
  lib/FrontendTool/FrontendTool.cpp
  lib/Serialization/Deserialization.cpp
  lib/Serialization/DeserializationErrors.h
  lib/Serialization/ModuleFile.h
  lib/Serialization/ModuleFileSharedCore.cpp
  lib/Serialization/ModuleFileSharedCore.h
  test/Frontend/crash-in-user-code.swift
  test/Frontend/crash.swift
  test/Serialization/AllowErrors/crash-adds-message.swift
  test/Serialization/Recovery/crash-recovery.swift
  test/Serialization/Recovery/crash-xref.swift
Labels: r5.5

#37791 [5.5][CSBindings] Fix inference of partial key path from conversion constraints
  include/swift/Sema/ConstraintLocator.h
  include/swift/Sema/ConstraintLocatorPathElts.def
  include/swift/Sema/ConstraintSystem.h
  lib/Sema/CSBindings.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/ConstraintLocator.cpp
  lib/Sema/TypeCheckConstraints.cpp
  test/expr/unary/keypath/keypath.swift
Labels: r5.5

#37790 [5.5][ConstraintSystem] Don't record a mismatch for synthesized arguments
  lib/Sema/CSSimplify.cpp
  test/Constraints/generics.swift
Labels: r5.5

#37813 AST: Use availability to disambiguate multiple overlapping conformances [5.5]
  include/swift/AST/DeclContext.h
  lib/AST/ConformanceLookupTable.cpp
  lib/AST/DeclContext.cpp
  lib/AST/Module.cpp
  test/Sema/Inputs/conformance_availability_overlapping_other.swift
  test/Sema/conformance_availability_overlapping.swift
Labels: r5.5

#37801 Fix some performance regressions [5.5]
  include/swift/AST/TypeCheckRequests.h
  lib/AST/Decl.cpp
  lib/AST/DeclContext.cpp
  lib/AST/TypeCheckRequests.cpp
Labels: r5.5

#37819 [5.5] Pass .tbd inputs down to the linker invocation.
  lib/Driver/DarwinToolChains.cpp
  test/Driver/linker-tbd.swift
Labels: r5.5

#37842 [5.5] Add a Subtraction Optimization
  lib/Sema/TypeCheckSwitchStmt.cpp
  test/Sema/exhaustive_switch_huge.swift.gyb
Labels: r5.5

#37848 [5.5] [Async Refactoring] Better handle non-refutable patterns
  include/swift/AST/DiagnosticsRefactoring.def
  include/swift/AST/Pattern.h
  include/swift/IDE/SourceEntityWalker.h
  lib/AST/Pattern.cpp
  lib/IDE/Refactoring.cpp
  lib/IDE/SourceEntityWalker.cpp
  test/refactoring/ConvertAsync/convert_params_single.swift
  test/refactoring/ConvertAsync/convert_pattern.swift
Labels: r5.5

#37880 Fix actor init diagnostic
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckDeclPrimary.cpp
  test/Distributed/distributed_actor_is_experimental.swift
  test/Distributed/distributed_missing_import.swift
  test/decl/var/default_init.swift
Labels: Concurrency

#37868 Sema: Allow omitting generic parameters when accessing member type with a fully-constrained 'where' clause [5.5]
  lib/Sema/TypeCheckNameLookup.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeChecker.h
  test/Generics/unbound.swift
  test/decl/typealias/fully_constrained.swift
Labels: r5.5

#37869 Sema: Allow omitting generic parameters when accessing member type with a fully-constrained 'where' clause [5.5-05/14/2021]
  lib/Sema/TypeCheckNameLookup.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeChecker.h
  test/Generics/unbound.swift
  test/decl/typealias/fully_constrained.swift
Labels: r5.5

#37886 Add missing distributed requirement to test
  test/Distributed/distributed_actor_is_experimental.swift
Labels: Concurrency

#37873 [5.5] [AST] Do not return invalid SourceLocs from Decl::getLoc
  lib/AST/Decl.cpp
  test/diagnostics/multi-module-diagnostics.swift
Labels: r5.5

#37894 [5.5] [Async Refactoring] Add @discardableResult for defaulted completion
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/convert_function.swift
Labels: r5.5

#37833 [5.5] SILGen: fix a crash when assigning a wrapped property in a convenience initializer
  lib/SILGen/SILGenLValue.cpp
  test/SILOptimizer/di_property_wrappers.swift
Labels: r5.5

#37902 [5.5] Fix actor init diagnostic
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckDeclPrimary.cpp
  test/decl/var/default_init.swift
Labels: r5.5

#37870 Sema: Downgrade potentially unavailable enum cases to a warning in module interfaces [5.5]
  include/swift/AST/DiagnosticsSema.def
  include/swift/Basic/LangOptions.h
  include/swift/Option/FrontendOptions.td
  lib/Driver/ToolChains.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/Sema/TypeCheckAttr.cpp
  test/Sema/Inputs/availability_enum_case_other.swift
  test/Sema/availability_enum_case.swift
Labels: r5.5

#37860 [5.4][IRGen] Disable pre-specialization for 32-bit ARM on Linux
  lib/IRGen/IRGenModule.cpp
Labels: r5.4

#37930 [SE-0316] Introduce the GlobalActor protocol to describe global actors.
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/KnownIdentifiers.def
  include/swift/AST/KnownProtocols.def
  lib/AST/ASTContext.cpp
  lib/AST/ProtocolConformance.cpp
  lib/IRGen/GenMeta.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  stdlib/public/Concurrency/Actor.swift
  stdlib/public/Concurrency/CMakeLists.txt
  stdlib/public/Concurrency/GlobalActor.swift
  stdlib/public/Concurrency/MainActor.swift
  test/attr/global_actor.swift
Labels: r5.5

#37909 [5.5] Special-case Pattern Binding Decls Created by LLDB
  include/swift/AST/ASTScope.h
  include/swift/AST/Decl.h
  lib/AST/ASTScopeCreation.cpp
  lib/AST/ASTScopeSourceRange.cpp
  lib/AST/Decl.cpp
Labels: r5.5

#37925 [5.5][Diagnostics] Make sure extension type repr is available before using it
  lib/Sema/CSDiagnostics.cpp
Labels: r5.5

#37924 [5.5][CSBindings] Overload variable shouldn't be delayed by its application
  lib/Sema/CSBindings.cpp
  test/Constraints/closures.swift
Labels: r5.5

#37881 [5.5] [Async Refactoring] Better handle known condition paths
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/convert_params_multi.swift
  test/refactoring/ConvertAsync/convert_pattern.swift
  test/refactoring/ConvertAsync/path_classification.swift
Labels: r5.5

#37918 [5.5][Refactoring] Support refactoring for `case let` patterns
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/convert_pattern.swift
Labels: r5.5

#37975 [Clang importer] Import Swift declaration modifiers from swift_attr.
  include/swift/AST/DiagnosticsClangImporter.def
  include/swift/Parse/Parser.h
  lib/ClangImporter/ImportDecl.cpp
  lib/Parse/ParseDecl.cpp
  test/ClangImporter/objc_async.swift
  test/IDE/print_clang_objc_async.swift
  test/Inputs/clang-importer-sdk/usr/include/ObjCConcurrency.h
Labels: r5.5

#37951 [5.5] fix weak reference lifetime warnings and disable by default
  lib/SILOptimizer/Mandatory/DiagnoseLifetimeIssues.cpp
  lib/SILOptimizer/PassManager/PassPipeline.cpp
  test/SILOptimizer/definite_init_diagnostics.swift
  test/SILOptimizer/diagnose_lifetime_issues.sil
  test/SILOptimizer/diagnose_lifetime_issues.swift
  test/SILOptimizer/diagnose_lifetime_issues_objc.swift
Labels: r5.5

#38030 [next branch] Update ClangModule API use
  lib/ClangImporter/ClangModuleDependencyScanner.cpp
Labels: clang importer

#38031 [5.5][CSSimplify] Fix warning check to account that "from" might be less optional than "to" type
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSSimplify.cpp
  validation-test/Sema/type_checker_crashers_fixed/rdar79523605.swift
Labels: r5.5

#37982 [5.5][SILGen] Fix a crash when a wrapped property initial value has a re-abstractable type.
  lib/SILGen/SILGenConstructor.cpp
  test/SILGen/property_wrappers.swift
Labels: r5.5

#38035 [5.5] Short-circuit `GlobalActorAttributeRequest` attempting to get the Source Location of a serialized decl.
  lib/Sema/TypeCheckConcurrency.cpp
  test/Serialization/Inputs/actor_bar.swift
  test/Serialization/actor-attr-query-cycle.swift
Labels: r5.5

#38048 Change the feature name for BuiltinTaskGroup.
  include/swift/Basic/Features.def
  lib/AST/ASTPrinter.cpp
  stdlib/public/Concurrency/TaskGroup.swift
Labels: r5.5

#37987 [Parser] Allow closures with custom attributes and capture lists.
  include/swift/Parse/Parser.h
  lib/Parse/ParseDecl.cpp
  lib/Parse/ParsePattern.cpp
  lib/Parse/ParseType.cpp
  lib/SIL/Parser/ParseSIL.cpp
  test/Concurrency/global_actor_function_types.swift
  test/Syntax/Outputs/round_trip_invalid.swift.withkinds
Labels: r5.5

#37075 Restrict uses of 'self' in actor initializers
  include/swift/AST/DiagnosticsSIL.def
  lib/SILOptimizer/Mandatory/DIMemoryUseCollector.cpp
  lib/SILOptimizer/Mandatory/DIMemoryUseCollector.h
  lib/SILOptimizer/Mandatory/DefiniteInitialization.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  test/Concurrency/Runtime/actor_keypaths.swift
  test/Concurrency/actor_definite_init.swift
  test/Concurrency/actor_isolation.swift
Labels: Concurrency, bug

#38009 Local functions can capture "self" as isolated.
  lib/Sema/TypeCheckConcurrency.cpp
  test/Concurrency/actor_isolation.swift
Labels: r5.5

#38037 [5.5][Sema] Use decodeIfPresent for optional enum params in Codable synthesis
  lib/Sema/DerivedConformanceCodable.cpp
  test/stdlib/CodableTests.swift
Labels: r5.5

#38061 [5.5][Sema] Use different solution vectors for `ComponentStep`s created by `DependentComponentSplitterStep`
  lib/Sema/CSStep.cpp
  lib/Sema/CSStep.h
  validation-test/Sema/sr14692.swift
Labels: r5.5

#37999 🍒[TaskLocal] copyTo must initializeWithCopy the task local value
  stdlib/public/Concurrency/TaskLocal.cpp
  test/Concurrency/Runtime/async_task_locals_copy_to_async.swift
Labels: r5.5

#38006 Sema: Reject generic arguments applied to 'Self' [5.5]
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckType.cpp
  test/type/self.swift
Labels: r5.5

#38007 Sema: Avoid an assertion when diagnosing failures in some cases with invalid associated types [5.5]
  lib/Sema/TypeCheckProtocol.cpp
  validation-test/compiler_crashers_2_fixed/sr14672.swift
Labels: r5.5

#38069 [5.5][Diagnostics] Adjust `Self` conformance check to find non-decl overload choices
  lib/Sema/CSSimplify.cpp
  validation-test/Sema/type_checker_crashers_fixed/rdar79268378.swift
Labels: r5.5

#38056 [5.5][CodeComplete] Mark results as not recommended if global actor context doesn't match
  lib/IDE/CodeCompletion.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  lib/Sema/TypeCheckConcurrency.h
  lib/Sema/TypeCheckStmt.cpp
  test/IDE/complete_global_actorisolation.swift
Labels: r5.5

#38094 [5.5][ClangImporter] Respect -working-directory in the created VFS
  include/swift/ClangImporter/ClangImporter.h
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ClangModuleDependencyScanner.cpp
  test/ClangImporter/MixedSource/broken-modules.swift
  test/ClangImporter/broken-modules.swift
  test/ClangImporter/non-modular-include.swift
  test/ClangImporter/working-directory.swift
  test/SourceKit/CursorInfo/injected_vfs.swift
Labels: r5.5

#38095 🍒[5.5][Concurrency] ban inheriting Actor explicitly by class
  docs/Diagnostics.md
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckProtocol.cpp
  test/Concurrency/actor_isolation.swift
  test/decl/class/actor/basic.swift
  test/decl/protocol/special/Actor.swift
Labels: r5.5

#38051 [5.5][IDE] Complete enum argument labels in unresolved member completions
  lib/IDE/ExprContextAnalysis.cpp
  test/IDE/complete_enum_unresolved_dot_argument_labels.swift
Labels: r5.5

#38043 [5.5] Restrict uses of 'self' in actor initializers
  include/swift/AST/DiagnosticsSIL.def
  lib/SILOptimizer/Mandatory/DIMemoryUseCollector.cpp
  lib/SILOptimizer/Mandatory/DIMemoryUseCollector.h
  lib/SILOptimizer/Mandatory/DefiniteInitialization.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  test/Concurrency/Runtime/actor_keypaths.swift
  test/Concurrency/actor_definite_init.swift
  test/Concurrency/actor_isolation.swift
Labels: Concurrency, bug, r5.5

#37877 [5.5][CodeCompletion] Don't offer completion names for closure argument names
  lib/Parse/ParseExpr.cpp
  test/IDE/complete_concurrency_specifier.swift
  test/IDE/complete_in_closures.swift
Labels: r5.5

#38076 Centralize task creation in the Concurrency runtime
  include/swift/ABI/MetadataValues.h
  include/swift/ABI/Task.h
  include/swift/ABI/TaskLocal.h
  include/swift/ABI/TaskOptions.h
  include/swift/AST/Builtins.def
  include/swift/Basic/Features.def
  include/swift/Runtime/Concurrency.h
  include/swift/Runtime/RuntimeFunctions.def
  lib/AST/ASTPrinter.cpp
  lib/AST/Builtins.cpp
  lib/IRGen/GenBuiltin.cpp
  lib/IRGen/GenCall.cpp
  lib/IRGen/GenCall.h
  lib/IRGen/GenConcurrency.cpp
  lib/IRGen/GenConcurrency.h
  lib/IRGen/IRGenModule.cpp
  lib/IRGen/IRGenModule.h
  lib/SIL/IR/OperandOwnership.cpp
  lib/SIL/IR/ValueOwnership.cpp
  lib/SIL/Utils/MemAccessUtils.cpp
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenBuiltin.cpp
  lib/SILGen/SILGenDecl.cpp
  lib/SILGen/SILGenFunction.h
  lib/SILOptimizer/Transforms/AccessEnforcementReleaseSinking.cpp
  stdlib/public/CompatibilityOverride/CompatibilityOverrideConcurrency.def
  stdlib/public/Concurrency/AsyncLet.cpp
  stdlib/public/Concurrency/AsyncLet.swift
  stdlib/public/Concurrency/Task.cpp
  stdlib/public/Concurrency/Task.swift
  stdlib/public/Concurrency/TaskCancellation.swift
  stdlib/public/Concurrency/TaskGroup.swift
  stdlib/public/Concurrency/TaskPrivate.h
  test/Concurrency/Runtime/async_task_cancellation_early.swift
  test/Concurrency/Runtime/async_task_cancellation_while_running.swift
  test/Concurrency/Runtime/async_taskgroup_is_empty.swift
  test/IRGen/async/builtins.sil
  test/SILGen/async_builtins.swift
  test/SILGen/async_let.swift
  test/SILOptimizer/closure_lifetime_fixup.swift
  unittests/runtime/Actor.cpp
  unittests/runtime/CompatibilityOverrideConcurrency.cpp
  unittests/runtime/TaskStatus.cpp
Labels: r5.5

#38088 Introduce fake symbols that were present with the old concurrency ABI.
  stdlib/public/Concurrency/CMakeLists.txt
  stdlib/public/Concurrency/LinkCompatibilityShims.cpp
Labels: r5.5

#38087 Disable standard substitutions when building with "older" _Concurrency module
  lib/AST/Module.cpp
Labels: r5.5

#38063 [5.5][Serialization] Recover from failures when correcting typos in `ModuleFile::lookupClassMembers`
  lib/Serialization/ModuleFile.cpp
  test/Serialization/Recovery/implementation-only-missing.swift
Labels: r5.5

#38108 [Amendment] SE-0296: Allow overloads that differ only in async
  include/swift/AST/Decl.h
  lib/AST/Decl.cpp
  test/ClangImporter/objc_async_conformance.swift
  test/decl/func/async.swift
Labels: r5.5

#37876 [5.5][CodeCompletion] Keep completion status when parsing postfix types
  include/swift/Parse/Parser.h
  lib/Parse/ParseType.cpp
  test/IDE/complete_type.swift
Labels: r5.5

#38113 🍒[5.5][Concurrency] Add tsan_release edge on task creation
  stdlib/public/Concurrency/GlobalExecutor.cpp
  stdlib/public/Concurrency/Task.cpp
  stdlib/public/Concurrency/ThreadSanitizer.cpp
  test/Concurrency/Runtime/actor_counters.swift
  test/Sanitizers/tsan/actor_counters.swift
Labels: r5.5

#38064 [5.5] [Concurrency] Deprecate typealias PartialAsyncTask
  stdlib/public/Concurrency/PartialAsyncTask.swift
  stdlib/public/Concurrency/SourceCompatibilityShims.swift
  test/stdlib/Concurrency.swift
Labels: r5.5

#38142 [5.5] Mark async_stream.swift as an executable_test
  test/Concurrency/Runtime/async_stream.swift
Labels: r5.5

#38141 [5.5] [IRGen] Remove a dump statement from GenConcurrency
  lib/IRGen/GenConcurrency.cpp
Labels: r5.5

#38143 [IRGen] swift_getFunctionTypeMetadataGlobalActor has concurrency availability
  include/swift/Runtime/RuntimeFunctions.def
  lib/IRGen/Linking.cpp
  test/Concurrency/Runtime/class_resilience.swift
  test/IRGen/async/weak_availability.swift
Labels: r5.5

#38137 [5.5][Diagnostics] Fix requirement note to properly handle layout requirements
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  test/Constraints/diagnostics.swift
  test/Constraints/overload.swift
  test/decl/ext/protocol.swift
Labels: r5.5

#38144 [5.5][Diagnostics] Correct the insert location of missing return type fix-it.
  lib/Sema/CSDiagnostics.cpp
  test/Constraints/diagnostics.swift
Labels: r5.5

#38152 [5.5] [Async Refactoring] Add missing null type check
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/convert_invalid.swift
Labels: r5.5

#38115 [5.5][Parse] Don't skip '}' when recovering from 'default' outside 'switch'
  lib/Parse/ParseStmt.cpp
  validation-test/IDE/crashers_2_fixed/rdar78781163.swift
Labels: r5.5

#38121 C++ Interop: avoid adding static members to the value constructor
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/static/Inputs/static-member-var.h
  test/Interop/Cxx/static/static-member-var-module-interface.swift
  test/Interop/Cxx/static/static-member-var.swift
Labels: C++ Interop

#38151 [5.5] Revert "SILGen: avoid reusing the same opened archetype in keypath setter and getter functions."
  lib/SILGen/SILGenExpr.cpp
Labels: r5.5

#38099 SILGen: Don't allow referencing the 'var' box before it's fully initialized [5.5]
  lib/SILGen/SILGenDecl.cpp
  lib/SILGen/SILGenFunction.h
  test/SILGen/capture_order.swift
Labels: r5.5

#38100 [5.5][IDE] Show completion results if member is followed by trailing closure
  lib/Parse/ParseExpr.cpp
  test/IDE/complete_with_trailing_closure.swift
Labels: r5.5

#38101 [5.5][Refactoring] Use internal completion handler labels for async function's return type
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertAsync/labeled_closure_params.swift
Labels: r5.5

#38114 Fix SILGen of access to isolated static properties
  lib/SILGen/LValue.h
  lib/SILGen/SILGenLValue.cpp
  test/Concurrency/Runtime/async_properties_actor.swift
  test/SILGen/hop_to_executor.swift
  test/SILGen/hop_to_executor_async_prop.swift
Labels: Concurrency, bug
