Repository swiftlang/swift, pull requests merged in 2022-04, with the labels that each got.

#42136 [Distributed] ID synthesis must be eager, or we run into issues in real projects
  include/swift/AST/Decl.h
  include/swift/AST/KnownProtocols.def
  lib/AST/Decl.cpp
  lib/IRGen/GenMeta.cpp
  lib/Sema/DerivedConformanceDistributedActor.cpp
  lib/Sema/DerivedConformances.cpp
  lib/Sema/DerivedConformances.h
  lib/Sema/TypeCheckProtocol.cpp
  lib/Sema/TypeCheckProtocol.h
  lib/Sema/TypeCheckProtocolInference.cpp
  test/decl/protocol/special/DistributedActor.swift
Labels: Distributed

#42149 [docs] Add a catch all document to record C++ interop oddities.
  docs/CppInteroperability/InteropOddities.md
Labels: C++ Interop

#42173 [5.6][SourceKit] Disable cancellation of in-flight non-completion requests
  tools/SourceKit/lib/SwiftLang/SwiftASTManager.cpp
  unittests/SourceKit/SwiftLang/CursorInfoTest.cpp
Labels: r5.6

#42231 [5.7][CSClosure] Handle wrapped variables without explicit initializers
  lib/Sema/CSClosure.cpp
  test/expr/closure/multi_statement.swift
Labels: r5.7

#42222 [cxx-interop] Fix linker errors when a template is used from different modules
  lib/IRGen/GenClangDecl.cpp
  test/Interop/Cxx/templates/instantiation-in-multiple-modules/Inputs/a.h
  test/Interop/Cxx/templates/instantiation-in-multiple-modules/Inputs/b.h
  test/Interop/Cxx/templates/instantiation-in-multiple-modules/Inputs/module.modulemap
  test/Interop/Cxx/templates/instantiation-in-multiple-modules/Inputs/wrapper.h
  test/Interop/Cxx/templates/instantiation-in-multiple-modules/instantiation-in-multiple-modules-irgen.swift
  test/Interop/Cxx/templates/instantiation-in-multiple-modules/instantiation-in-multiple-modules.swift
Labels: C++ Interop

#42193 [5.7][SourceKit] Disable cancellation of in-flight non-completion requests
  tools/SourceKit/lib/SwiftLang/SwiftASTManager.cpp
  unittests/SourceKit/SwiftLang/CursorInfoTest.cpp
Labels: r5.7

#42233 [5.7] Add test case for disabling lexical lifetimes.
  test/SILOptimizer/lexical_lifetime_elim.swift
Labels: r5.7

#42249 Cherry-pick latest SE-0346 changes to 5.7 branch
  include/swift/AST/ASTPrinter.h
  include/swift/AST/DiagnosticsParse.def
  include/swift/Basic/Features.def
  include/swift/Basic/LangOptions.h
  include/swift/Option/FrontendOptions.td
  lib/AST/ASTPrinter.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/Frontend/ModuleInterfaceSupport.cpp
  lib/Parse/ParseDecl.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeCheckType.h
  test/Constraints/opened_existentials.swift
  test/ModuleInterface/parameterized-protocol-synthesized-extension.swift
  test/ModuleInterface/parameterized-protocols.swift
  test/Parse/invalid.swift
  test/SILGen/parameterized_existentials.swift
  test/SILOptimizer/cast_folding_parameterized_protocol.swift
  test/type/opaque_parameters.swift
  test/type/parameterized_existential.swift
  test/type/parameterized_protocol.swift
  validation-test/compiler_crashers_2_fixed/unsupported_recursive_opaque_conformance.swift
Labels: r5.7

#42240 [5.7][CodeCompletion] Allow references to top-level functions with error parameters
  lib/Sema/CSGen.cpp
  lib/Sema/ConstraintSystem.cpp
  test/IDE/complete_call_arg.swift
Labels: r5.7

#41953 [cxx-interop] Import libstdc++ as a Clang module
  lib/ClangImporter/ClangImporter.cpp
  stdlib/public/CMakeLists.txt
  stdlib/public/Cxx/CMakeLists.txt
  stdlib/public/Cxx/libstdcxx.h
  stdlib/public/Cxx/libstdcxx.modulemap
  test/Interop/Cxx/stdlib/libcxx-module-interface.swift
  test/Interop/Cxx/stdlib/libstdcxx-module-interface.swift
  test/Interop/Cxx/stdlib/use-std-string.swift
Labels: C++ Interop

#42263 [cxx-interop] Fix test failures with older libstdc++
  stdlib/public/Cxx/libstdcxx.h
Labels: C++ Interop

#42269 [5.7][TypeChecker] Fix a crash in inherited default argument type-checking
  lib/AST/Decl.cpp
  lib/Sema/TypeCheckDeclPrimary.cpp
  test/Constraints/type_inference_from_default_exprs.swift
Labels: r5.7

#42216 [5.7] [SILOpt] Added flag to disable destroy hoisting.
  include/swift/AST/SILOptions.h
  include/swift/Option/FrontendOptions.td
  lib/Frontend/CompilerInvocation.cpp
  lib/SILOptimizer/PassManager/PassPipeline.cpp
  test/SILOptimizer/disable-copy-propagation-frontend-flag.swift
Labels: r5.7

#42272 [5.7][TypeChecker] SE-0347: Enable type inference from default expressions
  CHANGELOG.md
  include/swift/Basic/LangOptions.h
  lib/Frontend/CompilerInvocation.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/TypeCheckConstraints.cpp
  test/Constraints/type_inference_from_default_exprs.swift
  test/Constraints/type_inference_from_default_exprs_executable_test.swift
  test/decl/func/vararg.swift
  test/expr/closure/basic.swift
Labels: r5.7

#42282 [5.7][Type Resolution] Emit a tailored diagnostic for the incorrect `any P?` syntax.
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckType.cpp
  test/type/explicit_existential.swift
Labels: r5.7

#42298 [Distributed] Cache checking distributed func
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  lib/Sema/TypeCheckDistributed.cpp
  lib/Sema/TypeCheckDistributed.h
Labels: Distributed

#42309 RequirementMachine: Allow missing Sendable conformances [5.7]
  lib/AST/RequirementMachine/ConcreteContraction.cpp
  lib/AST/RequirementMachine/ConcreteTypeWitness.cpp
  lib/AST/RequirementMachine/RequirementLowering.cpp
  test/Generics/missing_sendable_conformance.swift
Labels: r5.7

#42310 ASTPrinter: Rename PrimaryAssociatedTypes feature to PrimaryAssociatedTypes2 [5.7]
  include/swift/Basic/Features.def
  lib/AST/ASTPrinter.cpp
  test/ModuleInterface/parameterized-protocols.swift
Labels: r5.7

#42299 🍒[5.7][Distributed] Cache checking distributed func
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  lib/Sema/TypeCheckDistributed.cpp
  lib/Sema/TypeCheckDistributed.h
Labels: Distributed, r5.7

#42184 [5.7][CodeCompletion] Migrate AccessorBeginning to solver-based
  lib/IDE/CodeCompletion.cpp
  lib/Parse/ParseDecl.cpp
Labels: r5.7

#42259 [5.7][Parser] When recovering from expression parsing don't stop at '{'
  include/swift/AST/DiagnosticsParse.def
  include/swift/Parse/Parser.h
  lib/Parse/ParseStmt.cpp
  lib/Parse/Parser.cpp
  test/IDE/complete_cross_import.swift
  test/IDE/complete_in_result_builder.swift
  test/Parse/availability_query.swift
  test/Parse/availability_query_unavailability.swift
  test/Parse/guard.swift
  test/Parse/recovery.swift
  test/Parse/switch.swift
  test/Parse/trailing_closures.swift
  test/Syntax/diagnostics_verify.swift
  test/decl/func/operator.swift
  test/decl/func/static_func.swift
  test/stmt/if_while_var.swift
Labels: r5.7

#42332 🍒 [5.7] CSApply: Handle unbound references to methods found via dynamic lookup
  lib/Sema/CSApply.cpp
  test/Interpreter/dynamic_lookup.swift
  test/SILGen/dynamic_lookup.swift
  test/SILGen/subclass_existentials.swift
  test/Sema/dynamic_self_implicit_conversions.swift
Labels: r5.7

#42341 [Distributed] SerializationReq must be associated type on DA
  include/swift/AST/DiagnosticsSema.def
  lib/AST/ASTDumper.cpp
  lib/AST/DistributedDecl.cpp
  lib/Sema/DerivedConformanceDistributedActor.cpp
  lib/Sema/TypeCheckProtocol.cpp
  stdlib/public/Distributed/DistributedActor.swift
  test/Distributed/actor_protocols.swift
Labels: Distributed

#42311 [Runtime] Add pointer auth to accessible function section/cache
  include/swift/ABI/MetadataValues.h
  include/swift/Runtime/Config.h
  stdlib/public/runtime/AccessibleFunction.cpp
Labels: Distributed

#42327 [5.7][Runtime] Add pointer auth to accessible function section/cache
  include/swift/ABI/MetadataValues.h
  include/swift/Runtime/Config.h
  stdlib/public/runtime/AccessibleFunction.cpp
Labels: Distributed, r5.7

#42312 [5.7][CursorInfo] Add Clang documentation to SymbolGraph output
  include/swift/AST/ASTPrinter.h
  include/swift/Basic/Unicode.h
  include/swift/SymbolGraphGen/SymbolGraphOptions.h
  lib/AST/ASTPrinter.cpp
  lib/Basic/Unicode.cpp
  lib/IDE/ModuleInterfacePrinting.cpp
  lib/SymbolGraphGen/Symbol.cpp
  test/SourceKit/CursorInfo/cursor_symbol_graph_objc.swift
  tools/SourceKit/lib/SwiftLang/SwiftSourceDocInfo.cpp
Labels: r5.7

#42352 [5.7] [Parse] Introduce `/.../` regex literals
  include/swift/AST/DiagnosticEngine.h
  include/swift/AST/DiagnosticsParse.def
  include/swift/Basic/LangOptions.h
  include/swift/Option/FrontendOptions.td
  include/swift/Parse/Lexer.h
  include/swift/Parse/Parser.h
  lib/AST/DiagnosticEngine.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/Parse/Lexer.cpp
  lib/Parse/ParseDecl.cpp
  lib/Parse/ParseExpr.cpp
  lib/Parse/Parser.cpp
  test/IDE/complete_regex.swift
  test/SourceKit/Sema/sema_regex.swift
  test/StringProcessing/Frontend/disable-flag.swift
  test/StringProcessing/Frontend/enable-flag.swift
  test/StringProcessing/Parse/forward-slash-regex.swift
  test/StringProcessing/Parse/regex.swift
  test/StringProcessing/Parse/regex_parse_end_of_buffer.swift
  test/StringProcessing/Parse/regex_parse_error.swift
  test/StringProcessing/Runtime/regex_basic.swift
  test/StringProcessing/SILGen/regex_literal_silgen.swift
  test/StringProcessing/Sema/regex_literal_type_inference.swift
  tools/swift-ide-test/swift-ide-test.cpp
  unittests/Parse/LexerTests.cpp
Labels: r5.7

#42356 [5.7][CursorInfo] Add ObjC location to generated symbol graph
  lib/SymbolGraphGen/Symbol.cpp
  test/SourceKit/CursorInfo/cursor_symbol_graph_objc.swift
Labels: r5.7

#42384 🍒 [5.7] CS: `optional` storage key path components are read-only
  lib/IRGen/GenObjC.cpp
  lib/Sema/TypeCheckStorage.cpp
  test/SILGen/keypaths_objc.swift
  test/expr/primary/keypath/swift-keypath-objc-optional-component.swift
Labels: r5.7

#42388 Don't emit @preconcurrency import warnings for Swift interfaces
  lib/Sema/TypeChecker.cpp
  test/ModuleInterface/SilencePreconcurrency.swiftinterface
Labels: r5.7

#42348 [Distributed] Require that SerReq can only be used with protocols
  include/swift/AST/DiagnosticsSema.def
  lib/AST/DistributedDecl.cpp
  lib/Sema/TypeCheckDistributed.cpp
  lib/Sema/TypeCheckDistributed.h
  lib/Sema/TypeCheckProtocol.cpp
  test/Distributed/distributed_serializationRequirement_must_be_protocol.swift
Labels: Distributed

#42417 Serialization: Round-trip primary associated type list [5.7]
  include/swift/AST/Decl.h
  include/swift/AST/LazyResolver.h
  lib/AST/Decl.cpp
  lib/ClangImporter/ImporterImpl.h
  lib/Sema/TypeCheckDecl.cpp
  lib/Serialization/DeclTypeRecordNodes.def
  lib/Serialization/Deserialization.cpp
  lib/Serialization/ModuleFile.h
  lib/Serialization/ModuleFormat.h
  lib/Serialization/Serialization.cpp
  lib/Serialization/Serialization.h
  test/Serialization/Inputs/parameterized_protocol_other.swift
  test/Serialization/parameterized_protocol.swift
  test/type/parameterized_protocol.swift
Labels: r5.7

#42420 Sema: remove debugging leftovers (NFCI)
  lib/Sema/TypeCheckDistributed.cpp
Labels: Distributed

#42331 [5.7][RequirementMachine] Diagnose type parameters that are made concrete by a same-type requirement.
  lib/AST/RequirementMachine/RequirementMachineRequests.cpp
  test/Compatibility/accessibility.swift
  test/Constraints/generic_super_constraint.swift
  test/Generics/concrete_contraction_unrelated_typealias.swift
  test/Generics/function_defs.swift
  test/Generics/protocol_self_concrete_error.swift
  test/Generics/requirement_machine_diagnostics.swift
  test/Generics/superclass_constraint_nested_type.swift
  test/IDE/print_usrs_opaque_types.swift
  test/Sema/accessibility.swift
  test/decl/typealias/generic.swift
  test/decl/typealias/protocol.swift
Labels: r5.7

#42391 [5.7][Type Resolution] Resolve `(any P.Type).Type` as the metatype of an existential metatype.
  lib/Sema/TypeCheckType.cpp
  test/type/explicit_existential.swift
Labels: r5.7

#42413 [5.7][Diagnostics] When replacing an existential parameter type with its generic equivalent, insert some instead of an explicit type parameter.
  lib/Sema/CSDiagnostics.cpp
  test/decl/protocol/existential_member_accesses_self_assoctype_fixit.swift
Labels: r5.7

#42404 [5.7][Frontend] SE-0347: Remove `type inference from default` flag from Fr…
  include/swift/Option/FrontendOptions.td
Labels: r5.7

#42213 runtime: allow over-aligned types in the runtime
  include/swift/Runtime/Atomic.h
  include/swift/Runtime/AtomicWaitQueue.h
  include/swift/Runtime/Heap.h
  stdlib/public/Concurrency/Actor.cpp
  stdlib/public/Concurrency/AsyncLet.cpp
  stdlib/public/Concurrency/TaskPrivate.h
  stdlib/public/SwiftShims/RefCount.h
  stdlib/public/runtime/KnownMetadata.cpp
  stdlib/public/runtime/Metadata.cpp
  stdlib/public/runtime/MetadataCache.h
Labels: r5.7

#42424 [5.7][Static Mirror] Extract names of external-type conformances
  include/swift/Reflection/TypeRefBuilder.h
  test/Reflection/Inputs/cmodules/module.modulemap
  test/Reflection/Inputs/cmodules/testModA.h
  test/Reflection/Inputs/cmodules/testModA.m
  test/Reflection/Inputs/swiftmodules/testModB.swift
  test/Reflection/conformance_descriptors_of_external_types.swift
Labels: r5.7

#42223 [cxx-interop] Allow anonymous enums to be imported as non-constants.
  lib/ClangImporter/ClangAdapter.cpp
  lib/ClangImporter/ClangAdapter.h
  lib/ClangImporter/ImportEnumInfo.cpp
  lib/ClangImporter/ImportName.cpp
  lib/ClangImporter/ImporterImpl.h
  test/Interop/Cxx/enum/Inputs/anonymous-with-swift-name.h
  test/Interop/Cxx/enum/Inputs/module.modulemap
  test/Interop/Cxx/enum/anonymous-with-swift-name-module-interface.swift
  test/Interop/Cxx/enum/anonymous-with-swift-name.swift
Labels: C++ Interop

#42427 [cxx-interop] Add basic support for using UFOs as members, etc.
  lib/IRGen/GenMeta.cpp
  lib/IRGen/GenReflection.cpp
  test/Interop/Cxx/foreign-reference/error-as-class-member.swift
  test/Interop/Cxx/foreign-reference/error-as-struct-member.swift
  test/Interop/Cxx/foreign-reference/pod.swift
Labels: C++ Interop

#42428 [cxx-interop] Work with definition in VisitCXXRecordDecl.
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/class/Inputs/forward-declared-cxx-record-used.h
  test/Interop/Cxx/class/Inputs/forward-declared-cxx-record.h
  test/Interop/Cxx/class/Inputs/module.modulemap
  test/Interop/Cxx/class/forward-declared-cxx-record-module-interface.swift
Labels: C++ Interop

#42378 5.7 fix cast ownership
  include/swift/AST/Types.h
  include/swift/SIL/DynamicCasts.h
  include/swift/SIL/OwnershipUtils.h
  include/swift/SIL/SILInstruction.h
  include/swift/SIL/TypeSubstCloner.h
  lib/AST/Type.cpp
  lib/SIL/IR/SILInstructions.cpp
  lib/SIL/Utils/DynamicCasts.cpp
  lib/SIL/Utils/MemAccessUtils.cpp
  lib/SIL/Utils/OwnershipUtils.cpp
  lib/SIL/Verifier/SILVerifier.cpp
  lib/SILGen/SILGenBuilder.cpp
  lib/SILGen/SILGenDynamicCast.cpp
  lib/SILGen/SILGenPattern.cpp
  lib/SILOptimizer/Mandatory/MoveOnlyChecker.cpp
  lib/SILOptimizer/SemanticARC/OwnershipLiveRange.cpp
  lib/SILOptimizer/Utils/CastOptimizer.cpp
  test/SILGen/opaque_values_silgen.swift
  test/SILOptimizer/rcidentity.sil
  test/SILOptimizer/rcidentity_opaque.sil
  test/SILOptimizer/retain_release_code_motion.sil
Labels: r5.7

#42330 RequirementMachine: Allow 'any C & P' to satisfy a superclass requirement 'C' if 'P' is an @objc protocol [5.7]
  lib/AST/RequirementMachine/PropertyUnification.cpp
  test/Generics/superclass_requirement_and_objc_existential.swift
Labels: r5.7

#42364 [cxx-interop] Fix libstdc++ test failure with CentOS 7
  test/Interop/Cxx/stdlib/libstdcxx-module-interface.swift
  test/Interop/Cxx/stdlib/use-std-string.swift
Labels: C++ Interop

#42431 [cxx-interop] Import enum, not typedef for parameter types.
  lib/ClangImporter/ImportType.cpp
  lib/ClangImporter/ImporterImpl.h
  test/Interop/Cxx/enum/Inputs/anonymous-with-swift-name.h
  test/Interop/Cxx/enum/anonymous-with-swift-name-module-interface.swift
  test/Interop/Cxx/enum/anonymous-with-swift-name.swift
Labels: C++ Interop

#42252 [Distributed] retain ad-hoc witnesses so that they are not optimized away in SIL
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsParse.def
  include/swift/AST/DistributedDecl.h
  include/swift/SIL/SILFunction.h
  lib/AST/DistributedDecl.cpp
  lib/IRGen/GenDistributed.cpp
  lib/SIL/IR/SILFunctionBuilder.cpp
  lib/SIL/IR/SILModule.cpp
  lib/SIL/IR/SILPrinter.cpp
  lib/SIL/Parser/ParseSIL.cpp
  lib/SILOptimizer/Analysis/CallerAnalysis.cpp
  lib/SILOptimizer/FunctionSignatureTransforms/FunctionSignatureOpts.cpp
  lib/SILOptimizer/IPO/DeadFunctionElimination.cpp
  lib/Serialization/DeserializeSIL.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/SILFormat.h
  lib/Serialization/SerializeSIL.cpp
  stdlib/public/Distributed/DistributedActorSystem.swift
  stdlib/public/Distributed/LocalTestingDistributedActorSystem.swift
  test/Distributed/Inputs/FakeDistributedActorSystems.swift
  test/Distributed/Runtime/distributed_actor_cross_module_final_class_adhoc_requirement_not_optimized_away.swift
  test/Distributed/distributed_actor_accessor_thunks_32bit.swift
  test/Distributed/distributed_actor_accessor_thunks_64bit.swift
  test/SILGen/distributed_thunk.swift
Labels: Distributed

#42412 [C++-Interop] Teach omitNeedlessWords to handle raw integer C-enums in C++
  lib/ClangImporter/ImportType.cpp
  test/Interop/Cxx/enum/Inputs/c-enums-withOptions-omit.h
  test/Interop/Cxx/enum/Inputs/module.modulemap
  test/Interop/Cxx/enum/c-enums-withOptions-omit.swift
Labels: C++ Interop

#42450 [cxx-interop] Ignore mutable fields when detecting method mutability
  lib/ClangImporter/ClangImporter.cpp
  test/Interop/Cxx/class/mutable-members-module-interface.swift
  test/Interop/Cxx/class/mutable-members-typechecker.swift
  test/Interop/Cxx/class/mutable-members.swift
  test/Interop/Cxx/ergonomics/Inputs/implicit-computed-properties.h
  test/Interop/Cxx/ergonomics/implicit-computed-properties-module-interface.swift
  test/Interop/Cxx/stdlib/use-std-string.swift
Labels: C++ Interop

#42451 [5.7][Distributed] Retain ad-hoc `decodeNextArgument` in distributed thunk
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsParse.def
  include/swift/AST/DistributedDecl.h
  include/swift/SIL/SILFunction.h
  lib/AST/DistributedDecl.cpp
  lib/IRGen/GenDistributed.cpp
  lib/SIL/IR/SILFunctionBuilder.cpp
  lib/SIL/IR/SILModule.cpp
  lib/SIL/IR/SILPrinter.cpp
  lib/SIL/Parser/ParseSIL.cpp
  lib/SILOptimizer/Analysis/CallerAnalysis.cpp
  lib/SILOptimizer/FunctionSignatureTransforms/FunctionSignatureOpts.cpp
  lib/SILOptimizer/IPO/DeadFunctionElimination.cpp
  lib/Serialization/DeserializeSIL.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/SILFormat.h
  lib/Serialization/SerializeSIL.cpp
  stdlib/public/Distributed/DistributedActorSystem.swift
  stdlib/public/Distributed/LocalTestingDistributedActorSystem.swift
  test/Distributed/Inputs/FakeDistributedActorSystems.swift
  test/Distributed/Runtime/distributed_actor_cross_module_final_class_adhoc_requirement_not_optimized_away.swift
  test/Distributed/distributed_actor_accessor_thunks_32bit.swift
  test/Distributed/distributed_actor_accessor_thunks_64bit.swift
  test/SILGen/distributed_thunk.swift
Labels: Distributed, r5.7

#42462 [5.7][TypeChecker] Disallow `if #unavailable` to produce different opaque …
  lib/Sema/MiscDiagnostics.cpp
  test/type/opaque_with_conditional_availability.swift
Labels: r5.7

#42452 [cxx-interop] Apply typedef -> enum patch to method param types as well.
  lib/ClangImporter/ImportType.cpp
  test/Interop/Cxx/enum/Inputs/anonymous-with-swift-name.h
  test/Interop/Cxx/enum/anonymous-with-swift-name-objc-module-interface.swift
Labels: C++ Interop

#42185 [5.7][CodeCompletion] Teach TypeCheckASTNodeAtLocRequest to check initializers
  lib/AST/DeclContext.cpp
  lib/IDE/ExprContextAnalysis.cpp
  lib/Sema/TypeCheckStmt.cpp
  test/IDE/complete_call_arg.swift
  test/IDE/complete_multiple_files.swift
Labels: r5.7

#42425 [5.7][IDE] Skip walking serialized internal top level decls in SemaAnnotator
  include/swift/AST/ASTWalker.h
  lib/AST/Module.cpp
  lib/IDE/SourceEntityWalker.cpp
Labels: r5.7

#42426 [5.7][SymbolGraph] Initialize newly added IncludeClangDocs field
  lib/DriverTool/swift_symbolgraph_extract_main.cpp
Labels: r5.7

#42490 🍒 [5.7] Use `AbstractStorageDecl::isSettableInSwift` to prohibit direct writes to `optional` requirements
  include/swift/AST/Decl.h
  lib/SILGen/SILGenExpr.cpp
  lib/Sema/ConstraintSystem.cpp
  lib/Sema/TypeCheckStorage.cpp
  test/Inputs/ObjCOptionalRequirements.h
  test/SILGen/keypaths_objc.swift
  test/SILGen/keypaths_objc_optional.swift
  test/decl/protocol/conforms/near_miss_objc.swift
  test/expr/primary/keypath/swift-keypath-objc-optional-component.swift
Labels: r5.7

#42481 [5.7] IRGen: Use the current function name for the swift_suspend_point thunk
  lib/IRGen/GenFunc.cpp
  test/DebugInfo/move_function_dbginfo_async.swift
  test/IRGen/async/hop_to_executor.sil
Labels: r5.7

#42495 [5.7-04182022][Distributed] Retain ad-hoc `decodeNextArgument` in distributed thunk
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsParse.def
  include/swift/AST/DistributedDecl.h
  include/swift/SIL/SILFunction.h
  lib/AST/DistributedDecl.cpp
  lib/IRGen/GenDistributed.cpp
  lib/SIL/IR/SILFunctionBuilder.cpp
  lib/SIL/IR/SILModule.cpp
  lib/SIL/IR/SILPrinter.cpp
  lib/SIL/Parser/ParseSIL.cpp
  lib/SILOptimizer/Analysis/CallerAnalysis.cpp
  lib/SILOptimizer/FunctionSignatureTransforms/FunctionSignatureOpts.cpp
  lib/SILOptimizer/IPO/DeadFunctionElimination.cpp
  lib/Serialization/DeserializeSIL.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/SILFormat.h
  lib/Serialization/SerializeSIL.cpp
  stdlib/public/Distributed/DistributedActorSystem.swift
  stdlib/public/Distributed/LocalTestingDistributedActorSystem.swift
  test/Distributed/Inputs/FakeDistributedActorSystems.swift
  test/Distributed/Runtime/distributed_actor_cross_module_final_class_adhoc_requirement_not_optimized_away.swift
  test/Distributed/distributed_actor_accessor_thunks_32bit.swift
  test/Distributed/distributed_actor_accessor_thunks_64bit.swift
  test/SILGen/distributed_thunk.swift
Labels: Distributed, r5.7

#42511 [cxx-interop] Add flag `cxx-interop-getters-setters-as-properties`.
  include/swift/Basic/LangOptions.h
  include/swift/Option/FrontendOptions.td
  lib/ClangImporter/ImportDecl.cpp
  lib/Frontend/CompilerInvocation.cpp
  test/Interop/Cxx/ergonomics/implicit-computed-properties-module-interface.swift
  test/Interop/Cxx/ergonomics/implicit-computed-properties.swift
  tools/swift-ide-test/swift-ide-test.cpp
Labels: C++ Interop

#42499 [5.7] Turn on Existential Metatypes
  lib/Sema/TypeCheckType.h
  test/Constraints/parameterized_existential_metatypes.swift
Labels: r5.7

#42482 [5.7-04182022] IRGen: Use the current function name for the swift_suspend_point thunk
  lib/IRGen/GenFunc.cpp
  test/DebugInfo/move_function_dbginfo_async.swift
  test/IRGen/async/hop_to_executor.sil
Labels: r5.7

#42534 [5.7][CodeCompletion] Only include results from other modules once
  include/swift/IDE/CompletionLookup.h
  lib/IDE/CompletionLookup.cpp
  test/IDE/complete_from_swift_module.swift
Labels: r5.7

#42535 [5.7-04182022][CodeCompletion] Only include results from other modules once
  include/swift/IDE/CompletionLookup.h
  lib/IDE/CompletionLookup.cpp
  test/IDE/complete_from_swift_module.swift
Labels: r5.7

#42316 [5.7][stdlib] Add `Clock.Duration` as an associated type requirement
  stdlib/public/Concurrency/Clock.swift
Labels: swift-evolution-approved

#42501 Fix https://bugs.swift.org/projects/SR/issues/SR-15807 [5.7]
  include/swift/AST/NameLookup.h
  include/swift/AST/NameLookupRequests.h
  include/swift/AST/NameLookupTypeIDZone.def
  lib/AST/NameLookup.cpp
  lib/Sema/TypeCheckProtocolInference.cpp
  test/Sema/Inputs/where_clause_across_module_boundaries_module.swift
  test/Sema/where_clause_across_module_boundaries.swift
Labels: r5.7

#42536 [5.7][CSApply] Rewrite types of a constructed tuple
  lib/Sema/CSApply.cpp
  validation-test/Sema/type_checker_crashers_fixed/rdar90366182.swift
Labels: r5.7

#42367 [5.7][CodeCompletion] Report type relations when completing inside result builders
  include/swift/Sema/ConstraintSystem.h
  lib/Sema/BuilderTransform.cpp
  lib/Sema/CSSolver.cpp
  lib/Sema/ConstraintSystem.cpp
  lib/Sema/TypeCheckConstraints.cpp
  test/IDE/complete_in_result_builder.swift
Labels: r5.7

#42567 Layout distributed actor id and actorSystem fields first in stored properties
  lib/Sema/TypeCheckStorage.cpp
  test/Distributed/SIL/distributed_actor_default_deinit_sil.swift
  test/Distributed/distributed_actor_layout.swift
Labels: Distributed

#42510 [SILGen] Use opaque AP for ObjC-async returns.
  lib/SIL/IR/SILInstructions.cpp
  lib/SILGen/ResultPlan.cpp
  validation-test/SILGen/Inputs/rdar85526916.h
  validation-test/SILGen/Inputs/rdar85526916.m
  validation-test/SILGen/rdar85526916.swift
  validation-test/compiler_crashers_2_fixed/rdar79383990.swift
  validation-test/compiler_crashers_2_fixed/rdar81590807.swift
  validation-test/compiler_crashers_2_fixed/rdar81617749.swift
Labels: r5.7

#42575 [5.7] [Sema] Diagnose regex literals if `Regex<Output>` is unavailable
  lib/Sema/TypeCheckAvailability.cpp
  test/StringProcessing/Frontend/enable-flag.swift
  test/StringProcessing/SILGen/regex_literal_silgen.swift
  test/StringProcessing/Sema/regex_literal_availability.swift
Labels: r5.7

#42579 🍒[5.7-04182022][Distributed] Pick prevent multiple id synthesis
  include/swift/AST/DistributedDecl.h
  lib/AST/DistributedDecl.cpp
  lib/SILGen/SILGenDistributed.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  test/Distributed/Inputs/EchoActor.swift
  test/Distributed/Runtime/distributed_actor_in_other_module.swift
Labels: Distributed

#42577 [Distributed] Guard ID synthesis from happening multiple times
  include/swift/AST/DistributedDecl.h
  lib/AST/DistributedDecl.cpp
  lib/SILGen/SILGenDistributed.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  test/Distributed/Inputs/EchoActor.swift
  test/Distributed/Runtime/distributed_actor_in_other_module.swift
Labels: Distributed

#42586 [cxx-interop] Use typedef's swift_name attr to rename anonymous enums.
  lib/ClangImporter/ImportName.cpp
  test/Interop/Cxx/enum/Inputs/anonymous-with-swift-name.h
  test/Interop/Cxx/enum/anonymous-with-swift-name-module-interface.swift
Labels: C++ Interop

#42569 [5.7] Layout distributed actor id and actorSystem fields first in stored properties
  lib/Sema/TypeCheckStorage.cpp
  test/Distributed/SIL/distributed_actor_default_deinit_sil.swift
  test/Distributed/distributed_actor_layout.swift
Labels: Distributed, r5.7

#42568 [5.7-04182022] Layout distributed actor id and actorSystem fields first in stored properties
  lib/Sema/TypeCheckStorage.cpp
  test/Distributed/SIL/distributed_actor_default_deinit_sil.swift
  test/Distributed/distributed_actor_layout.swift
Labels: Distributed

#42449 [5.7] Fix a compile-time issue in EscapeAnalysis
  lib/SILOptimizer/Analysis/EscapeAnalysis.cpp
Labels: r5.7

#42595 [Distributed] SILGen must consistently use prop get requests
  include/swift/AST/DistributedDecl.h
  lib/AST/DistributedDecl.cpp
  lib/SILGen/SILGenDistributed.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
Labels: Distributed

#42557 [Distributed] clean up some of the initialization code to be more robust
  lib/SILGen/SILGenDistributed.cpp
Labels: Distributed

#42596 Prepare to (but does not) enable string processing by default.
  include/swift/Option/FrontendOptions.td
  lib/Frontend/Frontend.cpp
  stdlib/cmake/modules/AddSwiftStdlib.cmake
Labels: Distributed

#42593 Make sure we don't provide duplicate synthesized conformance table entries
  lib/AST/Module.cpp
  lib/AST/ProtocolConformance.cpp
  test/Distributed/distributed_actor_layout.swift
Labels: Distributed

#42600 🍒[5.7][Distributed] SILGen must consistently use prop get requests
  lib/SILGen/SILGenDistributed.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
Labels: Distributed, r5.7

#42578 🍒[5.7][Distributed] Guard ID synthesis from happening multiple times
  include/swift/AST/DistributedDecl.h
  lib/AST/DistributedDecl.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  test/Distributed/Inputs/EchoActor.swift
  test/Distributed/Runtime/distributed_actor_in_other_module.swift
Labels: Distributed, r5.7

#42601 🍒[5.7-04182022][Distributed] SILGen must consistently use prop get requests
  lib/SILGen/SILGenDistributed.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
Labels: Distributed

#42599 Make sure we don't provide duplicate synthesized conformance table entries
  lib/AST/Module.cpp
  lib/AST/ProtocolConformance.cpp
  test/Distributed/distributed_actor_layout.swift
Labels: Distributed

#44620 [Distributed] unlock test which used to fail on 32bit watch
  test/Distributed/Runtime/distributed_actor_localSystem.swift
Labels: Distributed

#42383 [5.7][Changelog] fix formatting of recent items
  CHANGELOG.md
Labels: r5.7

#42361 🍒 [5.7] Add CHANGELOG entry for #41849 and #42332
  CHANGELOG.md
  test/Interpreter/dynamic_lookup.swift
Labels: r5.7

#42598 Make sure we don't provide duplicate synthesized conformance table entries
  lib/AST/Module.cpp
  lib/AST/ProtocolConformance.cpp
  test/Distributed/distributed_actor_layout.swift
Labels: Distributed, r5.7, pending-approval

#58398 [5.7][🍒] Fix jump-to-null issue for ObjC async calls.
  lib/SILGen/ExecutorBreadcrumb.h
  lib/SILGen/ManagedValue.cpp
  lib/SILGen/ManagedValue.h
  lib/SILGen/SILGenApply.cpp
  test/SILGen/objc_async.swift
  test/SILGen/objc_async_from_swift.swift
Labels: Concurrency, r5.7, pending-approval

#42613 [5.7] Trivial fix for an LICM assertion in projectLoadValue
  lib/SILOptimizer/LoopTransforms/LICM.cpp
  test/SILOptimizer/licm.sil
Labels: r5.7

#58428 [cxx-interop] Fix SIL deserialization error
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/SwiftLookupTable.cpp
  test/Interop/Cxx/class/nested-records-module-interface.swift
  test/Interop/Cxx/namespace/templates-module-interface.swift
Labels: C++ Interop

#58476 [5.7][🍒] Back out "Fix jump-to-null issue for ObjC async calls."
  lib/SIL/IR/SILInstruction.cpp
  lib/SILGen/ExecutorBreadcrumb.h
  lib/SILGen/ManagedValue.cpp
  lib/SILGen/ManagedValue.h
  lib/SILGen/SILGenApply.cpp
  test/SIL/verifier-no-nested-suspend.sil
  test/SILGen/objc_async.swift
  test/SILGen/objc_async_from_swift.swift
Labels: Concurrency, r5.7, pending-approval

#58477 [5.7-04182022][🍒] Enhance SILVerifier to catch more nested suspensions.
  lib/SIL/IR/SILInstruction.cpp
  test/SIL/verifier-no-nested-suspend.sil
Labels: Concurrency, r5.7

#42372 Clang nonmutating attribute
  include/swift/AST/DiagnosticsClangImporter.def
  include/swift/ClangImporter/ClangImporter.h
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImporterImpl.h
  test/Interop/Cxx/class/Inputs/mutability-annotations.h
  test/Interop/Cxx/class/mutability-annotations-module-interface.swift
  test/Interop/Cxx/class/mutability-annotations-typechecker.swift
Labels: C++ Interop

#58488 [5.7][ConstraintSystem] "too complex" diagnostic improvements
  include/swift/Sema/ConstraintSystem.h
  include/swift/Sema/SolutionResult.h
  lib/Sema/CSApply.cpp
  lib/Sema/CSSolver.cpp
  lib/Sema/CSStep.cpp
  lib/Sema/CSStep.h
  lib/Sema/ConstraintSystem.cpp
  validation-test/Sema/type_checker_perf/slow/rdar19612086.swift
  validation-test/Sema/type_checker_perf/slow/rdar22079400.swift
  validation-test/Sema/type_checker_perf/slow/rdar91310777.swift
Labels: r5.7

#58487 [5.7][ConstraintSystem] Extend availability check to cover unavailable ext…
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/availability.swift
Labels: r5.7

#58489 [🍒5.7] Use Disjunction Constraint to find main function
  include/swift/Basic/LangOptions.h
  include/swift/Option/Options.td
  include/swift/Sema/ConstraintSystem.h
  include/swift/Sema/IDETypeChecking.h
  lib/Driver/ToolChains.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/ConstraintSystem.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  test/Concurrency/async_main_resolution.swift
  test/Concurrency/where_clause_main_resolution.swift
  test/attr/ApplicationMain/attr_main_struct_from_two_protocols_one_missing.swift
Labels: r5.7

#58506 [5.7] Sema: Skip members of unavailable extensions for -require-explicit-availability
  lib/Sema/TypeCheckAvailability.cpp
  test/attr/require_explicit_availability.swift
Labels: r5.7

#42580 [5.7] remainder of alignment changes
  include/swift/Runtime/Atomic.h
  include/swift/Runtime/AtomicWaitQueue.h
  include/swift/Runtime/HeapObject.h
  stdlib/public/Concurrency/Actor.cpp
  stdlib/public/Concurrency/AsyncLet.cpp
  stdlib/public/Concurrency/Task.cpp
  stdlib/public/Concurrency/TaskGroup.cpp
  stdlib/public/Concurrency/TaskLocal.cpp
  stdlib/public/Concurrency/TaskPrivate.h
  stdlib/public/runtime/AccessibleFunction.cpp
  stdlib/public/runtime/AnyHashableSupport.cpp
  stdlib/public/runtime/AutoDiffSupport.cpp
  stdlib/public/runtime/HeapObject.cpp
  stdlib/public/runtime/KeyPaths.cpp
  stdlib/public/runtime/Metadata.cpp
  stdlib/public/runtime/MetadataImpl.h
  stdlib/public/runtime/MetadataLookup.cpp
  stdlib/public/runtime/ProtocolConformance.cpp
  stdlib/public/runtime/StackAllocator.h
  stdlib/public/runtime/SwiftRT-COFF.cpp
  stdlib/public/runtime/SwiftRT-ELF.cpp
  stdlib/public/runtime/SwiftValue.mm
Labels: r5.7

#58533 [nfc] [cxx-interop] Disable `ReadAccessor` benchmark.
  benchmark/utils/main.swift
Labels: C++ Interop
