Repository swiftlang/swift, pull requests merged in 2022-06, with the labels that each got.

#59183 Parameterized protocol improvements [5.7]
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/Types.h
  lib/AST/Type.cpp
  lib/Sema/TypeCheckDeclPrimary.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeCheckType.h
  test/type/parameterized_existential.swift
  test/type/parameterized_protocol.swift
Labels: r5.7

#59150 [5.7][SwiftSyntax] Add an API to enable or disable bare slash regex literals from SwiftSyntax
  include/swift-c/SyntaxParser/SwiftSyntaxParser.h
  test/Syntax/Parser/unterminated_regex.swift
  tools/libSwiftSyntaxParser/libSwiftSyntaxParser.cpp
  tools/libSwiftSyntaxParser/libSwiftSyntaxParser.exports
  tools/swift-syntax-parser-test/swift-syntax-parser-test.cpp
Labels: r5.7

#59022 [cxx-interop] Import attributes on inherited C++ methods
  include/swift/AST/Attr.h
  lib/ClangImporter/ClangImporter.cpp
  test/Interop/Cxx/class/inheritance/Inputs/functions.h
  test/Interop/Cxx/class/inheritance/functions-module-interface.swift
Labels: C++ Interop

#58910 Update cxx operator implementation
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImportName.cpp
  lib/ClangImporter/ImportType.cpp
  lib/SIL/IR/SILFunctionType.cpp
  lib/SILGen/SILGenApply.cpp
  test/Interop/Cxx/implementation-only-imports/Inputs/module.modulemap
  test/Interop/Cxx/implementation-only-imports/check-operator-visibility-inversed.swift
  test/Interop/Cxx/implementation-only-imports/check-operator-visibility.swift
  test/Interop/Cxx/implementation-only-imports/skip-forward-declarations.swift
  test/Interop/Cxx/namespace/free-functions-module-interface.swift
  test/Interop/Cxx/namespace/free-functions.swift
  test/Interop/Cxx/operators/member-inline-irgen.swift
  test/Interop/Cxx/operators/member-inline-module-interface.swift
  test/Interop/Cxx/operators/member-inline-silgen.swift
  test/Interop/Cxx/operators/member-inline-typechecker.swift
  test/Interop/Cxx/operators/member-inline.swift
  test/Interop/Cxx/operators/member-out-of-line-irgen.swift
  test/Interop/Cxx/operators/member-out-of-line-silgen.swift
  test/Interop/Cxx/operators/member-out-of-line.swift
  test/Interop/Cxx/operators/non-member-inline-module-interface.swift
  test/Interop/Cxx/operators/non-member-inline-typechecker.swift
  test/Interop/Cxx/operators/non-member-inline.swift
  test/Interop/Cxx/operators/non-member-out-of-line-irgen.swift
  test/Interop/Cxx/operators/non-member-out-of-line-silgen.swift
  test/Interop/Cxx/operators/non-member-out-of-line.swift
Labels: C++ Interop

#59219 SILGen: Emit calls to default argument generators at the right abstraction level [5.7]
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenExpr.cpp
  lib/SILGen/SILGenFunction.h
  test/SILGen/default_arguments_concrete.swift
Labels: r5.7

#59207 [cxx interoperability] Turn off non subscript templated operators
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/operators/Inputs/member-inline.h
  test/Interop/Cxx/operators/member-inline-module-interface.swift
Labels: C++ Interop

#59230 [5.7][CSSimplify] If function types mismatch on labels record a contextual mismatch
  lib/Sema/CSSimplify.cpp
  validation-test/Sema/type_checker_crashers_fixed/issue59058.swift
Labels: r5.7

#59149 [cxx interop] Export inout params as C++ reference
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/PrintClangFunction.cpp
  test/Interop/SwiftToCxx/functions/swift-primitive-inout-functions-cxx-bridging.swift
  test/Interop/SwiftToCxx/functions/swift-primitive-inout-functions-execution.cpp
Labels: C++ Interop

#59217 [Interop] [SwiftToCxx] New Throw Error Test
  test/Interop/SwiftToCxx/functions/swift-functions-errors-execution.cpp
  test/Interop/SwiftToCxx/functions/swift-functions-errors.swift
Labels: C++ Interop

#59119 [interop][SwiftToCxx] Gather initial struct layout information and em…
  include/swift/IRGen/IRABIDetailsProvider.h
  include/swift/PrintAsClang/PrintAsClang.h
  lib/FrontendTool/FrontendTool.cpp
  lib/IRGen/CMakeLists.txt
  lib/IRGen/IRABIDetailsProvider.cpp
  lib/PrintAsClang/CMakeLists.txt
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/DeclAndTypePrinter.h
  lib/PrintAsClang/ModuleContentsWriter.cpp
  lib/PrintAsClang/ModuleContentsWriter.h
  lib/PrintAsClang/PrintAsClang.cpp
  lib/PrintAsClang/PrintClangValueType.cpp
  lib/PrintAsClang/PrintClangValueType.h
  lib/PrintAsClang/SwiftToClangInteropContext.cpp
  lib/PrintAsClang/SwiftToClangInteropContext.h
  test/Interop/SwiftToCxx/structs/swift-struct-in-cxx.swift
  test/Interop/SwiftToCxx/structs/zero-sized-struct-in-cxx.swift
Labels: C++ Interop

#59247 [5.7] Increase expectation slop for clock tests
  test/Concurrency/Runtime/clock.swift
Labels: r5.7

#59236 AST: Fix debug info mangling of opaque result types with @_originallyDefinedIn [5.7]
  include/swift/AST/ASTMangler.h
  lib/AST/ASTMangler.cpp
  lib/SIL/IR/SILType.cpp
  test/ModuleInterface/originally-defined-attr-opaque-result.swift
Labels: r5.7

#59244 [5.7][ASTPrinter] Simplify archetype printing by visiting the interface type.
  lib/AST/ASTPrinter.cpp
  lib/AST/Type.cpp
  test/Generics/opaque_archetype_concrete_requirement.swift
  test/type/opaque_parameters.swift
Labels: r5.7

#59239 [5.7][Static Mirror] Handle anonymous contexts when re-constructing fully-qualified type names
  include/swift/ABI/Metadata.h
  include/swift/Reflection/TypeRefBuilder.h
  test/Reflection/Inputs/Conformances.swift
  test/Reflection/conformance_descriptors.swift
Labels: r5.7

#59216 [lit] Support executable and non-executable tests with C++ Interop
  test/lit.cfg
Labels: C++ Interop

#59245 [5.7][CSClosure] (Mostly NFC) Renames and introduction of `AnyFunctionRef`
  include/swift/Sema/Constraint.h
  include/swift/Sema/ConstraintLocator.h
  include/swift/Sema/ConstraintLocatorPathElts.def
  include/swift/Sema/ConstraintSystem.h
  lib/Sema/CSBindings.cpp
  lib/Sema/CSClosure.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSSimplify.cpp
  lib/Sema/Constraint.cpp
  lib/Sema/ConstraintLocator.cpp
  lib/Sema/ConstraintSystem.cpp
Labels: r5.7

#59261 [5.7][TypeChecker] Rework type-checking of `for-in` statements
  include/swift/AST/Stmt.h
  include/swift/Sema/Constraint.h
  include/swift/Sema/ConstraintSystem.h
  lib/AST/ASTDumper.cpp
  lib/AST/ASTScopeCreation.cpp
  lib/AST/ASTWalker.cpp
  lib/AST/NameLookup.cpp
  lib/AST/Stmt.cpp
  lib/IDE/ExprContextAnalysis.cpp
  lib/IDE/Formatting.cpp
  lib/IDE/SyntaxModel.cpp
  lib/SILGen/SILGenStmt.cpp
  lib/Sema/BuilderTransform.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CSBindings.cpp
  lib/Sema/CSClosure.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSFix.cpp
  lib/Sema/CSGen.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/CSSolver.cpp
  lib/Sema/Constraint.cpp
  lib/Sema/ConstraintSystem.cpp
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/PCMacro.cpp
  lib/Sema/PreCheckExpr.cpp
  lib/Sema/TypeCheckCodeCompletion.cpp
  lib/Sema/TypeCheckConstraints.cpp
  lib/Sema/TypeCheckEffects.cpp
  lib/Sema/TypeChecker.h
  test/AutoDiff/SILOptimizer/differentiation_control_flow_diagnostics.swift
  test/Interpreter/statements.swift
  test/SILGen/foreach.swift
  test/SILGen/foreach_async.swift
  test/SILGen/statements.swift
  test/SILOptimizer/inline_addressor.swift
  test/decl/var/async_let.swift
  test/expr/closure/multi_statement.swift
  test/expr/unary/async_await.swift
  test/stmt/async.swift
  test/stmt/foreach.swift
Labels: r5.7

#59297 [cxx-interop] Fix a potential dangling pointer in `String(cxxString:)`
  stdlib/public/Cxx/String.swift
Labels: C++ Interop

#59257 [5.7][Parseable Output] Generate valid output for files of unknown types
  lib/Basic/ParseableOutput.cpp
  lib/FrontendTool/FrontendTool.cpp
  test/Frontend/parseable_output_unknown_file_type.swift
Labels: r5.7

#59152 [cxx-interop][SwiftCompilerSources] Fix conversion between `std::string` and `Swift.String`
  SwiftCompilerSources/Sources/Basic/Utils.swift
  SwiftCompilerSources/Sources/SIL/BasicBlock.swift
  SwiftCompilerSources/Sources/SIL/Function.swift
  SwiftCompilerSources/Sources/SIL/GlobalVariable.swift
  SwiftCompilerSources/Sources/SIL/Instruction.swift
  SwiftCompilerSources/Sources/SIL/Value.swift
  test/SILOptimizer/addr_escape_info.sil
  test/SILOptimizer/escape_info.sil
  test/SILOptimizer/ranges.sil
Labels: C++ Interop

#59325 RequirementMachine: Concrete contraction needs to substitute the parent type of a subject type sometimes [5.7]
  lib/AST/RequirementMachine/ConcreteContraction.cpp
  lib/AST/RequirementMachine/MinimalConformances.cpp
  lib/Sema/TypeCheckType.cpp
  test/Generics/rdar94150249.swift
Labels: r5.7

#59340 [cxx-interop] Fix libstdc++ build failure on CentOS 7
  stdlib/public/Cxx/libstdcxx.h
Labels: C++ Interop

#59345 [cxx-interop] Fix assertion failure when looking up C++ operators
  lib/ClangImporter/ClangImporter.cpp
  test/Interop/Cxx/operators/non-member-inline-typechecker.swift
Labels: C++ Interop

#59318 [interop][SwiftToCxx] pass / return Swift struct values between C/C++…
  include/swift/IRGen/IRABIDetailsProvider.h
  lib/IRGen/IRABIDetailsProvider.cpp
  lib/PrintAsClang/ClangSyntaxPrinter.cpp
  lib/PrintAsClang/ClangSyntaxPrinter.h
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/ModuleContentsWriter.cpp
  lib/PrintAsClang/PrintAsClang.cpp
  lib/PrintAsClang/PrintClangFunction.cpp
  lib/PrintAsClang/PrintClangFunction.h
  lib/PrintAsClang/PrintClangValueType.cpp
  lib/PrintAsClang/PrintClangValueType.h
  lib/PrintAsClang/SwiftToClangInteropContext.cpp
  lib/PrintAsClang/SwiftToClangInteropContext.h
  test/Inputs/clang-importer-sdk/usr/include/string.h
  test/Interop/SwiftToC/structs/large-structs-pass-return-indirect-in-c-execution.c
  test/Interop/SwiftToC/structs/large-structs-pass-return-indirect-in-c.swift
  test/Interop/SwiftToC/structs/small-structs-64-bit-pass-return-direct-in-c.swift
  test/Interop/SwiftToC/structs/small-structs-pass-return-direct-in-c-execution.c
  test/Interop/SwiftToC/structs/small-structs-pass-return-direct-in-c.swift
  test/Interop/SwiftToCxx/structs/large-structs-pass-return-indirect-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/large-structs-pass-return-indirect-in-cxx.swift
  test/Interop/SwiftToCxx/structs/small-structs-pass-return-direct-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/small-structs-pass-return-direct-in-cxx.swift
  test/Interop/SwiftToCxx/structs/swift-struct-in-cxx.swift
  test/Interop/lit.local.cfg
  test/PrintAsCxx/empty.swift
Labels: C++ Interop

#59364 [interop][swiftToCxx] NFC, refactor out the code to print C++ impl class names and C s…
  lib/PrintAsClang/ClangSyntaxPrinter.cpp
  lib/PrintAsClang/ClangSyntaxPrinter.h
  lib/PrintAsClang/PrintClangValueType.cpp
Labels: C++ Interop

#59353 Revert "Revert "[cxx-interop][SwiftCompilerSources] Fix conversion between `std::string` and `Swift.String`""
  SwiftCompilerSources/Sources/Basic/Utils.swift
  SwiftCompilerSources/Sources/SIL/BasicBlock.swift
  SwiftCompilerSources/Sources/SIL/Function.swift
  SwiftCompilerSources/Sources/SIL/GlobalVariable.swift
  SwiftCompilerSources/Sources/SIL/Instruction.swift
  SwiftCompilerSources/Sources/SIL/Value.swift
  test/SILOptimizer/addr_escape_info.sil
  test/SILOptimizer/escape_info.sil
  test/SILOptimizer/ranges.sil
Labels: C++ Interop

#59292 [cxx-interop] Don't expose async or @_alwaysEmitIntoClient functions
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  test/Interop/SwiftToCxx/functions/swift-no-expose-unsupported-alwaysEmitInClient-func.swift
  test/Interop/SwiftToCxx/functions/swift-no-expose-unsupported-async-func.swift
  test/Interop/SwiftToCxx/functions/swift-transparent-functions-cxx-bridging.swift
  test/Interop/SwiftToCxx/functions/swift-transparent-functions-execution.cpp
Labels: C++ Interop

#59343 [5.7][TypeChecker/CodeCompletion] Re-introduce expression sanitization bef…
  lib/Sema/TypeCheckCodeCompletion.cpp
  validation-test/IDE/stress_tester_issues_fixed/rdar94619388.swift
Labels: r5.7

#59373 [nfc][cxx-interop] Remove brittle, special-case code for old operator implementation; add a test.
  include/swift/SIL/AbstractionPattern.h
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImporterImpl.h
  lib/SIL/IR/AbstractionPattern.cpp
  lib/SIL/IR/SILFunctionType.cpp
Labels: C++ Interop

#59362 🍒 [5.7] Update recent changelog entry to mention an edge-case source break
  CHANGELOG.md
Labels: r5.7

#59406 [interop][SwiftToCxx] emit swift type metadata access function declar…
  include/swift/IRGen/IRABIDetailsProvider.h
  lib/IRGen/IRABIDetailsProvider.cpp
  lib/PrintAsClang/CMakeLists.txt
  lib/PrintAsClang/ClangSyntaxPrinter.cpp
  lib/PrintAsClang/ClangSyntaxPrinter.h
  lib/PrintAsClang/ModuleContentsWriter.cpp
  lib/PrintAsClang/PrintClangValueType.cpp
  lib/PrintAsClang/PrintSwiftToClangCoreScaffold.cpp
  lib/PrintAsClang/PrintSwiftToClangCoreScaffold.h
  test/Interop/SwiftToCxx/core/swift-impl-defs-in-cxx-64-bit.swift
  test/Interop/SwiftToCxx/core/swift-impl-defs-in-cxx.swift
  test/Interop/SwiftToCxx/structs/swift-struct-in-cxx.swift
  test/PrintAsCxx/empty.swift
Labels: C++ Interop

#59404 [Distributed] cleanup existential check in SerReq checking
  lib/AST/DistributedDecl.cpp
Labels: Distributed

#42349 🍒[5.7][Distributed] Require that SerReq can only be used with protocols
  include/swift/AST/DiagnosticsSema.def
  lib/AST/DistributedDecl.cpp
  lib/Sema/TypeCheckDistributed.cpp
  lib/Sema/TypeCheckDistributed.h
  lib/Sema/TypeCheckProtocol.cpp
  test/Distributed/distributed_serializationRequirement_must_be_protocol.swift
Labels: Distributed, r5.7, pending-approval

#59411 [5.7] Sema: Infer the availability of extensions using the extended type instead of just the nominal
  lib/Sema/TypeCheckAvailability.cpp
  test/Incremental/Verifier/single-file-private/AnyObject.swift
  test/attr/attr_inlinable_available.swift
Labels: r5.7

#59358 [Distributed] Fix too restrictive distributed witness isolation checking
  include/swift/AST/Decl.h
  lib/AST/Decl.cpp
  lib/Sema/TypeCheckProtocol.cpp
  test/Distributed/Runtime/distributed_actor_local_only_witness_and_call.swift
  test/Distributed/distributed_protocol_isolation.swift
Labels: Distributed

#59397 🍒[5.7][Distributed] Fix too restrictive distributed witness isolation checking
  include/swift/AST/Decl.h
  lib/AST/Decl.cpp
  lib/Sema/TypeCheckProtocol.cpp
  test/Distributed/Runtime/distributed_actor_local_only_witness_and_call.swift
  test/Distributed/distributed_protocol_isolation.swift
Labels: Distributed, r5.7

#59435 SILOptimizer: Fix invariant violation in getWitnessMethodSubstitutions() with class witness methods [5.7]
  lib/SILOptimizer/Utils/Devirtualize.cpp
  test/SILOptimizer/devirt_class_witness_method_generic.swift
Labels: r5.7

#59418 [interop][SwiftToCxx] Pass struct to function as inout
  lib/PrintAsClang/PrintClangFunction.cpp
  lib/PrintAsClang/PrintClangValueType.cpp
  lib/PrintAsClang/PrintClangValueType.h
  test/Interop/SwiftToCxx/functions/swift-primitive-inout-functions-cxx-bridging.swift
  test/Interop/SwiftToCxx/functions/swift-primitive-inout-functions-execution.cpp
  test/Interop/SwiftToCxx/structs/large-structs-pass-return-indirect-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/large-structs-pass-return-indirect-in-cxx.swift
  test/Interop/SwiftToCxx/structs/small-structs-pass-return-direct-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/small-structs-pass-return-direct-in-cxx.swift
Labels: C++ Interop

#59438 [interop][SwiftToCxx] NFC, rename printStructDecl to printValueTypeDecl
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/PrintClangValueType.cpp
  lib/PrintAsClang/PrintClangValueType.h
Labels: C++ Interop

#59442 [cxx-interop] Re-enable C++ stdlib overlay on Linux
  lib/ClangImporter/ClangImporter.cpp
  stdlib/public/Cxx/CMakeLists.txt
  test/Interop/Cxx/stdlib/overlay/string.swift
Labels: C++ Interop

#59445 [interop][SwiftToCxx] emit instance property getters for structs
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/ModuleContentsWriter.cpp
  lib/PrintAsClang/PrintAsClang.cpp
  lib/PrintAsClang/PrintClangFunction.cpp
  lib/PrintAsClang/PrintClangFunction.h
  lib/PrintAsClang/PrintClangValueType.cpp
  lib/PrintAsClang/PrintClangValueType.h
  test/Interop/SwiftToC/functions/swift-function-argument-keyword-in-c.swift
  test/Interop/SwiftToCxx/functions/swift-function-argument-keyword-in-cxx.swift
  test/Interop/SwiftToCxx/properties/getter-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/properties/getter-in-cxx.swift
  test/Interop/SwiftToCxx/structs/swift-struct-in-cxx.swift
  test/PrintAsCxx/empty.swift
Labels: C++ Interop

#59437 [5.7][Diagnostics] Diagnose conflicting pattern variables
  include/swift/Sema/CSFix.h
  lib/Sema/CSClosure.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSSimplify.cpp
  test/expr/closure/multi_statement.swift
Labels: r5.7

#59460 [Distributed] Be able to synthesize actorSystem prop from request
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/DerivedConformances.cpp
Labels: Distributed

#59478 [interop][SwiftToCxx] place ptrauth attribute on the function type it…
  lib/PrintAsClang/PrintSwiftToClangCoreScaffold.cpp
  test/Interop/SwiftToCxx/core/swift-impl-defs-in-cxx.swift
Labels: C++ Interop

#59461 [interop][SwiftToCxx] emit non-mutating instance methods for structs
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/PrintClangFunction.cpp
  lib/PrintAsClang/PrintClangFunction.h
  test/Interop/SwiftToCxx/methods/method-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/methods/method-in-cxx.swift
Labels: C++ Interop

#59462 [cxx-interop][SwiftCompilerSources] Workaround for `std::string` crash on arm64 Linux
  SwiftCompilerSources/Sources/SIL/BasicBlock.swift
  SwiftCompilerSources/Sources/SIL/Function.swift
  SwiftCompilerSources/Sources/SIL/GlobalVariable.swift
  SwiftCompilerSources/Sources/SIL/Instruction.swift
  SwiftCompilerSources/Sources/SIL/Value.swift
  test/SILOptimizer/addr_escape_info.sil
  test/SILOptimizer/escape_info.sil
  test/SILOptimizer/ranges.sil
Labels: C++ Interop

#59465 [cxx-interop] Import iterator dereference operators
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/operators/Inputs/member-inline.h
  test/Interop/Cxx/operators/member-inline-module-interface.swift
  test/Interop/Cxx/operators/member-inline.swift
Labels: C++ Interop

#59459 🍒[5.7][Distributed] Be able to synthesize actorSystem prop from request
  lib/AST/DistributedDecl.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/DerivedConformances.cpp
Labels: Distributed, r5.7

#59513 Use the distributed thunk for non-distributed protocol requirements
  lib/SIL/IR/SILDeclRef.cpp
  lib/SILGen/SILGenPoly.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  test/SILGen/distributed_thunk.swift
Labels: Distributed

#59482 [interop][SwiftToCxx] Add support for emitting resilient struct bindings
  lib/PrintAsClang/ClangSyntaxPrinter.cpp
  lib/PrintAsClang/ClangSyntaxPrinter.h
  lib/PrintAsClang/PrintAsClang.cpp
  lib/PrintAsClang/PrintClangFunction.cpp
  lib/PrintAsClang/PrintClangValueType.cpp
  lib/PrintAsClang/PrintSwiftToClangCoreScaffold.cpp
  test/Inputs/clang-importer-sdk/usr/include/stdlib.h
  test/Interop/SwiftToCxx/core/swift-impl-defs-in-cxx.swift
  test/Interop/SwiftToCxx/structs/resilient-struct-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/resilient-struct-in-cxx.swift
  test/PrintAsCxx/empty.swift
Labels: C++ Interop

#59510 [cxx-interop] Remove "enable-cxx-interop" flag again.
  SwiftCompilerSources/CMakeLists.txt
  SwiftCompilerSources/Package.swift
  include/swift/Option/FrontendOptions.td
  lib/Frontend/CompilerInvocation.cpp
Labels: C++ Interop

#59511 [5.7] Runtime Casting for Extended Existentials
  include/swift/ABI/MetadataValues.h
  lib/IRGen/GenCast.cpp
  lib/SIL/Utils/DynamicCasts.cpp
  stdlib/public/runtime/Demangle.cpp
  stdlib/public/runtime/DynamicCast.cpp
  stdlib/public/runtime/MetadataLookup.cpp
  stdlib/public/runtime/Private.h
  test/Casting/ParameterizedExistentials.swift
  test/Interpreter/parameterized_existentials.swift
Labels: r5.7

#59421 [c++-interop] Providing information about enum types from inferDefaultArgument
  include/swift/AST/Decl.h
  include/swift/AST/DefaultArgumentKind.h
  lib/ClangImporter/ImportName.cpp
  lib/ClangImporter/ImportType.cpp
  lib/ClangImporter/ImporterImpl.h
  test/Interop/Cxx/enum/Inputs/c-enums-withOptions-omit.h
  test/Interop/Cxx/enum/c-enums-withOptions-omit.swift
Labels: C++ Interop

#59514 Use the distributed thunk for non-distributed protocol requirements
  lib/SIL/IR/SILDeclRef.cpp
  lib/SILGen/SILGenPoly.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  test/SILGen/distributed_thunk.swift
Labels: Distributed, r5.7

#59439 [cxx-interop] Runtime support for foreign reference types.
  include/swift/ABI/Metadata.h
  include/swift/ABI/MetadataKind.def
  include/swift/Remote/MetadataReader.h
  lib/IRGen/ForeignClassMetadataVisitor.h
  lib/IRGen/GenMeta.cpp
  lib/IRGen/GenProto.cpp
  lib/IRGen/GenReflection.cpp
  lib/IRGen/MetadataRequest.cpp
  stdlib/public/runtime/AnyHashableSupport.cpp
  stdlib/public/runtime/Casting.cpp
  stdlib/public/runtime/Demangle.cpp
  stdlib/public/runtime/ErrorObject.mm
  stdlib/public/runtime/FoundationSupport.cpp
  stdlib/public/runtime/Metadata.cpp
  stdlib/public/runtime/ProtocolConformance.cpp
  stdlib/public/runtime/ReflectionMirror.cpp
  test/Interop/Cxx/foreign-reference/error-in-generic-context.swift
  test/Interop/Cxx/foreign-reference/witness-table.swift
Labels: C++ Interop

#59530 [ClangImporter] NFC: extract Swift decl synthesis logic into a separate file
  lib/ClangImporter/CMakeLists.txt
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImportMacro.cpp
  lib/ClangImporter/ImporterImpl.h
  lib/ClangImporter/SwiftDeclSynthesizer.cpp
  lib/ClangImporter/SwiftDeclSynthesizer.h
Labels: C++ Interop

#59529 [interop][SwiftToCxx] support mutating struct methods in C++
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/PrintClangFunction.cpp
  lib/PrintAsClang/PrintClangFunction.h
  test/Interop/SwiftToCxx/methods/mutating-method-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/methods/mutating-method-in-cxx.swift
Labels: C++ Interop

#59518 [5.7][Parse] Set missing contextual keyword token kind for `async`
  lib/Parse/ParsePattern.cpp
  test/IDE/coloring.swift
  test/SourceKit/SyntaxMapData/Inputs/syntaxmap.swift
  test/SourceKit/SyntaxMapData/syntaxmap.swift.response
  unittests/Syntax/TypeSyntaxTests.cpp
  utils/gyb_syntax_support/DeclNodes.py
  utils/gyb_syntax_support/ExprNodes.py
  utils/gyb_syntax_support/TypeNodes.py
Labels: r5.7

#59536 [5.7][Diagnostics] Diagnose a mismatch between result builder result and return type
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/CSDiagnostics.cpp
  test/Constraints/result_builder_diags.swift
Labels: r5.7

#59537 [5.7][ConstraintSystem] Use '# of overloads' as a tie-breaker in ambiguities
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/diag_ambiguities.swift
  test/expr/expressions.swift
Labels: r5.7

#59481 [TypeChecker] Implement distributed computed properties
  include/swift/AST/ASTMangler.h
  include/swift/AST/Attr.def
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/Expr.h
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/AST/ASTDumper.cpp
  lib/AST/ASTMangler.cpp
  lib/AST/Decl.cpp
  lib/AST/DistributedDecl.cpp
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenDistributed.cpp
  lib/SILGen/SILGenFunction.h
  lib/SILGen/SILGenLValue.cpp
  lib/SILGen/SILGenType.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  lib/Sema/TypeCheckDeclOverride.cpp
  lib/Sema/TypeCheckDistributed.cpp
  lib/Sema/TypeCheckEffects.cpp
  stdlib/public/Distributed/DistributedActorSystem.swift
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_computedProperty.swift
  test/Distributed/distributed_actor_isolation.swift
  test/Distributed/distributed_actor_var_implicitly_async_throws.swift
Labels: Distributed

#59547 [interop][SwiftToCxx] emit struct initializers
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/PrintClangFunction.cpp
  lib/PrintAsClang/PrintClangFunction.h
  test/Interop/SwiftToCxx/initializers/init-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/initializers/init-in-cxx.swift
  test/Interop/SwiftToCxx/properties/getter-in-cxx.swift
Labels: C++ Interop

#59557 RequirementMachine: Relax assertion in verifyRewriteSystem() [5.7]
  lib/AST/RequirementMachine/RewriteSystem.cpp
  test/Generics/rdar94854326.swift
  test/Generics/rdar94980084.swift
Labels: r5.7

#59553 [5.7] Use platform versions in getSwift57Availability.
  lib/AST/Availability.cpp
Labels: r5.7

#59551 [cxx-interop] Import increment operators
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImportName.cpp
  lib/ClangImporter/SwiftDeclSynthesizer.cpp
  lib/ClangImporter/SwiftDeclSynthesizer.h
  test/Interop/Cxx/operators/Inputs/member-inline.h
  test/Interop/Cxx/operators/member-inline-module-interface.swift
  test/Interop/Cxx/operators/member-inline-typechecker.swift
  test/Interop/Cxx/operators/member-inline.swift
Labels: C++ Interop

#59559 Sema: Fix capture lifetime issue in protocol conformance sendable mismatch [5.7]
  lib/Sema/TypeCheckProtocol.cpp
  test/Concurrency/sendable_witness_check_delayed.swift
Labels: r5.7

#58475 🍒[5.7][Concurrency] Explicitly ban a class extending AnyActor as well
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/KnownProtocols.def
  lib/IRGen/GenMeta.cpp
  lib/Sema/TypeCheckProtocol.cpp
  stdlib/public/Concurrency/Actor.cpp
  test/Concurrency/actor_isolation.swift
  test/Distributed/actor_protocols.swift
  test/decl/class/actor/basic.swift
  test/decl/protocol/special/Actor.swift
Labels: Distributed, r5.7

#58473 [Concurrency] Explicitly ban a class extending AnyActor as well
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/KnownProtocols.def
  lib/IRGen/GenMeta.cpp
  lib/Sema/TypeCheckProtocol.cpp
  stdlib/public/Concurrency/Actor.cpp
  test/Concurrency/actor_isolation.swift
  test/Distributed/actor_protocols.swift
  test/decl/class/actor/basic.swift
  test/decl/protocol/special/Actor.swift
Labels: Concurrency, Distributed

#59563 🍒[5.7][Distributed] Implement distributed computed properties
  include/swift/AST/ASTMangler.h
  include/swift/AST/Attr.def
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/Expr.h
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/AST/ASTDumper.cpp
  lib/AST/ASTMangler.cpp
  lib/AST/Decl.cpp
  lib/AST/DistributedDecl.cpp
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenDistributed.cpp
  lib/SILGen/SILGenFunction.h
  lib/SILGen/SILGenLValue.cpp
  lib/SILGen/SILGenType.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  lib/Sema/TypeCheckDeclOverride.cpp
  lib/Sema/TypeCheckDistributed.cpp
  lib/Sema/TypeCheckEffects.cpp
  stdlib/public/Distributed/DistributedActorSystem.swift
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_computedProperty.swift
  test/Distributed/distributed_actor_isolation.swift
  test/Distributed/distributed_actor_var_implicitly_async_throws.swift
Labels: Distributed, r5.7

#58699 [cxx-interop][SwiftCompilerSources] Use `swift::SourceLoc` instead of `BridgedSourceLoc`
  SwiftCompilerSources/CMakeLists.txt
  SwiftCompilerSources/Package.swift
  SwiftCompilerSources/Sources/AST/DiagnosticEngine.swift
  SwiftCompilerSources/Sources/Basic/SourceLoc.swift
  SwiftCompilerSources/Sources/Parse/Regex.swift
  include/swift/AST/ASTBridging.h
  include/swift/Basic/BasicBridging.h
  include/swift/Basic/BridgingUtils.h
  include/swift/Parse/RegexParserBridging.h
  lib/AST/ASTBridging.cpp
  lib/Parse/ParseRegex.cpp
Labels: C++ Interop

#59607 [CXX Interoperability] Stop re-importing FuncDecl when FuncDecl is imported before parent record
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/operators/Inputs/member-inline.h
  test/Interop/Cxx/operators/member-inline.swift
Labels: C++ Interop

#59622 [interop][SwiftToCxx] NFC, add a test case for emitting @frozen structs
  test/Interop/SwiftToCxx/structs/resilient-struct-in-cxx.swift
  test/Interop/SwiftToCxx/structs/small-structs-pass-return-direct-in-cxx.swift
Labels: C++ Interop

#59642 [5.7] [Parse] Avoid skipping bodies with `/.../` regex literals
  include/swift/AST/DiagnosticEngine.h
  include/swift/Parse/Lexer.h
  include/swift/Parse/Parser.h
  lib/Parse/Lexer.cpp
  lib/Parse/ParseDecl.cpp
  lib/Parse/ParseExpr.cpp
  test/StringProcessing/Parse/forward-slash-regex-skipping-allowed.swift
  test/StringProcessing/Parse/forward-slash-regex-skipping-invalid.swift
  test/StringProcessing/Parse/forward-slash-regex-skipping.swift
Labels: r5.7

#59627 [Distributed] Unlock test which was ASAN failures in the past
  test/Distributed/Runtime/distributed_actor_in_other_module.swift
Labels: Distributed

#59646 RequirementMachine: Don't filter out unavailable Sendable conformance if allowMissing=true [5.7]
  lib/AST/ProtocolConformance.cpp
  lib/AST/RequirementMachine/ConcreteContraction.cpp
  lib/AST/RequirementMachine/ConcreteTypeWitness.cpp
  test/Generics/conditional_conformance_sendable.swift
Labels: r5.7

#59652 Mark SwiftToCxx execution tests as unsupported on arm64e for now
  test/Interop/SwiftToCxx/initializers/init-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/methods/method-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/methods/mutating-method-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/properties/getter-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/large-structs-pass-return-indirect-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/resilient-struct-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/small-structs-pass-return-direct-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/struct-with-refcounted-member-execution.cpp
Labels: C++ Interop

#59663 [cxx-interop] Add tests for `operator++()` that returns `void`
  test/Interop/Cxx/operators/Inputs/member-inline.h
  test/Interop/Cxx/operators/member-inline-module-interface.swift
  test/Interop/Cxx/operators/member-inline-typechecker.swift
  test/Interop/Cxx/operators/member-inline.swift
Labels: C++ Interop

#59654 [5.7][Sema] Diagnose redundant any on existential type
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckType.cpp
  test/type/explicit_existential.swift
Labels: r5.7

#59648 stdlib: Add SIMDMaskScalar.SIMDMaskScalar == SIMDMaskScalar requirement to SIMDScalar [5.7]
  stdlib/public/core/SIMDVector.swift
  test/Generics/rdar95075552.swift
  test/api-digester/Outputs/stability-stdlib-source-x86_64.swift.expected
  test/api-digester/stability-stdlib-abi-without-asserts.test
Labels: r5.7

#59196 [5.7][build-script] Cross-compile sourcekit-lsp for arm64
  utils/swift_build_support/swift_build_support/products/indexstoredb.py
  utils/swift_build_support/swift_build_support/products/product.py
  utils/swift_build_support/swift_build_support/products/swiftdriver.py
  utils/swift_build_support/swift_build_support/products/swiftpm.py
Labels: r5.7

#59658 [Distributed] Unlock test which was ASAN failures in the past (2)
  test/Distributed/Runtime/distributed_actor_localSystem.swift
Labels: Distributed

#41843 [SE-0358][stdlib] Adopt primary associated types
  stdlib/public/Concurrency/Clock.swift
  stdlib/public/core/BidirectionalCollection.swift
  stdlib/public/core/Collection.swift
  stdlib/public/core/CompilerProtocols.swift
  stdlib/public/core/Identifiable.swift
  stdlib/public/core/Instant.swift
  stdlib/public/core/LazyCollection.swift
  stdlib/public/core/LazySequence.swift
  stdlib/public/core/MutableCollection.swift
  stdlib/public/core/RandomAccessCollection.swift
  stdlib/public/core/Range.swift
  stdlib/public/core/RangeReplaceableCollection.swift
  stdlib/public/core/SIMDVector.swift
  stdlib/public/core/Sequence.swift
  stdlib/public/core/SetAlgebra.swift
  stdlib/public/core/Stride.swift
Labels: swift-evolution-pending-discussion

#59699 [Distributed] Revert "#59481 distributed-computed-properties"
  include/swift/AST/ASTMangler.h
  include/swift/AST/Attr.def
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/Expr.h
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/AST/ASTDumper.cpp
  lib/AST/ASTMangler.cpp
  lib/AST/DistributedDecl.cpp
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenDistributed.cpp
  lib/SILGen/SILGenFunction.h
  lib/SILGen/SILGenLValue.cpp
  lib/SILGen/SILGenType.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  lib/Sema/TypeCheckDeclOverride.cpp
  lib/Sema/TypeCheckDistributed.cpp
  lib/Sema/TypeCheckEffects.cpp
  stdlib/public/Distributed/DistributedActorSystem.swift
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_computedProperty.swift
  test/Distributed/distributed_actor_isolation.swift
  test/Distributed/distributed_actor_var_implicitly_async_throws.swift
Labels: Distributed

#59701 🍒[5.7][Distributed] Revert "#59481 distributed-computed-properties"
  include/swift/AST/ASTMangler.h
  include/swift/AST/Attr.def
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/Expr.h
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/AST/ASTDumper.cpp
  lib/AST/ASTMangler.cpp
  lib/AST/DistributedDecl.cpp
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenDistributed.cpp
  lib/SILGen/SILGenFunction.h
  lib/SILGen/SILGenLValue.cpp
  lib/SILGen/SILGenType.cpp
  lib/Sema/CSApply.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  lib/Sema/TypeCheckDeclOverride.cpp
  lib/Sema/TypeCheckDistributed.cpp
  lib/Sema/TypeCheckEffects.cpp
  stdlib/public/Distributed/DistributedActorSystem.swift
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_computedProperty.swift
  test/Distributed/distributed_actor_isolation.swift
  test/Distributed/distributed_actor_var_implicitly_async_throws.swift
Labels: Distributed, r5.7

#59669 [Interop][SwiftToCxx] Emit helper cases class in C++ for Swift enum
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  test/Interop/SwiftToCxx/enums/swift-enum-cases-in-cxx.swift
Labels: C++ Interop

#59697 [cxx-interop] Record extra layer of indirection when calculating clang type from SILType.
  lib/IRGen/GenCall.cpp
  lib/IRGen/GenClangType.cpp
  test/Interop/Cxx/foreign-reference/Inputs/move-only.h
  test/Interop/Cxx/foreign-reference/move-only.swift
Labels: C++ Interop

#59679 [lldb][cxx-interop] Tell LLDB about the extra layer of indireciton for foriegn reference types.
  lib/IRGen/IRGenDebugInfo.cpp
Labels: C++ Interop

#59613 [cxx-interop] Allow conforming C++ APIs that return IUO to Swift protocols
  lib/Sema/TypeCheckProtocol.cpp
  test/Interop/Cxx/class/Inputs/protocol-conformance.h
  test/Interop/Cxx/class/protocol-conformance-typechecker.swift
Labels: C++ Interop

#59645 [5.7][stdlib] use @_transparent in an appropriate spot
  stdlib/public/core/Optional.swift
Labels: r5.7, Standard Library

#59724 [5.7][PreCheckExpr] Don't silence errors while resolving types for 'litera…
  lib/Sema/PreCheckExpr.cpp
  lib/Sema/TypeCheckType.cpp
  test/Sema/diag_erroneous_iuo.swift
  test/type/types.swift
Labels: r5.7

#59733 [5.7] TempRValueOpt: don't move `end_access` instructions after a terminator instruction.
  lib/SILOptimizer/Transforms/TempRValueElimination.cpp
  test/SILOptimizer/temp_rvalue_opt_ossa.sil
Labels: r5.7

#59492 [cxx-interop] Add `CxxSequence` protocol to the stdlib overlay
  stdlib/public/Cxx/CMakeLists.txt
  stdlib/public/Cxx/CxxSequence.swift
  test/Interop/Cxx/stdlib/overlay/Inputs/custom-sequence.h
  test/Interop/Cxx/stdlib/overlay/Inputs/module.modulemap
  test/Interop/Cxx/stdlib/overlay/custom-sequence-typechecker.swift
  test/Interop/Cxx/stdlib/overlay/custom-sequence.swift
  test/Interop/Cxx/stdlib/overlay/std-string-overlay.swift
  test/Interop/Cxx/stdlib/overlay/string.swift
  validation-test/ParseableInterface/verify_all_overlays.py
Labels: C++ Interop

#59670 [5.7] [Parse] Fix code completion crash when avoiding skipping
  lib/Parse/ParseDecl.cpp
  test/SourceKit/CodeComplete/rdar95772803.swift
Labels: r5.7

#59747 [cxx-interop] Split C++ stdlib overlay into two modules
  stdlib/public/Cxx/CMakeLists.txt
  stdlib/public/Cxx/std/CMakeLists.txt
  stdlib/public/Cxx/std/String.swift
  stdlib/public/Cxx/std/libstdcxx.h
  stdlib/public/Cxx/std/libstdcxx.modulemap
  stdlib/public/Cxx/std/std.swift
  test/Interop/Cxx/stdlib/overlay/custom-sequence-typechecker.swift
  test/Interop/Cxx/stdlib/overlay/custom-sequence.swift
Labels: C++ Interop

#59728 Add CHANGELOG entry for redundant requirement warnings being disabled by default [5.7]
  CHANGELOG.md
Labels: r5.7

#59766 [5.7][TypeChecker] Don’t crash if a `ExplicitCastExpr` doesn’t have a cast type
  lib/Sema/TypeCheckAvailability.cpp
  validation-test/compiler_crashers_2_fixed/rdar95629905.swift
Labels: r5.7

#59779 [5.7] [Sema] Add fix-it to import RegexBuilder
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/KnownIdentifiers.def
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  test/StringProcessing/Sema/Inputs/dummy.swift
  test/StringProcessing/Sema/regex_builder_already_imported.swift
  test/StringProcessing/Sema/regex_builder_fix_import_after_imports.swift
  test/StringProcessing/Sema/regex_builder_fix_import_decl.swift
  test/StringProcessing/Sema/regex_builder_fix_import_top_level.swift
Labels: r5.7

#59769 [5.7][IRGen] Use existential AnyObject throughout IRGen.
  lib/IRGen/GenReflection.cpp
  lib/IRGen/MetadataRequest.cpp
  lib/SIL/IR/TypeLowering.cpp
Labels: r5.7

#59778 [5.7] [Parse] Ban trailing space for `/.../` regex literals
  include/swift/AST/DiagnosticsParse.def
  lib/Parse/Lexer.cpp
  test/StringProcessing/Parse/forward-slash-regex-skipping-allowed.swift
  test/StringProcessing/Parse/forward-slash-regex-skipping-invalid.swift
  test/StringProcessing/Parse/forward-slash-regex-skipping.swift
  test/StringProcessing/Parse/forward-slash-regex.swift
  test/StringProcessing/Parse/prefix-slash.swift
  test/StringProcessing/Sema/regex_literal_diagnostics.swift
Labels: r5.7

#59764 [Cxx] Make C++ flags configurable for Linux SDK
  cmake/modules/SwiftConfigureSDK.cmake
  stdlib/public/Cxx/std/CMakeLists.txt
Labels: C++ Interop

#59784 [5.7][TypeChecker] Adjust Double<->CGFloat conversion to always preserve its location
  include/swift/Sema/ConstraintSystem.h
  lib/Sema/CSApply.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/implicit_double_cgfloat_conversion.swift
  test/Constraints/overload_filtering_objc.swift
Labels: r5.7

#59783 [5.7][AST] Teach `computeNominalType` about nested ObjC protocols
  lib/AST/Decl.cpp
  test/ClangImporter/Inputs/nested_protocol_name.h
  test/ClangImporter/nested_protocol_name.swift
Labels: r5.7

#59694 [5.7][SE-0358][stdlib] Adopt primary associated types
  stdlib/public/Concurrency/Clock.swift
  stdlib/public/core/BidirectionalCollection.swift
  stdlib/public/core/Collection.swift
  stdlib/public/core/CompilerProtocols.swift
  stdlib/public/core/Identifiable.swift
  stdlib/public/core/Instant.swift
  stdlib/public/core/LazyCollection.swift
  stdlib/public/core/LazySequence.swift
  stdlib/public/core/MutableCollection.swift
  stdlib/public/core/RandomAccessCollection.swift
  stdlib/public/core/Range.swift
  stdlib/public/core/RangeReplaceableCollection.swift
  stdlib/public/core/SIMDVector.swift
  stdlib/public/core/Sequence.swift
  stdlib/public/core/SetAlgebra.swift
  stdlib/public/core/Stride.swift
Labels: swift-evolution-approved, r5.7, Standard Library

#59789 [5.7] [stdlib] Fix the name mangling for UnsafeMutableRawPointer.storeBytes
  stdlib/public/core/UnsafeRawPointer.swift
Labels: r5.7, Standard Library

#59794 Sema: Check conditional requirements in inferTypeWitnessesViaValueWitnesses() [5.7]
  lib/Sema/TypeCheckProtocolInference.cpp
  test/decl/protocol/req/associated_type_protocol_extension.swift
  test/decl/protocol/req/missing_conformance.swift
Labels: r5.7

#59797 [stdlib] Improve the mangled names of some @_alwaysEmitIntoClient functions
  stdlib/public/core/UnsafeBufferPointer.swift.gyb
  stdlib/public/core/UnsafePointer.swift
  stdlib/public/core/UnsafeRawBufferPointer.swift.gyb
  stdlib/public/core/UnsafeRawPointer.swift
Labels: Standard Library

#59700 [Distributed] Implement distributed computed properties via special accessor
  include/swift/AST/ASTMangler.h
  include/swift/AST/Attr.def
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/Expr.h
  include/swift/AST/StorageImpl.h
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/AST/ASTDumper.cpp
  lib/AST/ASTMangler.cpp
  lib/AST/Decl.cpp
  lib/AST/DistributedDecl.cpp
  lib/SILGen/SILGen.cpp
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenDistributed.cpp
  lib/SILGen/SILGenExpr.cpp
  lib/SILGen/SILGenFunction.h
  lib/SILGen/SILGenLValue.cpp
  lib/SILGen/SILGenType.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  lib/Sema/TypeCheckDeclOverride.cpp
  lib/Sema/TypeCheckDistributed.cpp
  lib/Serialization/Deserialization.cpp
  lib/Serialization/ModuleFormat.h
  lib/Serialization/Serialization.cpp
  stdlib/public/Distributed/DistributedActorSystem.swift
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_computedProperty.swift
  test/Distributed/distributed_actor_isolation.swift
  test/Distributed/distributed_actor_var_implicitly_async_throws.swift
Labels: Distributed

#59759 🌸 Warn about async-imported selector conflicts
  lib/Sema/TypeCheckDeclObjC.cpp
  test/Concurrency/Inputs/Delegate.h
  test/Concurrency/objc_async_overload.swift
  test/decl/Inputs/objc_redeclaration_multi_2.swift
  test/decl/objc_redeclaration.swift
  test/decl/objc_redeclaration_multi.swift
  test/decl/protocol/objc.swift
Labels: r5.7

#59736 🍒[5.7][Distributed] Fixes to distributed funcs and protocols
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/DistributedDecl.h
  include/swift/SIL/SILDeclRef.h
  lib/AST/DistributedDecl.cpp
  lib/SILGen/SILGenPoly.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckAttr.cpp
  lib/Sema/TypeCheckDeclPrimary.cpp
  lib/Sema/TypeCheckDistributed.cpp
  lib/Sema/TypeChecker.h
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_through_generic.swift
  test/Distributed/distributed_actor_generic_actor_distributed_call.swift
  test/Distributed/distributed_actor_inference.swift
  test/Distributed/distributed_actor_protocol_isolation.swift
  test/Distributed/distributed_actor_system_missing.swift
  test/Distributed/distributed_protocol_isolation.swift
  test/Distributed/distributed_protocols_distributed_func_serialization_requirements.swift
  test/decl/protocol/special/DistributedActor.swift
Labels: Distributed, r5.7

#59810 [ClangImporter] NFC: extract Clang include path mapping logic into a separate file
  lib/ClangImporter/CMakeLists.txt
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ClangIncludePaths.cpp
  lib/ClangImporter/ClangIncludePaths.h
Labels: C++ Interop

#59777 [5.7] [test] Update a couple of regex diagnostic locations
  test/StringProcessing/Parse/regex_parse_error.swift
Labels: r5.7
