Repository swiftlang/swift, pull requests merged in 2022-07, with the labels that each got.

#59806 CHANGELOG: Sync 5.7 section with main
  CHANGELOG.md
Labels: r5.7

#59673 [5.7] Ignore Sendable conformances in PrintAsClang
  lib/PrintAsClang/ModuleContentsWriter.cpp
  test/PrintAsObjC/protocols.swift
Labels: r5.7

#59839 [IRGen] Emit missing `sret` for function arguments
  lib/IRGen/GenCall.cpp
  test/Interop/Cxx/class/Inputs/module.modulemap
  test/Interop/Cxx/class/Inputs/returns-large-class.h
  test/Interop/Cxx/class/returns-large-class-irgen.swift
  test/Interop/Cxx/class/returns-large-class.swift
  test/Interop/Cxx/operators/member-inline.swift
  test/SILOptimizer/addr_escape_info.sil
  test/SILOptimizer/escape_info.sil
  test/SILOptimizer/ranges.sil
Labels: C++ Interop

#59834 [5.7] Generalize the Mangling of Constrained Existential Types
  docs/ABI/Mangling.rst
  include/swift/AST/ASTDemangler.h
  include/swift/AST/ASTMangler.h
  include/swift/Demangling/DemangleNodes.def
  include/swift/Demangling/Demangler.h
  include/swift/Demangling/TypeDecoder.h
  include/swift/Reflection/TypeRef.h
  include/swift/Reflection/TypeRefBuilder.h
  include/swift/Reflection/TypeRefs.def
  lib/AST/ASTDemangler.cpp
  lib/AST/ASTMangler.cpp
  lib/Demangling/Demangler.cpp
  lib/Demangling/NodePrinter.cpp
  lib/Demangling/OldRemangler.cpp
  lib/Demangling/Remangler.cpp
  lib/IRGen/GenExistential.cpp
  lib/IRGen/IRGenMangler.cpp
  stdlib/public/Reflection/TypeLowering.cpp
  stdlib/public/Reflection/TypeRef.cpp
  stdlib/public/runtime/MetadataLookup.cpp
  test/Demangle/Inputs/manglings.txt
  test/IRGen/existential_shape_metadata.swift
  test/SILGen/parameterized_existentials.swift
  test/SILOptimizer/cast_folding_parameterized_protocol.swift
  unittests/runtime/SpecifierDSL.h
Labels: r5.7

#59596 🍒 [5.7] Sema, DiagQoI: Fix and tailor diagnosis of explicit closure result type conflicts
  include/swift/AST/DiagnosticsSema.def
  include/swift/Sema/ConstraintLocatorPathElts.def
  lib/Sema/CSDiagnostics.cpp
  test/Constraints/closures.swift
  test/Sema/substring_to_string_conversion_swift4.swift
Labels: r5.7

#59846 [Glibc] Use VFS to inject modulemap into Glibc include path
  include/swift/AST/DiagnosticsClangImporter.def
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ClangIncludePaths.cpp
  lib/ClangImporter/ClangIncludePaths.h
Labels: C++ Interop

#59877 [cxx-interop] Update tests for foreign reference types
  test/Interop/Cxx/foreign-reference/Inputs/move-only.h
  test/Interop/Cxx/foreign-reference/Inputs/nullable.h
  test/Interop/Cxx/foreign-reference/Inputs/pod.h
  test/Interop/Cxx/foreign-reference/Inputs/singleton.h
  test/Interop/Cxx/foreign-reference/Inputs/witness-table.h
Labels: C++ Interop

#59874 🍒 [5.7][Distributed] Remove dist requirement explicit async throws limitation
  include/swift/AST/ActorIsolation.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/DistributedDecl.h
  include/swift/SIL/SILWitnessVisitor.h
  lib/AST/ASTMangler.cpp
  lib/AST/Decl.cpp
  lib/AST/TypeCheckRequests.cpp
  lib/Parse/ParseDecl.cpp
  lib/SIL/IR/SILFunctionType.cpp
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenPoly.cpp
  lib/SILGen/SILGenType.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckAttr.cpp
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_through_generic.swift
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_through_generic_and_inner.swift
  test/Distributed/distributed_actor_inference.swift
  test/Distributed/distributed_actor_isolation.swift
  test/Distributed/distributed_actor_protocol_isolation.swift
  test/Distributed/distributed_protocol_isolation.swift
  test/Distributed/distributed_protocols_distributed_func_serialization_requirements.swift
  test/SILGen/distributed_thunk.swift
  test/decl/protocol/special/DistributedActor.swift
Labels: Distributed, r5.7

#59722 [3/3][Distributed] Remove dist requirement explicit async throws limitation
  include/swift/AST/ActorIsolation.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/DistributedDecl.h
  include/swift/SIL/SILWitnessVisitor.h
  lib/AST/ASTMangler.cpp
  lib/AST/Decl.cpp
  lib/AST/TypeCheckRequests.cpp
  lib/Parse/ParseDecl.cpp
  lib/SIL/IR/SILFunctionType.cpp
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenPoly.cpp
  lib/SILGen/SILGenType.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/TypeCheckAttr.cpp
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_through_generic.swift
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_through_generic_and_inner.swift
  test/Distributed/distributed_actor_inference.swift
  test/Distributed/distributed_actor_isolation.swift
  test/Distributed/distributed_actor_protocol_isolation.swift
  test/Distributed/distributed_protocol_isolation.swift
  test/Distributed/distributed_protocols_distributed_func_serialization_requirements.swift
  test/SILGen/distributed_thunk.swift
  test/decl/protocol/special/DistributedActor.swift
Labels: Distributed

#59830 [5.7][SE-0361] Enable bound generic extensions.
  include/swift/Basic/LangOptions.h
  include/swift/Option/FrontendOptions.td
  lib/Frontend/CompilerInvocation.cpp
  lib/Sema/TypeCheckDecl.cpp
  test/ModuleInterface/specialized-extension.swift
  test/SILGen/mangling_specialized_extensions.swift
  test/decl/ext/extensions.swift
  test/decl/ext/generic.swift
  test/decl/ext/specialize.swift
  test/decl/typealias/generic.swift
Labels: r5.7

#59737 [cxx-interop] Fix lazy member lookup for forward-declared structs inside of a namespace.
  lib/ClangImporter/SwiftLookupTable.cpp
  test/Interop/Cxx/class/Inputs/forward-declared-in-namespace.h
  test/Interop/Cxx/class/Inputs/module.modulemap
  test/Interop/Cxx/class/forward-declared-in-namespace-typechecker.swift
Labels: C++ Interop

#59896 [5.7] Revert "[TypeChecker] Adjust Double<->CGFloat conversion to always pr…
  include/swift/Sema/ConstraintSystem.h
  lib/Sema/CSApply.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/implicit_double_cgfloat_conversion.swift
Labels: r5.7

#59906 [cxx-interop] Avoid importing too complex specializations
  include/swift/AST/DiagnosticsClangImporter.def
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImporterImpl.h
Labels: C++ Interop

#59912 [5.7] [test] Update Regex type for flattened captures
  test/StringProcessing/Sema/regex_literal_type_inference.swift
Labels: r5.7

#59908 [cxx-interop][SwiftCompilerSources] Remove `getCopiedBridgedStringRef` and `freeBridgedStringRef`
  SwiftCompilerSources/Sources/Basic/Utils.swift
  SwiftCompilerSources/Sources/SIL/Type.swift
  include/swift/Basic/BridgingUtils.h
  include/swift/SIL/SILBridging.h
  lib/Basic/BasicBridging.cpp
  lib/SIL/Utils/SILBridging.cpp
Labels: C++ Interop

#59935 RequirementMachine: Relax assertions in verifyRewriteSystem() [5.7]
  lib/AST/RequirementMachine/RewriteSystem.cpp
  test/Generics/rdar94746399.swift
Labels: r5.7

#59907 [cxx-interop][SwiftCompilerSources] Use `swift::CharSourceRange` instead of `BridgedCharSourceRange`
  SwiftCompilerSources/Sources/AST/DiagnosticEngine.swift
  SwiftCompilerSources/Sources/Basic/SourceLoc.swift
  include/swift/AST/ASTBridging.h
  include/swift/Basic/BasicBridging.h
  include/swift/Basic/BridgingUtils.h
  lib/AST/ASTBridging.cpp
Labels: C++ Interop

#59965 [cxx-interop] NFC: fix bad merge
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ClangIncludePaths.cpp
  lib/ClangImporter/ClangIncludePaths.h
Labels: C++ Interop

#59977 [5.7] Gather opaque type same-type requirements when scanning associated type infos from a binary
  include/swift-c/StaticMirror/BinaryScan.h
  include/swift/ABI/GenericContext.h
  include/swift/Reflection/TypeRefBuilder.h
  include/swift/StaticMirror/BinaryScanImpl.h
  test/Reflection/opaque_associated_type_requirements.swift
  tools/libStaticMirror/libStaticMirror.cpp
  tools/libStaticMirror/libStaticMirror.exports
Labels: r5.7

#59998 [cxx-interop] Enable a test on Windows
  test/Interop/Cxx/stdlib/overlay/custom-sequence-typechecker.swift
Labels: C++ Interop

#60022 [5.7] SILGen: Fix potential use-after-free in `@_backDeploy` coroutines
  lib/SILGen/SILGenBackDeploy.cpp
  test/SILGen/back_deploy_attribute_accessor_coroutine.swift
Labels: r5.7

#60018 [cxx-interop][SwiftCompilerSources] Use `DiagnosticInfo::FixIt` instead of `BridgedDiagnosticFixIt`
  SwiftCompilerSources/Sources/AST/DiagnosticEngine.swift
  SwiftCompilerSources/Sources/Basic/Utils.swift
  include/swift/AST/ASTBridging.h
  include/swift/module.modulemap
  lib/AST/ASTBridging.cpp
Labels: C++ Interop

#60034 [cxx-interop][SwiftCompilerSources] Use `swift::DiagnosticArgument` instead of `BridgedDiagnosticArgument`
  SwiftCompilerSources/Sources/AST/DiagnosticEngine.swift
  include/swift/AST/ASTBridging.h
  lib/AST/ASTBridging.cpp
Labels: C++ Interop

#60025 [stdlib] fix unaligned loads of large SIMD vectors on x86_64
  stdlib/public/core/StringUTF16View.swift
  stdlib/public/core/UnsafeRawPointer.swift
  test/stdlib/UnsafeRawPointer.swift
Labels: r5.7, Standard Library

#60027 [5.7][IRGen] Emit opaque type descriptors into client for `@_alwaysEmitI…
  include/swift/SIL/SILFunction.h
  lib/IRGen/IRGenModule.h
  lib/IRGen/IRGenSIL.cpp
  lib/IRGen/Linking.cpp
  lib/SIL/IR/SILFunction.cpp
  test/IRGen/Inputs/AlwaysInlineIntoWithOpaque.swift
  test/IRGen/Inputs/AlwaysInlineIntoWithOpaqueReplacement.swift
  test/IRGen/opaque_result_alwaysInlineIntoClient.swift
Labels: r5.7

#60042 [5.7][Swift Static Mirror] Avoid downcasting to 32-bit value when reading out TypeRef address of a same-type requirement
  include/swift/Reflection/TypeRefBuilder.h
Labels: r5.7

#60058 [interop][SwiftToCxx] mark value witness table functions as noexcept
  lib/PrintAsClang/PrintSwiftToClangCoreScaffold.cpp
  test/Interop/SwiftToCxx/core/swift-impl-defs-in-cxx.swift
  test/Interop/SwiftToCxx/core/validate-swift-impl-defs-in-cxx.cpp
Labels: C++ Interop

#60071 [interop][SwiftToCxx] add support for passing/returning value types from other modules
  lib/PrintAsClang/ClangSyntaxPrinter.cpp
  lib/PrintAsClang/ClangSyntaxPrinter.h
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/PrintClangFunction.cpp
  lib/PrintAsClang/PrintClangFunction.h
  lib/PrintAsClang/PrintClangValueType.cpp
  lib/PrintAsClang/PrintClangValueType.h
  test/Interop/SwiftToCxx/cross-module-refs/Inputs/structs.swift
  test/Interop/SwiftToCxx/cross-module-refs/imported-struct-refs-in-cxx.swift
Labels: C++ Interop

#60075 [5.7] IRGen: Weakly link associated conformance descriptors when either the protocol or the associated requirement is weak
  lib/IRGen/Linking.cpp
  test/IRGen/weak_import_associated_conformance_descriptor.swift
Labels: r5.7

#59937 🍒[5.7][Distributed] Disable test while we investigate arm64e issue
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_through_generic.swift
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_through_generic_and_inner.swift
Labels: Distributed, r5.7, arm

#60055 🍒[5.7][Distributed] Prevent remote distributed actor from running deinit body
  lib/SILGen/SILGenDestructor.cpp
  lib/SILGen/SILGenDistributed.cpp
  lib/SILGen/SILGenFunction.h
  test/Distributed/Runtime/distributed_actor_deinit.swift
  test/Distributed/Runtime/distributed_actor_remote_fieldsDontCrashDeinit.swift
  test/Distributed/Runtime/distributed_actor_remote_retains_system.swift
  test/Distributed/SIL/distributed_actor_default_deinit_sil.swift
Labels: Distributed, r5.7

#60093 [interop][SwiftToCxx] arm64e: authenticate value witness table in C++
  include/swift/ABI/MetadataValues.h
  lib/PrintAsClang/ClangSyntaxPrinter.cpp
  lib/PrintAsClang/ClangSyntaxPrinter.h
  lib/PrintAsClang/PrintClangValueType.cpp
  test/Interop/SwiftToCxx/enums/swift-enum-case-functions.swift
  test/Interop/SwiftToCxx/initializers/init-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/methods/method-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/methods/mutating-method-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/properties/getter-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/large-structs-pass-return-indirect-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/resilient-struct-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/resilient-struct-in-cxx.swift
  test/Interop/SwiftToCxx/structs/small-structs-pass-return-direct-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/structs/struct-with-refcounted-member-execution.cpp
  test/Interop/SwiftToCxx/structs/struct-with-refcounted-member.swift
Labels: C++ Interop

#60098 [interop][SwiftToCxx] support instance property setters in C++
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/PrintClangFunction.cpp
  test/Interop/SwiftToCxx/properties/setter-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/properties/setter-in-cxx.swift
  test/Interop/SwiftToCxx/structs/resilient-struct-in-cxx.swift
Labels: C++ Interop

#59624 [cxx-interop] Flip the switch: only import safe APIs.
  SwiftCompilerSources/Sources/Basic/SourceLoc.swift
  SwiftCompilerSources/Sources/Basic/Utils.swift
  docs/CppInteroperability/UserManual.md
  include/swift/AST/DiagnosticsClangImporter.def
  include/swift/Basic/Compiler.h
  include/swift/ClangImporter/ClangImporterRequests.h
  include/swift/ClangImporter/ClangImporterTypeIDZone.def
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImportName.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/TypeCheckType.cpp
  stdlib/public/Cxx/CxxSequence.swift
  stdlib/public/Cxx/std/String.swift
  test/ClangImporter/objc_parse.swift
  test/Interop/Cxx/class/Inputs/constructors.h
  test/Interop/Cxx/class/Inputs/destructors.h
  test/Interop/Cxx/class/Inputs/forward-declared-cxx-record.h
  test/Interop/Cxx/class/Inputs/protocol-conformance.h
  test/Interop/Cxx/class/Inputs/type-classification.h
  test/Interop/Cxx/class/inheritance/Inputs/fields.h
  test/Interop/Cxx/class/inheritance/Inputs/functions.h
  test/Interop/Cxx/class/invalid-class-errors.swift
  test/Interop/Cxx/class/invalid-unsafe-projection-errors.swift
  test/Interop/Cxx/class/method/Inputs/methods.h
  test/Interop/Cxx/ergonomics/Inputs/implicit-computed-properties.h
  test/Interop/Cxx/foreign-reference/Inputs/move-only.h
  test/Interop/Cxx/foreign-reference/Inputs/nullable.h
  test/Interop/Cxx/foreign-reference/Inputs/pod.h
  test/Interop/Cxx/foreign-reference/Inputs/singleton.h
  test/Interop/Cxx/foreign-reference/Inputs/witness-table.h
  test/Interop/Cxx/foreign-reference/not-any-object.swift
  test/Interop/Cxx/foreign-reference/value-type-errors.swift
  test/Interop/Cxx/namespace/Inputs/classes-second-header.h
  test/Interop/Cxx/namespace/Inputs/classes.h
  test/Interop/Cxx/namespace/Inputs/templates-second-header.h
  test/Interop/Cxx/namespace/Inputs/templates.h
  test/Interop/Cxx/operators/Inputs/member-inline.h
  test/Interop/Cxx/operators/Inputs/member-out-of-line.h
  test/Interop/Cxx/static/Inputs/inline-static-member-var.h
  test/Interop/Cxx/static/Inputs/static-member-func.h
  test/Interop/Cxx/static/Inputs/static-member-var.h
  test/Interop/Cxx/stdlib/overlay/Inputs/custom-sequence.h
  test/Interop/Cxx/stdlib/overlay/std-string-overlay.swift
  test/Interop/Cxx/stdlib/use-std-iterator.swift
  test/Interop/Cxx/templates/Inputs/define-referenced-inline.h
  test/Interop/Cxx/union/Inputs/anonymous-union-partly-invalid.h
  test/Interop/Cxx/value-witness-table/Inputs/copy-constructors.h
  test/Interop/Cxx/value-witness-table/Inputs/custom-destructors.h
  test/Interop/Cxx/value-witness-table/Inputs/witness-lifetime-operations.h
Labels: C++ Interop

#60130 [5.7][CSSimplify] Don't fix invalid r-value use for misplaced `&`
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/lvalues.swift
Labels: r5.7

#60132 [5.7][AST] SE-0347: Don't check default expression status in type request
  lib/AST/TypeCheckRequests.cpp
  test/Constraints/type_inference_from_default_exprs.swift
Labels: r5.7

#60134 [5.7][CSSimplify] Allow referencing typealias declarations via leading-dot…
  lib/Sema/CSSimplify.cpp
  test/Constraints/static_members_on_protocol_in_generic_context.swift
Labels: r5.7

#60001 [cxx-interop] Synthesize conformances to `UnsafeCxxInputIterator`
  include/swift/AST/KnownIdentifiers.def
  include/swift/AST/KnownProtocols.def
  lib/AST/ASTContext.cpp
  lib/ClangImporter/CMakeLists.txt
  lib/ClangImporter/ClangDerivedConformances.cpp
  lib/ClangImporter/ClangDerivedConformances.h
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImporterImpl.h
  lib/IRGen/GenMeta.cpp
  test/Interop/Cxx/stdlib/overlay/Inputs/custom-iterator.h
  test/Interop/Cxx/stdlib/overlay/Inputs/custom-sequence.h
  test/Interop/Cxx/stdlib/overlay/Inputs/module.modulemap
  test/Interop/Cxx/stdlib/overlay/custom-iterator-module-interface.swift
  test/Interop/Cxx/stdlib/overlay/custom-sequence-typechecker.swift
  test/Interop/Cxx/stdlib/overlay/custom-sequence.swift
Labels: C++ Interop

#60142 🌸 Further loosen selector conflict checks
  lib/AST/NameLookup.cpp
  lib/Sema/TypeCheckDeclObjC.cpp
  test/ClangImporter/Inputs/custom-modules/module.map
  test/ClangImporter/Inputs/custom-modules/objc_init_redundant.h
  test/ClangImporter/Inputs/objc_init_redundant_bridging.h
  test/ClangImporter/objc_init_redundant.swift
  test/Concurrency/objc_async_overload.swift
Labels: r5.7

#60079 [Interop] [SwiftToCxx] Implementing a naive exception to be thrown in C++ if an Error is thrown in Swift
  lib/PrintAsClang/PrintClangFunction.cpp
  lib/PrintAsClang/PrintSwiftToClangCoreScaffold.cpp
  test/Interop/SwiftToCxx/core/swift-impl-defs-in-cxx.swift
  test/Interop/SwiftToCxx/functions/swift-functions-errors-execution.cpp
  test/Interop/SwiftToCxx/functions/swift-functions-errors.swift
Labels: C++ Interop

#60155 [cxx-interop] Allow iterators with out-of-class `operator==`
  lib/ClangImporter/ClangDerivedConformances.cpp
  test/Interop/Cxx/stdlib/overlay/Inputs/custom-iterator.h
  test/Interop/Cxx/stdlib/overlay/custom-iterator-module-interface.swift
  test/Interop/Cxx/stdlib/overlay/custom-sequence-typechecker.swift
Labels: C++ Interop

#60028 [5.7] [stdlib] fix unaligned loads of large SIMD vectors on x86_64
  stdlib/public/core/StringUTF16View.swift
  stdlib/public/core/UnsafeRawPointer.swift
  validation-test/stdlib/UnsafeRawPointerInternal.swift
Labels: r5.7, Standard Library

#60145 Sema: Don't allow opaque return types to reference DynamicSelfType [5.7]
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/MiscDiagnostics.cpp
  test/type/opaque_return_dynamic_self.swift
Labels: r5.7

#60144 ASTMangler: Don't consider @_originallyDefinedIn when mangling local type discriminators [5.7]
  lib/AST/ASTMangler.cpp
  lib/Serialization/ModuleFormat.h
  test/DebugInfo/Inputs/local_type_originally_defined_in_other.swift
  test/DebugInfo/local_type_originally_defined_in.swift
Labels: r5.7

#60143 RequirementMachine: Fix a request cycle [5.7]
  lib/AST/RequirementMachine/RequirementLowering.cpp
  test/Generics/protocol_typealias_cycle_6.swift
Labels: r5.7

#60156 [5.7] SIL Optimizer: add the OptimizeHopToExecutor in the late pipeline.
  lib/SILOptimizer/PassManager/PassPipeline.cpp
  test/Concurrency/Runtime/exclusivity_custom_executors.swift
Labels: r5.7

#60149 [cxx-interop] Add back 'import_as_ref' attr for libswift hosttools.
  lib/ClangImporter/ClangImporter.cpp
Labels: C++ Interop

#60154 [cxx-interop] Remove impl for constexpr members
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/static/constexpr-static-member-var.swift
  test/Interop/Cxx/static/static-member-var-irgen.swift
  test/Interop/Cxx/static/static-member-var-silgen.swift
  test/Interop/Cxx/static/static-var-irgen.swift
  test/Interop/Cxx/static/static-var-silgen.swift
  test/Interop/Cxx/static/static-var.swift
Labels: C++ Interop

#60180 [cxx-interop] Add source locations to diagnostics for un-importable APIs.
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImportType.cpp
  lib/ClangImporter/ImporterImpl.h
Labels: C++ Interop

#60185 [5.7] Sema: Allow explicitly available overrides to be as available as their context
  lib/Sema/TypeCheckDeclOverride.cpp
  test/Sema/availability_versions.swift
Labels: r5.7

#60110 [5.7] Fix OwnershipLiveRange for @owned values getting transformed to none values via switch_enum
  lib/SILOptimizer/SemanticARC/OwnershipLiveRange.cpp
  test/SILOptimizer/semantic-arc-opts-loadcopy-to-loadborrow.sil
Labels: r5.7

#60184 [IRGen/Distributed] Adjust protocol requirement and witness table to handle distributed thunks
  lib/IRGen/GenMeta.cpp
  lib/IRGen/GenProto.cpp
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_through_generic.swift
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_through_generic_and_inner.swift
Labels: Distributed

#60189 🍒[5.7][IRGen/Distributed] Adjust protocol requirement and witness table to handle distributed thunks
  lib/IRGen/GenMeta.cpp
  lib/IRGen/GenProto.cpp
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_through_generic.swift
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_through_generic_and_inner.swift
Labels: Distributed, r5.7

#59509 [cxx-interop] Add support for reference counting operations on foreign reference types.
  include/swift/AST/Decl.h
  include/swift/AST/DiagnosticsClangImporter.def
  include/swift/AST/DiagnosticsIRGen.def
  include/swift/AST/ReferenceCounting.h
  include/swift/Basic/Compiler.h
  include/swift/ClangImporter/ClangImporterRequests.h
  include/swift/ClangImporter/ClangImporterTypeIDZone.def
  lib/AST/Decl.cpp
  lib/AST/NameLookupRequests.cpp
  lib/AST/Type.cpp
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/IRGen/ClassTypeInfo.h
  lib/IRGen/GenClass.cpp
  lib/IRGen/GenHeap.cpp
  lib/IRGen/GenObjC.cpp
  lib/IRGen/GenType.cpp
  lib/IRGen/GenValueWitness.cpp
  lib/IRGen/HeapTypeInfo.h
  lib/IRGen/IRGenFunction.h
  lib/IRGen/IRGenModule.h
  lib/IRGen/MetadataRequest.cpp
  lib/SIL/IR/SILFunctionType.cpp
  lib/SIL/IR/TypeLowering.cpp
  stdlib/public/runtime/Casting.cpp
  stdlib/public/runtime/ErrorObject.mm
  test/Interop/Cxx/foreign-reference/Inputs/module.modulemap
  test/Interop/Cxx/foreign-reference/Inputs/move-only.h
  test/Interop/Cxx/foreign-reference/Inputs/nullable.h
  test/Interop/Cxx/foreign-reference/Inputs/pod.h
  test/Interop/Cxx/foreign-reference/Inputs/reference-counted.h
  test/Interop/Cxx/foreign-reference/Inputs/singleton.h
  test/Interop/Cxx/foreign-reference/Inputs/witness-table.h
  test/Interop/Cxx/foreign-reference/invalid-retain-operation-errors.swift
  test/Interop/Cxx/foreign-reference/reference-counted-silgen.swift
  test/Interop/Cxx/foreign-reference/reference-counted.swift
Labels: C++ Interop

#60219 [cxx-interop] Do not crash when importing anonymous classes
  lib/ClangImporter/ImportName.cpp
  test/Interop/Cxx/class/Inputs/linked-records.h
  test/Interop/Cxx/class/linked-records-module-interface.swift
Labels: C++ Interop

#60174 [cxx-interop][SwiftCompilerSources] Use `llvm::StringRef` instead of `BridgedStringRef`
  SwiftCompilerSources/Sources/AST/DiagnosticEngine.swift
  SwiftCompilerSources/Sources/Basic/Utils.swift
  SwiftCompilerSources/Sources/Optimizer/PassManager/PassContext.swift
  SwiftCompilerSources/Sources/Optimizer/PassManager/PassRegistration.swift
  SwiftCompilerSources/Sources/SIL/Builder.swift
  SwiftCompilerSources/Sources/SIL/Function.swift
  SwiftCompilerSources/Sources/SIL/Registration.swift
  SwiftCompilerSources/Sources/SIL/Type.swift
  include/swift/Basic/BasicBridging.h
  include/swift/Basic/BridgingUtils.h
  include/swift/SIL/SILBridging.h
  include/swift/SILOptimizer/OptimizerBridging.h
  include/swift/module.modulemap
  lib/Basic/BasicBridging.cpp
  lib/SIL/IR/SILFunction.cpp
  lib/SIL/Utils/SILBridging.cpp
  lib/SILOptimizer/PassManager/PassManager.cpp
  lib/SILOptimizer/PassManager/Passes.cpp
  lib/SILOptimizer/SILCombiner/SILCombine.cpp
Labels: C++ Interop

#60220 [cxx-interop][NFC] Prettify stack trace for CxxIterator conformance synthesis
  lib/ClangImporter/ClangDerivedConformances.cpp
Labels: C++ Interop

#60215 [cxx-interop][diags] Fix diagnostics for records inside namespaces.
  lib/Sema/TypeCheckType.cpp
  test/Interop/Cxx/class/invalid-class-errors.swift
Labels: C++ Interop

#60241 [interop][docs] udpate CppInteroperabilityStatus.md for reverse interop
  docs/CppInteroperability/CppInteroperabilityStatus.md
  docs/CppInteroperability/UserGuide-CallingSwiftFromC++.md
Labels: C++ Interop

#60253 [cxx-interop] Do not crash when diagnosing cycles for C++ operators
  lib/ClangImporter/ImportDecl.cpp
Labels: C++ Interop

#60248 [cxx-interop] Make sure to print template instantiations in the module interface
  lib/ClangImporter/SwiftLookupTable.cpp
  test/Interop/Cxx/templates/Inputs/member-templates.h
  test/Interop/Cxx/templates/member-templates-module-interface.swift
Labels: C++ Interop

#60262 [cxx-interop] Improve performance of importing C++ namespaces
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/SwiftLookupTable.cpp
Labels: C++ Interop

#60254 [cxx-interop] Do not try to import uninstantiatable templates
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/templates/Inputs/member-templates.h
  test/Interop/Cxx/templates/member-templates-module-interface.swift
Labels: C++ Interop

#60260 [cxx-interop] Bump SWIFT_LOOKUP_TABLE_VERSION_MINOR after changes to …
  lib/ClangImporter/SwiftLookupTable.h
Labels: C++ Interop

#60087 [Interop][SwiftToCxx] Initial support for getting associated values from enum
  lib/PrintAsClang/ClangSyntaxPrinter.cpp
  lib/PrintAsClang/ClangSyntaxPrinter.h
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/PrintAsClang.cpp
  lib/PrintAsClang/PrintClangFunction.cpp
  lib/PrintAsClang/PrintClangFunction.h
  lib/PrintAsClang/PrintClangValueType.cpp
  lib/PrintAsClang/PrintClangValueType.h
  test/Interop/SwiftToCxx/enums/swift-enum-case-functions-execution.cpp
  test/Interop/SwiftToCxx/enums/swift-enum-case-functions.swift
  test/Interop/SwiftToCxx/enums/swift-enum-extract-payload-execution.cpp
  test/Interop/SwiftToCxx/enums/swift-enum-extract-payload.swift
  test/Interop/SwiftToCxx/structs/swift-struct-in-cxx.swift
  test/Interop/lit.local.cfg
  test/PrintAsCxx/empty.swift
  test/PrintAsObjC/empty.swift
Labels: C++ Interop

#60267 [cxx-interop] Conform `std::string` to `ExpressibleByStringLiteral`
  stdlib/public/Cxx/std/String.swift
  test/Interop/Cxx/stdlib/overlay/std-string-overlay.swift
Labels: C++ Interop

#60270 [interop][docs] cleanup CallingSwiftFromC++ guide
  docs/CppInteroperability/UserGuide-CallingSwiftFromC++.md
Labels: C++ Interop

#60269 [interop][SwiftToCxx] re-enable enum runtime tests on ARM64e
  test/Interop/SwiftToCxx/enums/large-enums-pass-return-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/enums/small-enums-pass-return-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/enums/swift-enum-case-functions-execution.cpp
  test/Interop/SwiftToCxx/enums/swift-enum-extract-payload-execution.cpp
Labels: C++ Interop

#60281 [cxx-interop][SwiftCompilerSources] Explicitly list used headers in the modulemap
  include/swift/module.modulemap
Labels: C++ Interop

#60283 [cxx-interop] Fix static extensions on foreign reference types.
  lib/SIL/IR/SILFunction.cpp
  test/Interop/Cxx/foreign-reference/pod.swift
Labels: C++ Interop

#60266 [Distributed] Dont hang calls on not found accessors
  stdlib/public/Distributed/DistributedActor.cpp
  stdlib/public/Distributed/DistributedActorSystem.swift
  stdlib/public/Distributed/DistributedMetadata.swift
  test/Distributed/Runtime/distributed_actor_func_calls_remoteCall_bad_targets.swift
  test/Distributed/Runtime/distributed_actor_remoteCall.swift
Labels: Distributed

#60282 [interop][SwiftToCxx] include <new> after <stdlib.h> (fixes local tests)
  lib/PrintAsClang/PrintAsClang.cpp
  test/PrintAsCxx/empty.swift
Labels: C++ Interop

#60285 [interop][SwiftToCxx] add _SwiftCxxInteroperability.h shims header and import it for C++ header mode
  lib/PrintAsClang/PrintAsClang.cpp
  lib/PrintAsClang/PrintSwiftToClangCoreScaffold.cpp
  stdlib/public/SwiftShims/CMakeLists.txt
  stdlib/public/SwiftShims/_SwiftCxxInteroperability.h
  stdlib/public/SwiftShims/module.modulemap
  test/Interop/SwiftToCxx/core/swift-impl-defs-in-cxx.swift
  test/Interop/lit.local.cfg
  test/PrintAsCxx/empty.swift
Labels: C++ Interop

#60305 [cxx-interop] Improve performance of importing C++ namespaces, part 2
  lib/ClangImporter/SwiftLookupTable.cpp
Labels: C++ Interop

#60300 [Interop][SwiftToCxx] Add pointer nullability annotation for inout function
  lib/PrintAsClang/PrintClangFunction.cpp
  test/Interop/SwiftToCxx/functions/swift-primitive-inout-functions-cxx-bridging.swift
Labels: C++ Interop

#60304 [interop][SwiftToCxx] NFC, move generic traits declarations to shims …
  lib/PrintAsClang/PrintSwiftToClangCoreScaffold.cpp
  stdlib/public/SwiftShims/_SwiftCxxInteroperability.h
  test/Interop/SwiftToCxx/core/swift-impl-defs-in-cxx.swift
Labels: C++ Interop
