Repository swiftlang/swift, pull requests merged in 2022-05, with the labels that each got.

#58604 🍒 [5.7] AST: Fix bug in subclass composition minimization
  lib/AST/Type.cpp
  test/type/subclass_composition.swift
Labels: r5.7

#58471 [5.7] Add emission of Frontend parseable-output in WMO jobs.
  lib/FrontendTool/FrontendTool.cpp
  test/Frontend/parseable_output.swift
  test/Frontend/parseable_output_error.swift
Labels: r5.7

#58608 [5.7] [MemAccessUtils] A resilient struct is a product leaf.
  lib/SIL/Utils/MemAccessUtils.cpp
  test/SILOptimizer/hoist_destroy_addr_resilient.sil
Labels: r5.7

#58534 [5.7][ConstraintSystem] Fail `~=` synthesis if constraint generation fails
  include/swift/Sema/ConstraintSystem.h
  lib/Sema/CSSimplify.cpp
  test/expr/closure/multi_statement.swift
  unittests/Sema/PlaceholderTypeInferenceTests.cpp
  unittests/Sema/UnresolvedMemberLookupTests.cpp
Labels: r5.7

#58628 [Distributed/SILGen] NFC: Remove a couple of unused variables
  lib/SILGen/SILGenDistributed.cpp
Labels: Distributed

#58443 [5.7] fix a crash/hang in SimplifyCFG.
  lib/SILOptimizer/Transforms/SimplifyCFG.cpp
  test/SILOptimizer/simplify_cfg_crash.swift
Labels: r5.7

#58537 [cxx-interop] Fix SIL deserialization error for C++ methods
  lib/Serialization/Deserialization.cpp
Labels: C++ Interop

#58543 [cxx-interop] Fix lookup of class template instantiations
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/SwiftLookupTable.cpp
Labels: C++ Interop

#58649 [gardening] Bolstered breadcrumb deferment with an assert.
  lib/SILGen/ResultPlan.cpp
Labels: Concurrency

#58659 [cxx-interop] Fix namespace lookup
  lib/ClangImporter/ClangImporter.cpp
Labels: C++ Interop

#58548 Revert "[5.7][ConstraintSystem] Extend availability check to cover unavailable ext…"
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/availability.swift
Labels: r5.7

#58629 [5.7-🍒] Proper fix for ObjC async jump to null
  lib/SILGen/ExecutorBreadcrumb.h
  lib/SILGen/ResultPlan.cpp
  lib/SILGen/ResultPlan.h
  lib/SILGen/SILGenApply.cpp
  test/Inputs/clang-importer-sdk/usr/include/ObjCConcurrency.h
  test/SILGen/objc_async.swift
  test/SILGen/objc_async_from_swift.swift
Labels: Concurrency, r5.7, pending-approval

#58665 [5.7] Use Location of Inference Sources as a Fallback
  lib/AST/RequirementMachine/RequirementMachineRequests.cpp
  test/type/parameterized_existential.swift
Labels: r5.7

#58631 [5.7-04182022 🍒] Proper fix for ObjC async jump to null
  lib/SILGen/ExecutorBreadcrumb.h
  lib/SILGen/ResultPlan.cpp
  lib/SILGen/ResultPlan.h
  lib/SILGen/SILGenApply.cpp
  test/Inputs/clang-importer-sdk/usr/include/ObjCConcurrency.h
  test/SILGen/objc_async.swift
  test/SILGen/objc_async_from_swift.swift
Labels: Concurrency, r5.7, pending-approval

#58672 [Distributed] Diagnose missing inout on remoteCall decls
  lib/AST/DistributedDecl.cpp
  test/Distributed/distributed_actor_system_missing_adhoc_requirement_impls.swift
Labels: Distributed

#58682 [5.7] [Parse] Split prefix operators from regex in the lexer
  include/swift/Parse/Lexer.h
  include/swift/Parse/Parser.h
  lib/Parse/Lexer.cpp
  lib/Parse/ParseExpr.cpp
  test/StringProcessing/Parse/forward-slash-regex-disabled.swift
  test/StringProcessing/Parse/forward-slash-regex.swift
Labels: r5.7

#42297 Reapply [cxx-interop][libswift] Use `std::string` instead of `BridgedStringRef`
  SwiftCompilerSources/CMakeLists.txt
  SwiftCompilerSources/Sources/SIL/BasicBlock.swift
  SwiftCompilerSources/Sources/SIL/Function.swift
  SwiftCompilerSources/Sources/SIL/GlobalVariable.swift
  SwiftCompilerSources/Sources/SIL/Instruction.swift
  SwiftCompilerSources/Sources/SIL/Value.swift
  cmake/modules/AddSwift.cmake
  cmake/modules/SwiftCXXUtils.cmake
  include/swift/SIL/SILBridging.h
  lib/SIL/Utils/SILBridging.cpp
  stdlib/public/Cxx/CMakeLists.txt
Labels: C++ Interop

#58694 [5.7][Remote AST] Support Parameterized Existential Types
  include/swift/ABI/GenericContext.h
  include/swift/ABI/Metadata.h
  include/swift/AST/ASTDemangler.h
  include/swift/Demangling/TypeDecoder.h
  include/swift/Reflection/TypeRef.h
  include/swift/Reflection/TypeRefBuilder.h
  include/swift/Remote/MetadataReader.h
  lib/AST/ASTDemangler.cpp
  lib/IRGen/MetadataRequest.cpp
  stdlib/public/runtime/Metadata.cpp
  stdlib/public/runtime/MetadataCache.h
  stdlib/public/runtime/MetadataLookup.cpp
  stdlib/public/runtime/ReflectionMirror.cpp
  test/RemoteAST/parameterized_existentials.swift
Labels: r5.7

#58645 [5.7] [Parse] Update for new regex compiler interface
  SwiftCompilerSources/Sources/Parse/Regex.swift
  lib/Parse/ParseRegex.cpp
  test/StringProcessing/Parse/forward-slash-regex.swift
Labels: r5.7

#58693 [5.7] Ban Nested `some` Types in Existentials
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeCheckType.h
  test/type/opaque_parameterized_existential.swift
  test/type/parameterized_existential.swift
  validation-test/compiler_crashers_2_fixed/unsupported_recursive_opaque_conformance.swift
Labels: r5.7

#58635 [5.7][Refactoring] Fix a crash that occurred when converting if/else of enum with raw value to switch statement
  lib/IDE/Refactoring.cpp
  test/refactoring/ConvertToSwitchStmt/Outputs/enum_with_raw_value/L8-3.swift.expected
  test/refactoring/ConvertToSwitchStmt/basic.swift
  test/refactoring/ConvertToSwitchStmt/enum_with_raw_value.swift
Labels: r5.7

#58691 [5.7][CodeCompletion] Maintain LeaveClosureBodiesUnchecked when checking pattern binding
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  lib/AST/Decl.cpp
  lib/Sema/TypeCheckDecl.cpp
  lib/Sema/TypeCheckDeclPrimary.cpp
  lib/Sema/TypeCheckStorage.cpp
  test/IDE/complete_in_closures.swift
Labels: r5.7

#58636 [5.7][CodeCompletion] Avoid creating circles in the USRBasedType supertype hierarchy
  lib/IDE/CodeCompletionResultType.cpp
  validation-test/IDE/crashers_2_fixed/rdar91765262.swift
Labels: r5.7

#58703 [5.7] [Regex] Downgrade implicit import warning to remark
  include/swift/AST/DiagnosticsFrontend.def
Labels: r5.7

#58656 [Distributed][Workaround] Initializers crash when DA has state and uses the local testing system
  lib/AST/DistributedDecl.cpp
  stdlib/public/Distributed/DistributedActorSystem.swift
  stdlib/public/Distributed/LocalTestingDistributedActorSystem.swift
  test/Distributed/Runtime/distributed_actor_init_local.swift
  test/Distributed/distributed_actor_layout.swift
  test/Distributed/distributed_actor_system_missing_adhoc_requirement_impls.swift
Labels: Distributed, RunTimeCrash

#58745 [Distributed] Enforce strict order of synthesized id and actorSystem properties; avoid wrong offset crashes
  lib/AST/DistributedDecl.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/DerivedConformanceDistributedActor.cpp
  lib/Sema/DerivedConformances.cpp
  lib/Sema/DerivedConformances.h
  stdlib/public/Distributed/LocalTestingDistributedActorSystem.swift
  test/Distributed/Runtime/distributed_actor_init_local.swift
  test/Distributed/distributed_actor_layout.swift
  test/Distributed/distributed_actor_system_missing_adhoc_requirement_impls.swift
  test/IRGen/distributed_actor.swift
Labels: Distributed

#58752 [Distributed] revert too aggressive synthesis removal, and fix it instead
  lib/Sema/DerivedConformanceDistributedActor.cpp
  lib/Sema/DerivedConformances.cpp
  test/Distributed/Runtime/distributed_actor_in_other_module.swift
Labels: Distributed

#58685 [5.7][Refactoring] Fix an issue where refactoring misses to refactor references after prefix operators
  lib/IDE/SwiftSourceDocInfo.cpp
  test/refactoring/rename/Outputs/prefix_operator/refactor.swift.expected
  test/refactoring/rename/prefix_operator.swift
Labels: r5.7

#58751 [5.7] fix a crash in AccessEnforementWMO
  lib/SILOptimizer/Transforms/AccessEnforcementWMO.cpp
Labels: r5.7

#58621 [5.7][IRGen] Return null reference from IRGenFunction::emitUnmanagedAlloc …
  lib/IRGen/GenHeap.cpp
  test/IRGen/partial_apply.sil
  test/Interpreter/closure_zero_size_allocation.swift
Labels: r5.7

#58717 [5.7][CSClosure] Mark partially inferred external declarations as invalid
  lib/Sema/CSClosure.cpp
  lib/Sema/CSStep.h
  test/expr/closure/multi_statement.swift
Labels: r5.7

#58747 🍒[5.7][Distributed] Force the order of properties in AST
  lib/SILGen/SILGenDistributed.cpp
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/DerivedConformanceDistributedActor.cpp
  lib/Sema/DerivedConformances.cpp
  lib/Sema/DerivedConformances.h
  stdlib/public/Distributed/LocalTestingDistributedActorSystem.swift
  test/Distributed/Runtime/distributed_actor_in_other_module.swift
  test/Distributed/Runtime/distributed_actor_init_local.swift
  test/IRGen/distributed_actor.swift
Labels: Distributed, r5.7

#58748 🍒[5.7-04182022][Distributed] Force the order of properties in AST
  lib/Sema/CodeSynthesisDistributedActor.cpp
  lib/Sema/DerivedConformanceDistributedActor.cpp
  lib/Sema/DerivedConformances.cpp
  lib/Sema/DerivedConformances.h
  stdlib/public/Distributed/LocalTestingDistributedActorSystem.swift
  test/Distributed/Inputs/EchoActor.swift
  test/Distributed/Runtime/distributed_actor_in_other_module.swift
  test/Distributed/Runtime/distributed_actor_init_local.swift
  test/IRGen/distributed_actor.swift
Labels: Distributed, r5.7

#58773 [CodeCompletion] _compilerInitialized and _local are UserInaccessible
  include/swift/AST/Attr.def
  test/SourceKit/CodeComplete/complete_override.swift.response
Labels: Distributed

#58794 [5.7][ConstraintSystem] A couple of `callAsFunction` fixes
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/callAsFunction.swift
  test/Constraints/result_builder.swift
Labels: r5.7

#58806 [5.7-04182022] Sema: Accept existentials without `any` in swiftinterfaces
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeChecker.h
  test/ModuleInterface/Inputs/existential-any-ignore-missing-in-interface.swiftinterface
  test/ModuleInterface/existential-any.swift
Labels: r5.7

#58805 [5.7] Sema: Accept existentials without `any` in swiftinterfaces
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeChecker.h
  test/ModuleInterface/Inputs/existential-any-ignore-missing-in-interface.swiftinterface
  test/ModuleInterface/existential-any.swift
Labels: r5.7

#58795 [5.7-04182022][ConstraintSystem] A couple of `callAsFunction` fixes
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/callAsFunction.swift
  test/Constraints/result_builder.swift
Labels: r5.7

#58820 [5.7] Teach Type Deserialization About Parameterized Protocol Types
  lib/Serialization/Deserialization.cpp
  test/Serialization/Inputs/parameterized_protocol_other.swift
  test/Serialization/parameterized_protocol.swift
Labels: r5.7

#58666 [5.7][CSSimplify] Don't attempt to synthesize ~= for optional base types
  lib/Sema/CSSimplify.cpp
  validation-test/Sema/type_checker_crashers_fixed/rdar92327807.swift
Labels: r5.7

#58842 [5.7][TypeChecker] NFC: Remove a literal to make test-case less flaky
  validation-test/Sema/type_checker_perf/fast/multi_statement_closure_with_simd_variable.swift
Labels: r5.7

#58807 Fix async_let playground transform
  lib/Sema/PlaygroundTransform.cpp
  test/PlaygroundTransform/async_let.swift
Labels: Concurrency

#58766 [5.7] Diagnose Availability for Parameterized Existential Types
  include/swift/AST/ASTContext.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/Types.h
  lib/AST/ASTContext.cpp
  lib/AST/Availability.cpp
  lib/Sema/TypeCheckAvailability.cpp
  lib/Sema/TypeCheckAvailability.h
  lib/Sema/TypeCheckProtocol.cpp
  test/Constraints/parameterized_existential_metatypes.swift
  test/Interpreter/parameterized_existentials.swift
  test/RemoteAST/parameterized_existentials.swift
  test/SILGen/parameterized_existentials.swift
  test/SILOptimizer/cast_folding_parameterized_protocol.swift
  test/Sema/availability_parameterized_existential.swift
Labels: r5.7

#58813 [5.7] RequirementMachine: Teach concrete contraction about nested associated types
  lib/AST/RequirementMachine/ConcreteContraction.cpp
  lib/AST/RequirementMachine/RequirementMachineRequests.cpp
  lib/AST/RequirementMachine/RuleBuilder.cpp
  test/Generics/concrete_conformances_in_protocol.swift
  test/Generics/concrete_same_type_versus_anyobject.swift
  test/Generics/conditional_requirement_inference_in_protocol.swift
  test/Generics/derived_via_concrete_in_protocol.swift
  test/Generics/non_confluent.swift
  test/Generics/rdar91594361.swift
  test/Generics/requirement_inference.swift
  test/Generics/requirement_machine_diagnostics.swift
  test/attr/accessibility_where_clause.swift
  validation-test/compiler_crashers_2_fixed/rdar56398071.swift
  validation-test/compiler_crashers_2_fixed/sr11639.swift
Labels: r5.7

#58538 [5.7] [Sema] Don't warn on trailing closures in closure conditions
  lib/Sema/MiscDiagnostics.cpp
  test/expr/closure/trailing.swift
Labels: r5.7

#58860 [5.7] [Parse] Allow prefix operators containing `/` with `/.../` regex literals
  include/swift/AST/DiagnosticsParse.def
  include/swift/Parse/Parser.h
  lib/Parse/Lexer.cpp
  lib/Parse/ParseDecl.cpp
  lib/Parse/ParseExpr.cpp
  test/StringProcessing/Frontend/enable-flag.swift
  test/StringProcessing/Parse/forward-slash-regex.swift
  test/StringProcessing/Parse/prefix-slash.swift
  test/StringProcessing/Parse/regex_parse_error.swift
Labels: r5.7

#58868 [5.7][Parseable Output] Compute file extensions using full extension strings
  lib/FrontendTool/FrontendTool.cpp
  test/Frontend/parseable_output.swift
Labels: r5.7

#58878 [5.7] Turn on Parameterized Existentials in Metatypes
  lib/Sema/TypeCheckType.h
  test/Constraints/parameterized_existential_metatypes.swift
Labels: r5.7

#58837 [5.7] Fix source range computation of regex literals for diagnostics
  include/swift/Basic/SourceManager.h
  lib/Parse/Lexer.cpp
  lib/Parse/ParseRegex.cpp
  test/StringProcessing/Sema/regex_literal_diagnostics.swift
Labels: r5.7

#58756 [5.7][SourceKit] In related idents, report underlying var of closure capture and shorthand if let binding
  test/SourceKit/RelatedIdents/related_idents.swift
  tools/SourceKit/lib/SwiftLang/SwiftSourceDocInfo.cpp
Labels: r5.7

#58850 [5.7][SourceKit] Guard DependencyStamps with a lock
  tools/SourceKit/lib/SwiftLang/SwiftASTManager.cpp
Labels: r5.7

#58769 [5.7][CodeCompletion] Mark types that can’t be used as attributes as having an invalid type relation when used after '@'
  include/swift/IDE/CodeCompletionResultType.h
  include/swift/IDE/CompletionLookup.h
  lib/IDE/CodeCompletion.cpp
  lib/IDE/CodeCompletionCache.cpp
  lib/IDE/CodeCompletionResultType.cpp
  test/IDE/complete_decl_attribute.swift
  test/IDE/complete_type_relation_global_results.swift
Labels: r5.7

#58884 [5.7][CodeCompletion] Annotate variables with effectful getters
  lib/IDE/CompletionLookup.cpp
  test/IDE/complete_effectful_accessor.swift
Labels: r5.7

#58866 [5.7][Remote AST] Support Parameterized Existential Types
  include/swift/ABI/GenericContext.h
  include/swift/ABI/Metadata.h
  include/swift/AST/ASTDemangler.h
  include/swift/Demangling/TypeDecoder.h
  include/swift/Reflection/TypeRef.h
  include/swift/Reflection/TypeRefBuilder.h
  include/swift/Remote/MetadataReader.h
  lib/AST/ASTDemangler.cpp
  lib/IRGen/MetadataRequest.cpp
  stdlib/public/runtime/Metadata.cpp
  stdlib/public/runtime/MetadataCache.h
  stdlib/public/runtime/MetadataLookup.cpp
  stdlib/public/runtime/ReflectionMirror.cpp
  test/RemoteAST/parameterized_existentials.swift
Labels: r5.7

#58843 [cxx-interop] Use VFS to inject modulemap into libstdc++ installation
  lib/ClangImporter/ClangImporter.cpp
  stdlib/public/Cxx/libstdcxx.h
  stdlib/public/Cxx/libstdcxx.modulemap
Labels: C++ Interop

#58452 [cxx-interop] Add basic C++ stdlib overlay
  include/swift/Option/FrontendOptions.td
  stdlib/public/Cxx/CMakeLists.txt
  stdlib/public/Cxx/String.swift
  stdlib/public/Cxx/std.swift
  test/Interop/Cxx/stdlib/overlay/string.swift
  validation-test/ParseableInterface/verify_all_overlays.py
Labels: C++ Interop

#58893 [5.7][CursorInfo] Report values shadowed using shorthand syntax as secondary results
  include/swift/IDE/Utils.h
  include/swift/Sema/IDETypeChecking.h
  lib/IDE/IDERequests.cpp
  lib/IDE/IDETypeChecking.cpp
  test/SourceKit/CursorInfo/closure_capture.swift
  test/SourceKit/CursorInfo/shorthand_if_let.swift
  tools/SourceKit/lib/SwiftLang/SwiftSourceDocInfo.cpp
Labels: r5.7

#41905 [cxx-interop] Add snake_case to CXXMethodBridging
  include/swift/ClangImporter/CXXMethodBridging.h
  test/Interop/Cxx/ergonomics/Inputs/implicit-computed-properties.h
  test/Interop/Cxx/ergonomics/implicit-computed-properties-module-interface.swift
  test/Interop/Cxx/ergonomics/implicit-computed-properties.swift
  test/SILOptimizer/array_element_propagation_ossa_nontrivial.sil
  utils/build_swift/tests/build_swift/test_driver_arguments.py
Labels: C++ Interop

#42411 [cxx-interop] Import complex inferred dependent return types
  lib/ClangImporter/ImportType.cpp
  test/Interop/Cxx/templates/Inputs/dependent-types.h
  test/Interop/Cxx/templates/dependent-types-module-interface.swift
  test/Interop/Cxx/templates/dependent-types-silgen.swift
  test/Interop/Cxx/templates/dependent-types.swift
Labels: C++ Interop

#58944 [cxx-interop] Do not run `SIL/verify_all_overlays.py` on `std`
  validation-test/SIL/verify_all_overlays.py
Labels: C++ Interop

#58937 [cxx-interop] Pass clangSema.TUScope when calling LookupName for availability
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/availability/Inputs/SomeModule.h
  test/Interop/Cxx/availability/Inputs/module.modulemap
  test/Interop/Cxx/availability/availability-objcxx-smoke.swift
Labels: C++ Interop

#58947 [cxx-interop] Disable failing tests to unblock nightly toolchains
  test/Interop/Cxx/stdlib/libstdcxx-module-interface.swift
  test/Interop/Cxx/stdlib/use-std-string.swift
Labels: C++ Interop

#58936 [5.7][SourceKit] Add whether a property is dynamic
  include/swift/IDE/Utils.h
  lib/IDE/IDERequests.cpp
  lib/IDE/Utils.cpp
  lib/Index/Index.cpp
  test/Index/Store/record-sourcefile.swift
  test/Index/index_callasfunction.swift
  test/Index/index_curry_thunk.swift
  test/Index/index_keypath_member_lookup.swift
  test/Index/index_static_funcs.swift
  test/Index/roles.swift
  test/SourceKit/CursorInfo/cursor_dynamic.swift
  test/SourceKit/Indexing/index.swift.response
  test/SourceKit/Indexing/index_effective_access_level.swift.response
  test/SourceKit/Indexing/index_forbid_typecheck.swift.response
  test/SourceKit/Indexing/index_operators.swift.response
Labels: r5.7

#58886 [5.7][CodeCompletion] Support type checking attributes even if they are not part of the AST
  include/swift/AST/ASTNode.h
  include/swift/AST/TypeCheckRequests.h
  include/swift/AST/TypeCheckerTypeIDZone.def
  include/swift/Parse/CodeCompletionCallbacks.h
  include/swift/Sema/IDETypeChecking.h
  lib/AST/TypeCheckRequests.cpp
  lib/IDE/CodeCompletion.cpp
  lib/IDE/ConformingMethodList.cpp
  lib/IDE/ExprContextAnalysis.cpp
  lib/IDE/ExprContextAnalysis.h
  lib/IDE/TypeContextInfo.cpp
  lib/Parse/ParseDecl.cpp
  lib/Sema/TypeCheckStmt.cpp
  lib/Sema/TypeChecker.cpp
  test/IDE/complete_attributes.swift
  test/IDE/complete_property_delegate_attribute.swift
Labels: r5.7

#58962 [cxx-interop] Extract libstdc++ installation path from Clang
  include/swift/AST/DiagnosticsClangImporter.def
  lib/ClangImporter/ClangImporter.cpp
  test/Interop/Cxx/stdlib/libstdcxx-module-interface.swift
  test/Interop/Cxx/stdlib/use-std-string.swift
Labels: C++ Interop

#58949 [5.7][Parse] Set missing contextual keyword token kind for `async`
  lib/Parse/ParsePattern.cpp
  test/IDE/coloring.swift
  test/SourceKit/SyntaxMapData/Inputs/syntaxmap.swift
  test/SourceKit/SyntaxMapData/syntaxmap.swift.response
  unittests/Syntax/TypeSyntaxTests.cpp
  utils/gyb_syntax_support/DeclNodes.py
  utils/gyb_syntax_support/ExprNodes.py
  utils/gyb_syntax_support/TypeNodes.py
Labels: r5.7

#58900 [5.7] Diagnose Availability for Parameterized Existential Types
  include/swift/AST/ASTContext.h
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/Types.h
  lib/AST/ASTContext.cpp
  lib/AST/Availability.cpp
  lib/Sema/TypeCheckAvailability.cpp
  lib/Sema/TypeCheckAvailability.h
  lib/Sema/TypeCheckProtocol.cpp
  test/Constraints/parameterized_existential_metatypes.swift
  test/Interpreter/parameterized_existentials.swift
  test/RemoteAST/parameterized_existentials.swift
  test/SILGen/parameterized_existentials.swift
  test/SILOptimizer/cast_folding_parameterized_protocol.swift
  test/Sema/availability_parameterized_existential.swift
Labels: r5.7

#58544 [5.7][stdlib][docs] Clarify BidirectionalCollection requirements
  stdlib/public/core/BidirectionalCollection.swift
Labels: r5.7, Standard Library, Documentation

#58946 [5.7] Support hermetic indexing information
  include/swift/AST/DiagnosticsFrontend.def
  include/swift/AST/IRGenOptions.h
  include/swift/Basic/PathRemapper.h
  include/swift/Index/IndexRecord.h
  include/swift/Option/Options.td
  lib/Driver/Driver.cpp
  lib/Driver/ToolChains.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/FrontendTool/FrontendTool.cpp
  lib/Index/IndexRecord.cpp
  lib/Serialization/Serialization.cpp
  test/Index/Store/unit-multiple-sourcefiles-remapped.swift
  test/Index/Store/unit-one-sourcefile-remapped.swift
  test/Index/Store/unit-pcm-dependency-remapped.swift
Labels: r5.7

#58987 [5.7][Serialization] Harden the compiler tag check on swiftmodules
  lib/Serialization/ModuleFileSharedCore.cpp
Labels: r5.7

#58986 [5.7][ConstraintSystem] A couple of improvements to multi-statement closure handling
  include/swift/Sema/CSFix.h
  lib/Sema/CSClosure.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSStep.cpp
  lib/Sema/CSStep.h
  test/Constraints/closures.swift
  test/Constraints/generics.swift
  test/expr/closure/multi_statement.swift
  test/expr/unary/keypath/keypath.swift
Labels: r5.7

#58988 [5.7][Serialization] Soft-reject swiftmodules built against a different SDK on tagged compilers
  include/swift/AST/SearchPathOptions.h
  include/swift/Basic/Version.h
  include/swift/Serialization/Validation.h
  lib/APIDigester/ModuleAnalyzerNodes.cpp
  lib/ASTSectionImporter/ASTSectionImporter.cpp
  lib/Basic/Version.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/Frontend/ModuleInterfaceLoader.cpp
  lib/Serialization/ModuleFile.cpp
  lib/Serialization/ModuleFileSharedCore.cpp
  lib/Serialization/ModuleFileSharedCore.h
  lib/Serialization/SerializedModuleLoader.cpp
  test/Serialization/restrict-swiftmodule-to-sdk.swift
  tools/lldb-moduleimport-test/lldb-moduleimport-test.cpp
  unittests/FrontendTool/ModuleLoadingTests.cpp
Labels: r5.7

#59027 [5.7][CSClosure] Specify stack capacity of a `SmallVector`
  lib/Sema/CSClosure.cpp
Labels: r5.7

#59029 [5.7][IDE] Skip walking serialized non-visible extension decls
  lib/AST/Module.cpp
  test/Index/skip-loaded-internal.swift
Labels: r5.7

#59042 [C++-Interop] Fix EffectiveClangContext for NS_OPTIONS EnumDecl lookup.
  lib/ClangImporter/SwiftLookupTable.h
  test/Interop/Cxx/enum/Inputs/c-enums-NS_OPTIONS.h
  test/Interop/Cxx/enum/Inputs/module.modulemap
  test/Interop/Cxx/enum/c-enums-NS_OPTIONS.swift
Labels: C++ Interop

#59077 [5.7][ASTPrinter] Print the desugared constraint type following the `any` keyword.
  include/swift/AST/PrintOptions.h
  lib/AST/ASTPrinter.cpp
  test/ModuleInterface/existential-any.swift
Labels: r5.7

#59078 [interop][swiftToCxx] emit empty skeleton C++ classes for Swift struc…
  lib/PrintAsClang/CMakeLists.txt
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/ModuleContentsWriter.cpp
  lib/PrintAsClang/PrintClangValueType.cpp
  lib/PrintAsClang/PrintClangValueType.h
  test/Interop/SwiftToCxx/structs/swift-struct-in-cxx.swift
Labels: C++ Interop

#59083 [5.7][CSClosure] Fix crash in `fallthrough` statement checking
  lib/Sema/CSClosure.cpp
  test/expr/closure/multi_statement.swift
Labels: r5.7

#59076 [5.7] Enable SE-0353 By Default
  CHANGELOG.md
  include/swift/Basic/LangOptions.h
  include/swift/Option/FrontendOptions.td
  lib/Frontend/CompilerInvocation.cpp
  lib/Sema/TypeCheckType.cpp
  lib/Sema/TypeCheckType.h
  test/Constraints/existential_metatypes.swift
  test/Constraints/parameterized_existential_metatypes.swift
  test/IRGen/existential_shape_metadata.swift
  test/Interpreter/parameterized_existentials.swift
  test/RemoteAST/parameterized_existentials.swift
  test/SILGen/parameterized_existentials.swift
  test/SILOptimizer/cast_folding_parameterized_protocol.swift
  test/Sema/availability_parameterized_existential.swift
  test/Serialization/parameterized_protocol.swift
  test/type/opaque_parameterized_existential.swift
  test/type/parameterized_existential.swift
  test/type/parameterized_protocol.swift
  validation-test/compiler_crashers_2_fixed/unsupported_recursive_opaque_conformance.swift
Labels: r5.7

#59084 [5.7][TypeChecker] SE-0324: Extend Swift -> C pointer conversions to `inout`
  include/swift/Sema/Constraint.h
  lib/Sema/CSApply.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/Constraint.cpp
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/Inputs/c_pointer_conversions.h
  test/Constraints/swift_to_c_pointer_conversions.swift.gyb
Labels: r5.7

#58776 [5.7][Sema] Limit optional type variable hole propagation only to OptionalEvaluationExpr binding
  lib/Sema/CSBindings.cpp
  test/Constraints/optional.swift
  test/Constraints/try_swift5.swift
  validation-test/IDE/stress_tester_issues_fixed/rdar93127707.swift
Labels: r5.7

#59088 [5.7][Test] Do not load string processing when recovery is disabled
  test/Index/skip-loaded-internal.swift
Labels: r5.7

#59106 [5.7][CSSimplify] Disfavor choices that have injected `callAsFunction`
  lib/Sema/CSSimplify.cpp
  test/Constraints/result_builder_callAsFunction.swift
Labels: r5.7

#59082 [5.7][TypeChecker] SE-0352: Require coercion if result type contains exist…
  include/swift/AST/DiagnosticsSema.def
  include/swift/Sema/CSFix.h
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/ConstraintSystem.cpp
  test/Constraints/opened_existentials.swift
  test/decl/protocol/existential_member_accesses_self_assoctype.swift
Labels: r5.7

#59109 [5.7] Handle ParamDecls and VarDecls in Argument Matching Diagnostics
  lib/Sema/CSSimplify.cpp
  test/Constraints/argument_matching.swift
Labels: r5.7

#58998 [5.7][SwiftSyntax] Parse regex literals using a fallback lexer implemented in C++
  include/swift/Parse/SyntaxRegexFallbackLexing.h
  lib/Parse/CMakeLists.txt
  lib/Parse/SyntaxRegexFallbackLexing.cpp
  test/Syntax/Parser/unterminated_multiline_regex.swift
  test/Syntax/Parser/unterminated_regex.swift
  test/Syntax/round_trip_regex.swift
  test/Syntax/round_trip_regex_escape_newline.swift
  test/Syntax/round_trip_regex_invalid.swift
  tools/libSwiftSyntaxParser/libSwiftSyntaxParser.cpp
  tools/swift-syntax-test/swift-syntax-test.cpp
Labels: r5.7

#58977 [5.7][SourceKit] Resolve a nondeterministic deadlock in SourceKit while cancelling
  tools/SourceKit/lib/SwiftLang/SwiftASTManager.cpp
Labels: r5.7

#59045 [5.7][CodeCompletion] Don’t compute type relations if the contextual type is `Any`
  lib/IDE/CodeCompletionResultType.cpp
  test/IDE/complete_at_top_level.swift
  test/IDE/complete_type_any.swift
Labels: r5.7

#59162 [Distributed] Missing diagnostic for onReturn ad-hoc req when it is mutating witness
  lib/AST/DistributedDecl.cpp
  lib/Sema/TypeCheckDistributed.cpp
  test/Distributed/distributed_actor_system_missing_adhoc_requirement_impls.swift
  test/Distributed/distributed_serializationRequirement_must_be_protocol.swift
Labels: Distributed

#59156 [cxx-interop] Do not warn about missing libstdc++ on Android
  lib/ClangImporter/ClangImporter.cpp
Labels: C++ Interop

#59166 [5.7][CSClosure] Perform syntactic checks on rewritten statements
  lib/Sema/CSClosure.cpp
  test/expr/closure/multi_statement.swift
Labels: r5.7

#59145 [5.7] Patch Out a Source of Iterator Invalidation
  include/swift/AST/FileUnit.h
  lib/AST/Module.cpp
  lib/Frontend/Frontend.cpp
Labels: r5.7

#59050 [cxx-interop] Pass sysroot to the Clang driver when detecting libstdc++ path
  lib/ClangImporter/ClangImporter.cpp
Labels: C++ Interop

#59120 [test] New test mode to execute all tests with C++ interop enabled.
  test/CMakeLists.txt
  test/lit.cfg
Labels: C++ Interop

#59138 🍒 [5.7] SE-0309: SILOptimizer fixes & reenable executable tests
  include/swift/SILOptimizer/Utils/Existential.h
  lib/SILOptimizer/SILCombiner/SILCombinerApplyVisitors.cpp
  lib/SILOptimizer/Utils/Devirtualize.cpp
  lib/SILOptimizer/Utils/Existential.cpp
  test/Interpreter/existential_member_accesses_self_assoctype.swift
  test/SILOptimizer/devirt_protocol_method_invocations.swift
  test/decl/protocol/existential_member_accesses_self_assoctype_exec.swift
Labels: r5.7

#58683 🍒[5.7][Distributed] Diagnose missing inout on remoteCall decls
  lib/AST/DistributedDecl.cpp
  test/Distributed/distributed_actor_system_missing_adhoc_requirement_impls.swift
Labels: Distributed, r5.7
