Repository swiftlang/swift, pull requests merged in 2025-02, with the labels that each got.

#79063 [6.1][Package CMO] Enable serializing decls imported with `@_spiOnly` or `package import`
  include/swift/AST/Module.h
  lib/AST/Module.cpp
  lib/SILOptimizer/IPO/CrossModuleOptimization.cpp
  test/SILOptimizer/package-cmo-import-filter.swift
Labels: 🍒 release cherry pick

#79076 [cxx-interop] Do not codegen zero-sized fields
  lib/IRGen/GenStruct.cpp
  test/Interop/Cxx/class/Inputs/member-variables.h
  test/Interop/Cxx/class/zero-sized-field.swift
Labels: c++ interop

#79045 [cxx-interop] Support nested classes in reverse interop
  include/swift/AST/SwiftNameTranslation.h
  lib/AST/SwiftNameTranslation.cpp
  lib/PrintAsClang/DeclAndTypePrinter.cpp
  lib/PrintAsClang/PrintClangClassType.cpp
  lib/PrintAsClang/PrintClangFunction.cpp
  test/Interop/SwiftToCxx/class/nested-classes-in-cxx-execution.cpp
  test/Interop/SwiftToCxx/class/nested-classes-in-cxx.swift
Labels: c++ interop

#79147 The SWIFT_DUMP_ACCESSIBLE_FUNCTIONS flag must be a bool, not a string
  stdlib/public/runtime/EnvironmentVariables.def
Labels: distributed

#79144 Ensure that distributed functions with typed throws can be called from outside the actor
  include/swift/AST/DiagnosticsSema.def
  lib/Sema/CSApply.cpp
  lib/Sema/TypeCheckConcurrency.cpp
  lib/Sema/TypeCheckDistributed.cpp
  test/Distributed/distributed_actor_typed_throws.swift
  test/Distributed/distributed_actor_unsupported_typed_throws.swift
Labels: distributed

#79040 [build-script] Disable building and installing the Foundation macros for standalone SDKs (#78782)
  utils/build-script-impl
Labels: 🍒 release cherry pick, swift 6.1-dev

#79148 [6.1] The SWIFT_DUMP_ACCESSIBLE_FUNCTIONS flag must be a bool, not a string
  stdlib/public/runtime/EnvironmentVariables.def
Labels: distributed

#79197 Fix typo, refine formatting in `EmbeddedSwift/UserManual.md`
  docs/EmbeddedSwift/UserManual.md
Labels: documentation, embedded

#79173 [6.1][Package CMO] Prevent serializing types from SDK/system modules imported as @_implementationOnly.
  lib/SILOptimizer/IPO/CrossModuleOptimization.cpp
  test/SILOptimizer/package-cmo-import-filter.swift
Labels: 🍒 release cherry pick

#79272 [test] [6.1] temporarily disable two Cxx tests on Windows because they fail in PR testing
  test/Interop/Cxx/stdlib/use-std-span.swift
  test/Interop/Cxx/stdlib/use-std-string-view.swift
Labels: 🍒 release cherry pick

#78758 🍒[cxx-interop] Do not import `std::__compressed_pair`
  lib/ClangImporter/ImportDecl.cpp
Labels: c++ interop

#79278 ClangImporter: support modularizing `__msvc_string_view.hpp`
  lib/ClangImporter/ClangIncludePaths.cpp
  stdlib/public/Platform/vcruntime.modulemap
Labels: c++ interop

#79307 ClangImporter: enable test, fix typo
  lib/ClangImporter/ClangIncludePaths.cpp
  test/Interop/Cxx/stdlib/use-std-string-view.swift
Labels: c++ interop

#79383 NFC: Update code owners for C++ interop
  .github/CODEOWNERS
Labels: c++ interop

#79396 [cxx-interop] Work around lifetime errors in SwiftifyImport generated code
  lib/Macros/Sources/SwiftMacros/SwiftifyImportMacro.swift
  stdlib/public/Cxx/CxxSpan.swift
  test/Interop/Cxx/stdlib/Inputs/std-span.h
  test/Interop/Cxx/stdlib/std-span-interface.swift
  test/Interop/Cxx/stdlib/std-span-transformed-execution.swift
  test/Macros/SwiftifyImport/CxxSpan/LifetimeboundSpan.swift
Labels: c++ interop

#79432 [cxx-interop] Remove a feature flag
  include/swift/Basic/Features.def
  lib/AST/FeatureSet.cpp
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/class/safe-interop-mode.swift
Labels: c++ interop

#77615 [AutoDiff] Support curry thunks differentiation in fragile funcs
  lib/SILOptimizer/Mandatory/Differentiation.cpp
  test/AutoDiff/SILOptimizer/differentiation_diagnostics.swift
  test/AutoDiff/SILOptimizer/fragile_curry_thunk.swift
  test/AutoDiff/SILOptimizer/generics.swift
  test/AutoDiff/compiler_crashers_fixed/rdar87429620-differentiable-curry-thunk-reqmachine.swift
Labels: AutoDiff

#79430 [6.1][Concurrency] Fix a few issues with matching `any Sendable` to `Any`
  lib/Sema/CSApply.cpp
  lib/Sema/CSDiagnostics.cpp
  lib/Sema/CSSimplify.cpp
  lib/Sema/MiscDiagnostics.cpp
  lib/Sema/TypeCheckAvailability.cpp
  test/Concurrency/predates_concurrency_swift6.swift
  test/Concurrency/sendable_to_any_for_generic_arguments.swift
  test/Interpreter/sendable_erasure_to_any_in_preconcurrency.swift
  test/SILGen/sendable_to_any_for_generic_arguments.swift
Labels: 🍒 release cherry pick

#79458 [cxx-interop] Remove duplicated logic to import types as unsafe
  lib/ClangImporter/ImportDecl.cpp
  test/Interop/Cxx/class/safe-interop-mode.swift
Labels: c++ interop

#78373 [AutoDiff] Allow closure differentiation when used as default arg val
  lib/SILOptimizer/Mandatory/Differentiation.cpp
  test/AutoDiff/SILOptimizer/differentiation_diagnostics.swift
Labels: AutoDiff

#79514 [cxx-interop] Support ObjC classes in generic context in reverse interop
  lib/PrintAsClang/ModuleContentsWriter.cpp
  lib/PrintAsClang/PrintClangValueType.cpp
  test/Interop/ObjCToSwiftToObjCxx/bridge-objc-types-back-to-objcxx-execution.mm
  test/Interop/ObjCToSwiftToObjCxx/bridge-objc-types-back-to-objcxx.swift
Labels: c++ interop

#77522 [cxx-interop] Infer SWIFT_SHARED_REFERENCE for types inheriting from a C++ foreign reference type
  include/swift/AST/DiagnosticsClangImporter.def
  include/swift/ClangImporter/ClangImporterRequests.h
  lib/AST/Decl.cpp
  lib/ClangImporter/ClangClassTemplateNamePrinter.cpp
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImportName.h
  lib/ClangImporter/ImportType.cpp
  lib/ClangImporter/ImporterImpl.h
  lib/ClangImporter/SwiftLookupTable.cpp
  lib/Sema/CSDiagnostics.cpp
  test/Interop/Cxx/class/conforms-to.swift
  test/Interop/Cxx/foreign-reference/Inputs/inheritance.h
  test/Interop/Cxx/foreign-reference/inheritance-diagnostics.swift
  test/Interop/Cxx/foreign-reference/inheritance-irgen.swift
  test/Interop/Cxx/foreign-reference/inheritance-module-interface.swift
  test/Interop/Cxx/foreign-reference/inheritance-silgen.swift
  test/Interop/Cxx/foreign-reference/inheritance.swift
Labels: c++ interop

#78796 Make Optional<T>.TangentVector methods inlineable
  stdlib/public/Differentiation/OptionalDifferentiation.swift
Labels: AutoDiff

#78806 Mark Differentiation related FloatingPoint methods with @inlinable
  stdlib/public/Differentiation/FloatingPointDifferentiation.swift.gyb
Labels: AutoDiff

#79472 [6.1] Sema: don't use `llvm::StringSwitch` for runtime function names
  lib/Sema/TypeCheckAttr.cpp
Labels: 🍒 release cherry pick, swift 6.1-dev

#79523 [stdlib] fix android build
  stdlib/public/Concurrency/Actor.cpp
Labels: 🍒 release cherry pick

#79324 [cxx-interop] Remove some duplicated lookups
  lib/ClangImporter/ClangImporter.cpp
  lib/ClangImporter/DWARFImporter.cpp
  lib/ClangImporter/ImportDecl.cpp
  lib/ClangImporter/ImportMacro.cpp
  lib/ClangImporter/ImportType.cpp
  lib/ClangImporter/ImporterImpl.h
Labels: c++ interop

#79691 [cxx-interop] Avoid warnings in strict memory safe mode on in generated code
  lib/Macros/Sources/SwiftMacros/SwiftifyImportMacro.swift
  test/Macros/SwiftifyImport/CountedBy/CountExpr.swift
  test/Macros/SwiftifyImport/CountedBy/MultipleParams.swift
  test/Macros/SwiftifyImport/CountedBy/Mutable.swift
  test/Macros/SwiftifyImport/CountedBy/MutableSpan.swift
  test/Macros/SwiftifyImport/CountedBy/NamedParams.swift
  test/Macros/SwiftifyImport/CountedBy/Nullable.swift
  test/Macros/SwiftifyImport/CountedBy/PointerReturn.swift
  test/Macros/SwiftifyImport/CountedBy/QualifiedTypes.swift
  test/Macros/SwiftifyImport/CountedBy/Return.swift
  test/Macros/SwiftifyImport/CountedBy/SharedCount.swift
  test/Macros/SwiftifyImport/CountedBy/SimpleCount.swift
  test/Macros/SwiftifyImport/CountedBy/SimpleSpan.swift
  test/Macros/SwiftifyImport/CountedBy/SimpleSpanWithReturn.swift
  test/Macros/SwiftifyImport/CountedBy/SpanAndUnsafeBuffer.swift
  test/Macros/SwiftifyImport/CountedBy/Unwrapped.swift
  test/Macros/SwiftifyImport/CxxSpan/LifetimeboundSpan.swift
  test/Macros/SwiftifyImport/CxxSpan/NoEscapeSpan.swift
  test/Macros/SwiftifyImport/SizedBy/MultipleParams.swift
  test/Macros/SwiftifyImport/SizedBy/Mutable.swift
  test/Macros/SwiftifyImport/SizedBy/MutableRawSpan.swift
  test/Macros/SwiftifyImport/SizedBy/Nullable.swift
  test/Macros/SwiftifyImport/SizedBy/Opaque.swift
  test/Macros/SwiftifyImport/SizedBy/Return.swift
  test/Macros/SwiftifyImport/SizedBy/SharedCount.swift
  test/Macros/SwiftifyImport/SizedBy/SimpleRawSpan.swift
  test/Macros/SwiftifyImport/SizedBy/SimpleRawSpanWithReturn.swift
  test/Macros/SwiftifyImport/SizedBy/SimpleSize.swift
  test/Macros/SwiftifyImport/SizedBy/SizeExpr.swift
  test/Macros/SwiftifyImport/SizedBy/Unwrapped.swift
Labels: c++ interop
